== Prefacio

Aunque he escogido el título "`Restauración del Cristianismo
Primitivo`" como el nombre principal de esta publicación,
en realidad se trata de una combinación de dos publicaciones distintas de William Penn.
Una es de su libro "`Restauración del Cristianismo
Primitivo`" (publicado por primera vez en 1696),
y la otra es "`Un Corto Relato del Surgimiento y Progreso del Pueblo llamado
Cuáqueros,`" que originalmente sirvió como introducción al Diario de George
Fox (publicado en 1694) y que después se imprimió por separado.
Las dos publicaciones se traslapan en su enfoque,
ambas relacionadas (en diversos grados) con el surgimiento de la Sociedad de Amigos,
y con los distintos principios y prácticas de este pueblo,
y se pensó que estos cortos libros podían combinarse y entrelazarse de tal modo
que le brindaran al lector una presentación más completa de estos temas,
que la que cada publicación podría hacer individualmente.
Al intentar hacer esto, me tomé un grado de libertad editorial: eliminé repeticiones,
agregué transiciones cortas entre secciones, y moví párrafos de un lado a otro,
poniéndolos donde parecían encajar mejor.
También he intentado modernizar cuidadosa y conscientemente, y algunas veces,
reformular el lenguaje arcaico (aunque hermoso) de Penn,
agregando ocasionalmente una referencia a las Escrituras
o una frase mía con la intención de dar mayor claridad.
Mi objetivo no era simplemente volver a publicar las obras de William Penn;
todas sus publicaciones originales aún existen y
están disponibles a través de muchas fuentes en línea.
Mi objetivo era presentarle al buscador de la verdad de hoy,
un relato legible e impactante sobre lo que Dios hizo en la antigua Sociedad de Amigos,
que es lo mismo que Él desea hacer en los corazones y vidas de cada cristiano moderno.

Quizás también sea necesario decir que, a lo largo de estas páginas,
Penn relata el estado de la Sociedad de Amigos tal como era hace más de trescientos años,
y sus palabras no describen (hasta donde yo sé) ninguna
de las reuniones o asociaciones actuales de los Cuáqueros.
La luz que resplandeció tan notoriamente en los corazones de estos hombres y mujeres,
se fue haciendo cada vez más tenue en las generaciones sucesivas,
al no ser abrazada ni obedecida con el mismo celo y entrega.
En este sentido,
la exhortación de Penn a los hijos de los Amigos (en las últimas páginas de este libro),
resultó ser tanto una advertencia como una profecía, y para mediados de los 1800,
la gran mayoría de los que llevaban el nombre de Cuáqueros,
eran ajenos a ese poder y presencia celestial que
al principio los había reunido para ser un pueblo.

[.signed-section-signature]
Jason Henderson

[.signed-section-context-close]
Febrero 2018
