== Una Epístola para el Lector.

[.salutation]
Querido lector,

El siguiente relato del pueblo llamado Cuáqueros fue escrito en el temor y amor de Dios;
en primer lugar, como un testimonio permanente de esa bendita verdad en lo íntimo,
con la cual Dios visitó mi alma en los días de mi juventud,
y por cuyo disfrute y amor llegué a estar dispuesto
a renunciar a los honores e intereses del mundo.
En segundo lugar, como un testimonio de ese pueblo menospreciado, a quien Dios,
por medio de Su propio bendito Espíritu,
reunió y unió con gran misericordia en la profesión santa de esta
verdad--cuya comunión valoro por encima de toda grandeza mundana.

Espero que sea evidente para todo lector sobrio y considerado que,
a pesar de todo el maltrato que hemos recibido del mundo,
nuestro gran deseo siempre ha sido la realidad y experiencia de la verdadera religión,
es decir, experimentar una transformación eficaz antes de nuestro gran y último cambio.
Y en verdad, deseamos que todos puedan llegar a este conocimiento interno,
discernible y experimentable de Dios,
a través de las convicciones y operaciones de la luz y Espíritu
de Cristo en sí mismos (el medio suficiente y bendito dado a todos),
y así conozcan realmente al único Dios verdadero, y a Jesucristo,
a quien Él ha enviado para iluminar y redimir al mundo.
Este conocimiento es, en verdad, la vida eterna; y que tú, querido lector, lo obtengas,
es el deseo ferviente de tu sincero amigo,

[.signed-section-signature]
William Penn
