== Capítulo I

[.chapter-subtitle--blurb]
Una Breve Reseña de las Diferentes Dispensaciones de Dios en el Mundo,
hasta el Tiempo en que Le Plació Levantar al Pueblo Llamado Cuáqueros.

Desde la creación del mundo ha habido varias dispensaciones
de Dios para con los hijos de los hombres;
y el gran propósito de todas ellas ha sido el honor de Su propio
y excelente nombre en la creación y restauración del hombre,
quien fue hecho a Su imagen y es la gloria de todas Sus obras.
El mundo comenzó con inocencia, y todo era bueno entonces,
tal como el buen Dios lo había hecho.
Y así como Él bendijo las distintas obras de Sus manos,
asimismo la naturaleza y armonía de ellas magnificaban a su Creador.
Entonces las estrellas del alba cantaban juntas de alegría,
y cada parte de Su obra decía "`amén`" a Su ley.
No había la menor discordia en toda la creación; sino que el hombre en el paraíso,
las bestias en el campo, las aves en el aire, los peces en el mar,
las luces en los cielos, los frutos de la tierra, sí, hasta el aire, la tierra,
el agua y el fuego, adoraban, alababan y exaltaban Su poder, sabiduría y bondad.
¡Oh, santo Sabbat! ¡Oh, día santo para el Señor!

Pero este feliz estado no duró mucho; porque el hombre, corona y gloria de todo,
al ser tentado a aspirar ser algo más allá de su lugar, lamentablemente cedió,
actuando en contra de su mandamiento y deber,
así como de su propio beneficio y felicidad,
y por ello cayó muy por debajo de su condición original.
De este modo perdió la imagen divina--la sabiduría,
el poder y la pureza en que había sido hecho;
y puesto que ya no era apto para el paraíso,
fue expulsado del jardín de Dios (que era su morada y residencia apropiada),
y echado como un pobre vagabundo fuera de la presencia de Dios, para vagar por la tierra,
la habitación de las bestias.

Sin embargo, el Dios que lo hizo tuvo compasión de él;
porque vio que el hombre había sido engañado, y que no había sido por malicia propia,
sino por la astucia de la serpiente (la cual había caído primero de su propio estado),
y a través de la mediación de la mujer--que era de su propia naturaleza
y su compañera--a quien la serpiente había engañado primero.
En consecuencia, Dios, en Su infinita bondad y sabiduría,
proporcionó una manera de reparar la brecha,
recuperar la pérdida y restaurar al hombre caído por medio de un Adán más noble y excelente,
que según la promesa nacería de una mujer.
Y así como por medio de una mujer el maligno había prevalecido sobre el hombre,
así también, por medio de una mujer vendría al mundo el postrer Adán,
y prevalecería contra la serpiente,
heriría su cabeza y redimiría al hombre de su poder--todo lo cual,
de manera extraordinaria,
fue cumplido personal y plenamente por y en el Hijo de Dios en la carne,
como el Salvador y Redentor del hombre.

Pero la manifestación del poder de Dios a través de Su Hijo no se limitó a ese tiempo;
porque tanto antes como desde Su bendita manifestación en la carne,
Él ha sido la luz y vida,
la roca y fortaleza de todos los que en cualquier época han temido a Dios.
Él estaba presente con ellos en sus tentaciones, los seguía en sus viajes y aflicciones,^
footnote:[1 Corintios 10:1-4]
y los apoyaba y sostenía a través y por encima de las dificultades
que los acompañaban en su peregrinaje terrenal.^
footnote:[Hebreos 11:26]
Fue sólo por medio de esto que el corazón de Abel fue más excelente que el de Caín,
que Set obtuvo la preeminencia y que Enoc caminó con Dios.
Fue esta luz y poder lo que contendió con el mundo
antiguo antes del diluvio (contra el cual se rebelaron),
y lo mismo que santificó e instruyó a Noé para salvación.

Pero los tratos externos de Dios con el hombre después de su caída,
especialmente con los patriarcas,
fueron generalmente a través del ministerio de los ángeles;
tal como los escritos del Antiguo Testamento lo expresan en muchos lugares,
como en el caso de Abraham, Jacob, etc.
La siguiente dispensación fue la de la ley por medio de Moisés,
la cual también fue entregada por medio de ángeles, como nos dice el apóstol.
Esta dispensación fue muy externa, adaptada a un estado degenerado y servil,
y por eso el apóstol Pablo la llamó "`ayo,`"^
footnote:[Gálatas 3:24-25]
porque señalaba y preparaba al pueblo para esperar y anhelar al Mesías,
quien los redimiría de la servidumbre de esa dispensación ceremoniosa e imperfecta,
al experimentar (dentro de sí mismos) las realidades de esas figuras y tipos misteriosos.
En ese entonces la ley estaba escrita en piedras, y el templo había sido hecho con manos,
y estaba acompañado de un sacerdocio físico, de ritos y de ceremonias externos,
que eran sombras de los bienes venideros.
Pero todo esto sólo serviría "`hasta que viniese la Simiente,`"^
footnote:[Gálatas 3:19]
es decir, hasta la manifestación más excelente y universal?
de Cristo; porque a Él fue hecha la promesa, y a todos los hombres solamente en Él,
en Quien la promesa es sí y amén; sí, la promesa de pasar de muerte a vida,
y alcanzar la inmortalidad y la vida eterna.

Los profetas vieron esto de antemano y consolaron a los
judíos creyentes con la certeza de su cumplimento.
Porque el ministerio de los profetas fue la cumbre de la dispensación Mosaica,
la cual finalizó en Juan, el que le preparó el camino al Mesías;
y el ministerio de Juan terminó en Aquel que es la plenitud de todo.
Fue entonces cuando Dios,
habiendo hablado muchas veces y en muchas maneras en otro
tiempo a los padres por medio de Sus siervos los profetas,
les habló a los hombres por medio de Su Hijo Jesucristo,
a quien constituyó Heredero de todo.
Este fue el amanecer del día del evangelio, la dispensación de hijos,
la cual comenzó un pacto mucho más cercano y una mejor esperanza; es decir,
el comienzo de la gloria de los postreros días y de la restauración de todas las cosas;
sí, la restauración del reino a Israel.

Entonces, el Espíritu,
que en dispensaciones anteriores había sido comunicado con mayor restricción,
comenzó a ser derramado sobre toda carne, de acuerdo con el testimonio del profeta Joel.
Y Dios, por Su infinita bondad, hizo que la luz que antes resplandecía en las tinieblas,
o sólo débilmente, resplandeciera de las tinieblas,
y el Lucero de la mañana comenzó a levantarse en los corazones de los creyentes,
dándoles el conocimiento de Dios en la faz, o aparición, de Su Hijo Jesucristo.

Y ahora, los pobres en espíritu, los mansos, los que verdaderamente lloran,
los que tienen hambre y sed de justicia, los pacificadores, los de corazón puro,
los misericordiosos y los perseguidos,
vinieron en memoria delante del Señor de manera más especial,
y fueron buscados y bendecidos por el verdadero Pastor de Israel.
La antigua Jerusalén, junto con sus hijos, envejeció,
y la nueva Jerusalén se convirtió en la madre de los hijos del día del evangelio.
Por lo tanto,
ya no sería en la antigua Jerusalén ni en el monte de Samaria
donde Dios habría de ser adorado por encima de otros lugares;
porque, he aquí, Su propio Hijo declara y predica que Él es Espíritu,
y que como tal será conocido y adorado en espíritu y en verdad.
Ahora Él se acercará más que en los tiempos antiguos, y escribirá Su ley en el corazón,
y pondrá Su temor y Su Espíritu en el interior, según Su promesa.
Y así, todas las señales,
tipos y sombras pasaron--pues el Día manifestó su insuficiencia
al no alcanzar el interior de la copa para limpiar la conciencia--y
todos los servicios rudimentarios expiraron en Él y por Él,
quien es la sustancia de todo.

Los apóstoles dieron testimonio de esta grande y bendita dispensación
del Hijo de Dios--a quienes el Señor había escogido y ungido por medio
de Su Espíritu--para volver a los judíos del prejuicio y de la superstición,
y a los gentiles de la vanidad y de la idolatría,
y dirigirlos hacia la Luz y Espíritu de Cristo que brillaba dentro de ellos,
a fin de que fueran vivificados de los delitos y pecados en que estaban muertos,
sirvieran al Dios vivo en la novedad del Espíritu de Vida,
y caminaran como hijos de la Luz y del Día. Aquellos que en verdad se revisten de Cristo,
la luz del mundo, ya no proveen para los deseos de la carne.
Y así, esta luz, Espíritu y gracia de Dios, que viene por Cristo y aparece en el hombre,
era el principio divino a partir del cual los apóstoles ministraban,
y al cual volvían las mentes de las personas,
y en el cual reunían y edificaban la iglesia de Cristo en sus días. Y
por esta causa les advertían a todos que no contristaran al Espíritu,
sino que esperaran en el Espíritu, hablaran en el Espíritu,
oraran en el Espíritu y caminaran en el Espíritu,
como lo único que probaba que ellos eran verdaderamente hijos engendrados por Dios,
no nacidos de carne, ni de sangre, ni de voluntad de hombre, sino de la voluntad de Dios.
Porque al hacer Su voluntad y negar la propia,
al beber la copa de Cristo y ser bautizados con Su bautismo,
se experimenta el camino y la senda por la cual todos
los herederos de la vida han viajado hacia la bendición.

¡Pero tristemente,
incluso en los días de los apóstoles (aquellas brillantes
estrellas del amanecer del evangelio),
comenzaron a aparecer algunas nubes que predecían un eclipse de esta primera gloria!
Varios de ellos les advirtieron anticipadamente a
los cristianos de su tiempo respecto a esto,
diciendo que ya entonces había, y que aún habría más,
una apostasía del poder de la piedad y de la pureza de esta dispensación espiritual,
por parte de aquellos que buscaban tener una apariencia de justicia en la carne,
pero en quienes el tropiezo de la cruz había cesado.
Su visión fue verdadera;
y lo que anunciaron a las iglesias reunidas por ellos en el nombre y poder de Jesús,
se cumplió; porque los cristianos se degeneraron rápidamente,
cayendo en prácticas externas, tales como días, comidas, y varias otras ceremonias.
Y peor aún, cayeron en contiendas y disputas sobre estas cosas,
separándose unos de otros, y envidiándose unos a otros.
Y, según encontraban poder para hacerlo, se persiguieron unos a otros,
para vergüenza y escándalo de su común cristianismo,
y para lamentable tropiezo y ofensa para los paganos.

Luego,
habiendo finalmente obtenido el poder mundano en sus manos
mediante reyes y emperadores que abrazaron la religión cristiana,
transformaron el reino de Cristo, que no es de este mundo, en un reino mundano; o,
al menos, llamaron "`reino de Cristo`" al reino mundano que estaba en sus manos.
Entonces, las invenciones y novedades humanas, tanto en la doctrina como en la adoración,
se amontonaron rápidamente en la iglesia; pues, en verdad,
se había abierto una puerta para tales cosas por la inmundicia
y la carnalidad que ya predominaba entre la mayoría de los cristianos,
quienes hacía mucho tiempo habían abandonado la guía
del Espíritu manso y celestial de Dios,
y se habían entregado a la superstición, a un culto voluntario y a una humildad falsa.

Y así como la superstición es ciega, también es temeraria y furiosa,
porque todos debían inclinarse ante su celo ciego e insaciable, o perecer por él. Y así,
en nombre del Espíritu, persiguieron la aparición misma del Espíritu de Dios en otros,
oponiéndose en los demás a lo que ellos resistían en sí mismos, a saber, la luz,
gracia y Espíritu del Señor Jesucristo.
Pero esto lo hicieron, y lo siguen haciendo, llamándolo herejía, cisma, innovación,
o cualquier otro nombre creíble;
a pesar de que el cristianismo verdadero no permite fundamento ni pretexto
alguno para perseguir a un hombre por cuestiones de mera religión,
siendo por naturaleza manso, gentil y tolerante, y consistiendo en fe, esperanza y amor,
cosas que ningún perseguidor puede tener.
Porque ¿cómo podría un perseguidor creer bien, tener una verdadera esperanza,
o una preocupación caritativa o tierna por otro,
mientras busca violentar la mente de otro,
o de perseguir su cuerpo por asuntos de fe o de adoración a Dios?

Así surgió la iglesia falsa y se sentó en?
el trono.
Pero, aunque había perdido su naturaleza,
de ninguna manera quiso renunciar a su buen nombre: esposa del Cordero,
verdadera iglesia y madre de los fieles; obligando a todos a recibir su marca,
ya sea en su frente o en su mano derecha; es decir, de manera pública o privada.
Pero, de hecho, ella era Babilonia, la madre de las rameras, la madre de los que,
a pesar de su apariencia y religión externa, habían adulterado y salido del Espíritu,
naturaleza y vida de Cristo, habiéndose vuelto vanos, mundanos, ambiciosos, codiciosos,
crueles, etc., los cuales son frutos de la carne, y no del Espíritu.

Fue en ese momento cuando la verdadera iglesia huyó al desierto,^
footnote:[Ver Apocalipsis 12:6]
es decir, huyó de la superstición y de la violencia, hacia un estado retirado,
apartado y solitario--se ocultó, por decirlo así, de la vista de los hombres,
aunque no salió del mundo.
Esto demuestra que su visibilidad anterior no era esencial para ser considerada
la verdadera iglesia según el juicio del Espíritu Santo;
porque ella era una iglesia tan verdadera en el desierto (aunque no tan visible y radiante),
como en su antiguo esplendor.
Se hicieron muchos intentos por regresar de este estado de desierto,
pero las aguas seguían muy altas y su camino permanecía bloqueado;
y muchos de sus excelentes hijos, en diversas naciones y épocas,
cayeron por la crueldad de la superstición,
porque no quisieron apartarse de su fidelidad a la verdad.

La época de la Reforma dio algunos pasos hacia ello,
tanto en la doctrina como en la adoración y en la práctica.
Pero cualquier avance en la práctica fracasó rápidamente;
porque la iniquidad fluyó libremente, tanto entre los profesantes^
footnote:[La palabra __profesantes__ se usa a través de este libro
para referirse a uno que profesa o afirma una creencia en Cristo.
De la misma manera,
la __profesión__ de una persona se refiera a lo que ellos creen o profesan como la verdad,
y no está relacionado con su empleo.]
de la Reforma como entre aquellos de quienes ellos se habían separado;
de modo que no podían distinguirse unos de otros por los frutos de su conducta.
Y los hijos de los reformadores (si no los reformadores mismos) comenzaron
a buscar la política y poder terrenal para sostener y continuar su Reforma,
que había comenzado con armas espirituales.
He pensado muchas veces que esta fue una de las principales razones por las que
la Reforma no hizo un mejor progreso en cuanto a la vida y el corazón de la religión.
Porque mientras los reformadores se mantuvieron humildes y de mente espiritual,
confiando en Dios, mirándolo, viviendo en Su temor, no consultando con carne y sangre,
ni buscando ser libres a su manera,
diariamente se añadían a la iglesia los que habían de ser salvos.
Pues por un tiempo, se preocuparon más por ser fieles e inofensivos bajo la persecución,
que por estar a salvo de ella,
teniendo mayor interés en difundir la verdad por medio de su fe y paciencia en la tribulación,
que en tomar el poder mundano de las manos de sus perseguidores.

En cuanto a la doctrina, los reformadores quedaron cortos en algunas cosas; en otras,
para evitar un extremo, corrieron hacia el otro; y en cuanto a la adoración, en general,
había mucho más del hombre en ella que de Dios.
Ellos reconocían la necesidad del Espíritu, la inspiración y la revelación, y de hecho,
basaron su separación y reforma en el sentido y entendimiento que de ello
habían recibido a partir de la lectura de las Escrituras de verdad.
Y esta era su afirmación: La Escritura es el texto, el Espíritu el intérprete,
y cada hombre puede decidir por sí mismo.
Sin embargo, aún quedaba demasiada invención, tradición y adorno humanos,
tanto en la oración como en la predicación;
y una autoridad y grandeza mundanas en sus ministros--especialmente en Gran Bretaña,
Suecia, Dinamarca y algunas regiones de Alemania.
Por tanto, le plació a Dios en Inglaterra trasvasarnos de una vasija a otra,
y humillar el ministerio, de modo que se volvieron más estrictos en la predicación,
más devotos en la oración, más celosos en guardar el día del Señor,
en catequizar a hijos y siervos,
y en repetir en casa a sus familiares lo que habían escuchado en el servicio religioso.
Pero a medida que crecieron en el poder eclesiástico,
fueron hallados no sólo expulsando a algunos fuera de sus templos,
sino forzando a otros a entrar.
Se mostraron rígidos en sus espíritus, en lugar de serios en sus vidas,
y más comprometidos con partidos políticos que con la piedad interior;
lo cual dio origen a otro pueblo, aún más retirado y vigilante.

Estos no buscaban comunión con todos, ni asociación con la iglesia nacional,
sino que formaban iglesias entre ellos con personas que
estaban dispuestas a ser responsables de sus conductas.
Tenían experiencias muy prometedoras de la obra de la gracia de Dios en sus corazones,
y vivían bajo acuerdos y pactos mutuos de comunión que los mantenían unidos.
Siendo de un temperamento algo más tierno,
este pueblo parecía recomendar la religión por los encantos de su amor,
misericordia y bondad, y no por los terrores de sus juicios y castigos;
con los que el primer grupo intentaba atemorizar a las personas
para llevarlas a la religión. Además daban más libertad
para profetizar que aquellos que fueron antes de ellos;
porque permitían que cualquier miembro hablara u orara,
así como su pastor (a quien siempre designaban ellos mismos, y no el magistrado civil).
Y si alguno de ellos sentía la carga de la palabra del Señor,
sin importar cual fuera su oficio, y sin distinción de clero o laico,
tenía la libertad de hablar, por muy simple y sin educación que fuera.

Pero desgraciadamente, incluso este pueblo sufrió una pérdida muy grande.
Porque al gustar el imperio mundano,
el favor de los príncipes y las ganancias que les seguían, se degeneraron en gran manera.
Y a pesar de que habían criticado a la iglesia nacional y a su ministerio,
así como a su mantenimiento forzado,^
footnote:[Diezmos obligatorios.]
cuando les llegó el turno de ser probados,
muchos fueron vencidos por el peso del honor mundano y ventaja terrenal.
Porque lograron puestos en parroquias lucrativas,
y rápidamente contradijeron sus propios principios; y, lo que es peor,
algunos de ellos se volvieron perseguidores declarados
de otros hombres en nombre de Dios,
habiendo ellos mismos salido recientemente del mismo horno de aflicción.

Esto llevó a muchos a dar un paso adicional, esto es,
sumergirse en el agua--para otro bautismo--creyendo
que no habían sido bautizados según las Escrituras,
y teniendo la esperanza de encontrar la presencia y el poder
de Dios que les faltaba al someterse a esta ordenanza.
Este pueblo estaba a favor de negar, e incluso de renuncia y censurar,
no sólo la necesidad,
sino también el uso de todo conocimiento humano en lo que respecta al ministerio,
y buscar únicamente las ayudas y los dones del Espíritu de Dios,
y aquellas habilidades naturales y comunes a los hombres.

Por un tiempo, estos parecían ser como el Juan de antaño;
una luz ardiente y brillante para otras sociedades cristianas.
Eran muy diligentes, simples y serios;
fuertes en las Escrituras y audaces en la profesión,
soportando mucha crítica y oposición. Pero aquello que había
fascinado a otros resultó ser también su lazo.
Porque fueron corrompidos con el sabor del poder mundano,
y se detuvieron demasiado en su dispensación de agua,
en lugar de avanzar más plenamente hacia la del Espíritu Santo y fuego,
el cual era el bautismo de Aquel que vino con el aventador en Su
mano para limpiar completamente Su era (y no sólo en parte),
y quitar la escoria y la impureza de Su pueblo, y hacer al hombre más puro que el oro.
Por lo tanto, se volvieron altivos, rudos y justos en su propia opinión,
oponiéndose a un mayor crecimiento en el Espíritu,
y olvidando los días de su infancia y pequeñez,
los cuales les habían dado algo de verdadera belleza.

Por eso, muchos los dejaron,
y también abandonaron todas las iglesias y sociedades visibles,
y anduvieron errantes como ovejas sin pastor, y como palomas sin compañía,
buscando a su Amado,
pero sin poder encontrar a Aquel que sus almas amaban por encima de su mayor gozo.
Algunos llamaron a estas personas "`Buscadores,`" y otros "`la Familia del Amor.`"
Y a medida que se conocían, a veces se reunían,
no para orar o predicar formalmente en tiempos o lugares determinados,
según sus propias voluntades, como solían hacerlo en tiempos pasados,
sino para esperar juntos en silencio; y cuando se levantaba algo en la mente de alguno,
que tenía el sabor del Manantial divino, algunas veces hablaban.
Pero sucedió que algunos no se mantuvieron en la humildad, ni en el temor de Dios, y así,
después de gran abundancia de revelaciones se enaltecieron desmedidamente.
Y por no mantener sus mentes en humilde dependencia en Aquel que había
abierto sus entendimientos para mirar las maravillas de Su ley,
se extraviaron en sus propias imaginaciones.
Luego, al mezclar sus ideas oscuras con las revelaciones divinas,
dieron a luz un nacimiento monstruoso,
para escándalo de todos los que temían a Dios y esperaban diariamente,
en el templo no hecho con manos, la consolación de Israel; es decir,
el judío interior y el circuncidado en espíritu.

Este pueblo recibió el nombre de Ranters,^
footnote:[En inglés,
la palabra "`rant`" significa hablar o gritar de una manera salvaje y apasionada.]
debido a sus extravagantes discursos y prácticas.
Interpretaban el cumplimiento de la ley por parte de Cristo como una exoneración
de toda obligación y deber que la ley requería de nosotros,
afirmando que ahora ya no era pecado hacer lo que antes sí lo era.
Y al declarar que el temor esclavizante de la ley había sido quitado por Cristo,
enseñaban que todo lo que el hombre hiciera era bueno,
con tal de que lo hiciera con el pensamiento y convicción de que así lo era.
Así, muchos cayeron en prácticas inmundas y escandalosas,
pretendiendo (como excusa) que podían, sin hacer ningún mal,
cometer el mismo acto que para otros era pecado;
porque distinguían entre la acción y el mal de la acción según
la dirección de la mente y la intención al llevarla a cabo.
Esto hizo que el pecado sobreabundara por la abundancia de la gracia,
convirtiendo la gracia de Dios en libertinaje,^
footnote:[Judas 1:4]
ofreciendo un pretexto más seguro para pecar que antes--como
si Cristo no hubiera venido a salvarnos de nuestros pecados,
sino en nuestros pecados; no a quitar el pecado,
sino para que pecáramos más libremente a costa Suya,
y con menor peligro para nosotros mismos.
Este engaño atrapó a muchos y los llevó a sufrir una profunda
y lamentable pérdida con respecto a su estado eterno.
Éstos se convirtieron en una gran molestia para las personas de mejor disposición,
y le dieron oportunidad a los más licenciosos para blasfemar.
