== Capítulo 4

[.chapter-subtitle--blurb]
Algunas Objeciones Examinadas y Respondidas

[.discourse-part]
Objeción:
Algunos pueden objetar que,
las virtudes y efectos que le atribuimos a la luz en el corazón corresponden,
en realidad, al Espíritu y a la gracia de Dios,
que son bendiciones propias del nuevo y segundo pacto, y fruto de la venida de Cristo.

[.discourse-part]
Respuesta:
Si las propiedades atribuidas a la luz en el corazón son las mismas
que se otorgan al Espíritu Santo y a la gracia de Dios,
entonces, ciertamente,
no son sino distintos términos o epítetos utilizados para expresar las
diversas manifestaciones u operaciones de un mismo Espíritu.

Ahora bien, para demostrar esto,
y ver si la luz en el corazón es de la misma naturaleza
que el Espíritu y la gracia de Dios,
y si conduce al mismo fin (que es llevar a las personas a Dios),
comparemos las propiedades de la luz con las del Espíritu y la gracia de Dios.
_Primero,_ la luz procede de la única Palabra, y de la única vida de esa única Palabra,
la cual era con Dios y era Dios (Juan 1:4 y 1:9). _Segundo,_ es universal; es decir,
está escrito que alumbra a todo hombre.
_Tercero,_ da el conocimiento de Dios y comunión con Él (Romanos 1:19; Juan 3:21;
1 Juan 1:5-6). _Cuarto,_ manifiesta y reprende el mal (Juan 3:20; Efesios 5:13). _Quinto,_
se establece como la regla y guía de la vida cristiana (Salmo 43:3; Juan 8:12;
Efesios 5:13 y 15). _Sexto,_
es la senda por la que el pueblo de Dios debe caminar (Salmos 119:105; Proverbios 4:18;
Isaías 2:5; 1 Juan 1:7 y Apocalipsis 21:24,
"`las naciones de los que son salvos andarán en la luz de ella).^
footnote:[Reina Valera 1602 Purificada]
_Por último,_
es la armadura de los hijos de Dios contra Satanás: "`El Señor es mi luz:
¿de quién temeré?`" Salmos 27:1;^
footnote:[Reina Valera 1602 Purificada]
y "`Vistámonos las armas de la luz`" Romanos 13:12.

Ahora comparemos todo esto con las propiedades del Espíritu Santo,
y su concordancia será muy evidente.
_Primero,_ el Espíritu procede de Dios,
porque es el Espíritu de Dios (Romanos 8:11). _Segundo,_ es universal;
contendió con el mundo antiguo (Génesis 6:3), y sin duda lo hace también con el nuevo.
A cada uno le ha sido dada una medida de Él para provecho (1 Corintios 12:7). _Tercero,_
revela a Dios (Job 32:8; 1 Corintios 2:10-11). _Cuarto,_
reprende el pecado (Juan 16:8). _Quinto,_
es la regla y guía por la cual los hijos de Dios deben andar (Romanos 8:14). _Sexto,_
es también la senda por la que deben andar (Romanos 8:1; Gálatas 5:16,
"`Andad en el Espíritu`"). _Por último,_
es el arma espiritual de todo cristiano verdadero (Efesios 6:17,
"`Tomad la espada del Espíritu, que es la palabra de Dios`"). Así pues,
espero que nadie niegue que esta luz y este Espíritu han de ser de una misma naturaleza,
obran un mismo efecto, y claramente tienden a un mismo y santo fin.

Y lo que se ha dicho acerca de luz y del Espíritu,
bien puede decirse también acerca de la luz y de la gracia de Dios.
Porque _primero,_
la gracia fluye de Cristo--la Palabra que se hizo carne--como también la luz;
porque así como "`en él estaba la vida, y la vida era la luz de los hombres`" (Juan 1:4),
también estaba "`lleno de gracia y de verdad`" (Juan 1:14),
y "`de su plenitud todos nosotros hemos recibido, y gracia por gracia`" (Juan 1:16).^
footnote:[Reina Valera 1602 Purificada]
_Segundo,_ es universal,
lo cual puede verse tanto en el texto anterior como
también en las palabras del apóstol a Tito:
"`Porque la gracia de Dios que trae salvación se
ha manifestado a todos los hombres`" (Tito 2:11).^
footnote:[Reina Valera de Gomez]
_Tercero,_ manifiesta el mal,
porque enseña a "`renunciar a la impiedad y a los deseos mundanos`" (Tito 2:12). _Cuarto,_
revela la piedad, y por tanto, necesariamente manifiesta a Dios.
_Quinto,_ es un instructor y guía,
porque el apóstol dice que enseña a vivir en este mundo sobria,
justa y piadosamente (Tito 2:12),
y aquí en esto se halla la regla o guía de la vida cristiana.
_Sexto,_ es, para los que la reciben,
todo lo que pueden necesitar o desear (2 Corintios 12:9,
"`Bástate mi gracia`")--un fuerte testimonio desde el cielo
a favor del poder de esta gracia que enseña y salva,
incluso bajo las más fuertes tentaciones.

[.discourse-part]
Objeción: Algunos pueden objetar que, antes de la venida de Cristo,
hay pocas referencias al Espíritu, y ninguna a la gracia.
Por lo tanto,
que el Espíritu--tal como se habla de Él en los escritos
del Nuevo Testamento--y más especialmente la gracia,
deben de ser algo diferente y más noble que la luz en el corazón.

[.discourse-part]
Respuesta: De ninguna manera es algo diferente,
sino otro nombre para otra manifestación u operación del mismo Espíritu.
Se le llama _luz_ por la percepción y discernimiento que da.
"`Sea la luz; y fue la luz,`" dijo Dios en el principio del mundo antiguo.
Así también, primero hay luz en el principio de la nueva creación de Dios en el hombre.
Se le llama _Espíritu,_ porque da vida, sentido, movimiento y vitalidad,
y así se menciona a menudo en los escritos tanto del Antiguo como del Nuevo Testamento.
Mediante este Espíritu, contendió Dios con el mundo antes del diluvio (Génesis 6:3),
y con Israel en el desierto (Nehemías 9:30). Y David clamó en la agonía de su alma:
"`¿A dónde me iré de tu Espíritu?`"
(Salmos 139:7); y los profetas lo sintieron con frecuencia.
Y se le llama _gracia,_ no por ser otro Espíritu,
sino porque es una dispensación más plena de la virtud y poder del mismo Espíritu divino;
la cual, siendo puramente el favor y la misericordia de Dios, y no mérito del hombre,
es debidamente llamada la gracia de Dios para el hombre indigno.

El viento no siempre sopla con fuerza, ni el cielo siempre envía lluvia con abundancia,
ni el sol siempre brilla con claridad.
¿Diremos, entonces, que no se trata del mismo _tipo_ de viento, de lluvia o de luz,
cuando sopla, llueve o brilla poco, que cuando sopla, llueve o brilla mucho?
Es ciertamente el mismo en naturaleza y género;
y así también ocurre con este bendito Espíritu en todas sus diversas dispensaciones,
manifestaciones y operaciones,
todas las cuales han sido para el beneficio del alma del hombre,
desde que comenzó el mundo.

Y nosotros, con plena libertad, humildad y agradecimiento,
reconocemos que la dispensación del Evangelio es la más clara, plena y noble de todas,
tanto con respecto a la venida de Cristo en la carne para ofrecerse como
nuestra única y santa ofrenda por el pecado mediante el Espíritu eterno;
como por el amanecer de Su luz,
el derramamiento de Su Espíritu y la aparición de Su gracia en el hombre y para el hombre,
de una manera más excelente después de Su ascensión. Pues,
si bien no era una luz o Espíritu diferente al que
Él le había dado al hombre en los siglos anteriores,
sí era una medida distinta y mayor;
y este es el gran privilegio del Evangelio por encima
de todas las dispensaciones anteriores.

Lo que antes brillaba tenuemente, desde entonces brilla con mayor gloria.
Lo que entonces aparecía oscuramente, ahora aparece con el rostro descubierto.
Los tipos,
las figuras y las sombras velaban Sus apariciones
y hacían que Su gloria se viera baja y tenue;
pero en el tiempo del Evangelio el velo ha sido rasgado y la gloria oculta ha sido manifestada.
Bajo la ley, el Espíritu no era más que un rocío o una ligera llovizna,
pero en el Evangelio, puede decirse que ha sido derramado sobre todos los hombres,
conforme a aquella misericordiosa y memorable promesa de Dios por medio del profeta Joel:
"`En los postreros días, derramaré de mi Espíritu sobre toda carne.`"^
footnote:[Joel 2:28; Hechos 2:17]

Cuando llueve abundantemente, decimos: "`¡Mira qué aguacero!`"
Así también Dios ha aumentado Su luz,
gracia y Espíritu para todos en estos postreros días.
No lo recibirán con escasez ni en pequeñas gotas,
sino plena, libre y desbordantemente.
Así, Pedro, aquel profundo y excelente apóstol,
aplicó la promesa de Joel al día de Pentecostés como el comienzo de su cumplimiento.
¡Esto es gracia, favor y bondad en verdad!
Por lo tanto,
puede llamarse apropiadamente _gracia_ a esta iluminación mucho más brillante,
y a este mayor derramamiento del Espíritu;
porque así como la venida del Hijo superó el tiempo de siervo,
así también la manifestación de la luz y del Espíritu de Dios desde la venida de Cristo,
superó la de todas las dispensaciones anteriores; no obstante,
siempre fue suficiente para salvar a todos los que caminaron en ella.

Este es nuestro entendimiento de la luz, Espíritu y gracia de Dios.
Y por lo que ha sido dicho, es evidente que son uno y lo mismo,
y que aquel que tiene la luz, no carece del Espíritu ni de la gracia de Dios,
si tan solo la recibe en el amor de ella.^
footnote:[Ver 2 Tesalonicenses 2:10]
Porque la misma luz que le aparece a él, es también el Espíritu que lo vivifica,
la gracia que lo enseña, lo ayuda y lo consuela.
Es suficiente en todas las circunstancias de la vida para
aquellos que con diligencia le prestan atención y la obedecen.

[.discourse-part]
Objeción: Algunos todavía pueden objetar: "`Si es así como ustedes lo declaran, ¿por qué,
entonces, todos los que son iluminados no son tan buenos como deberían ser,
o tan buenos como esta luz busca hacerlos?`"

[.discourse-part]
Respuesta: Porque las personas no la reciben ni la obedecen.
Todos los hombres tienen la capacidad de razonar, pero no todos son razonables.
¿Es culpa del grano que está en el granero el no producir fruto,
o del talento que está escondido en el pañuelo el no generar interés?

[.small-break]
'''

Es claro en la parábola que se dio un talento;
e igual de claro que era capaz de incrementarse--tanto porque talentos
idénticos habían dado ganancia en las manos de otros,
como porque el Juez justo esperaba recibir Su talento con intereses.
Ahora bien, ¿de quién fue la culpa de que el talento no se incrementara?
¿No fue del siervo inútil que fue infiel en lo poco?
Los ciegos no deben culpar al sol,
ni los pecadores acusar a la gracia de Dios de ser insuficiente.
Es el pecado el que oscurece el ojo,
endurece el corazón e impide que las cosas buenas lleguen a los hijos de los hombres.
Cristo nos dice: "`Si alguno quiere hacer Su voluntad, conocerá de la doctrina.`"^
footnote:[Juan 7:17 RV Gómez]
Los hombres que no viven conforme a lo que conocen,
no pueden culpar a Dios por no conocer más. La esterilidad está en nosotros,
no en el talento, y sería en verdad provechoso que se llevara al corazón.

[.discourse-part]
Objeción: Algunos todavía pueden objetar:
"`Si la humanidad siempre ha tenido el Espíritu Santo,
¿por qué las verdades del Evangelio no fueron conocidas tan plenamente
antes de la venida de Cristo por aquellos que eran obedientes a Él?

[.discourse-part]
Respuesta: Porque un niño no es un adulto, ni el principio es el fin; y sin embargo,
Aquel que es el principio también es el fin.
El Espíritu es el mismo, aunque no la manifestación,
y aquellos que son fieles a lo que conocen de la dispensación de su propio tiempo,
oirán la feliz bienvenida: "`Bien hecho, siervo bueno y fiel.`"^
footnote:[Mateo 25:21 RV Gómez]

Y, sin embargo,
muchos del pueblo de Dios en aquellos días sí tenían
una visión de la gloria de los postreros tiempos,
de la mejora del pacto y de la felicidad de la iglesia de Dios.
Esto lo vemos claramente en la profecía de Jacob y de Moisés acerca
de la restauración de Israel por medio del Mesías. Y David,
en muchos de sus excelentes salmos,
expresa un gozo sumamente palpable y extraordinario del Espíritu,
y profetiza cosas por venir.^
footnote:[Particularmente en el Salmo 2, 15, 18, 22, 23, 25, 27, 32, 36, 37, 42, 43, 45,
51, 84, etc.]
Los profetas están llenos de tales expresiones, y por esa razón llevan ese nombre.^
footnote:[Particularmente Isaías, capítulos 2, 9, 11, 25, 28, 32, 35, 42, 49, 50, 51, 52,
53, 54, 59, 60, 61, 63, 65, 65, 66. Jeremías también, capítulos 23, 30, 31, 33. Ezequiel,
capítulos 20, 34, 36, 37. Daniel, capítulos 8, 9, 10, 11, 12. Oseas, capítulos 1,
3+++.+++ Joel, capítulos 2, 3. Amós, capítulo 9. Miqueas, capítulos 4 y 5. Zacarías,
capítulos 6, 8, 9, 11, 13, 14. Malaquías, capítulos 3, 4.]
Todo eso no era otro Espíritu, sino otra manifestación del mismo Espíritu.
El Espíritu que vino sobre Moisés fue el mismo que vino sobre Juan el Bautista;
y el Espíritu que vino sobre Gedeón y Sansón, también descendió sobre Pedro y Pablo;
pero no fue la misma dispensación de ese Espíritu.

Ha sido el proceder de Dios el visitar y manifestarse
a los hombres según sus estados y condiciones,
y según hayan estado preparados para recibirlo, sea de manera más externa o interna,
física o espiritual.
No hay capacidad humana demasiado baja ni demasiado
alta para el alcance de este Espíritu Divino;
pues así como Él hizo y conoce a todos, así también alcanza a todos.
Él se extiende hasta el más bajo,
y aun el más alto no puede subsistir sin Él. Esto hizo que David gimiera en su angustia,
diciendo: "`¿A dónde me iré de tu Espíritu?
¿O a dónde huiré de tu presencia?`"^
footnote:[Salmos 139:7]
Aquí él implica que el Espíritu está en todas partes,
aunque no en todas ni en todo tiempo de la misma manera.
"`Si subiere a los cielos, allí estás Tú: y si en el infierno hiciere mi cama,
he aquí allí Tú estás. Si tomare las alas del alba, y habitare en el extremo de la mar,
aun allí me guiará Tu mano, y me asirá Tu diestra.`"^
footnote:[Salmos 139:8-10 RV1602P]
Sí, incluso allí esta Palabra Divina, esta luz de los hombres, este Espíritu de Dios,
me encontrará, me guiará, me ayudará,
y me consolará. Porque está conmigo dondequiera que esté y adondequiera que vaya,
en una forma u otra.
"`Te guiará cuando anduvieres; cuando durmieres te guardará;
hablará contigo cuando despertares;`"^
footnote:[Proverbios 6:22 RV Gómez]
y no podría deshacerme de Él--aun si así lo deseara--más
de lo que podría deshacerme de mí mismo;
tan presente está conmigo y tan estrechamente se adhiere a mí.

[.discourse-part]
Objeción:
Que los judíos hayan tenido esta luz no significa que los gentiles la tuvieran también;
sin embargo, según su doctrina, todos la tienen.

[.discourse-part]
Respuesta: Sí,
y la gloria de esta doctrina que profesamos es que
ella declara que el amor de Dios es ofrecido a todos.
Y además de los textos ya citados (que no podrían
expresarse de manera más completa y positiva),
el apóstol es muy específico en el segundo capítulo de su Epístola a los Romanos,
cuando dice: "`Los gentiles que no tienen ley, hacen por naturaleza lo que es de la ley,
éstos, aunque no tengan ley, son ley para sí mismos.`"^
footnote:[Romanos 2:14]
Es decir, no tenían una ley externa como la tenían los judíos,
pero tenían "`la obra de la ley escrita en sus corazones,`"^
footnote:[Romanos 2:15]
y así, teniendo la ley en sí mismos, bien podían ser ley para sí mismos.

Los judíos también la tenían así,
pero además contaban con mayores ayudas externas para animar su obediencia a ella,
cosas que Dios no concedió a ninguna otra nación. Es por esa razón que se dice
que la obediencia de los gentiles (o la incircuncisión) era por naturaleza,^
footnote:[Romanos 2:14]
o naturalmente, porque carecía de esas leyes y señales adicionales,
externas y extraordinarias que los judíos recibieron para provocarles a cumplir su deber.
Pero esto no solo no descarta a los gentiles obedientes, sino que más bien los exalta,
según el juicio del apóstol; porque, aunque tenían menos ventajas que los judíos,
la obra de la ley escrita en sus corazones se hacía mucho más evidente
por la vida piadosa que vivían en el mundo.

Luego Pablo añade: "`Dando testimonio su conciencia`"--o como también podría traducirse,
'`su consciencia atestiguando juntamente con ellos`'--"`y acusándose mientras tanto,
o también excusándose sus pensamientos, unos con otros,
en el día en que juzgará Dios los secretos de los hombres por Jesucristo,
según mi evangelio.`"^
footnote:[Romanos 2:15-16]
Esto nos presenta cuatro aspectos a favor de nuestro punto,
y merece nuestra seria reflexión: _Primero,_
que los gentiles tenían la ley escrita en sus corazones.
_Segundo,_ que su conciencia era un testigo o una evidencia válida respecto a su deber.
_Tercero,_
que el juicio hecho en ella será confirmado por el
evangelio del apóstol en el gran Día y,
por lo tanto, será válido e irreversible.
_Cuarto,_ que esto no podría ser así de ninguna manera,
a menos que la luz que brilla en la conciencia fuera una luz divina y suficiente.

[.discourse-part]
Objeción: Sin embargo, tal vez se objete: "`Si todo es obra de un solo Espíritu Santo,
entonces ¿por qué existen tantas modalidades y formas
de religión desde el principio del mundo?
Pues la religión patriarcal, la mosaica y la cristiana,
todas presentan grandes diferencias entre sí;
sin mencionar lo que ha sucedido a la religión cristiana
desde el día en que comenzó a ser proclamada al mundo.`"

[.discourse-part]
Respuesta: No sé cómo podrían llamarse correctamente religiones diferentes,
ya que todas afirman al verdadero Dios como el objeto de adoración,
al Señor Jesucristo como el único Salvador,
y a la luz o Espíritu de Cristo como el gran agente y medio
para la conversión del hombre y su felicidad eterna;
pues esto sería como decir que la infancia,
la juventud y la edad adulta constituyen tres hombres,
en lugar de tres etapas o períodos de crecimiento de un mismo hombre.
Pero dejando eso de lado,
las muchas modalidades o formas por las que Dios se aparece a los hombres
surgen (como ha sido dicho) de los diferentes estados de los hombres,
en todos los cuales parece haber sido la intención
principal de Dios evitar la idolatría y el vicio,
dirigiendo sus mentes al verdadero objeto de adoración y exigiendo la virtud y la santidad.
A los patriarcas,
parece haberles hablado principalmente por medio de ángeles en forma de hombres,
además de la iluminación interna del Espíritu.
A los profetas, en su mayor parte,
se comunicó por revelación del Espíritu Santo en ellos, y por medio de ellos,
al pueblo judío. Y desde la dispensación del evangelio, ha hablado por Su Hijo,
tanto externamente por medio de Su venida en la carne,
como internamente por Su aparición espiritual en el alma como la gran luz del mundo.
Sin embargo, en todas estas dispensaciones,
el uso de instrumentos o agentes externos debe entenderse como una "`siembra de luz`"^
footnote:[Salmos 97:11]
en la tierra por el mismo Espíritu,
que coopera con la manifestación de la luz que se experimenta
directamente en el propio pecho del hombre.

Esto es de gran importancia, tanto para nuestra información como para nuestro aliento,
que la obra de Dios, en relación con el hombre, es una y la misma,
y que Su ojo siempre ha estado puesto sobre lo mismo en todas Sus dispensaciones,
a saber,
hacer a los hombres verdaderamente buenos al sembrar
Su santo temor y reverencia en sus corazones.
Sin embargo,
Él ha sido condescendiente--debido a la dureza y oscuridad de los corazones de los hombres--al
acercarse y revelarles Su santa mente a través de formas sencillas y externas,
permitiendo que la Verdad se revista de varios tipos de vestimentas,
con el fin de alcanzar mejor el estado caído de los hombres,
y apartarlos de los dioses falsos y de una vida impía.

Y si consideramos la razón de la prevalencia de la idolatría en los tiempos más
antiguos y oscuros del mundo (acerca de lo cual la Escritura es muy detallada),
hallaremos que surge de lo siguiente: que su adoración era más sensual, y por lo tanto,
diseñada para satisfacer los sentidos de los hombres, siendo más externa y visible,
y más en sus propias manos para realizarla que una adoración de naturaleza más espiritual.
Ellos deseaban ver el objeto de su devoción,
y tener en su poder la capacidad de adorarlo como y cuando quisieran.
Por esta razón, Dios, mediante muchos juicios y grandes liberaciones,
engendró un pueblo para Sí Mismo, para que recordaran y adoraran la Mano que los salvó,
y que, al hacerlo,
desarraigaran la idolatría y plantaran el conocimiento y temor de Él en sus mentes,
como ejemplo para las otras naciones.
Cualquiera que lea Deuteronomio (que es un resumen de los otros
cuatro libros de Moisés) verá el frecuente y ferviente cuidado
y desvelo de ese buen hombre con respecto a este mismo punto,
y con cuánta frecuencia Israel, a pesar del amor,
cuidado y paciencia de Dios para con ellos,
se deslizó y reincidió en las costumbres idólatras de las naciones a su alrededor.^
footnote:[Varias otras Escrituras nos informan lo mismo,
especialmente las de los profetas, Isaías 54 y 4; Salmos 37 y 115; Jeremías 10,
donde el Espíritu Santo confronta y reprende al pueblo,
y se burla de sus ídolos con una especie de desprecio santo.
--W. P.]

Ahora bien, lo que es totalmente contrario a la idolatría, y por tanto,
es el mejor antídoto contra ella, es el mismo Espíritu de Dios del que hemos hablado.
Y cuanto más se vuelven las mentes de las personas y se acercan a Él, y cuanto más su fe,
su adoración y su obediencia se ligan a la santa iluminación y a Su poder,
más se acercan al propósito de Su creación, y, por consiguiente, a Su Creador.
Estos están más calificados espiritualmente,
y llegan a estar mejor preparados para adorar a Dios tal como Él es;
porque (como nos dice nuestro Señor Jesucristo), Él es Espíritu,
y será adorado en Espíritu y en Verdad.
Estos son los adoradores que Dios busca que le adoren en este día del evangelio.

"`La hora viene,`" dice Él, "`y ahora es;`"^
footnote:[Juan 4:23]
es decir, "`algunos ya lo hacen,
pero más lo harán;`" lo cual fue una afirmación muy precisa para el tiempo presente,
y una promesa y profecía del aumento de tales adoradores en el futuro.
Esto muestra que se pretendía un cambio de la adoración
y estado ceremoniales de la iglesia de Dios,
a la adoración y estado espirituales.
Así dice el texto: "`Mas la hora viene, y ahora es,
cuando los verdaderos adoradores adorarán al Padre en Espíritu y en Verdad;`"^
footnote:[Juan 4:23]
es decir, cuando la adoración a Dios será más interna que externa, y por lo tanto,
más conforme a la naturaleza de Dios y a la parte
más noble del hombre--el hombre interior y mejor.
Esta adoración es en el Espíritu, es decir, mediante el poder del Espíritu; y en Verdad,
es decir, en la substancia, no en sombras, ceremonias o formalidades.
He aquí una adoración en sinceridad, con y en la vida de Dios,
divinamente preparada y vivificada,
que lleva al hombre a ofrecer lo que es agradable para Él,
y eleva su alma a una íntima comunión y unión con Dios, que es Espíritu.

Y si esto se considera debidamente, será evidente que Dios,
en todas las diferentes manifestaciones de Sí Mismo,
se ha ido acercando cada vez más al interior de los hombres,
a fin de alcanzar sus entendimientos,
abrir sus corazones y darles una relación más plena y cercana con Él Mismo en el Espíritu.
Es allí, en el corazón,
donde el hombre debe buscar y encontrar el conocimiento
de Dios para su felicidad eterna.

Todas las cosas creadas muestran el poder,
la sabiduría de Dios y Su bondad para con la humanidad.
De hecho,
muchos recurren a la majestuosidad de la creación
para silenciar las objeciones ateas de los hombres.
Pero aunque todas las cosas creadas muestran que hay un Dios,
el hombre lo hace por encima de todo lo demás. Él es la piedra preciosa en el anillo,
y la joya más gloriosa del planeta.
El hombre es una composición de ambos mundos; su cuerpo es de este y su alma del otro.
El cuerpo es como el templo del alma, el alma el templo de la Palabra viva,
y la Palabra el gran templo y manifestación de Dios.
Mediante el cuerpo, el alma observa y contempla la creación,
y mediante la Palabra contempla a su Dios y al mundo que no tiene fin.
Se podría decir mucho más de este orden de cosas, pero deseo ser breve.
