== Capítulo V

[.chapter-subtitle--blurb]
Las Doctrinas de la Justificación y la Salvación

Mucho han rumorado y falsamente nos han acusado nuestros adversarios
con respecto a las importantes doctrinas del sacrificio de Cristo
por el cual Dios quedó satisfecho por nuestros pecados,
y del fundamento de la justificación de un pecador ante Dios.
Primero hablaré en términos negativos, acerca de lo que _no creemos,_
lo cual quizás haya dado ocasión a los que han sido más apresurados que sabios,
para juzgarnos deficientes en nuestra creencia en la eficacia de
la muerte y los sufrimientos de Cristo para justificación.

Primero,
nosotros no podemos creer que los sufrimientos y la muerte de Cristo satisfagan a Dios,
ni justifiquen a los hombres, de tal manera que, por medio de esa obra externa,
sean inmediatamente aceptados por Dios.
Creemos que, por dichos sufrimientos y muerte,
son verdaderamente puestos en un estado en el que son capaces de ser aceptados por Dios,
pero que es a través de la obediencia de la fe y la santificación del Espíritu,
que llegan a un verdadero estado de aceptación. No podemos considerar que un hombre
esté justificado delante de Dios mientras permanezca condenado a sus propios ojos,
o que algún hombre pueda estar en Cristo sin ser una nueva criatura;
o que Dios considere a los hombres de manera diferente a lo que realmente son.
Creemos que es un estado de presunción, y no de salvación,
llamar a Jesús Señor y no por obra del Espíritu Santo; o Amo,
cuando aún no es amo de sus afectos; o Salvador,
cuando no han sido salvados por Él de sus pecados; o Redentor,
cuando aún no han sido redimidos por Él de sus pasiones, orgullo, codicia, vanidad,
honores vanos, y de las amistades y gloria de este mundo.
Creemos que esto más bien es engañarse a sí mismo, porque "`Dios no puede ser burlado;
pues todo lo que el hombre sembrare,
eso también segará.`" Y aunque Cristo ciertamente murió por nosotros, debemos,
con la ayuda de Su gracia, "`obrar nuestra salvación con temor y con temblor.`"^
footnote:[Filipenses 2:12 RV 1602 Purificada]
Así como Él murió por el pecado, nosotros también debemos morir al pecado,
o no se puede decir verdaderamente que somos salvos
por la muerte y sufrimientos de Cristo,
ni completamente justificados y aceptos ante Dios.

[.offset]
Ahora hablaré en términos positivos,
acerca de lo que _sí creemos_ respecto a la justificación:

Nosotros creemos firmemente que Jesucristo fue nuestro santo sacrificio,
expiación y propiciación; que Él llevó nuestras iniquidades,
y que por Sus llagas fuimos sanados de las heridas que Adán nos causó en su caída;
y que Dios es justo al perdonar a los verdaderamente arrepentidos por el mérito
de esa santa ofrenda que Cristo hizo de Sí Mismo a Dios por nosotros.
Creemos que lo que Cristo hizo y padeció ha satisfecho y agradado a Dios,
y que fue por el bien del hombre caído que había desagradado a Dios.
Y que mediante la ofrenda de Sí mismo hecha una vez para siempre por el Espíritu eterno,
"`hizo perfectos para siempre a los que +++[+++en todos los tiempos]
son santificados,`"^
footnote:[Hebreos 10:14 RV1602P]
los que "`no andan conforme a la carne, sino conforme al Espíritu.`"^
footnote:[Romanos 8:1, 4.]

En resumen, creemos que la justificación consta de dos partes,
o tiene una doble consideración; a saber: la justificación de la culpa del pecado,
y la justificación del poder y la contaminación del pecado; y en este doble sentido,
la justificación otorga al hombre plena y clara aceptación delante de Dios.
Y es debido a la carencia de esta última parte que muchas almas
(que tienen inclinaciones religiosas) a menudo tienen dudas,
inquietudes de conciencia y desesperación,
a pesar de todo lo que sus maestros les dicen acerca del alcance y eficacia de la primera
parte de la justificación. Y es un error demasiado común entre los profesantes del cristianismo,
tratar de encubrir su propia desobediencia activa
y pasiva con la obediencia activa y pasiva de Cristo.

La primera parte de la justificación, que reconocemos con reverencia y humildad,
es únicamente por virtud de la muerte y sufrimientos de Cristo.
No es algo que podamos hacer, sino que es realizada por la operación del Espíritu Santo,
quien es capaz de cancelar las deudas pasadas y borrar las cuentas antiguas.
Es el poder y la eficacia de esta ofrenda propiciatoria,
sobre la base de la fe y el arrepentimiento,
lo que nos justifica de los pecados pasados;^
footnote:[Ver Romanos 3:25]
y es el poder del Espíritu de Cristo en nuestros corazones,
lo que nos purifica y nos hace aceptos ante Dios.
Porque mientras el corazón del hombre no sea purgado del pecado,
Dios nunca lo aceptará. Él reprende,
amonesta y condena a los que hospedan el pecado allí,
y no se puede decir correctamente que estos están en un estado justificado--ya
que la condenación y la justificación son contrarias entre sí. Por lo tanto,
aquellos que creen que están en un estado de justificación
debido a la obediencia activa y pasiva de Cristo,
aun cuando ellos mismos no son activa y pasivamente
obedientes al Espíritu de Cristo Jesús,
están bajo un engaño fuerte y peligroso ¡Y por clamar contra
esta imaginación (y doctrina) que complace al pecado,
es que somos considerados y criticados como personas que niegan
y desprecian la muerte y los sufrimientos de nuestro Señor Jesucristo!

Pero sepan todos aquellos que caminan en impiedad bajo una profesión de justificación:
que éstos añaden a los sufrimientos de Cristo y crucifican
de nuevo para sí mismos al Hijo de Dios,
hollando bajo sus pies la sangre de Su pacto.
Porque Dios no tomará por inocentes a los culpables,
ni justificará a los desobedientes e infieles.
Estos se engañan a sí mismos, y en el gran juicio final la sentencia para ellos no será:
"`Venid, benditos,`" porque no se les podrá decir: "`Bien,
buen siervo y fiel;`" sino más bien: "`Apartaos de mí,
malditos,`" pues viven y mueren en un estado reprobable y condenable.
Porque ninguno experimenta realmente a Cristo como su sacrificio,
si lo rechaza como su santificador;
porque el propósito de Su venida fue salvar a Su pueblo de la naturaleza y contaminación,
así como de la culpa del pecado.
Por consiguiente, aquellos que resisten Su luz y Espíritu,
hacen que Su venida y ofrenda no tengan efecto para ellos.

Por lo tanto, querido lector,
no te des por plenamente satisfecho con lo que Cristo
ha hecho por ti en Su bendita Persona fuera de ti,
sino esfuérzate por experimentar Su poder y reino dentro de ti,
para que el hombre fuerte (que por mucho tiempo ha dominado tu casa) sea atado,
sus bienes saqueados, sus obras desechas y el pecado terminado,
de acuerdo con 1 Juan 3:5-8. Para esto, dice este discípulo amado,
fue manifestado Cristo;
para que todas las cosas sean hechas nuevas--nuevos cielos y nueva tierra,
en los cuales mora la justicia.
En esto llegarás a glorificar a Dios en tu cuerpo y en tu espíritu--los
cuales son Suyos--y así vivirás para Él y no para ti mismo.
En verdad, tu amor, gozo, adoración y obediencia; tu vida, conducta y práctica;
tu estudio, meditación y devoción, todo será espiritual.

El Padre y el Hijo harán Su morada contigo, y Cristo se manifestará a ti;
porque el secreto del Señor es para los que le temen,
y estos tienen una unción santa que los guía a toda verdad,
sin necesidad de las enseñanzas de los hombres.
Sí, estos son mejor instruidos, ya que son enseñados por el oráculo Divino.
No son simples cristianos de oídas o de tradición, sino frescos y vivos testigos,
aquellos que han visto con sus propios ojos,
oído con sus propios oídos y palpado con sus propias manos la Palabra de vida,
en sus diversas operaciones, para la salvación de sus almas.
En esta Palabra se reúnen, en ella predican, y en ella oran y alaban.
¡He aquí el nuevo pacto cumplido, la iglesia, la unción y la adoración de Cristo!

=== La Salvación por medio de Cristo

Y para que nadie diga que somos ambiguos en nuestras expresiones,
y que alegorizamos la aparición de Cristo en la carne,
usando esa expresión solamente para referirnos a Su aparición interna en nuestra carne;
o que, cada vez que lo mencionamos a Él hablamos únicamente del misterio,
o del sentido espiritual y místico de Él,
es mi deseo preservar a todos de ser engañados por tales insinuaciones,
e informar y rescatar a los que están bajo el prejuicio de tales malentendidos,
declarando lo siguiente: Nosotros creemos y confesamos firmemente,
para la gloria de Dios Padre y el honor de Su querido y amado Hijo,
que Jesucristo tomó sobre Sí nuestra naturaleza, y fue como nosotros en todas las cosas,
excepto en el pecado.
Creemos que nació de la virgen María, sufrió bajo Poncio Pilato, el gobernador romano,
fue crucificado, muerto y sepultado en el sepulcro de José de Arimatea;
que resucitó al tercer día, ascendió al cielo y está sentado a la diestra de Dios,
en el poder y majestad de Su Padre, quien un día juzgará al mundo por medio de Él--sí,
por ese bendito Hombre, Jesucristo--conforme a sus obras.

Pero puesto que creemos esto, también debemos creer en lo que Cristo ha dicho:
"`Aquel que mora con vosotros, estará en vosotros.`"^
footnote:[Juan 14:17]
"`Vosotros en mí, y yo en vosotros,`"^
footnote:[Juan 14:20] etc.
Y en las muchas declaraciones similares de los apóstoles:
"`Pero cuando agradó a Dios revelar a su Hijo en mí.`"^
footnote:[Gálatas 1:16]
"`El misterio oculto desde los siglos, que es Cristo en los gentiles,
la esperanza de gloria.`"^
footnote:[Colosenses 1:27]
"`...que Jesucristo está en vosotros, a menos que estéis reprobados.`"^
footnote:[2 Corintios 13:5]
¿O deberíamos ser considerados un pueblo que niega la venida de Cristo en la carne,
y de todas las partes y aspectos de Su obra y sufrimientos,
solo porque creemos y enfatizamos la necesidad de creer,
recibir y obedecer Su aparición y manifestación interna y espiritual, a través de Su luz,
gracia y Espíritu en los corazones y conciencias de hombres y mujeres, para reprenderlos,
convencerlos, convertirlos y transformarlos?
Esto nos parece un trato duro e injusto por parte de nuestros adversarios.

Sin embargo,
estamos muy dispuestos a declarar ante todo el mundo que no podemos creer que
los hombres y las mujeres puedan ser salvos sólo por su fe en lo externo,
sin el sentido y la experiencia de lo interno.
Es a esto a lo que nos oponemos, y no a Su bendita manifestación en la carne.
Porque confesamos abiertamente que Cristo, en aquel tiempo,
venció a nuestro enemigo común, lo derrotó públicamente y,
participando de nuestra naturaleza, triunfó sobre aquel que había triunfado sobre ella^
footnote:[Es decir, la naturaleza del hombre,
refiriéndose a la conquista de Satanás y a su largo
reinado en y sobre la naturaleza caída de la humanidad.]
en nuestro antepasado Adán y en toda su posteridad.
Sin embargo, tan verdaderamente como Cristo lo venció en Su propia persona, así también,
al recibir y obedecer Su gracia Divina, Él vence al enemigo en nosotros; es decir,
lo detecta con Su luz en la conciencia,
y capacita a la criatura para resistir sus dardos de fuego,
pelear la buena batalla de la fe y vencer, y echar mano de la vida eterna.

Esta es la dispensación de la gracia que declaramos se ha manifestado a todos,
en diversas medidas,
enseñando a todos los que la reciben a "`renunciar a la impiedad y a los deseos mundanos,
y a vivir en este siglo sobria, justa y piadosamente,
aguardando la esperanza bienaventurada y la manifestación
gloriosa de nuestro gran Dios y Salvador Jesucristo.`"^
footnote:[Tito 2:11-13]
Y puesto que es a partir de la enseñanza,
experiencia y operación de esta gracia que ministramos a otros,
el propósito mismo de nuestro ministerio es volver los corazones
de las personas a esta gracia en sí mismas,
para que todas puedan hacer la buena y agradable voluntad de Dios,
y trabajar su salvación con temor y con temblor,
haciendo firme su llamado y elección celestiales.

Porque "`todo lo que el hombre sembrare, eso también segará;`"^
footnote:[Gálatas 6:7]
y "`es esclavo de aquel a quien obedece.`"^
footnote:[Romanos 6:16]
Debemos experimentar una verdadera regeneración,
o no podemos ser hijos de Dios ni herederos de la gloria eterna.
Para nacer de nuevo, otro Espíritu debe prevalecer en nosotros, leudarnos,
sazonarnos y gobernarnos, aparte del espíritu del mundo,
o de nuestros propios espíritus depravados.
Este no puede ser otro Espíritu que aquel que moraba en Cristo; porque está escrito que,
a menos que Su Espíritu more en nosotros, no somos de Él,
Romanos 8:9. Este Espíritu comienza con la convicción,
y termina en la conversión y en la perseverancia; una necesariamente siguiendo a la otra.
Porque la conversión es la consecuencia de obedecer las convicciones,
y la perseverancia es un fruto natural de la conversión y de haber nacido de Dios.
Los tales "`no practican el pecado, porque la Simiente de Dios permanece en ellos,`"^
footnote:[1 Juan 3:9]
y por medio de la fidelidad continúan hasta el fin y obtienen la promesa, es decir,
la vida eterna.

Pero que mi lector esté seguro de que nosotros sí reconocemos que Cristo,
a través de Su santa obra y sufrimiento,
ha obtenido misericordia de Dios Su Padre para la humanidad,
y que Su obediencia tiene una gran influencia sobre
nuestra salvación en todas sus partes y aspectos,
ya que por medio de ella venció,
llevó cautiva la cautividad y obtuvo dones para los
hombres (con otras preciosas y grandísimas promesas),
para que "`llegásemos a ser participantes de la naturaleza divina,
habiendo huido de la corrupción que hay en el mundo a causa de la concupiscencia.`"^
footnote:[2 Pedro 1:4]
Digo que,
ciertamente creemos y confesamos que la obediencia activa y pasiva
de Cristo Jesús influye nuestra salvación en todo su alcance,
salvándonos del poder y contaminación del pecado, así como también de la culpa,
siendo Él un conquistador así como también un sacrificio,
y ambas cosas a través del sufrimiento.
Sin embargo, aquellos que rechazan el don divino que Él obtuvo así, y les ha dado,
y mediante el cual pueden ver su pecado y la pecaminosidad de éste,
y arrepentirse y apartarse de él,
y que no esperan en Dios para recibir fuerza diaria
para resistir los dardos de fuego del enemigo,
ni ser consolados a través de la obediencia de la fe en esta gracia
divina del Hijo de Dios--tales personas no agradan a Dios,
ni creen verdaderamente en Dios,
ni están en un estado de verdadero cristianismo o salvación.
"`Mujer,`" le dijo Cristo a la samaritana en el pozo,
"`si conocieras el don de Dios, y quién es el que te habla,`"^
footnote:[Juan 4:10]
etc.
Las personas no conocen a Dios ni a Cristo (a quien conocer "`es la vida eterna,^
footnote:[Juan 17:3]`") porque son ignorantes del don de Dios, es decir,
la "`manifestación del Espíritu de Dios dada a cada uno para provecho;`"^
footnote:[1 Corintios 12:7]
la cual revela a Cristo y a Dios al alma.

La carne y la sangre no pueden hacer esto;
ser educados en Oxford y en Cambridge no puede hacerlo;
los idiomas y la filosofía no pueden hacerlo;
porque aquellos que "`mediante la sabiduría no conocieron a Dios,`"^
footnote:[1 Corintios 1:21]
tenían estas cosas como su sabiduría. Eran fuertes,
profundos y precisos en ese tipo de conocimiento; pero ¡ay! estaban nublados,
envanecidos y distanciados del conocimiento interno y salvador de Dios,
porque lo buscaban donde no puede ser hallado.
Pero la llave de David es otra cosa, la cual cierra y ninguno puede abrir,
y abre y ninguno puede cerrar.
Y todos los que reciben el don de Dios en sus corazones encuentran esta llave,
y ella les abre el conocimiento de Dios y de sí mismos, y les da una visión,
gusto y juicio de las cosas que es muy diferente de los que su
conocimiento intelectual o tradicional les puede dar.
Este es el principio de la nueva creación de Dios,
y por ella nos convertimos en nuevas criaturas.

Por tanto, hablamos con denuedo al declarar que no hay otro camino como este,
por el cual las personas puedan llegar a Cristo, o ser verdaderos cristianos,
o recibir el beneficio que proviene por los sufrimientos
y la muerte del Señor Jesucristo.

Y por tanto decimos--y con buena autoridad, incluso la de nuestra propia experiencia,
así como también la de las Escrituras de la Verdad--que Cristo no será
un sacrificio salvador para aquellos que se niegan a obedecerlo.
Los que rechazan el don, niegan al Dador,
en lugar de negarse a sí mismos por amor al Dador.
¡Ojalá las personas fueran sabias,
y consideraran el fin que les espera y las cosas que son para su paz eterna!
¿Por qué habrían de morir en una vana esperanza de vida,
mientras que la muerte todavía reina en el corazón? ¿O por
qué tienen la esperanza de vivir para siempre con Dios,
cuando no viven para Él, ni caminan con Él ahora?
¡Despierta tú que duermes en tu pecado, o en el mejor de los casos,
en tu propia justicia! ¡Despierta, te digo, y Cristo te dará vida!
Porque Él es el Señor del cielo, el Espíritu que da vida,
quien nos vivifica por Su Espíritu,
si no le resistimos ni apagamos con nuestra desobediencia,
sino que más bien lo recibimos,
amamos y obedecemos en todas sus santas directrices y enseñanzas.
"`Porque todos los que son guiados por el Espíritu de Dios, __éstos__ son hijos de Dios.`"^
footnote:[Romanos 8:14]

A este Espíritu Santo encomiendo a mi lector, para que pueda ver mejor dónde está Él,
y así llegar a la verdadera fe y al beneficio de los hechos
y sufrimientos de nuestro bendito Señor y Salvador Jesucristo.
Porque, en verdad, Él salva del poder y de la contaminación del pecado,
así como también de su culpa, a todos los que oyen Su llamado,
abren la puerta de sus corazones,
y le permiten realizar una reforma real y completa en y para ellos.
De este modo, el beneficio,
virtud y eficacia de Sus hechos y sufrimientos fuera de nosotros,
llegan a aplicarse y a experimentarse de manera viva y efectiva dentro de nosotros,
y se llega a sentir y conocer una comunión con Cristo en Su muerte y sufrimientos,
conforme a la doctrina de los apóstoles.
Pero aquellos que continúan viviendo en el pecado que hizo sufrir a Cristo,
demuestran que no lo conocen,
aunque profesen ser salvos por causa de Su muerte y sufrimientos.

Concluyo este capítulo con este ferviente deseo: que, aunque las personas se equivoquen,
malinterpreten o tergiversen nuestros puntos de vista sobre este importante tema,
no se engañen a sí mismas en el gran asunto de su propia salvación,
y que no les ocurra que, mientras felizmente declaran que Cristo lo ha hecho todo,
sean halladas por Él como desconocidas en el día final.
Lee el capítulo 7 de Mateo:
aquel que oye a Cristo--la gran Palabra de Dios--y _hace_ lo que Él ordena,
manda y recomienda por Su propio y bendito ejemplo,
es comparado con un edificador prudente que edificó sobre un fundamento sólido.
Ninguna otra casa permanecerá en la sacudida y juicio final.
Por esta razón, a menudo somos claros,
directos y sinceros con las personas para que consideren
que Cristo no vino a salvarlos _en,_
sino _de_ sus pecados.
Aquellos que piensan librarse de Su yugo y carga, de Su cruz y Su ejemplo,
y se sienten seguros alabando a Cristo por haber hecho todo
por ellos (cuando Él ha obrado poco o nada en ellos,
ni ellos han renunciado a nada por amor a Él),
despertarán al fin en una espantosa sorpresa, al sonido de la final trompeta,
y ante esta triste e irrevocable sentencia: "`Apartaos de mí, hacedores de maldad,
nunca os conocí.`"^
footnote:[Mateo 7:23; Lucas 13:27]
Ojalá todos eviten este terrible fin prestando atención a tiempo
a la voz de la sabiduría y volviéndose ante Su reprensión. Porque
ciertamente ella los guiará por caminos de justicia,
y en medio de las sendas de juicio, sus almas llegarán a heredar la sustancia--sí,
riquezas duraderas y justicia en el reino de Dios.
