== Capítulo VII

[.chapter-subtitle--blurb]
Otros Principios y Prácticas Distintivos

Además de estas doctrinas generales,
que eran como largas ramas en el árbol del evangelio,
surgieron varias doctrinas y prácticas particulares que evidenciaban
aún más las verdades que este pueblo defendía. Y,
de hecho, muchas de estas ramas o testimonios más pequeños,
son los que otros profesantes del cristianismo pretenden sostener en palabras y formas,
pero no en el poder de la piedad.
Porque, hablando en términos generales, el poder ha estado perdido por mucho tiempo,
debido a que el hombre se ha apartado de la gracia
o Semilla de vida que está en él. Y habiéndola ignorado,
ha perdido el sentido de ella,
a pesar de que solo en y por medio de ella el hombre puede
ser vivificado para servir al Dios vivo en novedad de vida.
Por lo tanto,
al descubrir que la _vida_ de la religión había sido en gran medida abandonada,
y que la mayoría de los hombres vivían y adoraban a Dios según sus propias
voluntades--y no según la voluntad de Dios ni la mente de Cristo--lo que
el pueblo llamado Cuáqueros buscaba no era mera creencia,
sino verdadera experiencia; no formalidad, sino verdadera piedad;
porque llegaron a ser conscientes en sus corazones (por la obra de los
justos juicios de Dios) de que "`sin santidad nadie verá al Señor.`"^
footnote:[Hebreos 12:14]
Algunos de sus testimonios distintivos son los siguientes:

_En primer lugar, la comunión y el amor unos a otros._
Esta es una característica notable entre ellos,
reconocida por todo tipo de personas respecto a este pueblo.
Se reúnen, se ayudan y se mantienen unidos, tanto que es común oír decir a las personas:
"`¡Miren cómo se aman y se cuidan los Cuáqueros unos a otros!`"
Por lo tanto, si amarse unos a otros, gozar de una comunión íntima en la religión,
y manifestar una solicitud constante de reunirse para adorar a
Dios y ayudarse entre sí es una señal del cristianismo primitivo,
ellos la tenían de manera amplia.
¡Bendito sea el Señor!

_En segundo lugar, recomiendan el silencio por medio de su ejemplo._
Usan muy pocas palabras en toda ocasión,
ya que "`en las muchas palabras no falta el pecado.`"^
footnote:[Proverbios 10:19]
Buscan con frecuencia la soledad y el retiro, pero cuando se encuentran en compañía,
se esfuerzan por no usar, ni escuchar voluntariamente,
conversaciones innecesarias o injustas,
conservando así sus mentes puras y sin las perturbaciones
de muchos pensamientos y distracciones que no son de provecho.
También cumplen su palabra en los negocios.
Su sí es sí, y su no es no;
y sus clientes no pueden (ni con muchas palabras) disuadirlos de ella,
porque para ellos la verdad es más importante que la costumbre o la ganancia.

_En tercer lugar, enseñan y practican el amor a sus enemigos._
No solo se niegan a buscar venganza por cualquier mal que
les hayan hecho (condenando esto como un espíritu no cristiano),
sino que perdonan libremente,
e incluso ayudan y alivian a aquellos que han sido crueles con ellos,
aun cuando tienen el poder de vengarse de sus opresores.
Se podrían dar muchos ejemplos extraordinarios de esto si el tiempo lo permitiera.

_En cuarto lugar, sufrir en lugar de pelear, es otro testimonio peculiar de este pueblo._
Afirman que el Espíritu de Cristo enseña a los hombres
a volver sus espadas en rejas de arado,
sus lanzas en hoces, y a no adiestrarse más para la guerra,^
footnote:[Ver Isaías 2:4]
para que el lobo pueda morar con el cordero, y el becerro con el león,^
footnote:[Ver Isaías 11:6]
y nada que cause mal o destrucción se aloje en los corazones de las personas.
Así exhortan a los hombres a emplear su celo contra el pecado,
y a volver su ira contra Satanás,
haciendo guerra contra el pecado y la iniquidad para destronar al autor de toda enemistad.
Porque todas las guerras y los pleitos surgen de
las pasiones de los corazones de los hombres,
según el apóstol Santiago,^
footnote:[Santiago 4:1-2]
y no del Espíritu manso de Cristo Jesús,
quien es capitán de otra guerra que se libra con otras armas.
Y, en verdad,
su testimonio en este aspecto no debe considerarse un desprecio al gobierno cívico,
ya que, si no pueden pelear a su favor, tampoco pueden pelear en su contra.
Tampoco es razonable culparlos por no pelear por otros,
cuando ni siquiera pelearían por sí mismos.
Pero, aunque no están a favor de las guerras, sí están a favor de someterse al gobierno,
y esto no solo lo hacen por temor al castigo, sino también por causa de la conciencia,
siempre y cuando el gobierno no interfiera con ella.
Porque ellos creen que el gobierno es una ordenanza de Dios y un gran beneficio
para la humanidad dondequiera que se administre con justicia.

_En quinto lugar, se niegan a sostener o mantener un ministerio humano._
A Dios le ha placido llamarlos a salir de tal ministerio,
y por causa de conciencia no pueden apoyarlo; y es sobre esta base,
y no por desafío ni por codicia,
que rehúsan pagar diezmos o cualquier otro supuesto derecho eclesiástico semejante,
acerca de lo cual se han escrito muchos libros en su defensa.
No pueden sostener con su dinero lo que no pueden aprobar, sino que, en verdad,
deben testificar en contra por dos razones: Primera,
porque todo mantenimiento obligatorio es expresamente contrario al mandamiento de Cristo,
quien dijo: "`Gratuitamente habéis recibido, gratuitamente dad;`"^
footnote:[Mateo 10:8 RV 1602 Purificada]
de modo que cualquier apoyo a los ministros del evangelio debe ser voluntario y no forzado.
Y segunda,
porque los ministros nacionales no tienen el Espíritu Santo como su fundamento,
sino una variedad de artes y conocimientos humanos.

_En sexto lugar, hablan verdad en toda ocasión, pero no se atreven a jurar;_
porque Cristo lo prohíbe, diciendo: "`Pero yo os digo: No juréis en ninguna manera;
ni por el cielo, porque es el trono de Dios; ni por la tierra,
porque es el estrado de sus pies; ni por Jerusalén,
porque es la ciudad del gran Rey... Pero sea vuestro hablar: Sí, sí; no, no;
porque lo que es más de esto, de mal procede.`"^
footnote:[Mateo 5:34-37]
Y Santiago, Su seguidor, dice: "`Pero sobre todo, hermanos míos, no juréis,
ni por el cielo, ni por la tierra, ni por ningún otro juramento;
sino que vuestro sí sea sí, y vuestro no sea no, para que no caigáis en condenación.`"^
footnote:[Santiago 5:12]
Jurar es innecesario y también malo,
porque el motivo de jurar es que el hombre no dice la verdad, cuando su sí,
realmente no es sí. Los juramentos se usaban para forzar a los hombres a decir la verdad,
y para darles a otros la seguridad de que lo que se había jurado era cierto.
Pero el sí del cristiano verdadero,
siendo realmente sí (porque él mismo ya está ligado
a la verdad) cumple el propósito del juramento,
y, por lo tanto, su uso es innecesario, superfluo y procede del mal.

_En séptimo lugar, no se permiten dar honores mundanos,
cumplidos vanos o títulos halagadores,
ni usar los saludos frecuentes y de moda de la época_.^
footnote:[En este tiempo,
el saludo común entre las personas consistía en arrastrar
el pie derecho hacia atrás sobre el suelo,
inclinarse mientras se quitaban el sombrero, y entonces,
adularse uno a otro con títulos como "`su Señoría`" o "`su Eminencia,`" etc.]
Esto lo evitan porque ven claramente la vanidad,
el orgullo y la ostentación que corresponden a tales cosas.
Cristo también prohibió tales cosas en Su día,
denunciando el espíritu que se halaga a sí mismo,
que ama las salutaciones en las plazas y que los hombres le llamen
"`Rabí.`" Su no conformación en estas cosas no proviene del orgullo,
la mala educación, capricho, ni buscan de esta manera distinguirse como un grupo,
sino que es por obediencia a la perspectiva y conciencia que han recibido del
Espíritu de Cristo respecto al origen y la tendencia perversa de tales cosas.
Y aunque esto ha hecho que su conducta sea desagradable para muchos
que son amadores de sí mismos y de ese honor que viene de los hombres,
con todo, tienen presente lo que Cristo les dijo a los judíos:
"`¿Cómo podéis vosotros creer, pues recibís gloria los unos de los otros,
y no buscáis la gloria que viene del Dios único?`"^
footnote:[Juan 5:44]

_En octavo lugar, han regresado a la manera simple de hablar._
Es decir, a usar _tú_ o _usted_ con una sola persona,
independientemente de su estatus o grado entre los hombres.^
footnote:[En el idioma inglés del siglo XVI, se puso de moda,
como una manera de mostrar honor o de halagar,
utilizar los equivalentes plurales "`vosotros`" o "`ustedes`"
para dirigirse a una sola persona de mayor estatus social,
mientras que las formas singulares "`tú`" o "`usted`" se reservaban para sirvientes,
niños o personas de una condición social o económica inferior.
Los primeros Amigos se mantuvieron en "`el lenguaje
simple`"--usando "`tú`" y "`usted`" con una persona,
y "`vosotros`" y "`ustedes`" con dos o más personas--sin
mostrar preferencia hacia ciertos individuos.
Esto puede parecer un asunto pequeño para un lector del siglo XXI,
pero es impresionante cuántos miles de Amigos fueron insultados, golpeados,
encarcelados e incluso colgados por negarse a seguir estas costumbres.]
Y aunque los hombres no usan otro lenguaje cuando se dirigen a Dios,^
footnote:[Aunque las personas en este tiempo usaban el plural "`vosotros`"
y "`ustedes`" para dirigirse a una sola persona de mayor estatus social,
todos continuaban usando "`tú`" para dirigirse a Dios en oración.
A los primeros amigos les parecía extraño e hipócrita que,
aunque sus perseguidores oraran a su Creador usando "`tú,`" no
toleraran que se dirigieran a ellos con el mismo lenguaje.]
ellos raras veces soportan que les hablemos de la misma manera.
Esto ha sido una gran prueba para el orgullo de muchos,
mostrando su ceguera y debilidad interior,
a pesar de su orgullosa profesión externa de religión. Y en verdad,
la postura de este pueblo en este punto es puramente por causa de conciencia,
independientemente de lo que la gente piense o diga de ellos.
Y aunque sean despreciados y tratados con maldad,
su manera sencilla de hablar está respaldada tanto por las Escrituras como por la gramática;
y así como tienen la corrección de lenguaje a su favor,
también han hallado paz en su práctica.

_En noveno lugar,
la simpleza y sencillez en su vestimenta y en el
mobiliario es otro testimonio peculiar de ellos,
junto con la moderación en la comida y la abstinencia de las vanas
recreaciones y pasatiempos del mundo_--todo lo cual el Espíritu
del Señor Jesucristo les ha enseñado que es conforme a la piedad.
Por lo tanto,
durante mucho tiempo han exhortado a todos a que
"`su modestia sea conocida a todos los hombres;`"^
footnote:[Filipenses 4:5 RVG, y RV1602 Purificada]
puesto que se han dado cuenta de que el Señor está
cerca para entrar en juicio contra toda extravagancia,
falta de modestia y exceso.

_En décimo lugar, se abstienen, en conciencia para con Dios,
de observar los llamados días santos y las festividades públicas._
Ellos saben que tales prácticas carecen de mandato divino, pues han sido instituidas,
ordenadas y establecidas según la voluntad del hombre.

_Por último,
han sido guiados por el buen Espíritu de nuestro Señor Jesucristo (siguiendo
el ejemplo de los primeros santos) a velar los unos por los otros,
para la preservación de toda la Sociedad,
en una conducta y disciplina acordes a su santa profesión._ El primer asunto de
importancia que surgió entre ellos como sociedad fue el ejercicio de la caridad:
suplir las necesidades de los pobres, y cuidar de las viudas,
los huérfanos y los desamparados.
En consecuencia,
se hacían colectas generosas para este y varios otros servicios en la iglesia,
que eran confiadas a hombres fieles de buena reputación,
que temían a Dios y no se cansaban de hacer el bien.
Esta sigue siendo su práctica regular y cuidadosa en todos
los lugares donde se encuentra este pueblo.

Y a medida que su número aumentaba considerablemente tanto en la ciudad
como en el campo--de modo que eran observados por toda clase de curiosos--les
preocupaba que todos los que pertenecían a la Sociedad caminaran como
es digno del evangelio en toda su conducta entre los hombres,
y en toda ocasión. Pues así como no obligan a nadie a unirse a ellos;
también insisten justamente en que quienes son de ellos anden conforme a su profesión,
para ser reconocidos por ellos y permanecer en comunión con ellos.

Y para que este buen orden se mantenga en los caminos de la verdad y sobriedad,
y para el consuelo y la edificación de la Sociedad,
se fijaron reuniones selectas para asuntos de negocios,
supervisión y disciplina en todos los lugares que habitan,
las cuales se celebran mensualmente, confluyendo en Reuniones Trimestrales,
y estas a su vez en una Reunión Anual mayor.
Estas fueron establecidas para mejorar la comunicación entre
ellos en aquellas cosas que sostienen la piedad y la caridad,
y para la administración cuidadosa de los pobres, huérfanos, conducta ordenada,
la integridad de su profesión religiosa, y el registros preciso de nacimientos,
matrimonios, entierros, sufrimientos y otros asuntos semejantes,
a fin de que este pueblo viva pacíficamente entre los hombres
y sea buen ejemplo en todas las cosas.

Este, pues, es el testimonio que debo dar del pueblo de Dios llamado Cuáqueros,
en cuanto a su surgimiento, apariencia, principios y prácticas en esta época del mundo,
tanto respecto de su fe y adoración, como de su disciplina y conducta.
