== Capítulo VIII

[.chapter-subtitle--blurb]
Varias Exhortaciones

Y ahora, Amigos, ustedes que profesan andar en este camino, permitan, les ruego,
una palabra de exhortación --padres como hijos, ancianos como jóvenes.
La gloria de este día,
y el fundamento de la esperanza que nos ha hecho no avergonzarnos
desde que el Señor nos reunió para ser un pueblo,
como saben, es aquel bendito don de la luz y la vida de Cristo que profesamos,
y hacia el cual dirigimos a todas las personas,
como el gran y divino instrumento y agente de la conversión del hombre a Dios.
Fue por este don que fuimos primero alcanzados y eficazmente
iluminados en cuanto a nuestro estado interior,
lo cual nos llevó a considerar nuestro fin,
llevándonos a poner al Señor delante de nuestros ojos y a contar nuestros días,
para que aplicáramos nuestros corazones a la sabiduría.

En aquel día no juzgábamos según la vista del ojo, ni según el oír del oído,
sino conforme a la luz y sentido que recibíamos de este bendito don; sí,
por él juzgábamos y actuábamos, en lo que se refería a las cosas y a las personas,
a nosotros mismos y a otros, y aun para con Dios nuestro Hacedor.
Porque siendo vivificados por este don en nuestro hombre interior,
fácilmente podíamos discernir la diferencia entre las cosas,
llegando a sentir lo que era correcto y lo que era errado,
lo que era conveniente y lo que no,
tanto en lo concerniente a los asuntos religiosos como a los civiles.
Y siendo este don de luz y vida el fundamento de la comunión de todos los santos,
era en él que nuestra comunión permanecía. En él
deseábamos conocernos los unos a los otros,
y obrar los unos para con los otros, y para con todos los hombres, en amor,
fidelidad y temor.

Cuando sentíamos las agitaciones y movimientos de esta gracia en nuestros corazones,
nos acercábamos al Señor y esperábamos ser preparados por ella,
para que pudiéramos sentir persuasiones y movimientos
antes de aproximarnos al Señor en oración,
o de abrir nuestras bocas en el ministerio.
En comenzar y terminar unidos a esta gracia estaba nuestro consuelo,
servicio y edificación. Y cuando nos adelantábamos a ella,
o quedábamos cortos en nuestros servicios,
nos cargábamos con pesadas cargas que teníamos que soportar;
hallando en nosotros una reprensión en vez de una aceptación, y en lugar de un "`Bien,
buen siervo,`" encontrábamos: "`¿Quién ha demandado esto de vuestras manos?`"^
footnote:[Isaías 1:12]
En aquel día éramos un pueblo muy ejercitado por Dios;
aun nuestro propio semblante y porte lo declaraban.

El cuidado de por los demás estaba entonces muy presente entre nosotros,
así como por nosotros mismos, y en especial por los recién convencidos.
A menudo teníamos la carga de la palabra del Señor por nuestros vecinos,
parientes y conocidos, y algunas veces por extraños también. Asimismo,
sufríamos dolores de parto por la preservación de unos y otros; no buscando,
sino evitando toda ocasión de frialdad o malentendido,
tratándonos unos a otro como quienes creían y sentían a Dios presente,
lo cual mantenía nuestra conducta inocente, seria y sobria,
guardándonos de las preocupaciones y amistades del mundo.
Sosteníamos la verdad en el Espíritu de ella, y no en nuestros propios espíritus,
ni según nuestras propias voluntades y afectos.

Estábamos humillados y sometidos al Señor,
de tal manera que era visible para todos los que nos conocían podían verlo.
No nos considerábamos a nuestra propia disposición, para ir a donde quisiéramos,
o decir o hacer lo que quisiéramos, o cuando lo quisiéramos.
Nuestra libertad estaba en la libertad del Espíritu de verdad; y ningún placer,
ni ganancia, ni miedo, ni favor, podían sacarnos de esta postura retirada,
estricta y vigilante.
Estábamos tan lejos de buscar ocasión de compañía social,
que la evitábamos cuando podíamos,
ocupándonos de nuestros propios negocios con moderación,
en lugar de entrometernos innecesariamente en los asuntos de otras personas.

Nuestras palabras eran pocas y "`sazonadas con sal,`"
nuestras expresiones serenas y sobrias,
y toda nuestra conducta estaba a la vista de todos.
Y es cierto que este tipo de vida retirada y estricta nos exponía
a la crítica de muchos de los libertinos y humoristas del mundo,
y de personas engreídas y llenas de su propia justicia;
pero era nuestra preservación de muchas trampas a las que los demás estaban
continuamente expuestos debido al predominio de los deseos de los ojos,
los deseos de la carne y la vanagloria de la vida,
que nunca carecen de oportunidad para atraer a los
hombres hacia la comunión con el mundo.

No puedo olvidar la humildad y el celo santo de aquel día. Oh,
cuán constantes en las reuniones, y cuán vigilantes en ellas;
cuán fieles a la vida de la verdad, así como también a los principios de la verdad;
y cuán sencillos y unidos nos sentíamos en nuestra comunión,
como en verdad corresponde a aquellos que profesan
tener una sola Cabeza --Cristo Jesús el Señor.

Ahora bien, primero, a ustedes mis amados y muy honrados hermanos en Cristo,
que están en el ejercicio del ministerio.
A ustedes les digo: ¡Oh, sientan vida en su ministerio!
Dejen que la vida sea su comisión, su fuente y tesoro en todas esas ocasiones;
de lo contrario (como bien saben) no se puede engendrar nada para Dios.
Porque nada da vida sino la vida de Dios;
y solo un ministerio en y desde esta vida puede vivificar a un
pueblo para Él. Hemos visto el fruto de todos los demás ministerios,
y cuán pocos son realmente vueltos por ellos de la maldad de sus caminos.
No es nuestro estudio, nuestra memoria,
ni la repetición de revelaciones pasadas en nuestra propia
voluntad y tiempo lo que realizará la obra de Dios.
Un ministerio doctrinal y seco, por más sólido que sea en palabras,
solo puede alcanzar los oídos, y su efecto, en el mejor de los casos, es como un sueño.

Hay otro tipo de solidez que es más eficaz que todo, a saber: Cristo el poder de Dios.
Esta es la llave de David, que abre y ninguno puede cerrar;
y cierra y ninguno puede abrir.
Este poder es a las palabras, lo que el aceite es a una lámpara,
y lo que el alma es al cuerpo, lo que hizo que Cristo dijera:
"`Mis palabras son Espíritu y son vida;`"^
footnote:[Juan 6:63]
es decir, proceden de la vida, y, por lo tanto, vivifican a todos los que las reciben.
Y si los discípulos que habían vivido con Jesús debieron
quedarse en Jerusalén hasta recibir este poder,
mucho más debemos nosotros esperar para recibir poder
de lo alto antes de ministrar en Su nombre,
si en verdad buscamos que las personas "`se conviertan de las tinieblas a la luz,
y de la potestad de Satanás a Dios.`"^
footnote:[Hechos 26:18]

Doblo fervientemente mis rodillas ante el Dios y Padre de nuestro Señor Jesucristo,
para que siempre sean de un mismo sentir,
y siempre esperen con reverencia la venida y revelación de la Palabra de vida,
y se aferren a ella en su ministerio y servicio,
y así puedan servir a Dios en Su propio Espíritu.
Y si su servicio es poco o mucho, está bien; pues mucho no es demasiado,
y lo mínimo es suficiente, siempre que fluya de la inspiración del Espíritu de Dios.
Pero, en verdad, sin ella, por mínimo que sea, es demasiado, y no tiene provecho alguno.

Porque es el Espíritu del Señor,
ya sea de manera directa o por medio del ministerio de Sus siervos,
el que enseña a Su pueblo provechosamente;^
footnote:[Ver Isaías 48:17]
y somos de provecho solo en la medida en que Lo llevemos con nosotros en nuestros servicios,
y no más allá. Porque si el Señor es quien debe obrar
todas las cosas en nosotros para nuestra salvación,
mucho más debe obrar a través de nosotros para la conversión y edificación de otros.
Por lo tanto, si alguna vez fue una cruz para nosotros hablar en Sus asambleas,
aunque el Señor lo demandaba de nuestras manos,
que nunca lo sea permanecer en silencio cuando Él lo demande.

Uno de los dichos más terribles en el libro de Dios dice:
"`Si alguno añadiere a las palabras de la profecía de este libro,
Dios traerá sobre él las plagas que están escritas en este libro.`"
Y retener el consejo de Dios es igual de terrible:
"`si alguno quitare de las palabras del libro de esta profecía,
Dios quitará su parte del libro de la vida.`"^
footnote:[Apocalipsis 22:18-19]
En verdad,
esto contiene una gran advertencia para todos los que usan el nombre del Señor;
para que estén bien seguros de que el Señor efectivamente habla,
y no se hallen entre el número de los que añaden al testimonio que el Señor les da,
ni entre los que lo retienen o disminuyen--pues ambas cosas son muy ofensivas para Dios.

Por lo tanto, hermanos, tengamos cuidado de no adelantarnos a nuestro líder,
ni de quedarnos atrás de Él, puesto que aquel que se apresura puede perder su camino,
y el que se queda atrás puede perder a su guía. Porque incluso
aquellos que anteriormente recibieron poder de lo alto,
tenían que esperar a recibir sabiduría para ver cómo "`usar bien la palabra;`"^
footnote:[2 Timoteo 2:15]
lo cual claramente implica que es posible que quien ha recibido la palabra del Señor,
dé un paso en falso en su uso y aplicación. Esto, sin duda,
proviene de un espíritu impaciente que actúa por sí mismo,
que produce una mezcla insana y peligrosa.
Un ministerio como este nunca podrá engendrar correctamente
para Dios un pueblo vivo y recto.

Siento mucha seriedad con respecto a esto, por encima de toda otra consideración,
sabiendo bien lo mucho que concierne al estado y preservación, presentes y futuros,
de la iglesia de Cristo Jesús,
la cual ha sido reunida y edificada por un ministerio vivo y poderoso.
Que sus ministerios, entonces, se mantengan,
se preserven y continúen siempre en las manifestaciones,
movimientos y provisiones de la misma vida y poder.

Y dondequiera que se observe que alguno ministra más a partir de sus dones y
habilidades que a partir de la vida y poder--aunque tenga un entendimiento iluminado
y doctrinal--sea debidamente advertido y amonestado para su propia preservación;
ya que éstos, sin duda, llegarán a depender de su propia autosuficiencia,
abandonando sin darse cuenta a Cristo, la Fuente viva,
para cavar para sí cisternas que no podrán retener aguas vivas.^
footnote:[Ver Jeremías 2:13]
Y, poco a poco, apartarán también a otros de esperar en el don de Dios en ellos mismos,
y de sentirlo obrar en otros (para su fortaleza y refrigerio), para que esperen _en ellos,_
y así se vuelvan de Dios al hombre otra vez.
Estos naufragan en cuanto a esa fe que una vez fue dada a los santos,
y a una buena conciencia hacia Dios,
las cuales solo se mantienen por ese don divino de vida que primero engendra la fe,
y luego despierta y santifica la conciencia.

Tampoco es suficiente que alguna vez hayamos experimentado el don divino,
y que por él hayamos alcanzado a los espíritus encarcelados,
y que hayamos sido los instrumentos para convencer a otros del camino de Dios,
si no permanecemos tan bajos y pobres en nosotros mismos,
y tan dependientes del Señor como siempre.
Porque ni la memoria, ni la repetición de revelaciones o experiencias anteriores,
llevará un alma a Dios, o dará pan a los hambrientos, o agua a los sedientos,
a menos que la vida acompañe todo lo que decimos; y eso debe ser esperado.

¡Oh que no tengamos ninguna otra fuente,
tesoro ni dependencia! ¡Que nadie se atreva a obrar por sí mismo para Dios,
simplemente porque por mucho tiempo ha obrado desde Dios!
Que nunca reemplacemos la necesidad de esperar,
con palabras que surjan de nuestra propia sabiduría,
ni pensemos que podemos hablar con menor cuidado y mayor libertad que antes.
Y que en el momento en que no sintamos que el Señor nos abre y nos ensancha con Su poder,
nunca excedamos Su provisión, ni llenemos el tiempo con lo nuestro,
sin importar lo que hayamos hecho en el pasado o cuál sea la expectativa de la gente.

Espero que siempre recordemos quién fue el que dijo:
"`Separados de mí nada podéis hacer.`"^
footnote:[Juan 15:5]
Nuestra competencia proviene de Él. Y, en verdad,
el ministerio del Espíritu debe mantener su paralelo
y concordancia con el nacimiento del Espíritu;
así como ningún hombre puede heredar el reino de Dios si no ha nacido del Espíritu,
tampoco ningún ministerio puede engendrar un alma para Dios sino aquel que es del Espíritu.
Fue por esto, como dije antes, que los discípulos esperaron antes de salir;
y fue en este mismo poder que nuestros ancianos hermanos
y mensajeros de Dios en nuestro día esperaron,
nos visitaron y nos alcanzaron.

Así pues, habiendo comenzado en el Espíritu,
que nadie jamás espere o busque ser perfeccionado en la carne;
porque ¿qué tiene que ver la carne con el Espíritu, o la paja con el trigo?
Y si permanecemos en el Espíritu, permaneceremos en la unidad de Él,
que es el fundamento de toda verdadera comunión. Porque al beber de un mismo Espíritu,
somos hechos un solo pueblo para Dios,
y por Él somos guardados en la unidad de la fe y en el vínculo de la paz.
De esta manera, ninguna envidia,
ni amargura ni contienda podrá tener lugar entre nosotros.
Así continuaremos velando unos por otros para bien, y no para mal; y jamás envidiaremos,
sino más bien nos regocijaremos plenamente al ver a otros crecer en las
riquezas de esa gracia mediante la cual Dios colma a Sus siervos fieles.

Y hermanos, ya que se les han encomendado los oráculos de Dios,
que les da frecuentes oportunidades y gran libertad con las personas entre las que viajan,
les ruego que no piensen que basta con declarar la palabra de vida en sus asambleas,
por muy edificantes y reconfortantes que sean esas
oportunidades tanto para ustedes como para ellos.
Sino que--como era la práctica del hombre de Dios
antes mencionado cuando estaba entre nosotros^
footnote:[Se refiere a George Fox]
--examinen el estado de las iglesias que visitan,
indagando quiénes entre ellos están afligidos o enfermos, quiénes son tentados,
y si alguno es infiel u obstinado, y entonces,
procuren atender estas cosas en la sabiduría y poder de Dios.
Esto allanará el camino para ustedes en sus corazones,
para que los reciban como hombres de Dios,
y les dará crédito con ellos para que puedan hacerles bien aconsejándolos en otros aspectos.
De este modo, los afligidos serán consolados por ustedes,
los tentados serán fortalecidos, los enfermos refrescados,
los infieles reprendidos y restaurados,
y los obstinados serán ablandados y preparados para la reconciliación.
Así se mostrarán como verdaderos obreros de Dios,
llevando a cabo sus asuntos para la alabanza de Su nombre,
quien los ha llamado de las tinieblas a la luz,
para que puedan volver a otros del poder de Satanás a Dios y a Su reino,
que está dentro.

Y ustedes, jóvenes convencidos,
les ruego y exhorto a esperar de manera diligente y casta en Dios,
en el camino de Su bendita manifestación y aparición interior en sus corazones.
No miren hacia afuera, sino hacia adentro.
No permitan que la libertad de otro sea trampa para ustedes; ni actúen por imitación,
sino por un verdadero sentir y experimentar el poder de Dios en ustedes mismos.
¡Oh, no aplasten los tiernos brotes de Su planta en sus almas,
ni se adelanten a sus movimientos santos y gentiles
debido a sus deseos y al ardor de sus afectos!
Recuerden que es una "`voz suave y delicada`"^
footnote:[1 Reyes 19:12 Reina Valera de Gómez]
la que nos habla en este día. No se puede escuchar
en el ruido ni en la prisa de la mente,
sino que se entiende con claridad en un estado retirado y vigilante.
Jesús amaba y a menudo escogió la soledad, yendo a las montañas,
a los huertos y a la orilla del mar para evitar las multitudes y el ajetreo,
y para mostrarles a Sus discípulos que era bueno
ser solitarios y estar libres de este mundo.

Dos enemigos yacen cerca de ustedes: la imaginación y la libertad carnal.
Pero la verdad simple, santa y viva que los ha convencido también los preservará,
si le prestan atención en ustedes mismos, y llevan todos los pensamientos,
inclinaciones y afectos a la luz, para ver si son hechos en Dios,
o si son del enemigo o de ustedes mismos.
De esta manera, se formará y preservará en ustedes un verdadero gusto,
discernimiento y juicio acerca de lo que deben hacer y dejar de hacer.
En su diligencia y fidelidad llegarán a heredar la sustancia, y Cristo,
la sabiduría eterna de Dios, llenará sus tesoros.
Y cuando sean convertidos, así como también convencidos,
entonces fortalezcan a sus hermanos,
y estén listos para toda buena palabra y obra a la cual el Señor los llame.
Entonces podrán vivir para la alabanza de Aquel que los ha escogido para ser
partícipes con los santos en luz de un reino que no puede ser conmovido,
de una herencia incorruptible en las moradas eternas.

Y ahora, en cuanto a ustedes, los hijos del pueblo de Dios,^
footnote:[Aquí se está dirigiendo a los hijos de la primera generación de Amigos.]
un gran peso reposa sobre mi espíritu por su bien,
y con frecuencia doblo mis rodillas ante el Dios de sus padres por ustedes,
para que lleguen a participar de la misma vida y
poder divinos que han sido la gloria de este día,
y lleguen a ser linaje de Dios, una nación santa y un pueblo adquirido,
celoso de buenas obras, cuando todas nuestras cabezas reposen en el polvo.
¡Oh jóvenes, hombres y mujeres, que no les baste ser hijos del pueblo del Señor;
es necesario que también nazcan de nuevo si desean heredar el reino!
Sus padres no son más que carne,
y solo pueden engendrarlos a la semejanza del primer Adán;
pero ustedes deben ser engendrados a la semejanza
del segundo Adán por medio de un nacimiento espiritual,
o no serán, _ni podrán ser,_ Sus hijos ni Su descendencia.

Por lo tanto, examínense cuidadosamente, ¡oh, hijos de los hijos de Dios!
Consideren su condición, y vean que son en relación con este parentesco,
familia y nacimiento divinos.
¿Han obedecido la luz, y han recibido y andado en el Espíritu,
el cual es la Semilla incorruptible y Palabra del reino de Dios,
de la que deben nacer de nuevo?
Dios no hace acepción de personas.
El padre no puede salvar ni responder por el hijo, ni el hijo por el padre.
En el pecado que cometan morirán; y en la justicia que hagan, por medio de Cristo Jesús,
vivirán; porque "`Si quisiereis y oyereis, comeréis el bien de la tierra.`"^
footnote:[Isaías 1:19]
No se engañen, Dios no puede ser burlado.
Todo lo que las naciones y pueblos siembren, eso segarán de la mano del Dios justo.
Y entonces sus muchos y grandes privilegios (por encima de los
hijos de otros pueblos) añadirán peso a la balanza contra ustedes,
si no escogen el camino del Señor. Porque no solo han tenido buena doctrina,
sino también buen ejemplo; y lo que es más,
han sido vueltos y han conocido a esa luz celestial de la que otros han estado,
en general, muy ignorantes.
Y si ustedes,
después de oír y ver las maravillas que Dios ha obrado en la liberación y preservación
de sus honorables padres (incluso a través de un mar de aflicciones),
y de contemplar las bendiciones temporales y espirituales
con las que Él los ha colmado ante la vista de sus enemigos;
digo, si descuidan y le dan la espalda a una salvación tan grande y cercana,
no solo serían los hijos más ingratos tanto para Dios como para ellos,
sino que no podrán evitar recibir un horrendo juicio de la mano
del Señor. ¡Pero que nunca sea así con ninguno de ustedes,
dice mi alma!

Por lo tanto, jóvenes, hombres y mujeres, vuelvan su mirada a la Roca de sus padres;
no hay otro Dios sino Él. No hay otra luz sino la de Él, ni otra gracia sino la de Él,
ni otro Espíritu sino el de Él para convencerlos, vivificarlos y consolarlos;
para conducirlos, preservarlos y guiarlos al reino eterno de Dios.
Búsquenlo, para que sean poseedores, así como profesantes de la verdad,
abrazándola no solo por educación, sino por juicio y convicción,
a partir de una sensibilidad engendrada en sus almas mediante
la operación del eterno Espíritu y poder de Dios.
Solo por esto llegarán a ser de la simiente de Abraham por medio de la fe,
y a experimentar la circuncisión no hecha con manos,
y así se convertirán en herederos de la promesa hecha a los padres de una corona incorruptible.
Entonces, como dije antes, llegarán a ser linaje de Dios,
sosteniendo la profesión de Su bendita verdad en la vida y poder de ella.
Porque la formalidad en la religión repugna a Dios y a todo hombre bueno.
Por tanto, les digo, cuídense de caer en la superficialidad y formalidad,
continuando con nuestra profesión religiosa sin esa sal y sabor por los
cuales ha llegado a obtener un buen testimonio entre los hombres.
Porque dondequiera que Su virtud divina no se sienta en el alma,
ni se espere ni se viva en ella, las impurezas brotarán y se mostrarán rápidamente,
y manifestarán la infidelidad de aquellas personas cuyos corazones no están sazonados
con la naturaleza de ese Espíritu Santo que profesan.

Por lo tanto, queridos hijos,
permítanme rogarles que cierren sus ojos ante las
tentaciones y seducciones de este mundo vil y perecedero,
y que no permitan que sus afectos sean cautivados
por esos deseos y vanidades a los que sus padres,
por amor de la verdad hace mucho tiempo, les dieron la espalda.
Antes bien, crean en la verdad y recíbanla en sus corazones,
para que sean hechos hijos de Dios,
y nunca se diga de ustedes lo que el evangelista escribió de los judíos en su tiempo,
que Cristo, la luz verdadera, "`vino a lo suyo, pero los suyos no le recibieron.`"^
footnote:[Juan 1:11]
Porque al igual que los judíos de aquel tiempo,
ustedes tienen el nombre y las prácticas del pueblo de Dios (puesto que son sus hijos),
y se puede decir que Cristo, mediante Su luz en ustedes, ha venido a los suyos;
pero si no le obedecen,
y le dan la espalda a Su luz al caminar en pos de las vanidades de sus mentes,
serán contados con aquellos que "`no lo recibieron.`"
Por lo tanto, vuélvanse al Señor y a Su don y Espíritu dentro de ustedes.
Escuchen Su voz y obedézcanla,
para que puedan poner su sello al testimonio de sus
padres por la evidencia de su propia experiencia.
Así las canas de sus queridos padres, que aún viven, descenderán a la tumba con alegría,
sabiendo que el Espíritu y naturaleza que han conocido y
amado vivirá en ustedes cuando ellos se hayan ido.

[.asterism]
'''

Concluiré este capítulo con unas pocas palabras dirigidas
a aquellos que no son de nuestra comunidad,
a cuyas manos pueda llegar este pequeño libro.

Amigos, puesto que son hijos e hijas de Adán, y mis hermanos según la carne,
mis deseos y oraciones a Dios han sido frecuentes y fervientes por ustedes, para que,
mediante el poder y Espíritu de Su Hijo Jesucristo--a quien Él ha dado como luz
y vida del mundo--experimenten que su Creador se convierta en su Redentor,
y un Restaurador de esa santa imagen que han perdido a causa del pecado.
¡Y oh, que ustedes, que son llamados cristianos,
lo reciban verdaderamente en sus corazones;
porque allí es donde lo necesitan! Él está a la puerta de sus corazones,
y llama para que lo dejen entrar;
pero ¡ay! encuentra que ya están llenos de otros invitados,
de modo que un pesebre solitario es Su porción entre ustedes,
como lo fue en la antigüedad.
Sin embargo,
ustedes están llenos de creencias y conceptos como
los judíos pretenciosos que no lo conocieron,
sino que lo rechazaron y maltrataron en los días de Su carne.
Y al igual que ellos,
si ustedes no llegan a poseer y a experimentar lo que profesan con palabras,
toda su formalidad en la religión no servirá de nada en el día del juicio de Dios.

Les ruego que reflexionen respecto a su condición eterna, y consideren qué derecho,
fundamento y cimiento tienen para su cristianismo.
¿Tienen algo más que una profesión y una creencia histórica de las verdades del evangelio?
¿Han experimentado el bautismo del Espíritu Santo y fuego,
y el aventador de Cristo que avienta la paja en sus corazones,
con todos los deseos y afectos carnales?
¿Experimentan la levadura divina del reino que, al ser recibida,
leuda toda la masa del hombre, santificándolo por completo, en cuerpo, alma, y espíritu?^
footnote:[Ver 1 Tesalonicenses 5:23]
Si este no es el fundamento de su confianza, todavía están en un estado miserable.

Quizás digan que, aunque son pecadores y viven diariamente bajo el dominio del pecado,
y no están santificados como lo he descrito, aun así, tienen fe en Cristo,
quien llevó la maldición por ustedes,
y que están completos en Él por la fe--habiéndoles sido imputada Su justicia.
Pero, mis amigos,
permítanme rogarles que no se engañen a sí mismos en un asunto
tan importante como es el destino de sus almas inmortales.
Si tienen verdadera fe en Cristo, su fe los purificará.^
footnote:[Ver Hechos 15:9]
Sí, los santificará; porque la fe de los santos fue "`su victoria sobre el mundo.`"^
footnote:[1 Juan 5:4]
Por la fe vencieron el pecado dentro de ellos, y a los hombres pecadores fuera de ellos.
Y si en verdad están en Cristo, no andarán conforme a la carne,
sino conforme al Espíritu, cuyos frutos son evidentes para todos.
Serán una nueva creación, nuevamente hechos, nuevamente formados,
según la voluntad y el molde de Dios.
Las cosas viejas habrán pasado, y he aquí, todas serán nuevas, es decir, nuevo amor,
deseos, voluntad, afectos y prácticas.
Ya no serán más ustedes quienes vivan (la parte carnal,
desobediente y mundana de ustedes), sino Cristo quien vive en ustedes.
El vivir será Cristo, y el morir será su ganancia eterna,
estando asegurados de que "`lo corruptible se vista de incorrupción,
y lo mortal se vista de inmortalidad,`"^
footnote:[1 Corintios 15:53]
teniendo una casa gloriosa, eterna en los cielos,
que nunca envejecerá ni pasará. Todo esto proviene
de la verdadera realidad de estar en Cristo,
así como el calor procede del fuego, y la luz del sol.

Por tanto,
tengan cuidado de presumir estar a salvo según tal suposición--creyendo
que están en Cristo cuando todavía viven en su vieja naturaleza
caída. Porque "`¿qué comunión tiene la luz con las tinieblas,
o Cristo con Belial?`"^
footnote:[2 Corintios 6:14-15]
Escuchen lo que el discípulo amado les dice: "`Hijitos, nadie os engañe;
el que hace justicia es justo, como Él es justo.`"^
footnote:[1 Juan 3:7]
Y también: "`Si decimos que tenemos comunión con él, y andamos en tinieblas, mentimos,
y no practicamos la verdad.`"^
footnote:[1 Juan 1:6]
Es decir, si continuamos en un camino pecaminoso,
cautivados por nuestros afectos carnales y no somos convertidos a Dios,
andamos en tinieblas y, en ese estado no podemos tener ninguna comunión con Dios.

Cristo reviste con Su justicia a los que reciben Su gracia en sus corazones,
se niegan a sí mismos, toman Su cruz diariamente y le siguen.
La justicia de Cristo hace que los hombres sean santos en el interior--de mente,
voluntad y prácticas santas.
El hecho de que la tengamos no significa que no sea de Cristo;
porque no es nuestra por naturaleza, sino por fe y adopción; es el don de Dios.
Pero, aun así, aunque no es nuestra justicia,
como _de_ nosotros o _proveniente de_ nosotros (porque en ese sentido es de Cristo,
siempre de y proveniente de Él), sin embargo, _es_ nuestra, y _debe ser nuestra_ en posesión,
eficacia y experiencia, para que nos haga algún bien; de lo contrario,
la justicia de Cristo no nos será de ningún provecho.
Fue de esta manera que Él fue hecho para los primeros cristianos su "`justicia,
santificación, justificación y redención`"^
footnote:[1 Corintios 1:30]
--no una imputación imperceptible,
sino una transformación palpable.
Y si alguna vez desean conocer el consuelo,
la sustancia y la médula de la religión cristiana,
deberán aprenderla y obtenerla también de esta manera.

Ahora, mis amigos, por lo que han leído,
pueden percibir que Dios en verdad ha visitado a un pueblo menospreciado
entre ustedes con este conocimiento y testimonio salvador--un pueblo
que Él ha sostenido y aumentado hasta hoy,
a pesar de la feroz oposición que ha encontrado.
Por lo tanto, no menosprecien la pequeñez de esta aparición; era, y todavía es,
(lo sabemos) un día de pequeñeces y de poca importancia para muchos,
y se le han dado muchos nombres duros y perversos.
Sin embargo, es de Dios;
vino de Él porque conduce a Él. Esto lo sabemos más allá de toda duda,
aunque no podemos hacer que ningún hombre sepa lo que nosotros sabemos,
a menos que tome la misma senda que hemos tomado.

El mundo habla de Dios, pero ¿qué hacen?
Oran por poder, pero rechazan la luz en la que se conoce el poder.
Así que, si desean conocer a Dios y adorarlo y servirlo como se debe,
deben acudir a los medios que Él ha ordenado y dado para este propósito.
Algunos los buscan en los libros y otros en hombres eruditos;
pero lo que buscan se halla dentro de ellos (aunque no viene de ellos mismos),
y por eso lo pasan por alto.
La voz es demasiado suave, la semilla es demasiado pequeña,
y la luz resplandece en las tinieblas, pero los hombres vagan errantes.
La mujer que perdió su moneda la encontró en su casa,
después de encender su lámpara y barrerla.
Ustedes deben hacer lo mismo, y así encontrarán la respuesta a la pregunta de Pilato:
"`¿Qué es la verdad?`"
De hecho, encontrarán la Verdad en lo íntimo, la luz de Cristo en su interior.
Porque Cristo es la luz del mundo,
y será una luz para ustedes que les muestra la verdad
de su condición. Y al prestarle atención a Él,
los guiará fuera de toda oscuridad hacia la maravillosa luz de Dios;
porque la luz aumenta sobre los obedientes.
Sí, "`Luz está sembrada para el justo,`"^
footnote:[Salmo 97:11]
y "`la senda de los justos es como la luz de la aurora,
que va en aumento hasta que el día es perfecto.`"^
footnote:[Proverbios 4:18]

Por lo tanto, amigos, ¡vuélvanse hacia adentro, vuélvanse hacia adentro, les ruego!
Donde se encuentra el veneno, allí también encontrarán el antídoto.
Es allí donde necesitan a Cristo, y es allí donde deben encontrarlo.
Busquen y hallarán, ¡lo testifico de parte de Dios!
Pero deben buscar correctamente, con todo su corazón, como hombres que buscan su vida,
sí, su vida eterna--con diligencia, humildad y paciencia,
como aquellos que no pueden hallar ningún placer, consuelo o satisfacción en nada más,
a menos que encuentren a Aquel que sus almas necesitan por encima de todo.
¡Oh, este es un camino de aflicción, de aflicción espiritual!
Que el mundo carnal y profano piense y diga lo que quiera.
Es por un camino de aflicción que deban andar hacia
la ciudad de Dios que tiene fundamentos eternos,
si desean llegar alguna vez.

[.offset]
¿Y qué hará esta bendita luz por ustedes?
Lo diré:

_En primer lugar,_
les mostrará cómo el hombre ha caído de Dios y el estado miserable en el que se encuentra.
Detectará el espíritu del mundo en cada uno de sus anzuelos y tentaciones,
y pondrá sus pecados en orden delante de sus ojos.^
footnote:[Ver Salmos 50:21; Salmos 90:8]

_En segundo lugar,_
engendrará un profundo sentimiento de tristeza en todos los que creen en su testimonio.
La luz les mostrará a Aquel a quien traspasaron,
los golpes y heridas que le han causado por su desobediencia,
y cómo lo han obligado a ser siervo por causa de sus pecados.
Entonces llorarán y se lamentarán por su terrible ofensa,
pero su dolor será esa "`tristeza que es según Dios, que obra arrepentimiento,`"^
footnote:[2 Corintios 7:10 RV1602P]
de la cual habla el apóstol.

_En tercer lugar,_ los llevará a una vigilancia santa,
para que tengan cuidado de no volver a hacerlo,
y para que el enemigo no los sorprenda de nuevo.
Así serán enseñados a llevar cada pensamiento, palabra y obra al juicio de la luz,
el cual es la calzada de santidad por la que caminan los redimidos del Señor. Entonces,
y no antes, amarán verdaderamente a Dios sobre todas las cosas,
y a sus prójimos como a sí mismos; y nada hará mal, nada dañará,
y no habrá quien espante en este santo monte.^
footnote:[Ver Isaías 11:9; 65:25; 17:2]
Entonces llegarán a ser verdaderamente de Cristo;
porque serán de Su naturaleza y Espíritu.
Y cuando sean de Cristo, entonces Cristo será de ustedes,
y experimentarán una preciosa comunión con el Padre y con el Hijo.
Y conocerán más allá de las palabras el poder de la sangre, sí,
de la sangre de Jesucristo, el Cordero sin mancha, que habla mejor que la sangre de Abel,
y limpia la conciencia de obras muertas para servir al Dios vivo.

[.asterism]
'''

He aquí el testimonio y la doctrina del pueblo llamado Cuáqueros.
He aquí su práctica y disciplina,
y los hombres y mujeres que fueron enviados por Dios para esta excelente obra y servicio.
Que Dios, en este día de Su gran amor y poder, tenga siempre la gloria, el honor,
la acción de gracias y el renombre, por medio de Su amado Hijo y Cordero,
nuestra luz y vida, que se sienta con Él en el trono, por los siglos de los siglos.
Amén.

[.small-break]
'''

--Habla uno a quien Dios favoreció hace mucho tiempo con Su visitación misericordiosa,
y quien no fue desobediente al llamado y visión celestial;
para quien el camino de la verdad es más hermoso y precioso que nunca,
y conociendo su belleza y beneficio por encima de todos los tesoros mundanos,
lo ha escogido como su más grande alegría,
y por eso les recomienda que lo amen y escojan, porque él es,
con gran sinceridad y afecto,

[.signed-section-closing]
Un amigo de sus almas,

[.signed-section-signature]
William Penn

[.signed-section-context-close]
1696
