[quote.epigraph, , Lucas 9:23]
____
Y decía a todos:
Si alguno quiere venir en pos de mí,
niéguese a sí mismo, tome su cruz cada día, y sígame.
____

[quote.epigraph, , 2 Timoteo 4:7-8]
____
He peleado la buena batalla, he acabado la carrera, he guardado la fe.
Por lo demás, me está guardada la corona de justicia, etc.
____

== Prólogo

El tratado titulado "`No Cruz, No Corona,`" escrito por William Penn (1644-1718)
durante su encarcelamiento en la Torre de Londres en 1668,
ha sido justamente considerado una de las mejores obras de su pluma.
Su educación y posición social lo capacitaron de manera notable para juzgar el vacío,
la vanidad y la pecaminosidad de los placeres terrenales
y la conformidad con el mundo que él censura en este libro,
y en contra de los cuales presenta contundentes argumentos
a partir de las Sagradas Escrituras.
Admirado y cortejado por sus talentos y logros,
amado por su disposición amable y buenos modales,
con el camino hacia el honor y el ascenso abierto delante de él,
tenía todos los incentivos que el mundo podía ofrecerle para perseguir sus gratificaciones.
Pero en el vigor y la frescura de la juventud,
cuando todo frente a él era brillante y prometedor,
en obediencia a la voluntad de su Padre celestial,
William Penn abandonó voluntariamente sus oportunidades de honor y ventaja terrenales,
renunció a las modas y costumbres de la época,
y vivió una vida seria y de negación al yo,
en conformidad con el ejemplo de los hombres santos de la
antigüedad y los preceptos de nuestro Señor y Sus apóstoles,
tal como se establecen en las Escrituras de la Verdad.

Como consecuencia de este cambio, sufrió mucha oposición de sus familiares y amigos,
e incluso fue desterrado de la casa de su padre.
Pero ni estas pruebas ni su posterior encarcelamiento,
pudieron quebrantar su confianza ni inducirlo a renunciar
a lo que creía que era su deber religioso.
Y Dios, a quien se esforzaba por servir y honrar en medio del escarnio y oprobio,
no sólo lo sostuvo por encima del temor del hombre y llenó su alma de paz y contentamiento,
sino que le devolvió su lugar en la estima y afectos de sus parientes,
haciéndolo una persona honorable ante los ojos del mundo por sus virtudes cristianas.
Su padre lo amó con mayor ternura,
y con su último aliento dio testimonio a favor de
los principios religiosos que su hijo había adoptado.

William Penn tenía veinticuatro años cuando escribió "`No Cruz, No Corona.`"
Por lo tanto, no fue una obra producida por el hastío del mundo,
ni por el disgusto que surge de muchos años de entrega a los placeres.
Fue el resultado de un estudio sereno y deliberado de la conducta y costumbres del mundo,
visto con el ojo de un cristiano sincero y devoto.
Él pensó, sintió y escribió como alguien consciente de la dignidad
y de las nobles facultades del hombre,
así como de su destino supremo como un ser inmortal.
La solidez del argumento, la profundidad de la experiencia cristiana,
la moralidad elevada y la religión pura, que abundan en esta obra,
la recomiendan para una lectura seria y atenta por
parte de todas las denominaciones del cristianismo.

[.signed-section-signature]
William Evans & Thomas Evans

[.signed-section-context-close]
Editores de The Friends Library -- 1837
