== Prólogo

El tratado titulado "`No Cruz, No Corona,`" escrito por William Penn (1644-1718)
durante su encarcelamiento en la Torre de Londres, en 1668,
ha sido apropiadamente considerado como una de las mejores producciones de su pluma.
Su educación y posición social lo capacitaron de manera eminente para juzgar el vacío,
la vanidad y el pecado los placeres terrenales
y la conformidad con el mundo que él censura aquí,
y en contra de los cuales produce tales argumentos
decisivos a partir de las Sagradas Escrituras.
Admirado y cortejado por sus talentos y logros,
amado por su amabilidad y buenos modales,
con el camino hacia el honor y la preferencia abierto delante de él,
tenía todos los incentivos que el mundo
podía ofrecer para perseguir sus gratificaciones.
Pero en el vigor y frescura de la juventud,
cuando todo lo que tenía delante de él era brillante y prometedor,
en obediencia a la voluntad de su Padre celestial,
William Penn abandonó voluntariamente sus oportunidades de honor y ventaja terrenales,
renunció a las modas y costumbres de la época, y vivió una vida seria y de abnegación,
en conformidad al ejemplo de los hombres santos de la
antigüedad y a los preceptos de nuestro Señor y Sus apóstoles,
como se establecen en las Escrituras de la Verdad.

Como consecuencia de este cambio,
sufrió mucha oposición de sus familiares y amigos,
e incluso fue desterrado de la casa de su padre.
Pero ni estas pruebas ni su posterior encarcelamiento,
pudieron quebrantar su confianza ni inducirlo a
renunciar a lo que creía que era su deber religioso.
Y Dios, a quien se esforzaba por servir y honrar en medio del escarnio y oprobio,
no solo lo sostuvo por encima del temor del hombre,
y llenó su alma de paz y contentamiento,
sino que le devolvió su lugar en la estima y afectos de sus parientes,
y lo convirtió en una persona honorable ante los ojos del mundo por sus virtudes cristianas.
Su padre lo amaba con mayor ternura,
y con su último aliento dio testimonio a favor de los
principios religiosos que su hijo había adoptado.

William Penn tenía veinticuatro años de edad cuando escribió "`No Cruz, No Corona.`"
Por lo tanto, este tratado no procedió del hastío del mundo,
o de ese disgusto que surge de muchos años de entrega a los placeres.
Fue el resultado de una inspección pausada y deliberada
de la conducta y costumbres del mundo,
desde la perspectiva del ojo de un cristiano sincero y devoto.
Él pensó, sintió y escribió,
como alguien consciente de la dignidad y de los dotes nobles del hombre,
y de su destino supremo como un ser inmortal.
La solidez del argumento, la profundidad de la experiencia cristiana,
la moralidad elevada y la religión pura, que abundan en esta obra,
hacen que sea recomendable a la lectura seria
y atenta de todas las denominaciones del cristianismo.

[.signed-section-signature]
William Evans & Thomas Evans

[.signed-section-context-close]
Editores de The Friends Library -- 1837
