== Prefacio de William Penn

Lector, el gran asunto de la vida del hombre es responder al propósito para el cual vive;
y esto es, glorificar a Dios y experimentar Su salvación. Este es el decreto del cielo,
tan antiguo como el mundo.
Pero la triste verdad es que lo que menos le importa al
hombre es lo que debería importarle más,
y se niega a investigar su propio ser, su origen, su deber y su propósito;
escogiendo más bien dedicar sus días a satisfacer el orgullo,
la codicia y el placer de su corazón, como si hubiera nacido para sí mismo,
o se hubiera dado vida a sí mismo,
y no estuviera sujeto al ajuste de cuentas y juicio de un Poder superior.
El pobre hombre se ha causado esta lamentable situación,
por su desobediencia a la ley de Dios en su corazón,
al hacer lo que sabe que no debería hacer y dejar de hacer lo que sabe que debería hacer.
Mientras esta enfermedad continúe sobre el hombre,
hará de Dios su enemigo y a sí mismo incapaz de recibir el amor y la salvación
que Dios ha manifestado al mundo por medio de Su Hijo Jesucristo.

Si tú, lector, eres tal persona,
mi consejo para ti es que te retires a tu interior y observes la condición de tu alma;
porque Cristo te ha dado luz con la que puedes hacerlo.
Escudriña cuidadosa y completamente; tu vida depende de ello; tu alma está en juego.
Tu vida solo la vives una vez; si la abusas, la pérdida es irreparable;
el mundo no es recompensa suficiente para rescatarte.
¿Entonces, por un mundo como este,
ignorarás el tiempo de tu visitación y perderás tu alma?
Oh, no provoques que Dios te rechace.
¿Sabes qué es ser rechazado?
Es Tofet; es el infierno, la angustia eterna de los condenados.

¡Oh Lector! ¡Cómo uno que conoce los terrores del Señor, te aconsejo que seas serio,
diligente y ferviente con respecto a tu propia
salvación! Como uno que conoce el consuelo,
la paz, la alegría y el placer de los caminos de justicia,
te exhorto e invito a abrazar las reprobaciones y convicciones
de la luz y Espíritu de Cristo en tu propia consciencia,
y llevar el juicio de tu pecado.
El fuego sólo quema el rastrojo; el viento sólo sopla la paja.
Rinde tu cuerpo, alma y espíritu a Él,
quién hace todas las cosas nuevas--nuevos cielos y nueva tierra, nuevo amor, nuevo gozo,
nueva paz, nuevas obras, una nueva vida y conducta.
Los hombres se han vuelto corruptos e inmundos por causa del pecado,
y deben ser salvados por medio del fuego, que los purifica.
Por esta razón la Palabra de Dios se compara con
un fuego y el Día de salvación con un horno;
y Cristo Mismo con un refinador de oro y un purificador de plata.

Ven, lector, escúchame por un momento; busco tu salvación;
esa es mi intención. Un Refinador se te ha acercado, Su gracia se te ha aparecido,
una gracia que te muestra los deseos mundanos y te enseña a negarlos.
Recibe Su levadura y ella te cambiará;
Su medicina y ella te curará. Él es infalible y gratuito.
Un toque de Su manto lo hizo en la antigüedad, y todavía lo hará,
porque Su virtud es la misma y no puede agotarse.
En Él mora la plenitud; ¡bendito sea Dios por Su suficiencia!
Puso el socorro sobre Él para que pudiera ser poderoso para salvar a todos
los que vengan a Dios por medio de Él. Hazlo así y te transformará. Sí,
"`cambiará tu vil cuerpo, para que sea hecho semejante a su cuerpo glorioso,
según la operación de Su poder por el cual puede también sujetar a Sí todas las cosas.`"^
footnote:[Filipenses 3:21 RV1602P]
¿Qué, pues, debemos hacer para experimentar Su poder y amor?
Esta es la corona, pero, ¿dónde está la cruz?
¿Dónde está la copa amarga y el bautismo sangriento?
Ven, lector, sea como Él. Por este gozo trascendental,
levanta tu cabeza por encima del mundo;
y entonces tu salvación se acercará verdaderamente.

La cruz de Cristo es el camino de Cristo a la Corona de Cristo.
Este es el tema del siguiente discurso--escrito por primera
vez durante mi encierro en la torre de Londres en el año 1668,
ahora reimpreso para que seas ganado para Cristo; o si ya has sido ganado,
llevado más cerca de Él. Es un camino al que Dios, en Su bondad eterna,
guío mis pies en la flor de mi juventud, cuando tenía como veintidós años de edad.
Él me tomó de la mano y me sacó de los placeres, vanidades y expectativas del mundo.
He probado los juicios de Cristo y Sus misericordias, y el desprecio y oprobio del mundo.
Me gozo en mi experiencia y la dedico a tu servicio en Cristo.
A mi país y al mundo de los cristianos la dejo.
Que Dios, si le place, la haga efectiva para todos ellos,
y vuelva sus corazones de esa envidia,
odio y amargura que tienen los unos contra los otros por cuestiones mundanas--
sacrificando la humanidad y la caridad por la ambición y la codicia,
por las cuales llenan la tierra de angustia y opresión.
Y que reciban el Espíritu de Cristo en sus corazones,
cuyos frutos son amor, paz, gozo, templanza y paciencia, afecto fraternal y caridad;
y así en cuerpo, alma y espíritu hagan una liga triple en contra del mundo,
la carne y el diablo, los únicos y comunes enemigos de la humanidad.
Y así, habiendo conquistado a sus enemigos por el poder de la cruz de Jesús,
y a través de una vida de negación de sí mismos,
al final lleguen al descanso eterno y reino de Dios.

[.signed-section-closing]
Así desea y ora tu ferviente amigo cristiano,

[.signed-section-signature]
William Penn.
