== Prefacio de William Penn

Lector, el gran asunto de la vida del hombre es responder al propósito para el cual vive;
y ese propósito es glorificar a Dios y experimentar
Su salvación. Este es el decreto del cielo,
tan antiguo como el mundo.
Pero la triste verdad es que lo que menos le importa
al hombre es lo que debería importarle más,
y se niega a investigar su propio ser, su origen, su deber y su propósito;
escogiendo más bien dedicar sus días a satisfacer el orgullo,
la codicia y el placer de su corazón, como si hubiera nacido para sí mismo,
o se hubiera dado vida a sí mismo,
y no estuviera sujeto al ajuste de cuentas y juicio de un Poder superior.
El pobre hombre se ha causado esta lamentable situación
por su desobediencia a la ley de Dios en su corazón,
al hacer lo que sabe que no debe hacer, y al dejar de hacer lo que sabe que debe hacer.
Mientras esta enfermedad continúe sobre el hombre,
hará de Dios su enemigo y a sí mismo incapaz de recibir el amor y la salvación
que Dios ha manifestado al mundo por medio de Su Hijo Jesucristo.

Si tú, lector, eres tal persona,
mi consejo para ti es que te retires a tu interior y observes la condición de tu alma;
porque Cristo te ha dado luz con la que puedes hacerlo.
Escudriña cuidadosa y completamente; tu vida depende de ello; tu alma está en juego.
Tu vida sólo la vives una vez; si la maltratas, la pérdida es irreparable;
el mundo no es recompensa suficiente para rescatarte.
¿Vas a ignorar, entonces, por un mundo como este,
el tiempo de tu visitación y así perder tu alma?
Oh, no provoques que Dios te rechace.
¿Sabes qué es ser rechazado?
Es Tofet; es el infierno, la angustia eterna de los condenados.

¡Oh lector! ¡Cómo uno que conoce los terrores del Señor, te aconsejo que seas serio,
diligente y ferviente con respecto a tu propia salvación! Como uno que conoce el consuelo,
la paz, la alegría y el placer de los caminos de justicia,
te exhorto y te invito a abrazar las reprobaciones y convicciones
de la luz y Espíritu de Cristo en tu propia conciencia,
y soportar el juicio de tu pecado.
El fuego sólo quema el rastrojo; el viento sólo sopla la paja.
Rinde tu cuerpo, alma y espíritu a Aquel que hace todas las cosas nuevas;
nuevos cielos y nueva tierra, nuevo amor, nuevo gozo, nueva paz, nuevas obras,
una nueva vida y conducta.
Los hombres se han vuelto corruptos e inmundos por causa del pecado,
y deben ser salvados por medio del fuego que purifica.
Por esta razón la Palabra de Dios se compara con
un fuego y el Día de salvación con un horno,
y Cristo Mismo con un refinador de oro y un purificador de plata.

Ven, lector, escúchame por un momento, busco tu salvación,
esa es mi intención. Un Refinador se ha acercado a ti, Su gracia se te ha aparecido,
una gracia que te muestra los deseos mundanos y te enseña a negarlos.
Recibe Su levadura y ella te cambiará. Recibe Su medicina
y ella te sanará. Él es tan infalible como gratuito.
Un toque de Su manto lo hizo en la antigüedad, y todavía lo hará,
porque Su virtud es la misma y no puede agotarse.
En Él habita la plenitud; ¡bendito sea Dios por Su suficiencia!
Puso el socorro sobre Él para que pudiera ser poderoso para salvar a todos los
que se acercan a Dios por medio de Él. Hazlo y Él te transformará. Sí,
Él "`cambiará nuestro vil cuerpo, para que sea hecho semejante a su cuerpo glorioso,
según la operación de Su poder por el cual puede también sujetar a Sí todas las cosas.`"^
footnote:[Filipenses 3:21 RV1602P]
¿Qué debemos hacer entonces para experimentar Su poder y amor?
Esta es la corona, ¿pero dónde está la cruz?
¿Dónde está la copa amarga y el bautismo sangriento?
Ven, lector, sé semejante a Él. Por este gozo trascendente,
levanta tu cabeza por encima del mundo,
y entonces tu salvación se acercará verdaderamente.

La cruz de Cristo es el camino de Cristo a la corona de Cristo.
Este es el tema del siguiente discurso,
escrito por primera vez durante mi encierro en la torre de Londres en el año 1668,
y ahora reimpreso, con el fin de que seas ganado para Cristo; o si ya has sido ganado,
que te acerques aún más a Él. Es un camino al que Dios, en Su bondad eterna,
guió mis pies en la flor de mi juventud,
cuando tenía como veintidós años. Él me tomó de la mano y me sacó de los placeres,
vanidades y expectativas del mundo.
He probado los juicios de Cristo y Sus misericordias, y el desprecio y oprobio del mundo.
Me gozo en mi experiencia y la dedico a tu servicio en Cristo.
La dejo a mi país y al mundo de los cristianos.
Que Dios, si le place, la haga efectiva para todos ellos,
y vuelva sus corazones de esa envidia,
odio y amargura que tienen los unos contra los otros por cuestiones mundanas--sacrificando
la humanidad y la caridad por la ambición y la codicia,
por las cuales llenan la tierra de angustia y opresión--y
reciban el Espíritu de Cristo en sus corazones,
cuyos frutos son amor, paz, gozo, templanza y paciencia, afecto fraternal y caridad;
y así en cuerpo, alma y espíritu hagan una triple alianza contra el mundo,
la carne y el diablo, los únicos comunes enemigos de la humanidad.
Y así, habiendo conquistado a sus enemigos por el poder de la cruz de Jesús,
y a través de una vida de negación al yo,
puedan al final alcanzar el reposo y el reino eternos de Dios.

[.signed-section-closing]
Así desea y ora tu ferviente amigo cristiano,

[.signed-section-signature]
William Penn
