== Capítulo I. Un Cristianismo sin Cruz

Aunque el conocimiento y la obediencia a la doctrina de la cruz de Cristo,
son de infinita importancia para las almas de los hombres--siendo
la única puerta al verdadero cristianismo y el camino que los antiguos
siempre anduvieron hacia la bendición--sin embargo,
con extrema aflicción, déjenme decir, es increíblemente poco entendida,
enormemente descuidada, y lo que es peor, muy amargamente contradicha por la vanidad,
superstición e intemperancia de los cristianos profesantes.
De hecho, tal es el estado de las cosas en este día, que debemos,
o bien renunciar a creer en lo que el Señor Jesús nos ha dicho:
"`El que no lleva su cruz y viene en pos de mí, no puede ser mi discípulo;`"^
footnote:[Lucas 9:23, 14:27]
o, admitiéndolo como verdad,
concluir que la mayoría de los cristianos se engañan miserablemente
a sí mismos en el gran asunto del cristianismo,
y frustran su propia salvación.

Porque,
aunque somos lo más tiernos y caritativos posible al considerar esas naciones
que afirman tener una participación en el santo nombre de Cristo,
si también queremos ser justos,
debemos reconocer que después de todas las ventajas bondadosas de luz
que han recibido estas últimas generaciones del mundo--por la venida,
vida, doctrina, milagros, muerte, resurrección y ascensión de Cristo,
junto con los dones de Su Espíritu Santo; a lo cual podemos agregar los escritos,
las obras y los sufrimientos de Sus queridos seguidores en todos los tiempos--parece
quedar muy poco del cristianismo aparte del nombre.
Y lamentablemente, el nombre de cristiano,
siendo ahora usurpado por la vieja naturaleza y vida pagana,
hace que muchos de los que lo profesan no sean más que verdaderos paganos disfrazados.
Porque aunque no adoren los mismos ídolos, adoran a Cristo con el mismo corazón;
y nunca podrán hacer otra cosa mientras vivan en los mismos deseos.
El cristiano no crucificado y los paganos son de la misma religión.

Porque aunque tienen diferentes objetos a los que dirigen sus oraciones,
la adoración en ambos casos es forzada y ceremoniosa,
y la deidad que realmente adoran es el dios de este mundo, el gran señor de los deseos,
ante quien se inclinan con todos los poderes del alma y de los sentidos.
¿Qué comeremos? ¿Qué beberemos? ¿Qué vestiremos? ¿Cómo pasaremos nuestro tiempo?
¿De qué manera podemos acumular riquezas, aumentar el poder,
expandir nuestros territorios,
y dignificar y perpetuar nuestros nombres y familias en la tierra?
Esta sensualidad vulgar es comprendida por el amado apóstol Juan en estas palabras:
"`Los deseos de la carne, los deseos de los ojos, y la vanagloria de la vida,
los cuales no provienen del Padre, sino del mundo que está bajo el maligno.`"^
footnote:[1 Juan 2:16, 5:19]

Es una reflexión triste, pero una realidad que no se puede negar,
que estos deseos mundanos llenan una gran parte del estudio,
atención y conducta del cristianismo.
Y lo que agrava la miseria es que estas cosas crecen con el tiempo;
pues cuanto más viejo es el mundo, peor se vuelve.
Los ejemplos de los depravados siglos pasados y sus miserables finales no han disuadido,
sino más bien alentado el nuestro.
En efecto, el hombre de hoy parece haber perfeccionado el antiguo legado de impiedad,
y lo ha llevado mucho más allá que los ejemplos antiguos, de modo que,
en lugar de avanzar en la virtud,
han caído escandalosamente por debajo de la vida de los paganos.
Su altivez, lascivia, inmundicia, embriaguez, juramentos, mentiras, envidia,
murmuraciones, crueldades, traiciones, codicia, injusticia y opresión son tan comunes,
y se cometen con tal creatividad y exceso,
que han hecho que los incrédulos tropiecen y se endurezcan,
y menosprecien esa religión santa a la que debieron
haber ganado sus afectos mediante su buen ejemplo.

Esta miserable desviación de los tiempos primitivos,
cuando la gloria del cristianismo era la pureza de sus profesantes,
no puedo sino llamarla la segunda y peor parte de la tragedia
que recayó sobre el bendito Salvador de la humanidad.
Porque los judíos,
debido al poder de la ignorancia y al prejuicio contra el modo nada mundano de Su aparición,
no quisieron reconocerlo cuando vino; por ello lo persiguieron durante dos o tres años,
y finalmente lo crucificaron en un día. Pero la crueldad
de los falsos cristianos dura mucho más. Ellos primero,
como Judas, lo han profesado, y luego, durante muchas generaciones, lo han traicionado,
perseguido y crucificado de la manera más vil,
mediante una perpetua apostasía en la conducta,
abandonando la negación al yo y la santidad de Su doctrina,
mostrando con sus vidas la falsedad de su fe.
Estos son los que el autor de la epístola a los Hebreos nos dice,
que están "`crucificando de nuevo para sí mismos al Hijo de Dios y exponiéndole a vituperio.`"^
footnote:[Hebreos 6:6]
Juan, en su revelación, llama a sus corazones contaminados,
"`Sodoma y Egipto en sentido espiritual, donde también nuestro Señor fue crucificado,`"^
footnote:[Apocalipsis 11:8]
donde él vio al Señor Jesús crucificado mucho después de haber ascendido.
Así como Cristo dijo en el pasado, que los enemigos del hombre son los de su propia casa;
de igual manera,
los enemigos de Cristo hoy son principalmente los
que pretenden ser de Su propia religión. De hecho,
estos lo escupen, lo clavan y traspasan,
lo coronan con espinas y le dan hiel y vinagre a beber.
Y esto no es difícil de comprender;
porque aquellos que viven en la misma naturaleza y semilla maligna que los judíos,
quienes lo crucificaron externamente, deben necesariamente crucificarlo internamente.
Los que rechazan la gracia hoy en sus propios corazones,
son uno en linaje y descendencia con los judíos de duro corazón,
que resistieron la gracia que entonces apareció en y por medio de Cristo.

El pecado es de una naturaleza en todo el mundo;
porque aunque un mentiroso no es un borracho, ni uno que jura un fornicario,
ni ninguno de ellos es propiamente un asesino, aun así, todos son de una misma iglesia,
todos ramas de una misma raíz impía, todos de una sola familia.
No tienen más que un padre, el diablo, como Cristo les dijo a los judíos profesantes,
la iglesia visible de esa época.
Él desestimó sus pretensiones de Abraham y Moisés, y claramente les dijo:
"`Todo aquel que hace pecado, esclavo es del pecado.`"^
footnote:[Juan 8:34]
Ellos hacían las obras del diablo, y por lo tanto, eran hijos del diablo.
Este argumento se sostendrá siempre sobre las mismas razones,
y por consiguiente sigue siendo válido.
Pablo dice: "`Sois esclavos de aquel a quien obedecéis.`"^
footnote:[Romanos 6:16]
Juan le dice a la iglesia de la antigüedad: "`Nadie os engañe;
el que practica el pecado es del diablo.`"^
footnote:[1 Juan 3:7-8]
¿Fue Judas un mejor cristiano por haber dicho: "`¡Salve, Maestro!`" y besar a Cristo?
¡De ninguna manera!
Estas palabras fueron la señal de su traición,
la señal por la cual los sangrientos judíos lo identificarían
y capturarían. Lo llamó Maestro,
pero lo traicionó. Lo besó, pero lo vendió para que lo mataran.
Esta es la sustancia de la religión del falso cristiano.
Si un hombre les pregunta: "`¿Es Cristo su Señor?`" Ellos exclamarán:
"`¡Dios no permita otra cosa! ¡Sí, Él es nuestro Señor!`" "`Muy bien,
¿pero guardan Sus mandamientos?`"
"`No, ¿cómo podríamos?`"
"`Entonces, ¿cómo son Sus discípulos?`"
"`Es imposible,`" dicen, "`¡Qué! ¿Quieres que guardemos Sus mandamientos?
¡Ningún hombre puede!`" ¿Pero es imposible hacer aquello
sin lo cual Cristo hizo imposible ser cristiano?
¿Exige Cristo algo inalcanzable?
¿Siega donde no ha sembrado, o requiere lo que no ha hecho posible?
Así es como, al igual que Judas, lo llaman Maestro,
pero se unen con el mal del mundo para traicionarlo.
Lo besan y lo abrazan, hasta donde alcanzan sus creencias;
y luego lo venden para satisfacer las pasiones que más disfrutan.

Que nadie engañe su propia alma; las uvas no se recogen de los espinos,
ni los higos de los abrojos; un lobo no es una oveja, ni un buitre una paloma.
Cualquiera que sea la forma, el pueblo, o la iglesia a la que pertenezcas,
esta es la verdad de Dios para la humanidad: Aquellos que tienen la forma de la piedad,
pero por sus vidas no crucificadas niegan su poder, constituyen la iglesia falsa,
no la verdadera.
Y aunque esta iglesia se llame a sí misma la novia del Cordero, o la iglesia de Cristo,
ella es la misteriosa Babilonia, que es apropiadamente llamada por el Espíritu Santo:
"`La madre de las rameras, y de las abominaciones de la tierra.`"^
footnote:[Apocalipsis 17:5]
Ella se ha degenerado de la castidad y pureza cristianas,
a todas las abominaciones de la Babilonia pagana--una lujosa ciudad de la antigüedad,
muy conocida como la sede de todos los reyes de Babilonia,
y en aquel entonces el lugar de más orgullo y lujo.
Como era entonces, así es la Babilonia mística hoy,
la gran enemiga del verdadero pueblo de Dios.

Es muy cierto que los que nacen de la carne odian y
persiguen a los que nacen del Espíritu,
los de corazón circuncidado.
Ellos no pueden reconocer ni adorar a Dios según las invenciones,
métodos y prescripciones de Babilonia, ni aceptar como doctrina sus vanas tradiciones,
así como tampoco pueden conformarse a sus modas y costumbres corruptas en su conducta.
Y debido a que no pueden conformarse,
la Babilonia apóstata rápidamente se convierte en perseguidora.
No le basta con desviarse de la pureza antigua;
otros deben hacerlo también. No les dará descanso a los que no
participen con ella en su degeneración ni reciban su marca.
¿Habrá alguien más sabio que ella, que la llamada iglesia madre?
No, no; ni nadie podrá hacer guerra contra la bestia sobre la que monta; es decir,
contra esos poderes mundanos que la protegen y prometen
mantenerla contra los clamores de sus disidentes.
La apostasía y la superstición son siempre orgullosas e impacientes con la disidencia.
Todos deben conformarse o perecer.
Por eso,
los testigos muertos y la sangre de las almas debajo del altar
se encuentran dentro de los muros de esta Babilonia mística,
la gran ciudad de los falsos cristianos,
y son cargados sobre ella por el Espíritu Santo en el libro de Apocalipsis.

Los hijos de Babilonia están tan completamente conquistados bajo el dominio de las tinieblas,
por medio de su continua desobediencia a la manifestación de la luz divina en sus almas,
que han olvidado lo que el hombre fue alguna vez, o lo que ellos deberían ser ahora.
No reconocen el cristianismo puro y verdadero cuando lo ven,
aunque se enorgullecen de profesarlo.
Su visión de la salvación es tan carnal y falsa,
que llaman a lo bueno malo y a lo malo bueno.
Hacen de un demonio un cristiano y de un santo un demonio.
Y aunque la indulgencia injusta de sus vidas es una fuente
de lamentación (como también de la destrucción de sí mismos),
aun así,
la falsa idea de que pueden ser hijos de Dios mientras se
encuentran en el estado de desobediencia a Sus santos mandamientos,
de todos los demás engaños, es el más letal para su condición eterna.
Por desgracia, creen que son discípulos de Jesús, aun cuando se rebelan contra Su cruz.
Se halagan a sí mismos como si fuesen miembros de la verdadera iglesia de Cristo,
la cual no tiene mancha ni arruga,
a pesar de que sus vidas están llenas de manchas y arrugas.
Porque están en paz en el pecado y seguros en su transgresión.

Sus vanas esperanzas silencian sus convicciones internas
y entierran todos los tiernos movimientos hacia el arrepentimiento,
de modo que su error respecto a su deber para con Dios es tan perjudicial
como su rebelión contra Él. Así caminan al borde del precipicio
y se adulan a sí mismos hasta que la tumba se los traga,
y el juicio del gran Dios rompe su letargo y desengaña sus pobres y miserables almas,
con la angustia de los inicuos como recompensa de sus obras.

Esto ha sido,
es y será la perdición de todos los cristianos mundanos--un final tan aterrador,
que la compasión por sí sola sería suficiente para animarme a disuadir
a todos contra las supersticiones y los deseos mundanos,
e invitar a los profesantes del cristianismo al conocimiento
y obediencia de la cruz diaria de Cristo,
como el único camino dado por Él y designado para
nosotros hacia la bendición. Mediante esta cruz diaria,
los que ahora no hacen más que usurpar el nombre de cristiano,
podrán obtener la verdadera realidad; y, por su poder,
ser partícipes de la resurrección que es en Cristo Jesús para una vida nueva.
Porque aquellos que realmente están en Cristo, es decir,
redimidos por Él e implantados en Él, son nuevas criaturas.
Ellos han recibido una nueva voluntad, una que hace la voluntad de Dios,
no la suya propia.
Oran en la verdad, y no se burlan de Dios cuando dicen: "`Hágase tu voluntad,
como en el cielo, así también en la tierra.`"^
footnote:[Mateos 6:10; Lucas 11:2]
Tienen nuevos afectos,
los cuales están puestos en las cosas de arriba y hacen de Cristo su tesoro eterno.
Tienen una nueva fe,
una que vence las trampas y tentaciones del espíritu del mundo en ellos mismos,
o cuando aparece a través de otros.
Y tienen nuevas obras,
no producto de artilugios supersticiosos ni de invenciones humanas,
sino los frutos puros del Espíritu de Cristo obrando en ellos, tales como el amor, gozo,
paz, mansedumbre, longanimidad, templanza, afecto fraternal, fe, paciencia y bondad,
contra lo cual no hay ley.

El apóstol Pablo nos dice,
que los que no tienen este Espíritu de Cristo y no caminan en Él "`no son de Él;`"^
footnote:[Romanos 8:9]
sino que la ira de Dios y la condenación de la ley reposan sobre ellos.
De hecho, "`ninguna condenación hay para los que están en Cristo Jesús,
los que no andan conforme a la carne, sino conforme al Espíritu.`"^
footnote:[Romanos 8;1]
Pero, por esta misma doctrina,
los que _no_ caminan según dicho Espíritu Santo _no_ están en Cristo.
Estos no tienen herencia en Él,
ni tienen ningún derecho legítimo para reclamar su salvación; en consecuencia,
para ellos hay condenación.

=== Un Reprobador y Salvador Interno

La religión de los impíos es una mentira:
"`No hay paz para los impíos,`" dice el profeta.^
footnote:[Isaías 48:22; Isaías 57:21]
Y realmente no puede haberla,
porque son reprobados en sus propias conciencias y condenados
en sus propios corazones por toda su desobediencia.
Vayan donde vayan, las reprensiones van con ellos, y muchas veces también los terrores.
Es un Dios ofendido el que los punza,
y por Su luz pone "`sus pecados delante de sus ojos.`"^
footnote:[Salmos 50:21 Literal del Inglés]
A veces se esfuerzan por apaciguarlo mediante su devoción y adoración externas,
pero en vano; porque la verdadera adoración a Dios es hacer Su voluntad,
la cual ellos transgreden.
A veces huyen hacia diversiones y compañías para
ahogar la voz del Reprobador y desafilar Sus saetas,
para ahuyentar los pensamientos perturbadores y resguardarse a
sí mismos fuera del alcance del Inquietador de sus placeres.
Pero el Todopoderoso, tarde o temprano,
de seguro los alcanzará. No hay forma de escapar de la justicia
de Dios para los que rechazan los términos de Su misericordia.
En efecto, su Acusador está con ellos siempre,
no pueden deshacerse de Él más de lo que pueden deshacerse de sí mismos.
Él está en medio de ellos, y se mantendrá cerca de ellos.
Ese Espíritu que testifica a favor de los espíritus de los justos,
testificará contra los de ellos.
Sí, sus propios corazones los condenarán abundantemente; y el apóstol Juan dice:
"`Si nuestro corazón nos condena, mayor es Dios, y conoce todas las cosas;`"^
footnote:[1 Juan 3:20]
es decir, no hay escapatoria de los juicios de Dios,
si el hombre no es capaz de escapar de la condenación de sí mismo.

En aquel Día,
los cristianos orgullosos y ostentosos aprenderán que Dios no hace acepción de personas;
que todas las sectas, denominaciones y nombres serán reducidos a estas dos categorías:
ovejas y cabras, justos e injustos.
De hecho, los mismos justos deben ser probados,
lo que hizo que un hombre santo exclamara: "`Si el justo con dificultad se salva,
¿en dónde aparecerá el impío y el pecador?`"^
footnote:[1 Pedro 4:18]
Si sus pensamientos,
palabras y obras deben ser probados y escrutados
por el Juez imparcial del cielo y de la tierra,
¿cómo podrían quedar eximidos los impíos? No,
Aquel que no puede mentir nos ha dicho que muchos dirán: "`¡Señor, Señor!`"
Presentarán su confesión de fe y enumerarán las obras que han hecho en Su nombre,
y sin embargo serán rechazados con esta horrible sentencia: "`Nunca os conocí;
apartaos de mí, hacedores de maldad.`"^
footnote:[Lucas 13:24-27; Mateos 7:21-23]
Es como si Él hubiera dicho: "`¡Fuera de aquí, hacedores de maldad!
Porque aunque me han profesado, no los conozco.
Váyanse y vuélvanse a los dioses que han servido; a sus amados deseos,
a los que han adorado, y al mundo maligno que tanto han codiciado y venerado.
Que ellos los salven ahora, si pueden, de la ira que vendrá sobre ustedes,
la cual es la paga por las obras que han hecho.`"
Aquí está el final de la obra de aquellos que construyen sobre la arena;
el aliento del Juez la derribará, y su caída será lamentable.

Pero para los justos la sentencia cambia,
y el Juez sonríe. Él dirige la mirada de amor sobre
Sus propias ovejas y las invita con estas palabras:
"`Vengan, benditas de mi Padre, quienes por su paciente perseverancia en hacer el bien,
han esperado por mucho tiempo la inmortalidad.
Ustedes han sido las verdaderas compañeras de Mis tribulaciones y de Mi cruz,
y con inquebrantable fidelidad, en obediencia a Mi santa voluntad,
han perdurado valientemente hasta el final, mirándome a Mí, el Autor de su preciosa fe,
para recibir el grande galardón que he prometido a los que me aman y no desmayan.
Oh, entren en el gozo de su Señor,
y hereden el reino preparado para ustedes desde la fundación del mundo.`"

¡Oh cristiandad!
Mi alma ruega fervientemente que,
después de todas tus elevadas doctrinas acerca de Cristo y de Su religión mansa y santa,
no seas rechazada por tu vida inapropiada y no cristiana en ese gran tribunal del mundo,
y al final pierdas esta salvación tan grande.
Escúchenme cristianos, esta vez, se los ruego:
¿Puede ser Cristo su Señor y ustedes no obedecerle?
¿O pueden ser Sus siervos y, sin embargo, no servirle realmente?
No se engañen, lo que siembren,
eso también segarán. Él no es su Salvador mientras rechacen Su gracia en sus corazones,
por medio de la cual desea salvarlos.
Vengan, díganme, ¿de qué los ha salvado?
¿Los ha salvado de sus deseos pecaminosos,
de sus afectos mundanos y de sus conversaciones vanas?
Si no, entonces Él no es su Salvador.
Porque, aunque se ofrece como Salvador para todos,
en realidad es Salvador sólo de aquellos que son salvados por Él;
y nadie es salvado por Él mientras viva en los males
por los cuales está perdido para Dios,
y de los que Él vino a salvarlos.

Es _del pecado_ que Cristo ha venido a salvar al hombre,
y de la muerte y la ira que son su paga.
Pero aquellos que no son salvos--es decir,
los que no han sido verdaderamente liberados por el poder de Cristo en sus almas,
del poder que el pecado ha tenido sobre ellos--no podrán ser salvados de la muerte
ni de la ira que son la paga segura del pecado en el que viven.
En la medida que las personas obtienen victoria sobre
los deseos malos y carnales a los que han sido adictas,
en esa medida son verdaderamente salvas,
y testigos de la redención que viene por Cristo Jesús. De hecho,
Su nombre muestra Su obra: "`Y llamarás su nombre JESÚS,
porque él salvará a su pueblo de sus pecados.`"^
footnote:[Mateos 1:21]
Juan, hablando de Cristo dice: "`He aquí el Cordero de Dios,
que quita el pecado del mundo.`"^
footnote:[Juan 1:29]
He aquí, Aquel a quien Dios ha dado por Luz al pueblo,
y por salvación a todos los que reciben Su luz y gracia en sus corazones,
y toman Su cruz diaria y Le siguen; es decir,
aquellos que prefieren negarse a sí mismos el placer de satisfacer sus deseos,
antes que pecar contra el conocimiento que Él les ha dado de Su voluntad,
o hacer lo que saben que no deben hacer.
