== Capítulo I. Un Cristianismo sin Cruz

Aunque el conocimiento y la obediencia a la doctrina de la cruz de Cristo,
es de una importancia infinita para las almas de los hombres--siendo
la única puerta al verdadero cristianismo y el camino que los
antiguos siempre anduvieron hacia la bendición--sin embargo,
con extrema aflicción, déjenme decirles, es tan poco entendida, tan descuidada,
y lo que es peor, tan amargamente contradicha por la vanidad,
superstición e intemperancia de los cristianos profesantes.
De hecho, tal es el estado de las cosas en este día,
que debemos o renunciar a la creencia de lo que el Señor Jesús nos ha dicho,
que "`el que no lleva su cruz cada día, y viene en pos de Mí,
no puede ser mi discípulo;`"^
footnote:[Lucas 9:23, 14:27]
o, admitiendo que es la verdad,
concluir que la mayoría de los cristianos miserablemente se
engañan a sí mismos con el gran asunto del cristianismo,
y defraudan su propia salvación.

Porque, aunque seamos los más tiernos y caritativos posible en nuestra consideración de
esas naciones que pretenden estar interesadas en el santo nombre de Cristo,
si vamos a ser justos también,
debemos reconocer que después de todas las ventajas bondadosas de la
luz que estas últimas generaciones del mundo han recibido,
por la venida, vida, doctrina, milagros, muerte, resurrección y ascensión de Cristo,
con los dones de Su Espíritu Santo, a lo cual podemos agregar los escritos,
las obras y los sufrimientos de Sus queridos seguidores en todos los tiempos,
parece que queda muy poco del Cristianismo aparte del nombre.
Y lamentablemente, el nombre de Cristiano,
siendo ahora usurpado por la vieja naturaleza y vida pagana,
hace que muchos de sus profesantes sean nada más que verdaderos paganos disfrazados.
Porque aunque ellos no adoran los mismos ídolos, adoran a Cristo con el mismo corazón;
y nunca podrán hacer otra cosa, mientras vivan en los mismos deseos.
El cristiano no crucificado y los paganos son de la misma religión.

Porque, aunque tienen diferentes objetos a los que dirigen sus oraciones, aun así,
la adoración de ambos es forzada y ceremoniosa,
y la deidad que realmente adoran es el dios de este mundo, el gran señor de los deseos;
ante él se inclinan con todos los poderes del alma y de los sentidos.
¿Qué comeremos, o qué beberemos, o qué vestiremos?
¿Y cómo pasaremos nuestro tiempo?
¿De qué manera podemos acumular riquezas, aumentar el poder,
expandir nuestros territorios,
y dignificar y perpetuar nuestros nombres y familias en la tierra?
Esta sensualidad vulgar es comprendida por el amado apóstol Juan en estas palabras:
"`Los deseos de la carne, los deseos de los ojos, y la vanagloria de la vida,
los cuales no provienen del Padre, sino del mundo que está yace en la maldad.`"^
footnote:[1 Juan 2:16, 5:19]

Es una reflexión triste, pero una realidad que no se puede negar,
que estos deseos mundanos llenan la gran parte del estudio,
atención y conducta del cristianismo.
Y, lo que agrava la miseria es que estas cosas crecen con el tiempo.
Porque a medida que el mundo envejece, se pone peor.
Los ejemplos de los depravados siglos antiguos y sus miserables finales,
no han disuadido, sino más bien alentado el nuestro.
De hecho, el pueblo de este día,
parece que ha perfeccionado la vieja escuela de la impiedad,
y la ha llevado mucho más allá que los ejemplos antiguos, de modo que,
en lugar de avanzar en la virtud,
han caído escandalosamente debajo de la vida de los paganos.
Su altivez, lascivia, inmundicia, embriaguez, sus juramentos, mentiras, envidias,
murmuraciones, crueldades, traiciones, su codicia, injusticia y opresión,
son tan comunes y cometidas con tal creatividad y exceso,
que han hecho que los incrédulos tropiecen y se endurezcan,
y que menosprecien esa religión santa a la que debieron
haber ganado sus afectos mediante su buen ejemplo.

Esta miserable deserción de los tiempos primitivos (cuando la gloria del
cristianismo era la pureza de sus profesantes) no puedo sino llamarla la segunda y
peor parte de la tragedia que vino sobre el bendito Salvador de la humanidad.
Porque los judíos,
a partir del poder de la ignorancia y de su prejuicio
contra el modo nada mundano de Su aparición,
no quisieron reconocerlo cuando vino, y, por lo tanto,
durante dos o tres años lo persiguieron y finalmente lo crucificaron en un día.
Pero la crueldad de los falsos Cristianos dura mucho más. Ellos primero,
como Judas, lo profesaron, y luego, durante estas muchas generaciones,
vilmente lo traicionaron,
lo persiguieron y lo crucificaron mediante una apostasía perpetua en la conducta,
abandonando la abnegación y la santidad de Su doctrina,
mostrando con sus vidas la falsedad de su fe.
Estos son los que el autor de la epístola a los hebreos nos dice que,
"`crucifican de nuevo para sí mismos al Hijo de Dios y le exponen a vituperio.`"^
footnote:[Hebreos 6:6 RV2009]
Juan, en su revelación, llama a sus corazones contaminados,
"`Sodoma y Egipto en sentido espiritual, donde también nuestro Señor fue crucificado,`"^
footnote:[Apocalipsis 11:8]
donde vio al Señor Jesús crucificado mucho después de haber ascendido.
Tal como Cristo dijo en la antigüedad,
que los enemigos del hombre principalmente son los de su propia casa;
así los enemigos de Cristo en este día son principalmente los
que pretenden ser de Su propia religión. De hecho,
estos lo escupen, lo perforan y lo traspasan, lo coronan con espinas,
y le dan hiel y vinagre a beber.
Y esto no es difícil de comprender;
porque aquellos que viven en la misma naturaleza y semilla malignas que los judíos,
quienes lo crucificaron externamente, deben necesariamente crucificarlo internamente.
Los que rechazan la gracia ahora en sus propios corazones,
son uno en linaje y descendencia con los judíos de duro corazón,
que resistieron la gracia que entonces apareció en y por Cristo.

El pecado es de una naturaleza en todo el mundo; porque,
aunque un mentiroso no es un borracho, ni uno que jura, un fornicario,
ni ninguno de estos es un asesino, aun así, todos son de una misma iglesia,
ramas de una misma raíz impía, todos de una sola familia.
No tienen más que un padre, el diablo, como Cristo les dijo a los judíos profesantes,
la iglesia visible de esa época.
Él tuvo por poco sus pretensiones de Abraham y Moisés, y claramente les dijo,
"`todo aquel que hace pecado, esclavo es del pecado.`"^
footnote:[Juan 8:34]
Ellos hacían las obras del diablo, y por lo tanto eran hijos del diablo.
Este argumento se mantendrá siempre por las mismas razones,
y por consiguiente es todavía bueno.
"`Sois esclavos,`" dice Pablo, "`de aquel a quien obedecéis.`"^
footnote:[Romanos 6:16]
Y Juan le dice a las iglesias de la antigüedad,
"`nadie os engañe; el que practica el pecado es del diablo.`"^
footnote:[1 Juan 3:7-8]
¿Fue Judas un mejor cristiano por haber dicho, "`¡Salve, Maestro!`" y besar a Cristo?
¡De ninguna manera!
Estas palabras fueron la señal de su traición,
la señal por la cual los sangrientos judíos lo
identificarían y capturarían. Él lo llamó Maestro,
pero lo traicionó. Lo besó, pero lo vendió para que lo mataran.
Esta es la sustancia de la religión del falso cristiano.
Si un hombre les pregunta: "`¿Es Cristo su Señor?`" Ellos clamarán,
"`¡Por supuesto! Sí, ¡Él es nuestro Señor!`"
"`Muy bien, pero ¿guardan Sus mandamientos?`"
"`No, ¿cómo podríamos?`"
"`¿Cómo entonces son Sus discípulos?`"
"`Es imposible,`" dicen,
"`¡Qué! ¿Quieres que guardemos Sus mandamientos? ¡Ningún hombre puede!`"
Pero, ¿es imposible hacer aquello, sin lo cual Cristo hizo imposible ser cristiano?
¿Cristo demanda algo excesivo?
¿Siega donde no ha sembrado, o requiere lo que no ha hecho posible?
Así es que, junto con Judas, lo llaman Maestro,
pero se unen con el mal del mundo para traicionarlo.
Lo besan y lo abrazan, hasta donde alcancen sus creencias;
y luego lo venden para satisfacer las pasiones que más disfrutan.

Que nadie engañe su propia alma; las uvas no se recogen de los espinos,
ni los higos de los abrojos; un lobo no es una oveja, ni un buitre una paloma.
Cualquiera sea la forma, el pueblo, o la iglesia de la que seas,
esta es la verdad de Dios para la humanidad: Los que tienen la forma de la piedad,
pero que con sus vidas no crucificadas niegan su poder, componen la iglesia falsa,
no la verdadera.
Y aunque esta iglesia puede llamarse a sí misma la novia del Cordero,
o la iglesia de Cristo, ella es la misteriosa Babilonia,
que es debidamente llamada por el Espíritu Santo,
"`la madre de las rameras, y de toda abominación.`"^
footnote:[Apocalipsis 17:5]
Ella se ha degenerado de la castidad y pureza cristianas,
a todas las abominaciones de la Babilonia pagana--una lujosa ciudad de la antigüedad,
muy conocida como la sede de todos los reyes de Babilonia,
y en aquel entonces el lugar de más orgullo y lujo.
Como ella era, así es la Babilonia mística, la gran enemiga del verdadero pueblo de Dios.

Es muy cierto que los que nacen de la carne,
odian y persiguen a los que nacen del Espíritu, los circuncisos de corazón,
los cuales no pueden reconocer, ni adorar a Dios según las invenciones,
métodos y prescripciones de Babilonia, ni recibir como doctrina sus vanas tradiciones,
ni cumplir con sus corruptas modas y costumbres en su conducta.
Y debido a que no se pueden conformar,
la Babilonia apostata rápidamente se convierte en perseguidora.
No es suficiente que ella misma decline la pureza antigua,
otros deben hacerlo también. No les dará descanso a los que no
participen con ella en su degeneración ni reciban su marca.
¿Habrá alguien más sabio que ella, que la así llamada iglesia madre?
No, no, ni nadie podrá hacer guerra contra la bestia sobre la que monta--
esos poderes mundanos que la protegen y prometen
mantenerla contra los clamores de sus disidentes.
La apostasía y la superstición son siempre orgullosas e impacientes
con la disensión. Todos deben conformarse o perecer.
Por lo tanto,
los testigos muertos y la sangre de las almas debajo del altar
se encuentran dentro de los muros de esta Babilonia mística,
la gran ciudad de los falsos cristianos,
y son cargados sobre ella por el Espíritu Santo en el libro de Apocalipsis.

Los hijos de Babilonia están conquistados tan
completamente bajo el dominio de las tinieblas,
por medio de su continua desobediencia a la manifestación de la luz divina en sus almas,
que han olvidado lo que el hombre fue alguna vez, o lo que ellos deberían ser ahora.
Ellos no reconocen el cristianismo puro y verdadero cuando lo ven,
aunque se enorgullecen de profesarlo.
Su visión de la salvación es tan carnal y falsa,
que a lo bueno lo llaman malo y a lo malo bueno.
Hacen del diablo un cristiano y de un santo un diablo.
Y aunque la injusta indulgencia de sus vidas es una fuente de
lamentación (como también de la destrucción de sí mismos),
sin embargo,
la noción falsa de que pueden ser hijos de Dios mientras están
en el estado de desobediencia a Sus santos mandamientos,
de todos los demás engaños, es el más mortal para su condición eterna.
Por desgracia,
ellos creen que son discípulos de Jesús aún cuando se rebelan contra Su cruz.
Se halagan a sí mismos como si fuesen miembros de Su
iglesia verdadera que no tiene mancha ni arruga,
a pesar de que sus vidas están llenas de manchas y arrugas.
Porque ellos están en paz en el pecado, y bajo seguridad en su transgresión.

Sus esperanzas vanas silencian sus convicciones internas y entierran
todos los tiernos movimientos hacia el arrepentimiento,
de modo que su error respecto a su deber a Dios es tan malicioso como
su rebelión contra Él. Así caminan sobre precipicios y se adulan a sí
mismos hasta que la tumba se los traga,
y el juicio del gran Dios rompa su letargo y desengañe sus pobres y miserables
almas con la angustia de los inicuos como recompensa por sus obras.

Esto ha sido,
es y será la perdición de todos los cristianos mundanos--un final tan terrible,
que nada más la compasión sería suficiente para incitarme a disuadir
a todos en contra de la supersticiones y deseos mundanos,
y para invitar a los profesantes del cristianismo al conocimiento y obediencia de
la cruz diaria de Cristo como el único camino dado por Él y designado para nosotros,
que conduce a la bendición. Mediante esta cruz diaria,
los que ahora no hacen sino usurpar el nombre, podrán tener la cosa misma;
y por su poder podrán ser partícipes de la resurrección
que es en Cristo Jesús para una vida nueva.
Porque aquellos que realmente están en Cristo, es decir,
redimidos por Él e implantados en Él, son nuevas criaturas.
Ellos han recibido una nueva voluntad, una que hace la voluntad de Dios, no la suya.
Oran en la verdad, y no se burlan de Dios cuando dicen,
"`Hágase tu voluntad, como en el cielo, así también en la tierra.`"^
footnote:[Mateos 6:10; Lucas 11:2]
Tienen nuevos afectos, que están puestos en las cosas de arriba,
y hacen de Cristo su tesoro eterno.
Tienen una nueva fe,
una que vence las trampas y tentaciones del espíritu del mundo en ellos mismos,
o cuando aparece a través de otros.
Y tienen nuevas obras, no de artilugios supersticiosos, ni de invenciones humanas,
sino los frutos puros del Espíritu de Cristo obrando en ellos--tales como el amor, gozo,
paz, mansedumbre, longanimidad, templanza, afecto fraternal, fe, paciencia y bondad,
y contra tales cosas no hay ley.

Aquellos que no tienen este Espíritu de Cristo y no caminan en Él,
el apóstol Pablo nos ha dicho que, "`no son de Él;`"^
footnote:[Romanos 8:9]
sino que la ira de Dios y la condenación de la ley reposan sobre ellos.
De hecho, "`ninguna condenación hay para los que están en Cristo Jesús,
los que no andan conforme a la carne, sino conforme al Espíritu.`"^
footnote:[Romanos 8;1]
Pero, por esta misma doctrina,
los que _no_ caminan según dicho Espíritu Santo _no_ están en Cristo.
Estos no tienen herencia en Él,
ni tienen ningún derecho verdadero de reclamar su salvación;
y consecuentemente para ellos hay condenación.

=== Un Reprobador y Salvador Interno

La religión de los impíos es una mentira: "`No hay paz,`" dice el profeta,
"`para los impíos.`"^
footnote:[Isaías 48:22; Isaías 57:21]
Y realmente no puede haberla,
porque ellos son reprobados en sus propias conciencias y
condenados en sus propios corazones por toda su desobediencia.
A donde quiera que vayan, la reprensión va con ellos,
y muchas veces los terrores también. Él que los compunge es un Dios ofendido,
y por Su luz "`puso sus pecados delante de sus ojos.`"^
footnote:[Salmos 50:21 Literal del Inglés]
A veces se esfuerzan por apaciguarlo mediante su devoción y adoración externas,
pero en vano; porque la adoración verdadera de Dios es hacer Su voluntad,
la cual ellos transgreden.
A veces huyen a los juegos y a la compañía para ahogar
la voz del Reprobador y desafilar Sus saetas,
para ahuyentar los pensamientos conflictivos y resguardarse a
sí mismos fuera del alcance del Inquietador de sus placeres.
Pero el Todopoderoso, tarde o temprano,
seguro que los alcanzará. No hay escape de Su juicio
para los que rechazan los términos de Su misericordia.
Ciertamente su Acusador está con ellos siempre,
no pueden deshacerse de
Él más que de sí mismos.
Él está en medio de ellos, y se mantendrá cerca de ellos.
Ese Espíritu que testifica a favor de los espíritus
de los justos testificará contra los suyos.
Sí, sus propios corazones los condenarán abundantemente;
y "`si nuestro corazón nos condena,`" dice el apóstol Juan,
"`mayor es Dios, y conoce todas las cosas;`"^
footnote:[1 Juan 3:20]
es decir, no hay escapatoria de los juicios de Dios,
si el hombre no es capaz de escapar de la condenación de sí mismo.

En aquel Día,
los cristianos orgullosos y ostentosos aprenderán que Dios no hace acepción de personas;
que todas las sectas, denominaciones y nombres serán reducidos a estas dos clases:
ovejas y cabras, justos e injustos.
De hecho, los mismos justos deben ser probados, lo cual hizo que un hombre santo clamara:
"`Si el justo con dificultad se salva, ¿En dónde aparecerá el impío y el pecador?`"^
footnote:[1 Pedro 4:18]
Si sus pensamientos,
palabras y obras deben ser probados y someterse al
escrutinio del Juez imparcial del cielo y de la tierra,
entonces ¿cómo los impíos serán eximidos?
No, Aquel que no puede mentir nos dijo que muchos dirán, "`¡Señor, Señor!`"
Presentarán su confesión de fe y contarán las obras que han hecho en Su nombre,
y sin embargo serán rechazados con esta horrible sentencia;
"`Nunca os conocí; apartaos de mí, hacedores de maldad.`"^
footnote:[Lucas 13:24-27; Mateos 7:21-23]
Como si Él hubiera dicho, '`¡Fuera malhechores!
Porque aunque me han profesado, no los conozco.
Váyanse de aquí, y vayan a los dioses que han servido; a sus deseos amados,
que han adorado, y al mundo maligno que tanto han codiciado y venerado.
Que ellos los salven ahora, si pueden, de la ira que vendrá sobre ustedes,
que es la paga por las obras que han hecho.`'
Aquí está el final de la obra de quienes construyen sobre la arena;
el aliento del Juez la derribará, y su caída será lamentable.

Pero para los justos la sentencia cambia y el Juez sonríe.
Él echa el ojo de amor sobre Sus propias ovejas y las invita con un:
"`Vengan, benditos de mi Padre, quienes, por medio de su perseverancia en hacer el bien,
han esperado por mucho tiempo la inmortalidad.
Ustedes han sido los verdaderos compañeros de Mis tribulaciones y de Mi cruz,
y que con una fidelidad inquebrantable, en obediencia a Mi santa voluntad,
han perdurado valientemente hasta el final, mirándome a Mí, el Autor de su preciosa fe,
por el grande galardón, que he prometido para aquellos que me aman y no desmayan.
Oh entren en el gozo de su Señor,
y hereden el reino preparado para ustedes desde de la fundación del mundo.`"

¡Oh Cristiandad!
Mi alma ruega fervientemente,
que después de todas sus doctrinas elevadas acerca de Cristo y Su religión mansa y santa,
no sean rechazados por sus vidas inapropiadas y
no cristianas en ese gran tribunal del mundo,
y al final pierdan esta salvación tan grande.
Escúchenme esta vez, les ruego: ¿Puede Cristo ser su Señor y ustedes no obedecerlo?
O ¿Pueden ser Su siervo y, sin embargo, no servirle realmente?
No se engañen, lo que siembren,
eso también segarán. Él no es su Salvador mientras rechacen Su
Gracia en su corazón por la cual los salvaría. Vengan,
díganme ¿de qué los ha salvado?
¿Los ha salvado de sus deseos pecaminosos,
de sus afectos mundanos y de sus conversaciones vanas?
Si no, entonces Él no es su Salvador.
Porque, aunque se ofrece como un Salvador para todos, sin embargo,
es en realidad un Salvador solo para aquellos que son salvos por Él;
y nadie es salvo por Él si todavía vive en los
males por los cuales está perdido para Dios,
y de los que Él vino a salvarlo.

Es del pecado que Cristo vino a salvar al hombre, y de la muerte y la ira como su paga.
Pero aquellos que no son salvos--es decir,
verdaderamente liberados por el poder de Cristo en sus almas,
del poder que el pecado ha tenido sobre ellos--nunca pueden salvarse de la
muerte y la ira que son la paga segura del pecado en el que viven.
En la medida que las personas obtienen victoria sobre los
deseos malos y carnales a los que han estado adictos,
en esa medida son verdaderamente salvos,
y testigos de la redención que viene por Cristo Jesús. De hecho,
Su nombre muestra Su labor; "`Y llamarás su nombre JESÚS,
porque él salvará a su pueblo de sus pecados.`"^
footnote:[Mateos 1:21]
"`He aquí,`" dice Juan de Cristo,
"`el Cordero de Dios, que quita el pecado del mundo.`"^
footnote:[Juan 1:29]
He aquí Él,
a quien Dios ha dado por Luz al pueblo y por salvación a todos
los que reciben Su luz y gracia en sus corazones,
y toman Su cruz diaria y Lo siguen--aquellos que preferirían
negarse a sí mismos el placer de satisfacer sus deseos,
que pecar en contra del conocimiento que Él les ha dado de Su voluntad,
o hacer lo que saben que no deberían hacer.
