== Capítulo II. La Gran Apostasía

¡Oh cristiandad!
Por todo lo que se ha dicho y por la lámpara que
el Señor ha encendido en ti (si la usas),
debería ser evidente: Primero, cuán grande ha sido tu apostasía;
porque en lugar de ser el templo del Señor,
te has convertido en una jaula de pájaros inmundos; y en lugar de una casa de oración,
eres una cueva de ladrones, una sinagoga de Satanás y la morada de todo espíritu inmundo.
Y segundo, que bajo todo este manifiesto abandono, no obstante,
has valorado el "`yo`" corrupto, basada en tu profesión del cristianismo,
y te has engañado terriblemente a ti misma con la esperanza de
salvación. Lo primero hace que tu enfermedad sea peligrosa,
pero lo último la hace casi incurable.

Sin embargo, hay misericordia en el Dios de compasión, para que sea temido.
Él no se deleita en la muerte eterna de los pobres pecadores,
ni de los que se han apartado,
sino que desea que todos lleguen al conocimiento y a la obediencia de la verdad,
y sean salvos.
Por lo tanto, ha enviado a Su Hijo como propiciación,
y lo ha dado como Salvador para quitar los pecados de todo el mundo,
para que aquellos que creen en Él y lo siguen puedan sentir la justicia de Dios en la
remisión de sus pecados y en la eliminación de sus transgresiones para siempre.
¡He aquí el remedio! ¡Una cura infalible,
escogida por Dios! ¡Un antídoto verdaderamente precioso que nunca ha fallado!
¡Una medicina universal de la que ninguna enfermedad podrá escapar jamás!

Pero ustedes dirán, ¿qué es Cristo, y dónde se halla?
¿Cómo es recibido y aplicado para que obre esta poderosa cura?
Les diré entonces: En primer lugar,
Él es la gran Luz espiritual del mundo que "`alumbra
a todo hombre que viene en este mundo.`"^
footnote:[Juan 1:9 RV1602P]
Y como Luz, les revela a los hombres sus obras de tinieblas y de iniquidad,
y los reprende por haberlas cometido.
En segundo lugar, Él no está lejos de ustedes,
como el apóstol Pablo dijo a los atenienses con respecto a Dios.
Y Cristo mismo dice: "`He aquí, yo estoy a la puerta y llamo;
si alguno oye mi voz y abre la puerta, entraré a él, y cenaré con él, y él conmigo.`"^
footnote:[Apocalipsis 3:20]
¿Qué puerta puede ser esta, sino la del corazón del hombre?

Pero, ¡ay!, tal como la posada de la antigüedad,
ustedes han estado llenos de otros huéspedes.
Sus afectos han hospedado a otros amantes;
no ha habido lugar para el Salvador en sus almas.
Por lo tanto, la salvación aún no ha entrado a sus casas,
aunque ha llegado a sus puertas, y a menudo se les ha ofrecido,
y la han profesado durante mucho tiempo.
Pero si Él todavía llama, si Él todavía toca la puerta, es decir,
si Su luz aún brilla y los reprende,
entonces hay esperanza de que su día no haya terminado,
y de que el arrepentimiento no esté oculto de sus ojos.
Sí, Su amor todavía está dirigido hacia ustedes,
y Su invitación santa continúa con la intención de salvarlos.

Por lo tanto, ¡oh cristiandad, crean, reciban y apliquen a Cristo correctamente!
Esto es de absoluta necesidad para que sus almas
vivan para siempre con Él. Él les dijo a los judíos:
"`Si no creéis que yo soy, en vuestros pecados moriréis; y a donde yo voy,
vosotros no podéis venir.`"^
footnote:[Juan 8:21, 24]
Debido a que ellos no le creyeron, no lo recibieron,
ni obtuvieron ningún beneficio de Él. Pero los que le creyeron, lo recibieron:
"`Mas a todos los que le recibieron,`" nos dice Su discípulo amado,
"`les dio potestad de ser hechos hijos de Dios.
Los cuales son engendrados, no de sangre, ni de voluntad de carne,
ni de voluntad de varón, sino de Dios.`"^
footnote:[Juan 1:12-13]
Es decir, que estos no son hijos de Dios según las modas,
las ordenanzas y las tradiciones de los hombres.
Estos no son Su iglesia ni Su pueblo según la voluntad de la carne y la sangre,
ni según las invenciones de los hombres carnales que no han experimentado
la regeneración ni el poder del Espíritu Santo.
No, estos son engendrados de Dios, según Su voluntad,
y según la operación y santificación de Su Espíritu y Palabra de vida en ellos.
Estos están bien familiarizados con la aplicación correcta de Cristo,
porque Él verdaderamente les ha sido hecho propiciación, reconciliación, salvación,
justicia, redención y justificación.

Así mismo les digo que,
a menos que crean que Aquel que está a la puerta de su corazón y llama,
que pone sus pecados en orden delante de sus ojos, y los llama al arrepentimiento,
es el Salvador del mundo, ustedes también morirán en sus pecados; y a donde Él ha ido,
ustedes nunca llegarán. Porque si no creen en Él,
es imposible que les haga bien o los salve.
Cristo no obra _contra_ la fe, sino por medio de ella.
Fue dicho en la antigüedad,
que Él no hizo muchos milagros en algunos lugares porque las personas
no creían en Él. Si ustedes creen verdaderamente en Él,
sus oídos estarán atentos a Su voz en ustedes,
y la puerta de sus corazones se abrirán a Su llamado.
Se entregarán a los descubrimientos de Su luz,
y las enseñanzas de Su gracia les serán muy preciadas.

Es la naturaleza de la verdadera fe engendrar un santo temor de ofender a Dios,
una profunda reverencia a Sus preceptos,
y una atención muy tierna al testimonio interno de Su Espíritu,
como aquello por medio de lo cual Sus hijos, en todas las edades,
han sido guiados a salvo a la gloria.
Porque así como los que verdaderamente creen,
reciben a Cristo en todas Sus ofertas al alma, también los que Lo reciben de esta manera,
reciben el poder para ser hechos hijos de Dios; es decir,
reciben el poder y habilidad interna para hacer lo que sea que Él requiera;
fuerza para hacer morir sus deseos, para controlar sus afectos,
resistir motivaciones malignas,
negarse a sí mismos y vencer al mundo en sus apariciones más tentadoras.

Esta es la vida de la bendita cruz de Cristo, que es el tema del siguiente discurso;
y ésta es la que tú, oh hombre, debes tomar,
si tienes la intención de ser un discípulo de Jesús.
Porque no puedes recibir verdaderamente a Cristo,
o creer en Él, mientras rechazas Su cruz.
Recibir a Cristo es el medio designado por Dios para la salvación. Por lo tanto,
tomar tu cruz diaria en pos de Él es el verdadero testimonio de haberle recibido,
y la gran señal del discipulado.
"`Si alguno quiere venir en pos de mí, niéguese a sí mismo, y tome su cruz, y sígame.`"^
footnote:[Mateos 16:24]

Esto, cristianos, es lo que tanto les ha faltado,
y la falta de ello ha demostrado ser la causa de
la lamentable apostasía del cristianismo puro.
Consideren esto bien, porque es su deber,
y será de gran utilidad para su restauración. Así como el conocimiento
correcto de una enfermedad guía al médico a hacer un juicio acertado
y seguro en la aplicación de su medicina,
de igual manera,
conocer y considerar la causa primaria de esta falla
y enfermedad espiritual que les ha sucedido,
les iluminará mucho en el camino de su recuperación. Para hacer esto,
será necesaria una visión general del estado primitivo del cristianismo y de
la obra de aquellos que trabajaron primero en la viña de Cristo.

=== El Cristianismo Primitivo

La obra del apostolado, nos dice un destacado obrero en ella,
era convertir a las personas "`de las tinieblas a la luz,
y de la potestad de Satanás a Dios.`"^
footnote:[Hechos 26:18]
Es decir, que en lugar de ceder a las tentaciones e inclinaciones de Satanás,
quien es el príncipe de las tinieblas o de la iniquidad (siendo
una palabra metáfora de la otra) por cuyo poder sus entendimientos
estaban oscurecidos y sus almas mantenidas en servidumbre al pecado,
debían volver sus mentes a la aparición de Cristo, la Luz y el Salvador del mundo.
Por Su luz Él resplandece en sus almas y, de ese modo, los hace ver sus pecados.
Descubre cada tentación y movimiento en ellos hacia el mal,
y los reprende cada vez que ceden a ello,
para que de esta manera puedan convertirse en hijos
de la luz y caminar en la senda de la justicia.
Para esta bendita obra de reforma, Cristo dotó a Sus apóstoles con Su Espíritu y poder,
para que los hombres no siguieran durmiendo en la
seguridad del pecado y en la ignorancia de Dios,
sino que despertaran a la justicia y recibieran vida del Señor Jesucristo.
Entonces, ellos fueron capacitados para dejar de pecar,
para negarse a sí mismos los placeres de la iniquidad y,
mediante el arrepentimiento verdadero, volver sus corazones a Dios haciendo el bien,
en lo cual encontraron paz.
Y en verdad, Dios bendijo tanto las fieles labores de estos pobres
comerciantes (Sus grandes embajadores para la humanidad),
que, en unos pocos años,
muchos miles que habían vivido sin Dios en el mundo--sin un sentido o temor de Él,
en iniquidad y como extraños a la obra de Su Espíritu en sus corazones,
estando cautivos por los deseos carnales--fueron internamente
golpeados y vivificados por la Palabra de Vida,
y hechos partícipes de la venida y el poder del Señor
Jesucristo como Juez y Legislador en sus almas.
Por Su santa luz y Espíritu,
las cosas ocultas de las tinieblas fueron sacadas a la luz y condenadas,
y el arrepentimiento puro de esas obras muertas fue engendrado en ellos
para que sirvieran al Dios vivo en la novedad del Espíritu.

En consecuencia, estos ya no vivían para sí,
ni se dejaban llevar por sus antiguos deseos,
que los habían seducido del verdadero temor de Dios.
En lugar de eso,
la ley del Espíritu de vida (por la que vencieron la ley del pecado
y de la muerte) era su delicia y en ella meditaban día y noche.
Su temor a Dios ya no provenía de los mandamientos de hombres,
sino del conocimiento que habían recibido de la propia
obra e impresiones de Dios en sus almas.
Habían abandonado a sus antiguos amos--el mundo,
la carne y el diablo--y se habían entregado a la guía santa de la gracia de Cristo,
que les enseñaba a "`renunciar a la impiedad y a los deseos mundanos,
y a vivir en este mundo presente sobria, justa y piadosamente.`"^
footnote:[Tito 2:11]
Esta es, en verdad, la cruz de Cristo;
y aquí está la victoria que le da a aquellos que la toman.
Por esta cruz morían diariamente a la vieja vida que habían vivido,
y mediante una santa vigilancia contra los movimientos secretos del mal en sus corazones,
aplastaban el pecado en su concepción, sí, incluso en sus tentaciones.
De modo que, como dice el apóstol Juan hablando del que es engendrado de Dios,
"`se guardaba a sí mismos, y el maligno no los tocaba.`"^
footnote:[1 Juan 5:18 RV1602P]

La luz, que Satanás no puede soportar, y con la que Cristo los había iluminado,
descubría su adversario en todos sus acercamientos y asaltos a la mente,
y el poder que recibían a través de su obediencia a las manifestaciones de la luz bendita,
los capacitaba para resistirlo y vencerlo en todas sus estratagemas.
Así fue como, donde una vez nada era examinado, ahora nada quedaba sin examinar.
Cada pensamiento debía ir a juicio,
y tanto su origen como su tendencia debían ser aprobados
antes de que le permitieran algún lugar en sus mentes.
No había ningún temor de hospedar enemigos como amigos,
siempre que se mantuviera esta estricta guardia en la puerta misma del alma.
Los cielos y la tierra antiguos, es decir,
la vieja forma de vida terrenal y la vieja adoración carnal o figurativa pasaban rápidamente,
y cada día todas las cosas se volvían nuevas.
"`Pues no es judío el que lo es exteriormente,
ni es la circuncisión la que se hace exteriormente en la carne;
sino que es judío el que lo es en lo interior, y la circuncisión es la del corazón,
en espíritu, no en letra; la alabanza del cual no viene de los hombres, sino de Dios.`"^
footnote:[Romanos 2:28-29]

La gloria de la cruz brillaba tan claramente a través de la negación
al yo en las vidas de aquellos que la tomaban diariamente,
que llenó a los paganos de asombro, y en poco tiempo sacudió sus altares,
desacreditó sus oráculos, impactó a la multitud,
invadió los tribunales y venció a sus ejércitos, de tal manera que llevó a sacerdotes,
magistrados y generales en triunfo tras de ella como trofeos de su poder y victoria.

Mientras esta integridad habitaba en los cristianos,
poderosa era la presencia e invencible el poder que los acompañaba.
Apagaron fuegos impetuosos, taparon bocas de leones, evitaron filo de espada,
derrotaron instrumentos de crueldad, convencieron jueces y convirtieron verdugos.
Los medios con los que sus enemigos buscaban destruirlos sólo lograban incrementarlos;
y por la profunda sabiduría de Dios,
aquellos que con todas sus maquinaciones trataban de extinguir
la verdad eran hechos grandes promotores de ella.
Entre los fieles no se permitía un pensamiento vano, ni una palabra ociosa,
ni una acción impropia, no, ni siquiera una mirada impura.
No había vestimenta refinada, atavíos ostentosos,
saludos halagadores ni honores personales;
mucho menos podían encontrar lugar y ejemplo entre ellos las inmoralidades
obscenas y vicios escandalosos que ahora están de moda entre los cristianos.
Su mayor interés no era cómo gastar su precioso tiempo, sino como redimirlo,
para tener suficiente para "`ocuparse en su salvación con temor y temblor,`"^
footnote:[Filipenses 2:12]
no con fiestas y bailes de máscaras, ni con teatros, danzas, banquetes ni juegos, ¡no,
no! "`Hacer firme su vocación y elección`"^
footnote:[2 Pedro 1:10]
les era mucho más preciado que los pobres e insignificantes placeres de la mortalidad.

Habiendo, junto con Moisés, "`visto al Invisible`"^
footnote:[Hebreos 11:27]
y hallado que Su misericordia era mejor que la vida,
y la paz de Su Espíritu más que el favor de los príncipes,
no temieron la ira de César y escogieron sufrir las aflicciones de los verdaderos
peregrinos de Cristo antes que gozar de los deleites temporales del pecado.
Sí, tuvieron por mayores riquezas Sus vituperios
que los tesoros perecederos de la tierra.
Y si las tribulaciones del cristianismo les eran
más deseables que todas las comodidades del mundo,
y los vituperios de uno más atractivos que todos los honores del otro, entonces no había,
ciertamente,
tentación en el mundo que pudiera hacer tambalear la integridad de la cristiandad.

=== La Gran Apostasía

Con esta breve perspectiva de lo que era el cristianismo, puedes ver, oh cristiandad,
lo que no eres y lo que deberías ser.

Pero, ¿cómo es posible que, de un pueblo tan manso, misericordioso, abnegado, sufrido,
moderado, santo, justo y bueno, y tan semejante a Cristo cuyo nombre llevaban,
hoy encontremos un cristianismo que es supersticioso, idólatra, perseguidor, orgulloso,
apasionado, envidioso, malicioso, egoísta, bebedor, lascivo, impuro, mentiroso, perjuro,
maldiciente, codicioso, opresor,
estafador--con todas las otras abominaciones conocidas en la tierra,
y en un grado tan excesivo que resulta un escándalo
incluso para la peor de las edades paganas,
superándolas más en el mal que en el tiempo: digo,
cómo ocurrió esta lamentable deserción? Ofrezco esto
como la razón indudable de esta degeneración,
a saber:
_La falta de atención en la mente de los cristianos a la luz de Cristo brillando en ellos,
que primero les mostró sus pecados y los reprobó,
y también les enseñó y los capacitó para negarlos y resistirlos._
Porque es cierto que,
cualquiera que sea la medida de temor hacia Dios
y la abstinencia de la injusticia que experimenten,
esto no fue enseñado por los mandamientos de los hombres,
sino por aquella luz y gracia que revela los pensamientos
e intenciones más secretas del corazón,
escudriña sus partes más íntimas,
pone sus pecados en orden delante de sus ojos y los reprende por ellos,
no permitiendo que ni un solo pensamiento,
palabra u obra infructífera de las tinieblas quede sin juicio.
Por lo tanto, cuando comenzaron a ignorar esta luz y gracia,
a descuidar la vigilancia santa que una vez fue establecida en sus corazones,
y dejaron de velar allí como antes (para la gloria de Dios y para su propia paz),
entonces,
el incansable enemigo del bien del hombre rápidamente aprovechó esta negligencia,
y a menudo los sorprendió con tentaciones,
cuya concordancia con sus propias inclinaciones hizo
que la conquista sobre ellos no fuese difícil.

Sí, se rehusaron a tomar el santo yugo de Cristo y llevar su cruz diaria.
Fueron indiferentes con sus propios afectos y no mantuvieron control sobre sus acciones,
olvidando llevar cuentas en sus propias conciencias por medio de Cristo, su luz,
el gran Obispo de sus almas y Juez de sus obras.
De esta manera, su temor santo decayó y su amor se enfrió;
y así la vanidad se multiplicó y el deber se convirtió en una carga.

Entonces surgió la formalidad, en lugar del poder de la piedad;
y la superstición ocupó el lugar de la obra de Cristo.
Y a pesar de que la intención de Cristo era sacar
las mentes de sus discípulos de un templo externo,
con sus ritos y servicios carnales,
y llevarlos a la adoración de Dios interna y espiritual
(adecuada a la naturaleza de la divinidad),
aun así, se introdujo nuevamente la adoración mundana, humana y pretenciosa,
y se restablecieron el sacerdocio, el templo y el altar del mundo.
Ahora "`los hijos de Dios una vez más vieron que las hijas de los hombres eran hermosas,`"^
footnote:[Genesis 6:2]
es decir,
el ojo puro que el arrepentimiento había abierto
y que no veía ninguna hermosura fuera de Cristo,
se oscureció; y el ojo del deseo fue abierto de nuevo por el dios del mundo.
Y entonces aquellos placeres mundanos--que hacen que quienes los aman se olviden de Dios,
a pesar de que una vez fueron despreciados por amor a Cristo--comenzaron
a recuperar su antigua belleza e interés en sus afectos;
y agradándoles, se volvieron la búsqueda, la preocupación y el placer de sus vidas.

Es cierto,
todavía quedaban las formas externas de adoración y una
reverencia sólo de nombre y de palabras a Dios y a Cristo.
Pero esto fue todo lo que sobrevivió; porque el tropiezo de la santa cruz cesó,
el poder de la piedad se negó, la negación al yo se perdió,
y a pesar de que se hicieron fructíferos en la invención de ornamentos ceremoniosos,
permanecieron estériles en cuanto a los benditos frutos del Espíritu.
¡Ay!
Mil cáscaras no pueden hacer un grano, ni muchos cadáveres un hombre vivo.

Así, la religión cayó de la experiencia a la tradición,
y la adoración cayó del poder a la forma, de la vida a la letra.
En lugar de elevar peticiones vivas y poderosas a Dios,
animadas por un profundo sentido de necesidad y por la asistencia
del Espíritu Santo (por quien los antiguos oraban,
luchaban y prevalecían con Dios), he aquí, una repetición predeterminada,
una formalidad aburrida e insípida, que consiste en inclinarse y arrodillarse,
en vestidos y muebles especiales, en perfumes,
voces y música--una actuación más apropiada para la recepción de algún príncipe terrenal,
que para la adoración celestial del único Dios verdadero e inmortal,
quien es un espíritu eterno e invisible.

A medida que sus corazones se hacían más carnales, su religión también lo hacía;
y como ya no les gustaba como era, la amoldaron a su gusto.
Sin ninguna duda, olvidaron las palabras del santo profeta:
"`El sacrificio de los impíos es abominación a Jehová,`"^
footnote:[Proverbios 15:8]
y el dicho de Santiago: "`Pedís, y no recibís,`" ¿por qué? "`porque pedís mal;`"^
footnote:[Santiago 4:3]
es decir, con un corazón que no es recto, sino falso y no crucificado,
no en la fe que purifica el alma, y por lo tanto, nunca pueden recibir lo que piden.
Por eso, ahora puede decirse con verdad,
que la condición de muchos se empeora por su religión,
porque son tentados a pensar que son mejores por ella, a pesar de que no lo son.

Por esta visión que se les da de su caída del cristianismo primitivo,
y de la verdadera causa de ello--a saber,
un abandono de la cruz diaria de Cristo--confío en
que el camino a la restauración sea fácilmente visto.
Por la puerta por la que salieron, deben volver a entrar.
Así como todo se perdió por rechazar y dejar caer la cruz diaria,
tomarla y soportarla será su medio de recuperación. Esta
es la manera por la que los pecadores y los apóstatas se
convierten en discípulos de Jesús. "`Si alguno,`" dice Cristo,
"`quiere venir en pos de mí y ser mi discípulo, niéguese a sí mismo, y tome su cruz,
y sígame.`"
Nada inferior a esto servirá. Así como esto es suficiente, también es indispensable.
No hay corona sino por medio de la cruz; no hay vida eterna sino a través de la muerte.
Y es justo que esos deseos malvados y bárbaros que crucificaron de nuevo a Cristo, ahora,
por Su santa cruz, sean crucificados en ustedes.
La sangre requiere sangre; Su cruz es la muerte del pecado que causó Su muerte;
y Él es la muerte de la muerte, según aquel pasaje: "`¡Oh muerte, yo seré tu muerte!`"^
footnote:[Oseas 13:14 Reina Valera de Gomez]
