== Capítulo II. La Gran Apostasía

¡Oh Cristiandad!
Por todo lo que se ha dicho,
y por la lámpara que el Señor ha encendido en ustedes (si la usan),
debería aparecer evidentemente: Primero, cuán grande ha sido su rebelión;
porque en lugar de ser el templo del Señor,
se han convertido en una jaula de pájaros inmundos; y en lugar de una casa de oración,
son una cueva de ladrones, una sinagoga de Satanás y la morada de todo espíritu inmundo.
Y segundo, que bajo toda esta manifiesta deserción, ustedes, sin embargo,
han estimado a su "`yo`" corrupto, basados en su profesión del cristianismo,
y se han engañado terriblemente a sí mismos con la esperanza de la
salvación. Lo primero hace que su enfermedad sea peligrosa,
pero lo último la hace casi incurable.

Sin embargo, hay misericordia en el Dios de compasión, para que sea reverenciado.
Él no se deleita en la muerte eterna de los pobres pecadores y rebeldes,
sino que desea que todos vengan al conocimiento y a la obediencia de la verdad,
y sean salvos.
Por lo tanto, ha enviado a Su Hijo como propiciación,
y lo ha dado como Salvador para quitar los pecados del mundo entero,
para que aquellos que creen en Él y lo siguen,
puedan sentir la justicia de Dios en la remisión de sus
pecados y en la eliminación de sus transgresiones para siempre.
¡He aquí el remedio!
¡Una cura infalible, escogida por Dios!
¡Un antídoto realmente precioso que nunca ha fallado!
¡Una medicina universal de la que ninguna enfermedad podría escapar jamás!

Pero ustedes dirán, ¿qué es Cristo, y dónde se encuentra?
¿Cómo es recibido y aplicado para que obre esta poderosa cura?
Les diré entonces: En primer lugar,
Él es la gran Luz espiritual del mundo que
"`alumbra a todo hombre que viene en este mundo.`"^
footnote:[Juan 1:9 RV1602P]
Y como Luz, les revela a los hombres sus obras de tinieblas y de iniquidad,
y los reprende por haberlas cometido.
En segundo lugar, que no está lejos de ustedes,
como el apóstol Pablo dijo a los Atenieses con respecto a Dios.
Y Cristo mismo dice, "`He aquí, yo estoy a la puerta y llamo;
si alguno oye mi voz y abre la puerta, entraré a él, y cenaré con él, y él conmigo.`"^
footnote:[Apocalipsis 3:20]
¿Qué puerta puede ser esta, sino la del corazón del hombre?

Pero, por desgracia, tal como la posada de la antigüedad,
ustedes han estado llenos de otros invitados.
Sus afectos han hospedado a otros amantes;
no ha habido lugar para su Salvador en sus almas.
Por lo tanto, la salvación aún no ha entrado a su casa, aunque ha llegado a su puerta,
y a menudo se les ha ofrecido, y la han profesado durante mucho tiempo.
Pero si todavía llama, si todavía toca la puerta, es decir,
si Su luz aún brilla y los reprende,
entonces hay esperanza de que su día no haya terminado,
y de que el arrepentimiento no esté oculto de sus ojos.
Sí, Su amor todavía está hacia ustedes,
y Su invitación santa continúa con la intención de salvarlos.

Por lo tanto, ¡Oh Cristiandad, crean, reciban y apliquen a Cristo correctamente!
Esto es de absoluta necesidad,
para que sus almas vivan para siempre con Él.
Él les dijo a los judíos,
"`Si no creéis que yo soy, en vuestros pecados moriréis; y a donde yo voy,
vosotros no podéis venir.`"^
footnote:[Juan 8:21, 24]
Debido a que ellos no le creyeron, por eso, no lo recibieron,
ni obtuvieron ningún beneficio de Él. Pero los que le creyeron, Lo recibieron;
"`Y a todos los que le recibieron,`" dice Su propio discípulo amado,
"`les dio poder para ser hechos hijos de Dios; los cuales no son engendrados de sangre,
ni de voluntad de carne, ni de voluntad de varón, sino de Dios`"^
footnote:[Juan 1:12-13]
Es decir, que estos no son hijos de Dios según las modas,
las ordenanzas y las tradiciones de los hombres.
Estos no son Su iglesia ni Su pueblo de acuerdo a la voluntad de la carne y la sangre,
ni de acuerdo a las invenciones de los hombres carnales que no han
experimentado la regeneración ni el poder del Espíritu Santo.
No, estos nacieron de Dios, según Su voluntad,
y según la operación y santificación de Su Espíritu y Palabra de vida en ellos.
Tales como estos están bien familiarizados con la aplicación correcta de Cristo,
porque Él verdaderamente les ha sido hecho propiciación, reconciliación, salvación,
justicia, redención y justificación.

Así mismo les digo,
a menos que crean que Aquel que está a la puerta de su corazón y toca,
y que pone sus pecados en orden delante de sus ojos y los llama al arrepentimiento,
es el Salvador del mundo, ustedes también morirán en sus pecados;
y a donde Él se ha ido, nunca llegarán.
Porque si no creen en Él,
es imposible que les haga bien o efectúe su salvación.
Cristo no obra en contra de la fe, sino por medio de ella.
Fue dicho en la antigüedad,
que Él no hizo muchos milagros en algunos lugares porque las personas no creían en Él.
Si ustedes creen verdaderamente en Él,
su oído estará atento a Su voz en ustedes,
y la puerta de su corazón se abrirá a Sus toques.
Se entregarán a los descubrimientos de Su luz,
y las enseñanzas de Su gracia les serán muy preciadas.

Es la naturaleza de la verdadera fe engendrar un santo temor de ofender a Dios,
una profunda reverencia a Sus preceptos y una atención muy tierna del
testimonio interno de Su Espíritu como aquello por lo que Sus hijos,
en todas las edades, han sido guiados a salvo a la gloria.
Porque, así como los que verdaderamente creen,
reciben a Cristo en todas Sus ofertas al alma,
también aquellos que Lo reciben de esta manera,
reciben el poder para ser hechos hijos de Dios; es decir,
reciben el poder o habilidad interna para hacer lo que sea que Él requiera:
fuerza para mortificar sus deseos, para controlar sus afectos,
resistir motivaciones malignas,
negarse a sí mismos y vencer al mundo en sus apariciones más tentadoras.
Esta es la vida de la bendita cruz de Cristo, que es el tema del siguiente discurso;
y esto es lo que tú, oh hombre, debes tomar,
si tienes la intención de ser un discípulo de Jesús.
Porque no puedes recibir verdaderamente a Cristo,
o creer en Él, mientras rechazas Su cruz.
Recibir a Cristo es el medio designado por Dios para la salvación, y, por lo tanto,
tomar tu cruz diaria y seguirlo es el verdadero testimonio de haberlo recibido,
y la gran marca del discipulado.
"`Si alguno quiere venir en pos de mí, niéguese a sí mismo, y tome su cruz, y sígame.`"^
footnote:[Mateos 16:24]

Cristianos, esto es lo que tanto les ha faltado,
y la falta de ello ha demostrado ser la causa de
la declinación miserable del cristianismo puro.
Consideren esto bien, porque es su deber,
y será de gran utilidad para su restauración. Así como el
conocimiento correcto de una enfermedad guía al médico a hacer
un juicio correcto y seguro en la aplicación de su medicina,
de la misma manera,
conocer y considerar la primera causa de esta falla y
enfermedad espiritual que les ha sucedido,
los iluminará mucho en el camino de su recuperación.
Para hacer esto, será necesario tener una visión general del estado primitivo del
cristianismo y de la obra de aquellos que laboraron primero en la viña de Cristo.

=== El Cristianismo Primitivo

La obra del apostolado, nos dijo un obrero principal en ella,
fue convertir a los pueblos
"`de las tinieblas a la luz, y de la potestad de Satanás a Dios.`"^
footnote:[Hechos 26:18]
Es decir, que en lugar de que se entreguen a las tentaciones y mociones de Satanás,
quien es el príncipe de las tinieblas o la
iniquidad (siendo una cosa metáfora de la otra),
por cuyo poder sus entendimientos fueron oscurecidos y
sus almas se mantenían en servidumbre al pecado,
ellos deben volver sus mentes a la aparición de Cristo, la Luz y el Salvador del mundo.
Por Su luz Él resplandece en sus almas y de ese modo los hace ver sus pecados.
Descubre cada tentación y movimiento en ellos hacia el mal,
y los reprende cada vez que ceden a ello,
para que de esta manera puedan convertirse en hijos de
la luz y caminen en la senda de la justicia.
Cristo, para esta bendita obra de reforma, dotó a Sus apóstoles con Su Espíritu y poder,
para que los hombres ya no duerman en seguridad en el pecado y en la ignorancia de Dios,
sino que se despierten para la justicia y reciban vida del Señor Jesucristo.
Estos entonces, fueron capacitados para dejar de pecar,
para negarse a sí mismos los placeres de la iniquidad y,
mediante el arrepentimiento verdadero, volver sus corazones a Dios haciendo el bien,
en lo cual encontraron paz.
Y de verdad,
Dios bendijo tanto las labores fieles de estos pobres
comerciantes (Sus grandes embajadores para la humanidad),
que, en unos pocos años,
muchos miles que habían vivido sin Dios en el mundo--sin un sentido o temor de Él,
en iniquidad y como extraños a la obra de Su Espíritu en sus corazones,
estando cautivos por los deseos carnales--fueron golpeados y
vivificados internamente por la Palabra de Vida,
y hechos partícipes de la venida y el poder del Señor
Jesucristo como un Juez y un Legislador en sus almas.
Por Su santa luz y Espíritu,
las cosas ocultas de las tinieblas fueron sacadas a la luz y condenadas,
y el arrepentimiento puro de esas obras muertas fue engendrado en
ellos para que sirvieran al Dios vivo en la novedad del Espíritu.

Consecuentemente, estos ya no vivían para sí,
ni se dejaban llevar por sus antiguos deseos que los
habían seducidos fuera del verdadero temor de Dios.
En lugar de eso,
la ley del Espíritu de vida
(por la que vencieron la ley del pecado y de la muerte)
era su delicia y en ella meditaban día y noche.
Su temor de Dios ya no provenía de mandamientos de hombres,
sino del conocimiento que habían recibido de Su propia obra e impresiones en sus almas.
Ellos abandonaron sus antiguos maestros--el mundo,
la carne y el diablo--y se entregaron a la guía santa de la gracia de Cristo,
que les enseñaba a "`renunciar a la impiedad y a los deseos mundanos,
y a vivir en este mundo presente sobria, justa y piadosamente.`"^
footnote:[Tito 2:11]
Esta es la cruz de Cristo en verdad;
y aquí está la victoria que le da a aquellos que la toman.
Por esta cruz ellos morían diariamente a la vida vieja que habían vivido,
y por una vigilancia santa en contra de los
movimientos secretos del mal en sus corazones,
aplastaron el pecado en su concepción, sí, incluso en sus tentaciones.
De modo que, como aconseja el apóstol Juan,
"`se guardaban a sí mismos, y el maligno no los tocaba.`"^
footnote:[1 Juan 5:18 RV1602P]

La luz, que Satanás no puede soportar, y con la que Cristo los había iluminado,
descubría su adversario en todos sus acercamientos y asaltos a la mente,
y el poder que recibían a través de su obediencia a las
manifestaciones de la luz bendita,
los capacitaba para resistirlo y vencerlo en todas sus estratagemas.
Así que, donde una vez nada era examinado, ahora todo era examinado.
Cada pensamiento debía ir a juicio,
y su levantamiento y tendencia debían aprobarse antes
de que le permitieran algún lugar en sus mentes.
No había ningún temor de hospedar enemigos como amigos,
mientras esta estricta guardia se mantenía en la puerta misma del alma.
Los cielos y tierra antiguos, es decir,
la vieja forma de vida terrenal y la vieja adoración
carnal o figurativa pasaban rápidamente,
y cada día todas las cosas se volvían nuevas.
"`Pues no es judío el que lo es exteriormente,
ni es la circuncisión la que se hace exteriormente en la carne;
sino que es judío el que lo es en lo interior, y la circuncisión es la del corazón,
en espíritu, no en letra; la alabanza del cual no viene de los hombres, sino de Dios.`"^
footnote:[Romanos 2:28-29]

La gloria de la cruz brilló tan claramente a través de la
abnegación en las vidas de aquellos que la tomaban diariamente,
que llenó a los paganos de asombro, y en poco tiempo sacudió sus altares,
desacreditó sus oráculos, golpeó la multitud,
invadió los tribunales y venció a sus ejércitos, de tal manera que llevó a sacerdotes,
magistrados y generales en triunfo tras de ella como trofeos de su poder y victoria.

Mientras esta integridad habitaba en los cristianos,
poderosa era la presencia e invencible el poder que los acompañaba.
Apagaron fuegos impetuosos, taparon bocas de leones, evitaron filo de espada,
derrotaron instrumentos de crueldad, convencieron jueces y convirtieron verdugos.
Los medios que sus enemigos buscaban para destruirlos solo los aumentaba;
y por la profunda sabiduría de Dios,
aquellos que con todas sus maquinaciones trataban de extinguir la verdad,
eran hechos grandes promotores de ella.
Entre los fieles no se permitía ni un pensamiento vano, ni una palabra ociosa,
ni una acción impropia; no, ni siquiera una mirada inmodesta.
No había vestimenta llamativa, atavíos ostentosos,
saludos halagadores ni honores personales;
mucho menos podrían esas obscenas inmoralidades y vicios
escandalosos que ahora están de moda entre los cristianos,
encontrarse entre ellos.
Su mayor interés no era como gastar su tiempo precioso, sino como redimirlo,
para que pudieran tener suficiente para
"`ocuparse en su salvación con temor y temblor,`"^
footnote:[Filipenses 2:12]
no con fiestas de baile, ni con teatros, danzas, banquetes ni juegos, ¡no,
no! "`Hacer firme su vocación y elección`"^
footnote:[2 Pedro 1:10]
les era mucho más preciado que los pobres e insignificantes placeres de la mortalidad.

Habiendo, con Moisés, "`visto al Invisible,`"^
footnote:[Hebreos 11:27]
y descubierto que Su misericordia era mejor que la vida,
y la paz de Su Espíritu más que el favor de los príncipes,
al igual que él no temieron la ira de César,
y escogieron sufrir las aflicciones de los verdaderos peregrinos de
Cristo antes que gozar de los deleites temporales del pecado.
Sí, tuvieron por mayores riquezas Sus vituperios que los tesoros perecederos de la tierra.
Y si las tribulaciones del cristianismo les eran más
deseables que todas las comodidades del mundo,
y los reproches de uno más atractivos que todos los honores del otro,
entonces seguramente no había tentación en el mundo que
pudiera quebrantar la integridad de la Cristiandad.

=== La Gran Apostasía

Con esta breve perspectiva de lo que fue el cristianismo, ustedes pueden ver,
oh Cristiandad, lo que no son y lo que deberían ser.

Pero ¿cómo es que, de un pueblo tan manso, misericordioso, abnegado, sufrido, moderado,
santo, justo y bueno, y tan semejante a Cristo cuyo nombre llevaba,
hoy encontramos un cristianismo que es supersticioso, idólatra, perseguidor, orgulloso,
apasionado, envidioso, malicioso, egoísta, bebedor, lascivo, impuro, mentiroso, perjuro,
maldiciente, codicioso, opresor,
estafador--con todas las otras abominaciones conocidas en la tierra,
que serían un escándalo incluso para la peor de las edades paganas,
superándolas más en el mal que en el tiempo: digo,
cómo ocurrió esta lamentable deserción? Ofrezco esto
como la razón indudable de esta degeneración, a saber:
_La falta de atención en sus mentes a la luz de Cristo brillando en ustedes,
que primero les mostró sus pecados, y los reprobó,
y también les enseñó y los capacitó para negarlos y resistirlos._
Porque es cierto que,
cualquiera que sea la medida de temor hacia Dios y la
abstinencia de la injusticia que experimentan,
esto no fue enseñado por los mandamientos de los hombres,
sino por aquella luz y gracia que revela los
pensamientos e intenciones más secretas del corazón,
escudriña sus partes más internas,
pone sus pecados en orden delante de sus ojos y los reprende por ellos,
no permitiendo que ni un solo pensamiento,
palabra u obra infructífera de las tinieblas quede sin juicio.
Por lo tanto, cuando comenzaron a ignorar esta luz y gracia,
a descuidar la vigilancia santa que una vez fue puesta en su corazón y no se
mantuvieron vigilantes allí como antes para la gloria de Dios y para su propia paz,
entonces el incansable enemigo del bien del hombre
rápidamente se aprovechó de esta negligencia,
y a menudo los sorprendió con tentaciones,
que (estando acomodadas a sus propias inclinaciones)
hizo que la conquista sobre ustedes no fuese difícil.

Sí, se rehusaron a tomar el santo yugo de Cristo y llevar su cruz diaria.
Fueron indiferentes con sus propios afectos y no
mantuvieron ningún control sobre sus acciones,
olvidándose de llevar una cuenta en sus propias conciencias por medio de Cristo, su luz,
el gran Obispo de sus almas y Juez de sus obras.
De esta manera, su temor santo decayó y su amor se enfrío;
y por lo tanto la vanidad se multiplicó y el deber se convirtió en una carga.

Entonces vino la formalidad, en vez del poder de la piedad;
y la superstición, en lugar de la obra de Cristo.
Y a pesar de que la intención de Cristo fue sacar las mentes de sus discípulos
fuera de un templo externo (con sus ritos y servicios carnales) a la adoración de
Dios interna y espiritual (adecuada a la naturaleza de la divinidad),
aun así, una adoración mundana, humana y pretenciosa ha sido introducida de nuevo,
y se han restablecido el sacerdocio, el templo y el altar del mundo.
Ahora "`los hijos de Dios una vez más vieron que las hijas de los hombres eran hermosas,`"^
footnote:[Genesis 6:2]
es decir, el ojo puro,
que el arrepentimiento había abierto y el cual no veía ninguna hermosura fuera de Cristo,
se oscureció; y el ojo del deseo fue abierto de nuevo por el dios del mundo.
Y entonces esos placeres mundanos--que hacen que
aquellos que los aman se olviden de Dios,
a pesar de que una vez estos fueron despreciados por amor a Cristo--
comenzaron a recuperar su antigua belleza e interés en sus afectos;
y amándolos, se volvieron la búsqueda, la preocupación y el placer de sus vidas.

Es cierto,
todavía quedaron las formas externas de adoración y una
reverencia sólo de nombre y de palabras a Dios y a Cristo.
Pero esto es todo lo que sobrevivió; porque la ofensa de la santa cruz cesó,
el poder de la piedad se negó,
la abnegación se perdió y a pesar de que se hicieron
fructíferos en la invención de ornamentos ceremoniosos,
permanecieron estériles en cuanto a los benditos frutos del Espíritu.
Y ¡Ay! Miles de cáscaras no pueden hacer un solo grano,
ni muchos cadáveres un hombre vivo.

Así, la religión cayó de la experiencia a la tradición
y la adoración cayó del poder a la forma,
de la vida a la letra.
En lugar de elevar peticiones vivas y poderosas a Dios,
animadas por un profundo sentido de necesidad y por la asistencia del
Espíritu Santo (por medio de quien los antiguos oraban,
luchaban y prevalecían con Dios), he aquí, una repetición prescrita,
una formalidad pesada e insípida, que consiste en inclinarse y arrodillarse,
en vestidos y muebles especiales, en perfumes,
voces y música--una presentación más apropiada
para la recepción de algún príncipe terrenal,
que para la adoración celestial del único Dios verdadero e inmortal,
quien es un espíritu eterno e invisible.

A medida que su corazón se hacía más carnal, su religión también lo hacía;
y como ya no les gustaba como era, la amoldaron a su gusto.
Sin ninguna duda olvidaron las palabras del santo profeta,
"`El sacrificio de los impíos es abominación a Jehová,`"^
footnote:[Proverbios 15:8]
y el dicho de Santiago, "`Pedís, y no recibís,`" y ¿por qué? "`porque pedís mal,`"^
footnote:[Santiago 4:3]
es decir, con un corazón que no es recto, sino falso y no crucificado.
No pides en la fe que purifica el alma, y así nunca pueden recibir lo que piden.
Por tanto, ahora se puede decir en verdad,
que la condición de muchos se empeora por su religión,
porque son tentados a pensar que son mejores por ella, a pesar de que no lo son.

Con esta visión que se les da de su caída del cristianismo primitivo,
y de la verdadera causa de ello--a saber,
un abandono de la cruz diaria de Cristo--estoy seguro de que
el camino de su restauración puede verse fácilmente.
Por la puerta por la que salieron, deben entrar.
Tal como todo se perdió al rechazar y dejar caer la cruz diaria,
tomarla y soportarla será su medio de recuperación. Esta es la
manera por la que los pecadores y los apóstatas se convierten
en los discípulos de Jesús. "`Si alguno,`" dice Cristo,
"`quiere venir en pos de mí y ser mi discípulo, niéguese a sí mismo, y tome su cruz, y sígame.`"
Nada inferior a esto servirá. Así como esto es suficiente, también es indispensable.
No hay corona sino por medio de la cruz; no hay vida eterna sino a través de la muerte.
Y lo justo es que esos deseos malvados y bárbaros que crucificaron de nuevo a Cristo,
ahora sean, por Su santa cruz, crucificados en ustedes.
La sangre requiere sangre; Su cruz es la muerte del pecado que causó Su muerte;
y Él es la muerte de la muerte, según ese pasaje, "`¡Oh muerte, yo seré tu muerte!`"^
footnote:[Oseas 13:14 Reina Valera de Gomez]
