== Capítulo III. La Cruz Diaria

Por lo tanto, ¡oh Cristiandad! la cruz diaria,
siendo tanto en aquel tiempo como ahora el único camino hacia la gloria,
será de gran ventaja para su alma considerar seriamente:

[.numbered]
_Primero:_ ¿Qué es la cruz de Cristo?

[.numbered]
_Segundo:_ ¿Dónde se debe tomar la cruz de Cristo?

[.numbered]
_Tercero:_ ¿Cómo y de qué manera se debe cargar?

[.numbered]
_Cuarto:_ ¿Cuál es la gran obra y asunto de la cruz?

En cuanto a lo primero--¿Qué es la cruz de Cristo?
La cruz de Cristo es una metáfora tomada del madero externo, o cruz de madera,
sobre la cual Cristo se sometió a la voluntad de Dios,
permitiendo que sufriera la muerte en manos de hombres malvados.
La cruz mística o diaria es esa gracia o poder divino
que crucifica las voluntades carnales de los hombres,
contradice sus afectos corruptos y se opone constantemente a
los apetitos excesivos y carnales de sus mentes.
Este poder se puede llamar debidamente el instrumento de la santa muerte de
los hombres al mundo y para ser hechos conforme a la voluntad de Dios.
Nada más puede mortificar el pecado o hacer fácil que nos sometamos a la voluntad
divina en cosas que de otra manera serían muy contrarias a la nuestra.

"`La predicación de la cruz`" en los tiempos primitivos fue
llamada acertadamente por Pablo (ese famoso y diestro apóstol
en las cosas espirituales) "`el poder de Dios;`"^
footnote:[1 Corintios 1:18 RV1602P]
aunque para los que se pierden, fue en aquel tiempo, como también ahora, una locura.
Es decir, para aquellos que estaban verdaderamente cansados y cargados,
y en necesidad de un libertador, a quienes el pecado les era pesado y detestable,
la predicación de la cruz
(por la cual el pecado debía ser crucificado) era el poder de Dios,
o la predicación del poder divino mediante el cual
fueron hechos discípulos de Cristo e hijos de Dios.
Y este poder obraba tan fuertemente en ellos,
que ningún burlador orgulloso o disoluto podía sacarlos del amor a ello.
Pero para aquellos que andaban en el camino espacioso,
en la latitud completa de sus propios deseos,
y que dedicaban su tiempo y atención a los placeres de sus apetitos corruptos,
para quienes todos los yugos y frenos eran y son intolerables,
para estos la predicación de la cruz era y es una locura.

¿Dónde aparece esta cruz y dónde debe tomarse?
Yo respondo, adentro, es decir, en el corazón y en el alma--
porque donde está el pecado, allí debe estar la cruz.
Toda maldad sale de adentro.
Cristo enseñó que "`de dentro, del corazón de los hombres, salen los malos pensamientos,
los adulterios, las fornicaciones, los homicidios, los hurtos, las avaricias,
las maldades, el engaño, la lascivia, la envidia, la maledicencia, la soberbia,
la insensatez.
Todas estas maldades de dentro salen, y contaminan al hombre.`"^
footnote:[Marcos 7:21-23]
El corazón del hombre es el asiento del pecado, y donde está contaminado,
allí debe ser santificado; donde vive el pecado, allí debe morir, debe ser crucificado.
La costumbre de hacer el mal ha hecho natural que los hombres hagan el mal;
y así como el alma gobierna el cuerpo,
esta naturaleza corrupta controla al hombre entero.
Pero, aun así, todo sale de adentro.

La experiencia enseña a cada hijo e hija de Adán la verdad de esto.
Las tentaciones del enemigo siempre se dirigen al corazón o la mente, que están adentro:
Si ellos no caen, el alma no peca, pero si son abrazadas,
entonces la concupiscencia (o deseo excesivo) es concebida inmediatamente,
y como dice el apóstol: "`Entonces la concupiscencia, después que ha concebido,
da a luz el pecado; y el pecado, siendo consumado (es decir, llevado a cabo),
da a luz la muerte.`"^
footnote:[Santiago 1:15]
Aquí está tanto la causa como el efecto, la genealogía del pecado,
su nacimiento y su fin.

En todo esto, el corazón del hombre malo es la fábrica del diablo, su taller,
el lugar de su residencia, donde ejerce su poder y su arte.
Por lo tanto,
la redención del alma es debidamente llamada "`deshacer las obras del diablo`"^
footnote:[1 Juan 3:8]
y "`traer la justicia perdurable.`"^
footnote:[Daniel 9:24]
Cuando los judíos querían difamar el milagro de Cristo de
sacar demonios al llamarlo blasfemamente el poder de Beelzebú,
Cristo dice, "`¿cómo puede alguno entrar en la casa del hombre fuerte,
y saquear sus bienes, si primero no le ata?
Y entonces podrá saquear su casa.`"^
footnote:[Mateos 12:29]
Esto nos demuestra tanto la contrariedad entre Beelzebú
como el poder por el que Cristo lo desposeía,
y nos enseña que las almas de los impíos son la "`casa`" del diablo,
y que sus bienes, sus obras malvadas,
nunca podrán ser destruidas hasta que sea atado aquel que las hizo y guarda la casa.
Todo esto hace que sea fácil saber dónde debe tomarse la cruz
(que es lo único por lo que el hombre fuerte puede ser atado,
sus bienes sacados y sus tentaciones resistidas) esto es, internamente,
en el corazón del hombre.

En el siguiente lugar, ¿cómo y de qué manera se debe llevar diariamente la cruz?
El camino, al igual que la cruz, es espiritual.
_Es la sumisión interna del alma a la voluntad de Dios tal como se
manifiesta por la luz de Cristo en las conciencias de los hombres,_
aunque sea contraria a sus propias inclinaciones.
Por ejemplo, cuando se presenta el mal,
aquello que lo revela también instruye a no ceder a él, y si un hombre recibe su consejo,
le da poder para escapar de ello.
Pero aquellos que miran y contemplan la tentación,
al final se unen con ella y son vencidos por ella;
la consecuencia de lo cual es culpa y juicio.

Por lo tanto,
así como la cruz de Cristo es ese Espíritu y poder en los hombres
(aunque no de los hombres, sino de Dios)
que contradice y reprende los deseos y afectos carnales,
así la manera de tomar la cruz es una rendición entera
del alma a los descubrimientos y requerimientos de ella,
sin consultar el placer mundano,
o la comodidad o interés carnal (porque estos pueden ser cautivados en un instante).
De este modo el alma debe vigilar continuamente contra cada aparición del mal, y,
por la obediencia de la fe (en verdadero amor a Dios y confianza en Él),
ofrecer alegremente a la muerte de la cruz esa naturaleza maligna en sí misma que,
no soportando el calor del asedio, y siendo impaciente en la hora de la tentación,
traicionaría fácilmente (por su cercanía con el tentador), su propia alma en sus manos.

¡Esto puede demostrar a la experiencia de todos,
lo difícil que es ser un verdadero discípulo de Jesús!
El camino de verdad es angosto y la puerta muy estrecha,
donde ni una palabra, no,
ni un solo pensamiento debe eludir la vigilancia ni escapar del juicio.
Tal diligencia, tal precaución, tal paciencia, tal constancia, tal temor y temblor santo,
dan una interpretación fácil a ese duro dicho,
"`La carne y la sangre no pueden heredar el reino de Dios.`"
Porque aquellos que están cautivados por los deseos y
afectos carnales no pueden cargar la cruz;
y los que no la pueden llevar, nunca tendrán la corona.
Para reinar, es necesario sufrir primero.
