== Capítulo III. La Cruz Diaria

Por lo tanto, ¡oh Cristiandad! siendo la cruz diaria, tanto en aquel entonces como ahora,
el único camino hacia la gloria, será de gran ventaja para tu alma considerar seriamente:

[.numbered-group]
====

[.numbered]
_Primero:_ Qué es la cruz de Cristo.

[.numbered]
_Segundo:_ Dónde se debe tomar la cruz de Cristo.

[.numbered]
_Tercero:_ Cómo y de qué manera se debe cargar.

[.numbered]
_Cuarto:_ Cuál es la gran obra y propósito de la cruz.

====

En cuanto a lo primero: ¿Qué es la cruz de Cristo?
La cruz de Cristo es una metáfora tomada del madero externo, o cruz de madera,
sobre la cual Cristo se sometió a la voluntad de Dios,
permitiendo que sufriera la muerte a manos de hombres malvados.
La cruz mística o diaria es esa gracia o poder divino
que crucifica las voluntades carnales de los hombres,
contradice sus afectos corruptos y se opone constantemente
a los apetitos desordenados y carnales de sus mentes.
Este poder puede ser justamente llamado el instrumento del santo morir
del hombre al mundo y de su conformidad a la voluntad de Dios.
Nada más puede hacer morir el pecado o facilitar
nuestra sumisión a la voluntad divina en cosas que,
de otra manera, serían muy contrarias a la nuestra.

"`La predicación de la cruz`" en los tiempos primitivos fue llamada acertadamente por
Pablo (ese famoso y diestro apóstol en las cosas espirituales) "`el poder de Dios;`"^
footnote:[1 Corintios 1:18 RV1602P]
aunque para los que se pierden, era entonces, como ahora, locura.
Es decir,
para aquellos que estaban verdaderamente cansados y cargados y en necesidad de un libertador,
para quienes el pecado era una carga y detestable,
la predicación de la cruz (por la cual el pecado
debía ser crucificado) era el poder de Dios,
o la predicación del poder divino mediante el cual
eran hechos discípulos de Cristo e hijos de Dios.
Y este poder obraba tan fuertemente en ellos,
que ningún burlador orgulloso o disoluto podía sacarlos del amor
por él. Pero para aquellos que andaban en el camino ancho,
en completa latitud de sus propios deseos,
y que dedicaban su tiempo y atención a los placeres de sus apetitos corruptos,
para quienes todos los yugos y frenos eran y son intolerables,
para estos la predicación de la cruz era y es locura.

Segundo: ¿Dónde aparece esta cruz y dónde debe tomarse?
Yo respondo, en el interior, es decir, en el corazón y en el alma;
porque donde está el pecado, allí debe estar la cruz.
Toda maldad proviene del interior.
Cristo enseñó: "`Porque de dentro, del corazón de los hombres,
salen los malos pensamientos, los adulterios, las fornicaciones, los homicidios,
los hurtos, las avaricias, las maldades, el engaño, la lascivia, la envidia,
la maledicencia, la soberbia, la insensatez.
Todas estas maldades de dentro salen, y contaminan al hombre.`"^
footnote:[Marcos 7:21-23]
El corazón del hombre es el asiento del pecado, y donde está contaminado,
allí debe ser santificado; donde vive el pecado, allí debe morir, debe ser crucificado.
La costumbre de hacer el mal ha hecho natural que los hombres hagan el mal;
y así como el alma gobierna el cuerpo,
esta naturaleza corrupta controla al hombre entero.
Pero, aun así, todo proviene del interior.

La experiencia enseña a cada hijo e hija de Adán la verdad de esto.
Las tentaciones del enemigo siempre se dirigen al corazón o a la mente,
que están en el interior: Si no son acogidas, el alma no peca, pero si son abrazadas,
entonces la concupiscencia (o deseo desordenado) es concebida inmediatamente,
y como dice el apóstol: "`Entonces la concupiscencia, después que ha concebido,
da a luz el pecado; y el pecado, siendo consumado (es decir, llevado a cabo),
da a luz la muerte.`"^
footnote:[Santiago 1:15]
Aquí está tanto la causa como el efecto, la genealogía del pecado,
su nacimiento y su fin.

En todo esto, el corazón del hombre malo es la casa de moneda del diablo,
donde acuña sus obras, el lugar de su residencia, donde ejerce su poder y su arte.
Por lo tanto,
la redención del alma es debidamente llamada "`deshacer las obras del diablo`"^
footnote:[1 Juan 3:8]
y "`traer la justicia perdurable.`"^
footnote:[Daniel 9:24]
Cuando los judíos intentaron difamar el milagro de Cristo de expulsar
demonios imputándolo blasfemamente al poder de Beelzebú,
Cristo dice: "`¿Cómo puede alguno entrar en la casa del hombre fuerte,
y saquear sus bienes, si primero no le ata?
Y entonces podrá saquear su casa.`"^
footnote:[Mateos 12:29]
Esto nos demuestra tanto la contrariedad entre Beelzebú
y el poder por el que Cristo lo desposeía,
como nos enseña que las almas de los impíos son la "`casa`" del diablo, y que sus bienes,
sus malas obras,
nunca podrán ser destruidas hasta que sea atado aquel que las hizo y guarda la casa.
Todo esto hace fácil saber dónde se debe tomar la cruz,
lo único por lo que el hombre fuerte puede ser atado,
sus bienes saqueados y sus tentaciones resistidas; esto es, en el interior,
en el corazón del hombre.

Tercero: ¿Cómo y de qué manera se debe llevar la cruz diariamente?
El camino, al igual que la cruz, es espiritual.
_Es la sumisión interna del alma a la voluntad de Dios tal como
se manifiesta por la luz de Cristo en las conciencias de los hombres,_
aunque sea contraria a sus propias inclinaciones.
Por ejemplo, cuando se presenta el mal,
aquello que lo revela también instruye a no ceder a él, y si un hombre recibe su consejo,
le da poder para escapar de él. Pero los que miran y contemplan la tentación,
al final se unen a ella y son vencidos por ella; cuya consecuencia es culpa y juicio.

Por lo tanto,
así como la cruz de Cristo es ese Espíritu y poder
en los hombres (aunque no _de_ los hombres, sino de Dios)
que se opone y reprende los deseos y afectos carnales, así también,
_la manera de tomar la cruz es una completa rendición del
alma a las manifestaciones y requerimientos de ella,
sin consultar el placer mundano, o la comodidad o interés carnal_
(porque estos son capturados en un instante).
De este modo debe velar continuamente el alma contra cada aparición del mal y,
mediante la obediencia de la fe (en verdadero amor a Dios y confianza en Él),
ofrecer alegremente a la muerte de la cruz esa naturaleza maligna en ella que,
al no soportar el calor del asedio y al ser impaciente en la hora de la tentación,
por su cercanía con el tentador, traicionaría fácilmente su propia alma en sus manos.

¡Esto puede demostrar, por la experiencia de todos,
cuán difícil es ser un verdadero discípulo de Jesús! El camino es angosto en verdad,
y la puerta muy estrecha, donde ni una palabra, no,
ni siquiera un pensamiento debe eludir la vigilancia ni escapar del juicio.
Tal diligencia, tal cautela, tal paciencia, tal constancia, tal temor y temblor santo,
dan una interpretación fácil a ese duro dicho:
"`La carne y la sangre no pueden heredar el reino de Dios.`"
Porque aquellos que están cautivados por los deseos
y afectos carnales no pueden llevar la cruz;
y los que no la pueden llevar, nunca tendrán la corona.
Para reinar, es necesario sufrir primero.
