== Capítulo IV. Negando el Yo Lícito

En cuarto lugar: ¿Cuál es la gran obra y asunto de la Cruz con respecto al hombre?
Es tan importante que esto se responda de manera verdadera, clara y completa,
que pareciera que todo lo anterior solo sirve como su prefacio.
Equivocarse en esto no es menos que el desvío del alma
de su camino a la bendición. Por lo tanto,
procuraré contestar la pregunta,
con la ayuda de Dios y del mejor entendimiento que Él me ha
dado en la experiencia de varios años de discipulado.

La gran obra y asunto de la cruz de Cristo, en el hombre,
es la abnegación--una palabra poco comprendida,
pero de mucha profundidad
en sí misma y de gran contradicción al mundo.
El Hijo de Dios se nos ha adelantado, y,
mediante la copa amarga que bebió y el bautismo que sufrió,
nos ha dejado un ejemplo para que sigamos sus pasos.
Esto lo llevó a hacerles esa pregunta difícil a la esposa de Zebedeo y a sus dos hijos,
cuando ella le pidió que en Su reino uno se sentará a Su derecha y otro a Su izquierda:
"`¿Podéis beber del vaso que Yo he de beber,
y ser bautizados con el bautismo con qué Yo soy bautizado?`"
Al parecer la fe de ellos era fuerte; respondieron, "`Podemos.`"
A lo cual Él respondió: "`A la verdad, de mi vaso beberéis,
y con el bautismo con que yo soy bautizado, seréis bautizados;`"^
footnote:[Mateo 20:20-23]
pero su recompensa la dejó a Su Padre.

¿Cuál fue la copa que bebió y el bautismo que sufrió? Respondo;
fueron la negación y la ofrenda de Sí mismo mediante el
Espíritu eterno a la voluntad de Dios,
padeciendo las tribulaciones de Su vida y las agonías de Su muerte sobre la cruz,
para la salvación del hombre.

Ahora ¿Cuál es nuestra copa y cruz que debemos beber y sufrir?
La negación y la ofrenda de nosotros mismos, mediante el mismo Espíritu,
para hacer o sufrir la voluntad de Dios para Su servicio y gloria.
Esta es la verdadera vida y obediencia de la cruz de Jesús--todavía estrecha,
pero antes de Cristo era un camino cerrado.
Porque Cristo vino en la grandeza de Su amor y fuerza cuando no había nadie que ayudara,
ni abriera los sellos,
ni diera conocimiento o dirigiera el curso de la recuperación de los pobres hombres.
Y aunque estaba vestido con las debilidades de un hombre mortal,
siendo fortificado internamente por la omnipotencia del Dios inmortal,
viajó a través de todos los apuros y dificultades de la humanidad; y,
como el primero de todos los demás, anduvo el camino jamás recorrido hacia la bendición.

¡Oh vamos, sigámoslo!
Al más incansable y victorioso Capitán de nuestra salvación,
a quien todos los Alejandro Magnos y poderosos Cesares no se pueden comparar.
Porque todos estos fueron grandes príncipes de su clase, y conquistadores también,
pero con principios muy diferentes.
Cristo se despojó a Sí mismo para salvar a la humanidad;
pero estos arruinaron pueblos enteros para aumentar su nombre.
Vencieron a otros, no a ellos mismos; pero Cristo conquistó el yo,
el mismísimo poder que los venció a ellos.
Afirmaron su imperio con rapiña y sangre;
pero Él con sufrimiento y persuasión. Prevalecieron a través de la fuerza,
pero Cristo nunca hizo uso de la imposición. La miseria
y la esclavitud siguieron todas sus victorias,
pero Cristo trajo libertad y felicidad a los que Él venció. En todo lo que hicieron,
buscaron complacerse a sí mismos; en todo lo que Él hizo,
tuvo como objetivo agradar a Su Padre, quien es Dios de dioses,
Rey de reyes y Señor de señores.
Por lo tanto, es debidamente llamado príncipe y el conquistador más excelente.
Y es este el patrón de la negación del yo más perfecto que debemos seguir,
si alguna vez llegamos a la gloria.

=== El Yo Lícito

Para hacer esto, consideremos la abnegación en su verdadera distinción y alcance.
Hay un yo lícito y uno ilícito, y ambos deben ser negados por amor a Aquel que,
en sumisión a la voluntad de Dios,
no estimó nada precioso para Sí mismo para poder salvarnos.
Y a pesar de que casi ninguna parte del mundo ha progresado hasta el
punto de necesitar una lección sobre la negación del yo lícito (dado
que cada día sacrifican con avidez a los placeres del yo ilícito),
al menos la mencionaré,
ya que posiblemente esto dé con algunos que están tan avanzados en
esta guerra espiritual como para recibir beneficio de la misma.

El yo lícito que debemos negar, es esa comodidad, tranquilidad,
disfrute y abundancia que, en sí mismo, está tan lejos de ser malo,
que pudiera considerarse la recompensa y la bendición de Dios para nosotros:
cosas como esposos, esposas, hijos, casas, tierra, reputación, libertad y la vida misma.
Estas cosas son favores de Dios,
que podemos disfrutar con placer lícito y aumentar
justamente como nuestros intereses honestos.
Pero cuando Dios las requiere, en cualquier momento,
o si le place probar nuestros afectos separándonos de ellas, yo digo,
cuando estas cosas entran en competencia con Él, no deben ser preferidas sino negadas.

Cristo mismo descendió de la gloria de Su Padre y voluntariamente se
despojó a Sí Mismo en medio de los hombres para llevarnos a Dios.
No estimando el ser igual a Dios como cosa a que aferrarse,
se humilló a Sí Mismo hasta la pobre forma de siervo; sí,
hasta la muerte vergonzosa de la Cruz,
y así nos dio un ejemplo de humildad pura y sumisión
absoluta a la voluntad de nuestro Padre celestial.

Él nos enseña esta doctrina con estas palabras:
"`El que ama a padre o madre, hijo o hija más que a mí, no es digno de Mí.`"
Nuevamente, "`Cualquiera de vosotros que no renuncia a todo lo que posee,
no puede ser Mi discípulo.`"
Él claramente le dijo al joven rico que, si quería la vida eterna,
debía venderlo todo y seguirlo: una doctrina que le fue triste,
como también lo es para aquellos como él,
quienes a pesar de todas sus elevadas pretensiones de religión,
aman sus posesiones más que a Cristo.
Aun así,
esta doctrina de la negación del yo permanece como la condición para la felicidad eterna:
"`Si alguno quiere venir en pos de mí, niéguese a sí mismo, y tome su cruz, y sígame.`"

Esto hizo que esos pescadores honestos dejaran sus
comercios legales y lo siguieran cuando los llamó;
y causó que otros que esperaban la consolación de Israel ofrecieran sus propiedades,
reputaciones, libertades y también sus vidas al disgusto y la furia
de sus familiares y del gobierno bajo el cual vivían,
por la ventaja espiritual que recaía sobre ellos por
medio de su fiel adherencia a Su santa doctrina.

Es cierto, muchos buscaron excusarse para no seguirlo,
como se ve en la parábola de la fiesta de bodas.
Algunos habían comprado tierras,
algunos se habían casado con esposas y otros habían
comprado yuntas de bueyes y dijeron que no podían ir.
¡Ay! Un amor inmoderado por el mundo los estorbó.
En lugar de actuar como sus siervos,
estos disfrutes lícitos se convirtieron en sus ídolos;
los adoraron más que a Dios y no quisieron renunciar a ellos para venir a Dios.
Esto fue escrito para su reproche,
y aquí podemos ver el poder del yo sobre el hombre mundano,
y el peligro que le viene por abusar de las cosas lícitas.
¡Qué! ¿Su esposa es más preciada que su Salvador?
¿Prefieren su tierra y sus bueyes antes que la salvación de su alma?
¡Oh! Tengan cuidado de que sus comodidades no resulten ser trampas primero,
y después maldiciones.
Sobrevalorarlas es provocar que Aquel que las dio las tome nuevamente.
Vengan, más bien, a seguir a Aquel que le da vida eterna al alma.

¡Ay de aquellos que tienen sus corazones en sus posesiones terrenales!
Porque cuando se van,
su cielo se queda aquí. Apegarse a sus tesoros mundanos
es el pecado de la mayor parte del mundo,
y cuán lamentable es contemplar sus deseos manchados y
enredados con sus conveniencias y comodidades en ello.
El verdadero hombre abnegado es un peregrino;
pero el hombre egoísta es un habitante del mundo.
El primero utiliza el mundo como los hombres usan los barcos,
para transportarse a sí mismo o sus provisiones en un viaje hacia el hogar;
el otro no busca nada más (no importa lo que diga) que
establecerse en plenitud y comodidad aquí,
y le gusta tanto que, si pudiera, nunca lo cambiaría. No,
no se molestará en pensar en el otro mundo hasta
que esté seguro de que ya no vivirá en este.
¡Entonces, por desgracia, será demasiado tarde!
No al seno de Abraham, sino al lado del rico debe ir;
la historia es tan cierta como triste.

Por otro lado, no es por nada que los discípulos de Jesús se niegan a sí mismos; y,
de hecho, Cristo Mismo tenía puesto Su ojo en el gozo eterno.
"`Por el gozo puesto delante de Él,`" dice el autor de hebreos, "`sufrió la cruz;`"^
footnote:[Hebreos 12:2]
es decir, se negó a sí mismo y soportó los vituperios y la muerte del impío,
menospreciando el oprobio, la deshonra y el escarnio del mundo.
Esto hizo que Él no tuviera miedo ni retrocediera y
ahora está sentado a la diestra del trono de Dios.
Cuando Pedro le preguntó qué tendrían los que habían dejado todo para seguirlo,
Él (para el estímulo y el gran consuelo de Sus discípulos) respondió,
"`De cierto os digo que en la regeneración,
cuando el Hijo del Hombre se siente en el trono de su gloria,
vosotros que me habéis seguido también os sentaréis sobre doce tronos,
para juzgar a las doce tribus de Israel,`"^
footnote:[Mateo 19:28]
el cual en ese entonces estaba en la apostasía de la vida y del poder de la piedad.
Esta fue la porción de Sus discípulos,
los compañeros más inmediatos de Sus tribulaciones y los primeros mensajeros de Su Reino.
Pero lo que sigue es para todos: "`Y cualquiera que haya dejado casas, o hermanos,
o hermanas, o padre, o madre, o mujer, o hijos, o tierras, por mi nombre,
recibirá cien veces más, y heredará la vida eterna.`"^
footnote:[Mateo 19:29]
Es este grande galardón, esta corona eterna de justicia, que, en todas las eras,
ha levantado en las almas de los justos una negación santa, sí, un desprecio del mundo.

=== El Ejemplo de los Antiguos

Esta no es una doctrina nueva; es tan antigua como Abraham,
porque en varios de los acontecimientos más extraordinarios,
era evidente que su vida se componía de abnegación. Primero,
al abandonar su propia tierra,
en la que bien podemos suponer que estaba establecido en medio de la abundancia o,
al menos, de la suficiencia.
¿Y porque la dejó? Porque Dios lo llamó. Esto debería ser un motivo suficiente;
pero tal es la degeneración del mundo que, en realidad, no lo es.
En efecto, el mismo hecho ahora, con el mismo incentivo en cualquier hombre,
aunque alabado en Abraham, sería escarnecido y ridiculizado.
¡Ay, cuán propensas son las personas a elogiar lo que no entienden!
Y ¡cómo admiran en sus ancestros los mismos hechos que
desprecian en los fieles discípulos de su propio tiempo!

Pero Abraham obedeció y el resultado fue que Dios le dio una tierra buena y ancha.
Esta fue la primera recompensa de su obediencia; la siguiente fue un hijo en su vejez,
pasado el tiempo de que su esposa pudiera dar a luz.
Sin embargo, Dios pronto le pidió a su amado, su hijo único, la felicidad de su vejez,
el hijo de un milagro,
aquel de quien dependía el cumplimiento de la promesa hecha a Abraham.
Dios le pidió a este hijo,
trayendo una prueba que uno pensaría que podría fácilmente
derrocar su fe y debilitar su integridad,
o al menos provocar esta disputa en él: "`Esta orden es irracional y cruel;
debe ser del tentador, no puede ser de Dios.
Porque,
¿Dios me daría un hijo para hacer un sacrificio de él?
¿Debería un padre ser el verdugo de su único hijo?
Que me requiera ofrecer al hijo de Su propia promesa,
por medio del cual se ejecutará Su pacto, es absurdo.`"
Así Abraham naturalmente pudo haber argumentado,
con el fin de resistir la voz de Dios y complacer sus grandes afectos por su amado Isaac.
Pero el buen viejo Abraham, que conocía la voz que le había prometido un hijo,
no la había olvidado cuando volvió a pedírselo.
Él no discutió, aunque parecía extraño,
y aunque sin duda sintió una medida de sorpresa y horror como hombre.
Había aprendido a creer que Dios, quien le dio un hijo mediante un milagro,
podría hacer otro para preservarlo o restaurarlo.
Sus afectos no podían superar su deber, y mucho menos vencer su fe.

Abraham se inclinó a la voz del Todopoderoso, edificó un altar,
ató a su único hijo sobre este,
encendió el fuego y extendió su mano para tomar el cuchillo;
pero el ángel detuvo el golpe.
"`Detente, Abraham, tu integridad ha sido probada.`"
¿Y qué siguió? Un carnero sirvió para el sacrificio e Isaac fue devuelto a él nuevamente.
Esto muestra qué tan poco se necesita cuando todo ha sido entregado,
y cómo un pequeño sacrificio contenta al Todopoderoso, donde el corazón es aprobado.
No es el sacrificio lo que aboga por el corazón,
sino el corazón que le da aceptación al sacrificio.

Dios a menudo toca nuestros mayores consuelos y requiere lo
que más amamos y estamos menos dispuestos a dejar.
Él no siempre los quita totalmente, sino que prueba la integridad del alma,
nos advierte de los excesos y,
para que podamos recordarlo (el Autor de todas las bendiciones que poseemos),
nos enseña a vivir desapegados del mundo.
Hablo de mi experiencia: La manera de mantener nuestros disfrutes es renunciando a ellos.
Y aunque esto sea difícil, es dulce cuando estas cosas nos son devueltas,
como Isaac lo fue para su padre, con más amor y bendición que antes.
¡Oh, mundo necio! ¡Oh, cristianos mundanos! ¡No solo extraños,
sino enemigos de esta excelente fe!
Y mientras estén así, nunca experimentarán la recompensa de ella.

La abnegación de Job también fue muy impresionante.
Porque cuando los mensajeros de sus aflicciones se le
acercaron con una triste historia tras otra,
hasta que quedó casi tan desnudo como cuando nació,
lo primero que hizo fue postrarse en tierra y adorar ese poder, y besar esa mano,
que lo despojó. Estaba tan lejos de murmurar,
que concluyó sus pérdidas de bienes y de hijos con estas palabras:
"`Desnudo salí del vientre de mi madre, y desnudo volveré allá. Jehová dio,
y Jehová quitó; sea el nombre de Jehová bendito.`"^
footnote:[Job 1:21]
¡Oh, la profunda fe, paciencia y contentamiento de este excelente hombre!
Uno hubiera pensado que estas repetidas noticias de ruina habrían
sido suficientes para derribar su confianza en Dios,
pero no fue así; su fe lo mantuvo.
Y él nos dice por qué--"`Yo sé (dice él) que mi Redentor vive.`"^
footnote:[Job 19:25]
Y es manifiesto que Su Redentor en verdad vivía, porque lo había redimido del mundo.
Su corazón no estaba en sus comodidades mundanas;
su esperanza vivía por encima de los disfrutes
del tiempo y de las angustias de la mortalidad.
No fue tentado por lo primero, ni conmovido por lo último;
sino que estaba firmemente convencido de,
"`que después de que mi piel haya sido arrancada de mi carne, veré a Dios.`"^
footnote:[Job 19:26 Traducción Literal]
Así, el corazón de Job se sometió a la voluntad de Dios y se consoló en ella.

Moisés es el siguiente ejemplo de abnegación notable en la historia sagrada,
antes de los tiempos de la aparición de Cristo en la carne.
Cuando era un bebe, había sido salvado mediante una Providencia extraordinaria,
y al parecer por lo que siguió, para un servicio extraordinario.
La hija de Faraón,
cuya compasión fue el medio de su preservación
(cuando el rey había decretado la matanza de los varones hebreos),
lo tomó por su hijo y le dio la educación del palacio de su padre.
Su propia presencia elegante y sus habilidades extraordinarias,
junto con el amor de ella por él y el deseo de que su padre lo ascendiera,
debieron haberlo hecho, si no capaz de heredar el trono,
al menos de ser un ministro principal bajo aquel príncipe rico y poderoso.
Porque Egipto fue en aquel entonces lo que fueron después Atenas y Roma,
el centro más famoso de aprendizaje, artes y gloria.

Pero Moisés fue destinado para otra obra y guiado por una mejor estrella,
un principio superior.
Tan pronto como llegó a una edad de discernimiento,
la impiedad de Egipto y las opresiones de sus hermanos allí,
se hicieron una carga demasiado pesada para él. Y aunque un hombre
tan sabio y bueno no podría haber carecido de sentimientos generosos
y agradecidos por la bondad de la hija del rey para con él,
aun así, también había visto "`al Dios Invisible,`"^
footnote:[Hebreos 11:27 PDT]
y no se atrevía a vivir en la comodidad y en la abundancia de la casa de Faraón
mientras que a sus pobres hermanos se les exigía hacer ladrillo sin paja.
Y así, con el temor del Todopoderoso apoderándose de su corazón,
rehusó noblemente llamarse hijo de la hija de Faraón,
escogiendo antes ser maltratado con los despreciados y oprimidos israelitas,
y ser el compañero de sus tentaciones y peligros,
"`que gozar de los deleites temporales del pecado;`"^
footnote:[Hebreos 11:25]
teniendo por mayores riquezas los vituperios de Cristo
(que sufrió al hacer esa elección en contra del mundo)
que todos los tesoros de ese reino.

Tampoco era tan tonto como pensaban; puesto que tenía la razón de su lado.
Se dice que Él, "`tenía puesta la mirada en el galardón;`"^
footnote:[Hebreos 11:26]
de manera que sólo rechazó un beneficio menor por uno mayor.
En esto, su sabiduría trascendió la de los egipcios;
porque ellos eligieron el mundo presente
(que es tan incierto como el clima)
y así perdieron ese mundo que no tiene fin.
Moisés consideró más profundamente,
sopesó los placeres de esta vida en la balanza de la eternidad
y descubrió que no tenían peso allí. Se gobernaba a sí mismo,
no por la posesión inmediata, sino por la naturaleza y la duración de la recompensa.
Su fe corrigió sus afectos y le enseñó a sacrificar los placeres del
yo por la esperanza que tenía de una recompensa futura más excelente.

Isaías no fue un caso insignificante de la misma bendita abnegación; quien,
de un cortesano se convirtió en profeta, y dejó los intereses mundanos de uno por la fe,
paciencia y sufrimientos del otro.
Su elección no solo le hizo perder el favor de los hombres,
sino que la iniquidad de ellos (enfurecidos por su integridad ante Dios en sus
fervientes y audaces reprensiones hacia ellos) lo hicieron un mártir al final;
porque lo aserraron bárbaramente en el reinado de Manases.
Así murió ese hombre excelente, comúnmente llamado el Profeta Evangélico.

Agregaré un ejemplo más, la fidelidad de Daniel.
Este era un joven santo y sabio, quien,
cuando sus ventajas externas entraban en competencia con su deber ante Dios Todopoderoso,
renunció a todas.
En lugar de estar preocupado por cómo protegerse a sí mismo,
como uno que no se preocupa por nada menos que eso,
era (ante el peligro más extremo para sí mismo),
sumamente cuidadoso de cómo preservar el honor
de Dios mediante la fidelidad a Su voluntad.
Y aunque esto al principio lo expuso a la ruina, sin embargo,
(como un gran estímulo para todos los que
conservan la conciencia limpia en un tiempo malo)
su fidelidad a su Creador finalmente lo hizo prosperar mucho en el mundo;
y el Dios de Daniel se hizo famoso y temible a través de su perseverancia,
incluso ante los ojos de los reyes paganos.

¿Y qué diré de todos los demás quienes,
no estimando ninguna cosa preciosa para poder hacer la voluntad de Dios,
abandonaron sus comodidades mundanas y expusieron su tranquilidad y
seguridad (tan a menudo como la visión celestial los llamaba) a la ira y a
la malicia de los príncipes degenerados y de la iglesia apóstata?
En especial Jeremías, Ezequiel y Miqueas, quienes después de haberse negado a sí mismos,
en obediencia a la voz divina, sellaron su testimonio con su sangre.

Así, negarse a sí mismo fue la práctica y la gloria de los ancestros,
que fueron predecesores de la venida de Cristo en la carne.
¿Y deberíamos esperar el cielo ahora sin esto,
cuando nuestro Salvador Mismo fue hecho el ejemplo más excelente de ello?
Y eso, no como algunos lo desearían, a saber, "`Él sufrió por nosotros,
para que no tengamos que sufrir;`" sino al contrario, Él sufrió por nosotros,
para que podamos negarnos a nosotros mismos y entonces
ser los verdaderos seguidores de Su bendito ejemplo.

=== Deja Todo por Él

Por lo tanto, quienquiera que seas, que deseas hacer la voluntad de Dios,
pero desfalleces debido a la oposición de las consideraciones mundanas,
recuerda que te digo, en el nombre de Cristo, que aquel que prefiere padre o madre,
hermana o hermano, esposa o hijo, casa o tierra, reputación, honor, oficio,
libertad o vida, antes que el testimonio de la luz de Jesús en su propia consciencia,
será rechazado por Él, en el juicio solemne y general del mundo,
cuando todos serán juzgados y recibirán de acuerdo a las obras hechas
(no a la profesión hecha) en esta vida.
La doctrina de Jesús es que, si tu mano derecha te es ocasión de caer,
debes cortarla; y si tu ojo derecho te es ocasión de caer, debes sacarlo;
es decir, si las comodidades más preciadas, más útiles y tiernas que disfrutas,
se interponen en el camino de tu alma,
interrumpiendo tu obediencia a la voz de Dios y tu
conformidad a Su voluntad santa revelada en tu alma,
estás llamado, bajo pena de condenación, a dejarlas.

El camino de Dios es un camino de fe,
que es tan oscuro para los sentidos naturales como
mortal para el "`yo.`"
Los hijos de obediencia, con el santo Pablo,
estiman todas las cosas basura y desecho para ganar a Cristo,
y para experimentar y andar en este camino angosto.
La especulación no servirá,
ni los conceptos refinados entrarán. Solo el obediente comerá del fruto de esta tierra.
"`Si alguno quisiere hacer su voluntad,`" dice el bendito Jesús,
"`conocerá de Mi doctrina;`"^
footnote:[Juan 7:17 RV1602P]
a estos Él les enseñará. No hay lugar en el corazón para la instrucción,
donde el "`yo`" lícito es señor y no servidor.
Porque el "`yo`" no puede recibirla;
y lo que debería recibirla es oprimido por el "`yo,`" con miedos y dudas:
"`¿Qué dirán mi padre o mi madre?
¿Cómo me tratará mi esposo?
O, ¿Qué harán los magistrados conmigo?
Porque, aunque siento una poderosa persuasión y una clara
convicción en mi alma sobre esto o aquello,
sin embargo, considerando cuán menospreciado es,
los enemigos que tiene y lo extraño que pareceré para algunos,
espero que Dios se compadezca de mi debilidad si me rindo.
No soy más que carne y sangre; quizás más adelante Él me capacité mejor;
y hay tiempo suficiente.`"
Así habla el hombre egoísta y cobarde.

Razonar siempre es lo peor, porque el alma pierde cuando consulta;
pero la manifestación de la luz trae poder con ella.
Dios nunca busca persuadir los razonamientos de las personas;
sino que las empodera en su sumisión. Él no
requiere nada sin dar la capacidad de realizarlo;
porque eso sería burlarse de los hombres, y no salvarlos.
Es suficiente que hagas lo que Dios muestra como tu deber,
con tal que te rindas a la luz o Espíritu por el cual te da ese conocimiento.
Aquellos que no reciben a Cristo en Sus convicciones en el alma,
son los que carecen de poder, y a estos siempre les faltará. Pero los que sí lo reciben,
también reciben poder (como los santos de antaño) para ser hechos hijos de Dios,
a través de la obediencia pura de la fe.

Por lo tanto, permítanme implorarles por el amor y la misericordia de Dios,
por la vida y la muerte de Cristo,
por el poder de Su Espíritu y la esperanza de la inmortalidad,
ustedes cuyos corazones están puestos en sus comodidades temporales,
siendo amadores de sí mismos más que de estas cosas celestiales
¡dejen que el tiempo pasado sea suficiente para tales cosas!
No piensen que es suficiente estar libre de ciertas
impiedades graves en las que se encuentran otros,
mientras que su amor desmesurado por las cosas lícitas
contamina su disfrute de ellas y saca su corazón del temor,
amor, obediencia y abnegación de un verdadero discípulo de Jesús.
Vuélvanse, pues, y escuchen la voz apacible en su conciencia;
ella les habla de sus pecados y de su miseria en ellos.
Les da un descubrimiento vivo de la vanidad del mundo y le abre a su alma una
perspectiva de la eternidad y de los consuelos de los justos que están en reposo.
Si se aferran a ella, los divorciará del pecado y del yo.
Pronto notarán que el poder de sus encantos excede el de la riqueza,
el honor y la belleza del mundo, y, finalmente,
les concederá esa tranquilidad que las tormentas
del tiempo nunca pueden naufragar o trastornar.
Aquí todos sus disfrutes son bendecidos.
Aunque sean pequeños, sin embargo, son grandes debido a esa presencia que los acompaña.

Incluso en este mundo, los justos tienen la mejor parte,
ya que usan el mundo sin remordimiento,
y no abusan de él. Ellos ven y bendicen la mano que los alimenta,
los viste y los preserva.
Mirándolo a Él en todos Sus dones, no adoran los dones, sino al Dador.
En verdad, la dulzura de Su bendición es una ventaja que tienen sobre los que no lo ven.
No se enorgullecen en su prosperidad, ni son derribados en sus adversidades;
porque son moderados en lo primero y consolados en lo otro, por Su presencia divina.

En resumen,
el cielo es el trono y la tierra no es más que el estrado de
los pies de ese hombre que tiene el "`yo`" bajo los pies.
Aquellos que conocen esta condición no serán movidos fácilmente.
Ellos aprenden a contar sus días para que no sean
sorprendidos cuando su tabernáculo se deshiciere.
Aprenden a "`redimir el tiempo, porque los días son malos;`"^
footnote:[Efesios 5:16 RV1602P]
recordando que no son más que administradores y
que deben rendir sus cuentas a un Juez imparcial.
Por lo tanto, no para sí mismos, sino para Él viven, y en Él mueren,
y son bendecidos con los que mueren en el Señor.
Así concluyo mi discurso sobre el uso correcto del "`yo`" lícito.
