== Capítulo IV. La Negación del Yo Lícito

En cuarto lugar: ¿Cuál es la gran obra y propósito de la Cruz?
Es tan importante que esto se responda de manera verdadera, clara y completa,
que pareciera que todo lo anterior sólo sirve como su prefacio.
Equivocarse en esto equivale a desviar el alma de su camino a la bendición. Por lo tanto,
procuraré contestar la pregunta con la ayuda de Dios
y del mejor entendimiento que Él me ha dado,
en la experiencia de varios años de discipulado.

La gran obra y propósito de la cruz de Cristo en el hombre, es la negación al yo;
una expresión poco comprendida,
pero de mucha profundidad
en sí misma y de fuerte oposición al mundo.
El Hijo de Dios se nos ha adelantado,
y--mediante la copa amarga que bebió y el bautismo que sufrió--nos
ha dejado un ejemplo para que sigamos sus pasos.
Esto le hizo plantear aquella difícil pregunta a la esposa de Zebedeo y a sus dos hijos,
cuando ella le pidió que uno se sentara a Su derecha y otro a Su izquierda en Su reino:
"`¿Podéis beber del vaso que Yo he de beber,
y ser bautizados con el bautismo con qué Yo soy bautizado?`"
Al parecer la fe de ellos era fuerte pues respondieron: "`Podemos.`"
A lo cual Él respondió: "`A la verdad, de mi vaso beberéis,
y con el bautismo con que yo soy bautizado, seréis bautizados;`"^
footnote:[Mateo 20:20-23]
pero dejó su recompensa en manos de Su Padre.

¿Cuál fue la copa que Él bebió y el bautismo que sufrió? Respondo:
fueron la negación y la ofrenda de Sí mismo, mediante el Espíritu eterno,
a la voluntad de Dios,
padeciendo las tribulaciones de Su vida y las agonías de Su muerte sobre la cruz,
para la salvación del hombre.

Ahora bien, ¿cuál es _nuestra_ copa y cruz que debemos beber y sufrir?
Son la negación y la ofrenda de nosotros mismos, mediante el mismo Espíritu,
para hacer o sufrir la voluntad de Dios en Su servicio y para Su gloria.
Esta es la verdadera vida y obediencia de la cruz de Jesús; todavía estrecha,
pero antes de Cristo era un camino cerrado;
porque Cristo vino en la grandeza de Su amor y fuerza cuando no había nadie que ayudara,
ni abriera los sellos,
ni diera conocimiento o dirigiera el curso de la recuperación de los pobres hombres.
Y aunque estaba vestido de las debilidades de un hombre mortal,
siendo fortalecido internamente por la omnipotencia del Dios inmortal,
atravesó todas las estrecheces y dificultades de la humanidad; y,
como el primero de todos los demás, anduvo el camino jamás recorrido hacia la bendición.

¡Oh, vamos, sigamos al más incansable y victorioso Capitán de nuestra salvación,
con quien no pueden compararse todos los Alejandros Magnos y poderosos Cesares!
Porque todos estos fueron grandes príncipes de su clase, y conquistadores también,
pero con principios muy diferentes.
Cristo se despojó a Sí mismo para salvar a la humanidad;
pero estos arruinaron pueblos enteros para engrandecer sus nombres.
Ellos vencieron a otros, no a sí mismos; pero Cristo conquistó el yo,
el mismísimo poder que los venció a ellos.
Ellos extendieron su imperio con rapiña y sangre;
pero Él con sufrimiento y persuasión. Ellos prevalecieron a través de la fuerza,
pero Cristo nunca hizo uso de la imposición. La miseria
y la esclavitud siguieron todas sus victorias,
pero Cristo trajo libertad y felicidad a los que venció. En todo lo que hicieron,
buscaron complacerse a sí mismos; en todo lo que Él hizo,
tuvo como objetivo agradar a Su Padre, quien es Dios de dioses,
Rey de reyes y Señor de señores.
Por lo tanto, es correctamente llamado el más excelente príncipe y conquistador.
Y es este patrón más perfecto de negación al yo el que debemos seguir,
si queremos llegar alguna vez a la gloria.

=== El Yo Lícito

Para ello,
consideremos la negación al yo en su verdadera distinción y alcance.
Hay un yo lícito y un yo ilícito, y ambos deben ser negados por amor a Aquel que,
en sumisión a la voluntad de Dios, no estimó nada como precioso para poder salvarnos.
Y a pesar de que apenas alguna parte del mundo ha progresado lo suficiente
como para necesitar una lección sobre la negación del yo lícito (dado
que cada día se entregan con avidez a los placeres del yo ilícito),
aun así, lo mencionaré brevemente,
ya que es posible que esto llegue a algunos que estén tan avanzados
en esta guerra espiritual como para beneficiarse de ello.

El yo lícito que debemos negar es esa comodidad, tranquilidad, disfrute y abundancia que,
en sí mismos, están tan lejos de ser malos,
que pueden considerarse la recompensa y la bendición de Dios para nosotros;
cosas como esposos, esposas, hijos, casas, tierra, reputación, libertad y la vida misma.
Estas cosas son favores de Dios,
que podemos disfrutar con placer lícito y aumentar
justamente según nuestros intereses honestos.
Pero cuando Dios las requiere, en cualquier momento,
o si le place probar nuestros afectos separándonos de ellas; yo digo,
cuando estas cosas entran en competencia con Él, no deben ser preferidas, sino negadas.

Cristo mismo descendió de la gloria de Su Padre,
y voluntariamente se despojó a Sí Mismo en medio de los hombres para llevarnos a Dios.
No estimando el ser igual a Dios como cosa a que aferrarse,
se humilló a Sí Mismo hasta la pobre forma de siervo; sí,
hasta la vergonzosa muerte de cruz,
y así nos dio un ejemplo de humildad pura y de absoluta
sumisión a la voluntad de nuestro Padre celestial.

Él nos enseña esta doctrina con estas palabras: "`El que ama a padre o madre,
hijo o hija más que a mí, no es digno de Mí.`" De nuevo:
"`Cualquiera de vosotros que no renuncia a todo lo que posee,
no puede ser Mi discípulo.`"
Él claramente le dijo al joven rico que si quería tener vida eterna,
debía venderlo todo y seguirlo.
Esta doctrina le resultó triste, como también les resulta a aquellos que,
a pesar de todas sus elevadas pretensiones de religión,
aman sus posesiones más que a Cristo.
Aun así,
esta doctrina de la negación al yo permanece como la condición para la felicidad eterna:
"`Si alguno quiere venir en pos de mí, niéguese a sí mismo, y tome su cruz, y sígame.`"

Esto hizo que aquellos pescadores honestos dejaran sus oficios
lícitos y lo siguieran cuando Él los llamó;
y llevó a otros que esperaban la consolación de Israel a ofrecer también sus propiedades,
reputaciones, libertades y sus vidas,
a pesar del disgusto y furia de sus familiares y del gobierno bajo el cual vivían,
por el beneficio espiritual que recaía sobre ellos
por su fiel adherencia a Su santa doctrina.

Es cierto, muchos buscaron excusarse para no seguirlo,
como se ve en la parábola de la fiesta de bodas.
Algunos habían comprado tierras, algunos se habían casado,
y otros habían comprado yuntas de bueyes y dijeron que no podían asistir.
¡Ay!
Un amor desmedido por el mundo los estorbó. En lugar de actuar como sus siervos,
estos disfrutes lícitos se convirtieron en sus ídolos;
los adoraron más que a Dios y no quisieron renunciar a ellos para ir a Dios.
Esto ha sido escrito para vergüenza de los judíos,
y en ello podemos ver el poder del yo sobre el hombre mundano,
y el peligro que le acarrea abusar de las cosas lícitas.
¡Qué! ¿Tu esposa es más preciada que tu Salvador?
¿Prefieres tu tierra y tus bueyes antes que la salvación de tu alma?
¡Oh!
Ten cuidado de que tus comodidades no resulten primero trampas y luego maldiciones.
Sobrevalorarlas es provocar que Aquel que te las dio las tome nuevamente.
Ven más bien a seguir a Aquel que da vida eterna al alma.

¡Ay de aquellos que tienen sus corazones en sus posesiones terrenales!
Porque cuando se van,
su cielo se queda aquí. Apegarse a sus tesoros mundanos
es el pecado de la mayor parte del mundo,
y cuán lamentable es contemplar sus afectos manchados
y enredados con sus comodidades y bienes.
El hombre que verdaderamente niega al yo es un peregrino;
pero el hombre egoísta es un habitante del mundo.
El primero utiliza el mundo como los hombres usan los barcos,
para transportarse a sí mismo o sus provisiones en un viaje hacia el hogar;
el otro no busca nada más (no importa lo que diga)
que establecerse en plenitud y comodidad aquí,
y le gusta tanto que, si pudiera, nunca lo cambiaría. No,
no se molestará en pensar en el otro mundo hasta
que esté seguro de que ya no vivirá en este.
¡Entonces, por desgracia, será demasiado tarde!
No irá al seno de Abraham, sino al lado del rico; la historia es tan cierta como triste.

Por otro lado, no es en vano que los discípulos de Jesús se nieguen a sí mismos; y,
de hecho, Cristo mismo tenía Su ojo en el gozo eterno.
"`Por el gozo puesto delante de Él,`" dice el autor a los Hebreos, "`sufrió la cruz;`"^
footnote:[Hebreos 12:2]
es decir, se negó a Sí mismo y soportó los vituperios y la muerte del impío,
menospreciando el oprobio, la deshonra y el escarnio del mundo.
Esto hizo que Él no tuviera miedo ni retrocediera,
y ahora está sentado a la diestra del trono de Dios.
Para el ánimo y gran consuelo de Sus discípulos,
cuando Pedro le preguntó qué tendrían los que habían dejado todo para seguirlo,
Él respondió: "`De cierto os digo que en la regeneración,
cuando el Hijo del Hombre se siente en el trono de su gloria,
vosotros que me habéis seguido también os sentaréis sobre doce tronos,
para juzgar a las doce tribus de Israel,`"^
footnote:[Mateo 19:28]
que entonces estaba en la apostasía de la vida y del poder de la piedad.
Esta fue la porción de Sus discípulos,
los compañeros más inmediatos de Sus tribulaciones y los primeros mensajeros de Su Reino.
Pero lo que sigue es para todos: "`Y cualquiera que haya dejado casas, o hermanos,
o hermanas, o padre, o madre, o mujer, o hijos, o tierras, por mi nombre,
recibirá cien veces más, y heredará la vida eterna.`"^
footnote:[Mateo 19:29]
Este grande galardón, esta corona eterna de justicia, es lo que, en todas las eras,
ha despertado en las almas de los justos una santa negación, sí,
un desprecio por el mundo.

=== El Ejemplo de los Antiguos

Esta no es una doctrina nueva; es tan antigua como Abraham.
En varias ocasiones muy notables, su vida estuvo marcada por la negación al yo.
Primero, al abandonar su propia tierra,
en la que bien podemos suponer que estaba establecido en medio de la abundancia o,
al menos, de la suficiencia.
¿Y porque la dejó? Porque Dios lo llamó. Esto debería ser un motivo suficiente;
pero tal es la degeneración del mundo que, en realidad, no lo es.
De hecho, el mismo acto, impulsado por el mismo incentivo en cualquier hombre hoy,
aunque alabado en Abraham, sería escarnecido y ridiculizado.
¡Ay,
cuán propensas son las personas a elogiar lo que no entienden!
¡Y cómo admiran en sus ancestros los mismos hechos que desprecian
en los fieles discípulos de su propio tiempo!

Pero Abraham obedeció y el resultado fue que Dios le dio una tierra buena y ancha.
Esta fue la primera recompensa por su obediencia; la siguiente fue un hijo en su vejez,
pasado el tiempo en que su esposa podía concebir.
Sin embargo, Dios pronto le pidió su tesoro más preciado, su único hijo,
la alegría de su vejez, el hijo de un milagro,
aquel en quien descansaba el cumplimiento de la promesa hecha a Abraham.
Dios le pidió a este hijo,
trayendo una prueba que uno pensaría que bien podría
haber derribado su fe y debilitado su integridad,
o al menos provocado esta disputa en él: "`Esta orden es irracional y cruel;
debe ser del tentador, no puede ser de Dios.
Porque, ¿me habría dado Dios un hijo para después pedirme que lo sacrificara?
¿Debería un padre ser el verdugo de su único hijo?
Que me pida ofrecer al hijo de Su propia promesa, por quien Su pacto ha de cumplirse,
es absurdo.`"
Así habría podido argumentar Abraham, de manera natural,
con el fin de resistir la voz de Dios y complacer sus grandes afectos por su amado Isaac.
Pero el buen anciano Abraham, que conocía la voz que le había prometido un hijo,
no la había olvidado cuando volvió a llamarlo.
Él no discutió, aunque le pareciera extraño, y aunque sin duda,
sintiera una medida de sorpresa y horror como hombre.
Había aprendido a creer que el Dios que le había dado un hijo mediante un milagro,
podría hacer otro milagro para preservarlo o restaurarlo.
Sus afectos no pudieron superar su deber, y mucho menos vencer su fe.

Abraham se inclinó a la voz del Todopoderoso, edificó un altar,
ató a su único hijo sobre él,
encendió el fuego y extendió su mano para tomar el cuchillo;
pero el ángel detuvo el golpe.
"`Detente, Abraham, tu integridad ha sido probada.`"
¿Y qué siguió? Un carnero sirvió para el sacrificio e Isaac fue suyo de nuevo.
Esto muestra cuán poco servirá cuando todo ha sido entregado,
y cuán pequeño es el sacrificio que satisface al Todopoderoso cuando el corazón es aprobado.
No es el sacrificio el que recomienda al corazón,
sino el corazón el que da aceptación al sacrificio.

Dios a menudo toca nuestras mayores comodidades y pide aquello
que más amamos y estamos menos dispuestos a dejar.
Él no siempre las quita totalmente, sino que prueba la integridad del alma,
nos advierte de los excesos y,
para que nos acordemos de Él (el Autor de todas las bendiciones que poseemos),
nos enseña a vivir desapegados del mundo.
Hablo desde mi experiencia:
la manera de conservar lo que nos deleita es renunciando a ello.
Y aunque esto sea difícil, es dulce cuando son devueltas, como lo fue Isaac a su padre,
con más amor y bendición que antes.
¡Oh, mundo necio! ¡Oh, cristianos mundanos! ¡No sólo son extraños,
sino enemigos de esta excelente fe!
Y mientras lo sean, nunca podrán experimentar la recompensa de ella.

La negación al yo de Job también fue muy impresionante.
Porque cuando los mensajeros de sus aflicciones se
agolparon sobre él con una triste historia tras otra,
hasta dejarlo casi tan desnudo como cuando nació,
lo primero que hizo fue postrarse en tierra y adorar ese poder,
y besar esa mano que lo despojó. Estaba tan lejos de murmurar,
que concluyó sus pérdidas de bienes y de hijos con estas palabras:
"`Desnudo salí del vientre de mi madre, y desnudo volveré allá. Jehová dio,
y Jehová quitó; sea el nombre de Jehová bendito.`"^
footnote:[Job 1:21]
¡Oh, la profunda fe, paciencia y contentamiento de este excelente hombre!
Uno hubiera pensado que estas repetidas noticias de ruina
habrían sido suficientes para derribar su confianza en Dios,
pero no fue así; su fe lo mantuvo.
Y él nos dice por qué: "`Yo sé (dice él) que mi Redentor vive.`"^
footnote:[Job 19:25]
Y es manifiesto que Su Redentor en verdad vivía, porque lo había redimido del mundo.
Su corazón no estaba en sus comodidades mundanas;
su esperanza vivía por encima de los disfrutes del tiempo y de las angustias de la mortalidad.
No fue tentado por lo primero, ni movido por lo último;
sino que estaba firmemente convencido de "`que después
de que mi piel haya sido arrancada de mi carne,
veré a Dios.`"^
footnote:[Job 19:26 Traducción Literal]
De esta manera, el corazón de Job se sometió a la voluntad de Dios y se consoló en ella.

Moisés es el siguiente gran ejemplo en la historia sagrada de notable negación al yo,
antes de los tiempos de la aparición de Cristo en la carne.
Cuando era un bebé, había sido salvado por una Providencia extraordinaria,
y al parecer por lo que siguió, para un servicio extraordinario.
La hija de Faraón,
cuya compasión fue el medio de su preservación (cuando el
rey había decretado la matanza de los varones hebreos),
lo tomó como su hijo y le dio la educación propia de la corte de su padre.
Su propia presencia agraciada y sus habilidades extraordinarias,
unidas al amor que ella le tenía y el deseo de que su padre lo ascendiera,
debieron haberlo hecho, si no capaz de heredar el trono,
al menos ser un ministro principal bajo aquel príncipe rico y poderoso.
Porque Egipto era entonces lo que Atenas y Roma fueron después:
el centro más famoso de conocimiento, arte y gloria.

Pero Moisés había sido designado para otra obra y guiado por una mejor estrella,
un principio superior.
Tan pronto como llegó a una edad de discernimiento,
la impiedad de Egipto y las opresiones de sus hermanos allí se hicieron una carga demasiado
pesada para él. Y aunque un hombre tan sabio y bueno no podría haber carecido de sentimientos
generosos y agradecidos por la bondad de la hija del rey para con él,
aun así, también había visto "`al Dios Invisible,`"^
footnote:[Hebreos 11:27 PDT]
y no se atrevió a vivir en la comodidad y en la abundancia de la casa de Faraón
mientras que sus pobres hermanos eran obligados a hacer ladrillo sin paja.
Y así, con el temor del Todopoderoso apoderándose de su corazón,
rehusó noblemente llamarse hijo de la hija de Faraón,
y escogió ser maltratado con los despreciados y oprimidos israelitas,
y ser el compañero de sus tentaciones y peligros,
antes "`que gozar de los deleites temporales del pecado;`"^
footnote:[Hebreos 11:25]
teniendo por mayores riquezas los vituperios de Cristo (que sufrió al hacer esa
elección en contra del mundo) que todos los tesoros de ese reino.

Tampoco fue tan tonto como pensaban; puesto que tenía la razón de su lado.
Se dice que él "`tenía puesta la mirada en el galardón;`"^
footnote:[Hebreos 11:26]
de manera que sólo rechazó un beneficio menor por uno mayor.
En esto, su sabiduría trascendió la de los egipcios;
porque ellos eligieron el mundo presente (que es tan incierto
como el clima) y así perdieron ese mundo que no tiene fin.
Moisés miró más profundamente,
sopesó los placeres de esta vida en la balanza de la eternidad
y descubrió que no tenían peso allí. Se gobernó a sí mismo,
no por la posesión inmediata, sino por la naturaleza y duración de la recompensa.
Su fe corrigió sus afectos y le enseñó a sacrificar los placeres del yo
por la esperanza que tenía de una futura y más excelente recompensa.

Isaías no fue un ejemplo nada insignificante de la misma bendita negación al yo; quien,
de cortesano, se convirtió en profeta,
y dejó los intereses mundanos de lo primero por la fe,
paciencia y sufrimientos de lo segundo.
Su elección no sólo le hizo perder el favor de los hombres,
sino que la iniquidad de ellos (excitada por su integridad ante Dios en sus fervientes
y audaces reprensiones hacia ellos) lo hicieron un mártir al final;
porque lo aserraron bárbaramente en el reinado de Manasés. Así murió ese excelente hombre,
comúnmente llamado el Profeta Evangélico.

Agregaré un ejemplo más a partir de la fidelidad de Daniel.
Este fue un joven santo y sabio, quien,
cuando sus ventajas externas entraron en competencia con su deber hacia el Dios Todopoderoso,
renunció a todas.
En lugar de preocuparse por su propia seguridad,
como si ésta fuera la menor de sus consideraciones,
se preocupó (hasta el máximo riesgo de su vida) por preservar
el honor de Dios mediante la fidelidad a Su voluntad.
Y aunque esto al principio lo expuso a la ruina, aun así,
(como un gran aliento para todos los que conservan la conciencia limpia en tiempos malos),
su fidelidad a su Creador finalmente lo hizo prosperar mucho en el mundo;
y el Dios de Daniel se hizo famoso y temible a través de su perseverancia,
incluso ante los ojos de los reyes paganos.

¿Y qué diré de todos los demás, quienes,
no estimando ninguna cosa preciosa para poder hacer la voluntad de Dios,
abandonaron sus comodidades mundanas y expusieron su tranquilidad y seguridad
(tan a menudo como la visión celestial los llamaba) a la ira y a la malicia
de los príncipes degenerados y de una iglesia apóstata?
En especial Jeremías, Ezequiel y Miqueas, quienes después de haberse negado a sí mismos,
en obediencia a la voz divina, sellaron su testimonio con su sangre.

Así, pues, la negación al yo fue la práctica y la gloria de los antiguos,
que fueron precursores de la venida de Cristo en la carne.
¿Y podremos esperar el cielo sin ella hoy,
cuando nuestro Salvador mismo fue hecho el ejemplo más excelente de ella?
Y eso, no como algunos ansiosamente desearían decir, a saber, "`Él sufrió por nosotros,
para que nosotros no tengamos que sufrir;`" sino al contrario, Él sufrió por nosotros,
para que nosotros pudiéramos negarnos a nosotros mismos
y así ser los verdaderos seguidores de Su bendito ejemplo.

=== Deja Todo por Él

Por tanto, quienquiera que seas tú, que deseas hacer la voluntad de Dios,
pero desfalleces debido a la oposición de las consideraciones mundanas,
recuerda que te digo, en el nombre de Cristo, que aquel que prefiere padre o madre,
hermana o hermano, esposa o hijo, casa o tierra, reputación, honor, oficio,
libertad o vida, antes que el testimonio de la luz de Jesús en su propia conciencia,
será rechazado por Él en el juicio solemne y general del mundo,
cuando todos serán juzgados y recibirán de acuerdo a las
obras hechas (no en las palabras profesadas) en esta vida.
La doctrina de Jesús es que si tu mano derecha te es ocasión de caer, debes cortarla;
y que si tu ojo derecho te es ocasión de caer, debes sacarlo; es decir,
si las comodidades más preciadas,
más útiles y tiernas que disfrutas se interponen en el camino de tu alma,
interrumpiendo tu obediencia a la voz de Dios y tu
conformidad a Su santa voluntad revelada en tu alma,
estás llamado, bajo pena de condenación, a separarte de ellas.

El camino de Dios es un camino de fe,
el cual es tan oscuro para los sentidos naturales como mortal para el yo.
Los hijos de obediencia, con el santo Pablo,
estiman todas las cosas como basura y estiércol para ganar a Cristo,
y para experimentar y andar en este camino angosto.
La especulación no servirá, ni podrán entrar los conceptos refinados.
Sólo el obediente comerá del fruto de esta tierra.
"`Si alguno quisiere hacer su voluntad,`" dice el bendito Jesús,
"`conocerá de Mi doctrina;`"^
footnote:[Juan 7:17 RV1602P]
a estos Él les enseñará. No hay lugar en el corazón para
la instrucción cuando el yo lícito es señor y no siervo.
Porque el yo no puede recibirla;
y lo que debería recibirla es oprimido por el yo con miedos y dudas:
"`¿Qué dirán mi padre o mi madre?
¿Cómo me tratará mi esposo?
O, ¿qué harán los magistrados conmigo?
Porque,
aunque siento una poderosa persuasión y una clara
convicción en mi alma sobre esto o aquello,
aun así, al considerar cuán menospreciado es,
los enemigos que tiene y lo extraño que pareceré para algunos,
espero que Dios se compadezca de mi debilidad si me rindo.
No soy más que carne y sangre; quizás más adelante Él me capacité mejor;
y hay tiempo suficiente.`"
Así habla el hombre egoísta y cobarde.

Razonar es siempre lo peor, porque el alma pierde cuando consulta;
pero la manifestación de la luz trae poder con ella.
Dios nunca ha tratado de convencer a las personas sin darles también poder,
tras su sumisión. Él no requiere nada sin dar la capacidad de realizarlo,
porque eso sería burlarse de los hombres, y no salvarlos.
Es suficiente que hagas lo que Dios muestra como tu deber,
con tal que te rindas a la luz o Espíritu por el cual te da ese conocimiento.
Aquellos que no reciben a Cristo en Sus convicciones en el alma,
son los que carecen de poder, y a estos siempre les faltará. Pero los que sí lo reciben,
también reciben poder (como los santos de antaño) para ser hechos
hijos de Dios a través de la obediencia pura de la fe.

Por lo tanto, permítanme rogarles por el amor y la misericordia de Dios,
por la vida y la muerte de Cristo,
por el poder de Su Espíritu y la esperanza de la inmortalidad,
a ustedes cuyos corazones están puestos en sus comodidades temporales,
y son amantes de sí mismos más que de estas cosas celestiales,
¡dejen que el tiempo pasado sea suficiente para tales cosas!
No piensen que es suficiente estar libres de ciertas
impiedades graves en las que se encuentran otros,
mientras que su amor desmedido por las cosas lícitas contamina
su disfrute de ellas y saca sus corazones del temor,
amor, obediencia y negación al yo de un verdadero discípulo de Jesús. Vuélvanse, pues,
y escuchen la voz apacible en sus conciencias;
ella les habla de sus pecados y de su miseria en ellos.
Les da un descubrimiento vivo de la vanidad del mundo,
y abre ante sus almas una perspectiva de la eternidad
y de los consuelos de los justos que están en reposo.
Si se aferran a ella, los divorciará del pecado y del yo.
Pronto notarán que el poder de sus encantos excede al de la riqueza,
el honor y la belleza del mundo,
y finalmente les concederá esa tranquilidad que las tormentas
del tiempo no pueden hacer naufragar ni trastornar.
Aquí todos sus disfrutes son bendecidos.
Aunque sean pequeños, son grandes debido a esa presencia que los acompaña.

Incluso en este mundo, los justos tienen la mejor parte,
ya que usan el mundo sin remordimiento y no abusan
de él. Ellos ven y bendicen la mano que los alimenta,
los viste y los preserva.
Mirándolo a Él en todos Sus dones, no adoran los dones, sino al Dador.
En efecto, la dulzura de Su bendición es una ventaja que tienen sobre los que no lo ven.
No se enorgullecen en su prosperidad, ni son derribados en sus adversidades;
porque son moderados en lo primero y consolados en lo otro por Su presencia divina.

En resumen,
el cielo es el trono y la tierra no es más que el estrado
de los pies de ese hombre que tiene el yo bajo los pies.
Aquellos que conocen esta condición no serán movidos fácilmente.
Ellos aprenden a contar sus días para no ser sorprendidos cuando su tabernáculo se deshaga.
Aprenden a "`redimir el tiempo, porque los días son malos;`"^
footnote:[Efesios 5:16 RV1602P]
recordando que no son más que mayordomos y que deben rendir cuentas a un Juez imparcial.
Por lo tanto, no para el yo, sino para Él viven, y en Él mueren,
y son bendecidos con los que mueren en el Señor. Así concluyo
mi exposición sobre el uso correcto del yo lícito.
