== Capítulo V. Negando el Yo Ilícito

Ahora vengo al "`yo`" ilícito, que es, en una medida u otra,
el problema presente de la mayor parte de la humanidad.
Este yo ilícito es de dos formas.
Primero, aquello que se relaciona con la adoración^
footnote:[Con "`Adoración,`" Penn no se refiere solamente cantar, alabar, etc.
Sino al servicio entero del hombre hacia a Dios,
o a todo lo que se relaciona directamente con Dios, o que el hombre dirige hacia Él.]
religiosa.
Segundo, aquello que tiene que ver con la conducta moral y civil en el mundo,
y es de infinita importancia que los consideremos a ambos.
Seré tan breve como sea posible con tranquilidad en mi
conciencia y sin dañar el asunto en cuestión.

El "`yo`" ilícito en la religión, que debe ser crucificado por la cruz de Cristo,
es la invención y ejecución del hombre, de la adoración a Dios,
que realmente no es adoración en absoluto,
ni en su institución ni realización. En este gran error,
muchos de los que se atribuyen el nombre de cristianos toman la delantera,
siendo los más externos,
extravagantes y supersticiosos en su adoración. Estos no solamente se
desvían excesivamente por falta de preparación espiritual en su forma
de rendir adoración al Dios Todopoderoso (quien es espíritu eterno),
sino que la adoración en sí misma se compone de lo que
es absolutamente inconsistente con la forma y práctica
de la doctrina de Cristo y el ejemplo apostólico.
La adoración de los apóstoles era simple y espiritual; la de hoy es llamativa y mundana.
La adoración de Cristo era interna, en el alma; la del mundo es externa y corporal.
La verdadera adoración correspondía a la naturaleza de Dios, que es espíritu;
pero la adoración inventada por el hombre se adapta a la parte carnal.
En lugar de excluir la carne y la sangre,
he aquí que ahora hay una adoración calculada para satisfacer la carne,
como si la meta no fuera presentarle a Dios una adoración que le agradara,
sino inventar una que le agradara al hombre.

Esta es una adoración decorada con edificios e imágenes majestuosas,
muebles y vestimentas costosos, voces y música refinadas, lámparas,
velas de cera y perfumes caros,
y todo hecho con la variedad más placentera para los sentidos
externos que el arte puede inventar o el dinero procurar.
Actúan como si el mundo volviera a ser judío o egipcio otra vez,
o como sí Dios fuese un anciano y Cristo un pequeño niño,
que debe ser tratado con una especie de espectáculo religioso--porque así es
como muchos lo pintan en sus templos y lo imaginan en sus mentes.
Tal adoración carnal encaja muy bien con esta idea de Dios,
porque cuando los hombres piensan que Él es como uno de ellos,
no es de extrañar que se dirijan a Él y Lo entretengan de una
manera que les gustaría recibir de otras personas.

Pero ¿Qué dijo el Todopoderoso a ese pueblo tan carnal de la antigüedad,
en una ocasión similar?
"`Pensabas que de cierto sería yo como tú; pero te reprenderé,
y pondré tus pecados delante de tus ojos.
Entended ahora esto, los que os olvidáis de Dios, no sea que os despedace,
y no haya quien os libre.
El que sacrifica alabanza me honrará; y al que ordenare su camino,
le mostraré la salvación de Dios.`"^
footnote:[Salmos 50:21-23]
La adoración aceptable para Él es,
"`hacer justicia, y amar misericordia, y humillarte ante tu Dios.`"^
footnote:[Miqueas 6:8]
Aquel que escudriña el corazón y prueba los pensamientos del hombre,
y pone sus pecados en orden delante de sus ojos,
quien es el Dios de los espíritus de toda carne, no mira la cubierta externa,
sino la disposición interna del alma y la inclinación del corazón. Tampoco se puede
pensar sobriamente que Él que está "`vestido de gloria y de magnificencia,
que se cubre de luz como de vestidura, que extiende los cielos como una cortina,
que establece sus aposentos entre las aguas, que pone las nubes por su carroza,
que anda sobre las alas del viento; que hace a los vientos sus mensajeros,
y a las flamas de fuego sus ministros, y que fundó la tierra sobre sus cimientos;
para que jamás sea removida,`"^
footnote:[Salmos 104:1-5]
puede adorarse adecuadamente mediante esas invenciones humanas
que son el refugio de un pueblo que ha apostatado del poder y
la espiritualidad primitivos de la adoración cristiana.

=== El Templo Interno

Cristo estaba sacando a sus discípulos de la gloria y la adoración del
templo externo e instituyó una adoración más interna y espiritual,
en la cual instruía a Sus seguidores.
"`Ni en este monte ni en Jerusalén,`" le dice Cristo a la Samaritana,
"`adoraréis al Padre.
Dios es Espíritu; y los que le adoran,
en espíritu y en verdad es necesario que adoren.`"^
footnote:[Juan 4:21, 24]
Es como si hubiera dicho: '`Por causa de la debilidad del pueblo, Dios accedió,
en tiempos pasados, a limitarse a un tiempo, lugar, templo y servicio externos,
en y por los que sería adorado;
pero esto fue durante la ignorancia de los hombres de Su omnipresencia,
cuando no consideraban lo que es Dios ni donde está. Yo
he venido a revelarlo a todos los que Me reciben.
Dios es Espíritu, y será adorado en espíritu y en verdad.`'

Las personas deben conocerlo como un espíritu, considerándolo y adorándolo como tal.
No es la adoración corporal,
ni los servicios ceremoniales que ahora se usan entre ustedes,
los que servirán o darán aceptación ante este Dios que es un espíritu.
Deben obedecer a Su Espíritu que contiende con
ustedes para sacarlos fuera del mal del mundo,
para que, al someterse a sus instrucciones y mandamientos en sus propias almas,
puedan saber lo que es adorarlo como un espíritu.
Entonces entenderán, que no se trata de ir a esta montaña, ni a Jerusalén,
sino hacer la voluntad de Dios y guardar Sus mandamientos.
Mediten en su propio corazón y no pequen; tomen su cruz,
mediten en Su santa ley y sigan el ejemplo de Aquel a quien el Padre ha enviado.

Esteban, ese audaz y fiel mártir de Jesús, les dijo a los judíos,
cuando era prisionero ante su concilio, "`Salomón le edificó casa;
si bien el Altísimo no habita en templos hechos de mano, como dice el profeta:
El cielo es mi trono, y la tierra el estrado de mis pies.
¿Qué casa me edificaréis? dice el Señor; ¿O cuál es el lugar de mi reposo?
¿No hizo mi mano todas estas cosas?`"^
footnote:[Hechos 7:47-50]
¡He aquí, un derrocamiento total de todos los templos mundanos y accesorios ceremoniosos!
El mártir continúa su golpe sobre los judíos apóstatas (que
fueron los adoradores extravagantes,
ceremoniosos y mundanos de aquel tiempo), diciendo:
"`¡Duros de cerviz, e incircuncisos de corazón y de oídos!
Vosotros resistís siempre al Espíritu Santo; como vuestros padres,
así también vosotros.`"^
footnote:[Hechos 7:51]
Es como sí les hubiera dicho: '`Ni su templo exterior, sus ritos,
sus servicios figurativos, ni sus pretensiones de una sucesión natural de Abraham,
o de una sucesión religiosa de Moisés son de importancia;
porque ustedes resisten al Espíritu y se oponen a Sus instrucciones.
Ustedes no quieren someterse a Su consejo, y sus corazones no son rectos hacia Dios.
¡Ustedes son los sucesores de la iniquidad de sus padres!
Y, aunque de boca son admiradores de los profetas,
no son los sucesores de su fe ni de su vida.`'

El profeta Isaías lleva esto un poco más allá de lo que cita Esteban.
Porque, después de haber declarado lo que no es la casa de Dios
(el lugar donde mora Su gloria), estas palabras siguen inmediatamente:
"`Pero miraré a aquel que es pobre y humilde de espíritu, y que tiembla a mi palabra.`"^
footnote:[Isaías 66:2]
¡He aquí, oh hombre carnal y supersticioso,
el verdadero adorador y el lugar del reposo de Dios!
Esta es la casa y el templo de Aquel a quien los cielos de los cielos
no pueden contener--una casa que el "`yo`" no puede edificar,
ni el arte o poder del hombre preparar o consagrar.

Pablo, ese gran apóstol de los gentiles,
usa expresamente la palabra templo dos veces para referirse al hombre,
y no a un edificio construido por la mano y el arte del hombre.
En su primera epístola a la iglesia de Corintios, escribe:
"`¿O ignoráis que vuestro cuerpo es templo del Espíritu Santo,
el cual está en vosotros, el cual tenéis de Dios?`"^
footnote:[1 Corintios 6:19]
Y nuevamente, les dice a las mismas personas, en su segunda epístola:
"`porque vosotros sois el templo del Dios vivo, como Dios ha dicho;`"
y luego cita las palabras de Dios por medio del profeta,
"`Yo moraré en ellos, y andaré en ellos; y yo seré el Dios de ellos,
y ellos serán mi pueblo.`"^
footnote:[2 Corintios 6:16 RV1602P]
Este es el templo bajo el evangelio, la iglesia cristiana,
cuyos ornamentos no son los bordados ni los muebles del arte y riqueza del mundo,
sino las gracias del Espíritu--mansedumbre, amor, fe, paciencia, abnegación y caridad.
Aquí es donde la Sabiduría eterna--
"`la cual estaba con Dios desde la eternidad, antes que los montes fuesen formados`"--
elige morar, "`regocijándome (dice Él) en la parte habitable de Su tierra;
y mis delicias son con los hijos de los hombres,`"^
footnote:[Proverbios 8:31]
no en casas hechas de madera y piedra.
Esta casa viviente es más gloriosa que la casa muerta de Salomón,
que no era más que una figura; sí, así como Salomón era una figura de Cristo,
quien nos edifica como un templo santo para Dios.
Se prometió en la antigüedad que
"`La gloria de esta casa postrera será mayor que la de la primera;`"^
footnote:[Hageo 2:9 RVG]
lo cual puede aplicarse verdaderamente a esta.
Porque el profeta no hablaba de un templo o casa
externa que excede a otro en belleza externa;
porque, ¿cuál sería el beneficio de eso?
Pero la promesa fue que la gloria divina,
la hermosura de la santidad en la casa del evangelio o iglesia,
compuesta de creyentes regenerados, excedería la gloria externa del templo de Salomón,
la cual, en comparación con la de los días postreros,
era como la diferencia entre carne y espíritu,
o semejanzas que se desvanecen en comparación con la sustancia eterna.

Los cristianos sí tienen lugares de reunión, pero no a la manera de los judíos o paganos,
sino al contrario, simples, sin extravagancia ni ceremonia,
de acuerdo con la simplicidad de la vida y doctrina de su bendito Señor.
Porque la presencia de Dios no es con la casa,
sino con los que están en ella, quienes son la iglesia del evangelio, y no la casa.
¡Oh que aquellos que se llaman cristianos conocieran la verdadera santidad
en sí mismos mediante el lavamiento de la gracia regeneradora de Dios,
en lugar de esa santidad imaginaria atribuida a los lugares!
Entonces sabrían qué es la iglesia y dónde es que Dios aparece en este día del evangelio.
Sí, esto hizo que el profeta David dijera,
"`Toda gloriosa en su interior es la hija del Rey; de brocado de oro es su vestido.`"^
footnote:[Salmos 45:13 RVG]
¿Cuál es la gloria que está dentro de la verdadera iglesia,
y ese oro que constituye su gloria interior?
Dime, ¡oh hombre supersticioso! ¿Son sus majestuosos templos, altares, alfombras, mesas,
tapices, vestimentas, órganos, voces, velas, lámparas, incensarios, platos y joyas,
y otros muebles de este tipo, que se encuentran en sus templos mundanos?
¡Nada que ver!
Estas cosas no son nada en comparación con el adorno divino de la hija del Rey del cielo,
la iglesia bendita y redimida de Cristo.
¡Oh miserable apostasía! Oh miserable sustituto de la pérdida de la vida apostólica,
la gloria espiritual de la iglesia primitiva.

=== Las Falsas Cruces de los Hombres

Sin embargo,
algunos de estos admiradores de la pompa y de la gloria
externa quieren ser considerados amantes de la cruz,
y por lo tanto se han hecho muchas.
Pero ¡Ay! ¿Qué tiene que ver esto con el verdadero cristianismo?
Porque mientras estos pretenden adorar a Dios con sus cruces externas,
muy peligrosamente se apartan de la verdadera cruz de Cristo y de esa santa
abnegación del "`yo`" que fue de Su bendita designación. De hecho,
esas cruces parecen interponerse en el camino de la verdadera,
porque en lugar de crucificar sus voluntades, las han hecho de acuerdo a su voluntad,
y asimismo las usan;
de modo que estas cruces decorativas se han convertido en un
emblema de los que no hacen nada más que lo que desean.
Sin embargo, por estas cruces,
desean ser considerados los discípulos de Aquel que nunca hizo Su propia voluntad,
sino solo la voluntad de su Padre celestial.

Estas cruces externas pueden ser cargadas fácilmente
por carne y sangre puesto que ellas las inventaron.
Por lo tanto, no son la cruz de Cristo,
la cual es el poder de Dios para crucificar carne y sangre.
Miles de ellas no tiene más virtud que una migaja.
Son sombras pobres y vacías, llevadas como amuletos,
a pesar de que no pueden repeler ni un solo mal.
De hecho, los hombres pecan mientras las llevan sobre sus espaldas;
y aunque las exhiben sobre su corazón, por desgracia,
sus deseos amados yacen allí también sin la menor interrupción.
Son tan mudas como los dioses falsos de Baal,
ya que no tienen vida ni poder.
¿Y cómo podrían? Pues su sustancia es terrenal y su imagen y hechura
no son más que los inventos y la obra de artistas mundanos.
Son yugos sin restricción y cruces que nunca crucifican.
Un montón de ellos dejaría a un hombre tan vivo en la carne como lo encontró.
Los hombres se sacarían los sesos con ellas antes que sus pecados;
y esto, me temo, que ya se sabe en la conciencia de los que las usan y las adoran.

Tampoco es una vida aislada
(la justicia pretendida de algunos que se encierran en monasterios y conventos)
más encomiable,
ni un paso más cerca de la naturaleza de la verdadera cruz; porque,
aunque esto no es ilícito, tampoco es natural,
y la religión verdadera no lo enseña. El verdadero
convento o monasterio cristiano está adentro,
donde el alma se enclaustra del pecado.
Y los verdaderos seguidores de Cristo llevan consigo esta casa religiosa,
no absteniéndose de las interacciones con el mundo, aunque se guardan de sus males.

Pero la vida del monasterio es un tipo de abnegación ocioso y poco productivo,
que es gravoso para los demás.
Hombres y mujeres son encerrados adentro no sea que afuera hagan el mal,
aprendiendo una especie de paciencia por la fuerza,
una abnegación contra su propia voluntad,
evitando la tentación en lugar de aprender a ser fieles y constantes en ella.
No es un gran logro si no cometen los pecados que no son tentados a cometer;
porque el corazón no desea lo que el ojo no ve.

La cruz de Cristo es de otra naturaleza.
Realmente vence al mundo y conduce a una vida de pureza frente a las tentaciones.
Quienes la llevan no se encadenan así por temor a morder; ni se encierran,
no sea que se roben su fe.
Reciben poder de Cristo, su capitán,
para resistir el mal y hacer lo que es bueno ante los ojos de Dios.
De hecho, renuncian al mundo y aman su oprobio por encima de su alabanza.
No ofenden a los demás, al contrario, aman a los que los ofenden.
¿Qué mundo tendríamos si todos, por temor a transgredir,
se enjaulan detrás de cuatro paredes?
No, la perfección de la vida cristiana se extiende hacia cada
trabajo y comercio honesto que se usa entre los hombres.
Tal severidad no es el efecto del Espíritu libre de Cristo,
sino de una humildad voluntaria y carnal--grilletes fabricados y colocados por el hombre,
sin prescripción ni razón.

Los monasterios y los conventos son sus propios
legisladores y establecen sus propias reglas,
castigos y penitencia,
una severidad forzada que no concuerda con el resto de la creación.
Porque la sociedad es uno de los grandes propósitos para la creación,
y no debe ser destruida por temor al mal.
Es el pecado que la arruina, el que debe ser desterrado,
mediante la reprensión continua y el destacado ejemplo de la virtud probada.
La verdadera piedad no aparta a los hombres de la sociedad,
sino que les permite vivir mejor en ella,
y estimula sus esfuerzos para repararla--
"`no escondiendo su luz debajo del almud, sino poniéndola sobre la mesa, en el candelero.`"

Además, esas cosas son inventos egoístas,
ya que debido a ellas los hombres huyen por sus vidas,
dejando el mundo y permitiendo que se pierda.
Los cristianos deberían más bien mantener el timón y guiar al barco a su puerto correcto;
no huir silenciosamente de la nave por la parte de atrás,
dejando a los que quedan sin piloto,
para ser llevados por la furia de los tiempos
malos sobre las rocas o arenas de la ruina.

Tomar la cruz de Jesús es un ejercicio mucho más interno.
Es la vigilancia y disciplina del alma,
en conformidad con la mente divina revelada en ella.
¿No sigue el cuerpo al alma, y no el alma al cuerpo?
Considera pues,
que ninguna celda externa puede proteger al alma de los deseos
o a la mente de sus infinitas imaginaciones injustas.
"`Los pensamientos del corazón de los hombres son de continuo solamente el mal.`"^
footnote:[Génesis 6:5]
El mal viene de adentro, y no de afuera.
¿Cómo, pues, podría una aplicación externa remover una causa interna?
O, ¿cómo podría una restricción impuesta al cuerpo limitar la actividad de la mente?

Examina, oh hombre, tu fundamento, qué es y quién te puso allí;
no sea que al final resulte que has puesto un engaño eterno en tu propia alma.
Debo confesar que estoy ansioso por la salvación de mi propia especie.
Habiendo encontrado misericordia con mi Padre celestial,
no quisiera que ninguno se engañe a sí mismo para su perdición,
especialmente sobre la religión,
donde las personas son más propensas a dar todo por hecho,
y perder infinitamente por su auto-adulación y negligencia.

La justicia interna e inmutable de Jesús es algo muy diferente de
todas las devociones inventadas del pobre hombre supersticioso;
y ser aprobado delante de los ojos de Dios sobrepasa todos los ejercicios
corporales en la religión que resultan de la invención de los hombres.
El alma que es despertada y preservada por Su santo poder y
Espíritu vive para Él en el camino de Su propia institución,
y lo adora en Su propio Espíritu--es decir, en el sentido,
vida y dirección santos del mismo--lo cual en
efecto es la verdadera adoración evangélica.

No es mi intención menospreciar el verdadero retiro cristiano; porque no sólo reconozco,
sino que admiro la soledad.
Cristo mismo fue un ejemplo de ello.
Él amaba y escogía frecuentar muchas montañas, huertos y costas solo.
De hecho, es un requisito para el crecimiento de la piedad,
y yo reverencio la virtud que la busca y la usa, deseando que hubiera más en el mundo.
Pero esto debería ser voluntario y no forzado.
