== Capítulo VI. La Adoración Espiritual

Hay otros de una opinión más refinada y de una práctica más reformada,
que no se atreven a utilizar (mucho menos a adorar), un pedazo de madera o piedra,
o una imagen de plata u oro;
quienes no permitirán esa extravagancia que otros practican en su adoración,
como si la adoración de Cristo fuera de este mundo, aunque Su reino sea de otro.
Sin embargo, aunque estos son doctrinalmente contrarios a tales supersticiones,
no dejan de inclinarse ante sus propios deberes religiosos,
mientras estiman esas cosas que van contra la corriente de su
comodidad carnal como una cruz demasiado grande para soportar.
Porque si se abstienen de los pecados evidentes y escandalosos,
o si el acto no se consuma,
aunque los malos pensamientos de dicho acto son abrazados (de
modo que tienen plena libertad en la mente),
se consideran lo suficientemente salvos,
dentro de los límites del discipulado y del cristianismo.
Pero esto también queda muy corto de la verdadera disciplina de la cruz de Cristo,
y aquellos que se engañan a sí mismos llevando esta cruz falsa, al final,
serán decepcionados por un fundamento arenoso,
y con el clamor del Esposo a la medianoche.
Porque Cristo dijo, "`Mas yo os digo que de toda palabra ociosa que hablen los hombres,
de ella darán cuenta en el día del juicio.`"^
footnote:[Mateos 12:36]

No es la realización de deberes religiosos lo que Dios considera,
sino la fuente de lo que se hace.
Los hombres pueden (y algunos lo hacen) contradecir sus propias voluntades
en sus propias voluntades--una omisión o comisión voluntaria.
Pero "`¿Quién demanda esto de vuestras manos?`"^
footnote:[Isaías 1:12]
fue lo que Dios les dijo a los judíos de antaño, cuando parecían ansiosos por servirle,
pero según sus propias ideas e inventos, y en su propio tiempo y voluntad.
Estos no se acercaban con un alma verdaderamente
tocada y preparada por el poder divino de Dios,
sino solo con una adoración corporal, que el apóstol nos dice que es poco provechosa.
¡Ay! No aferrarse a la cruz en la adoración (así como en otras cosas)
ha sido la gran causa de la superstición perjudicial que todavía existe en el mundo.
¡Porque los hombres no han llevado su adoración a la luz más que sus pecados!
De hecho,
han considerado ignorantemente su adoración como una especie de excusa para sus pecados,
nunca considerando que sus acciones religiosas necesiten una cruz, o una defensa.

=== Un Corazón Preparado para Adorar

La verdadera adoración solo puede surgir de un corazón preparado por el Señor--
una preparación que es mediante la santificación del Espíritu Santo.
Porque ciertamente,
si los hijos de Dios deben ser guiados por este Espíritu en el
curso general de sus vidas como lo enseña Pablo,
cuánto más debería ser este el caso en su adoración a su Creador y Redentor.
Cualquier oración que se ofrezca, o doctrina que se predique,
que no provenga de la preparación del Espíritu Santo, no es aceptable para Dios,
ni puede ser la verdadera adoración del evangelio que es en espíritu y en verdad.
Porque ¿qué son las palabras elocuentes y apasionadas para el Dios Todopoderoso;
o la dedicación de cualquier lugar o tiempo a Él? Él es un espíritu,
para quien las palabras,
los lugares y los tiempos (si se consideran debidamente) son impropios o inadecuados.
Aunque son los instrumentos de la adoración pública,
no son más que corporales y visibles,
y no pueden hacer que nuestras peticiones influyan más con Dios,
mucho menos abogar por ellas ante el Invisible Creador.
Las palabras son para el bien de la congregación,
pero es el lenguaje del alma lo que Dios escucha.
El alma tampoco puede gemir ni hablar adecuadamente al Dios Todopoderoso,
salvo por la ayuda de Su Espíritu.
El alma del hombre, sin importar cuán viva esté en otras cosas,
está muerta para Dios hasta que Él sople el Espíritu de vida en ella; sin el Espíritu,
el alma no puede vivir para Él, y mucho menos adorarlo.
Por lo tanto,
Dios (por medio del profeta Ezequiel) nos dice en una
visión acerca de la restauración de la humanidad:
"`He aquí yo abriré vuestros sepulcros y pondré mi Espíritu en vosotros, y viviréis.`"^
footnote:[Ezequiel 37:12, 14]

Ahora,
el hecho de que Cristo enseñó a Sus discípulos a orar no es un argumento contra esto,
porque el asunto no es si los hombres pueden repetir Sus palabras
(como ahora se practica con demasiada superstición y presunción),
sino si pueden decirlas con el mismo corazón,
y bajo las mismas cualificaciones con las que
Sus pobres discípulos y seguidores las dijeron.
Porque tanto los discípulos de aquel entonces como los verdaderos discípulos ahora,
no deben orar sus propias oraciones, sino más bien las de Él, según Él los capacite.

Ahora consideren,
si se nos dijo que no nos preocupáramos por lo que
diremos cuando nos presentemos ante príncipes mundanos,
porque en ese momento nos será dado;
y si en aquel momento "`no somos nosotros los que hablamos,
sino el Espíritu de nuestro Padre que habla en nosotros,`"^
footnote:[Mateos 10:20]
entonces, mucho menos nuestra habilidad, estudio,
y retórica naturales serán aceptados cuando nos acerquemos al gran Príncipe de príncipes,
Rey de reyes y Señor de señores.
Es Su ayuda lo que necesitamos, y nos la dará si realmente somos Sus hijos.
Porque no solo la boca del cuerpo,
sino la boca del alma está cerrada hasta que Dios la abra;
pero al ser abierta por Su Espíritu, Él ama oír el lenguaje de ella.
De hecho, Su oído está abierto a todas esas peticiones,
y Su Espíritu intercede fuertemente por los que las ofrecen;
pero el cuerpo nunca debe comenzar la oración antes que el alma.

Pero, se podría preguntar: ¿Cómo se obtendrá esta preparación?
Respondo: esperando pacientemente, aunque vigilante y fervientemente en Dios.
"`Oh Señor,`" dice el salmista,
"`El deseo de los humildes oíste, Tú dispones su corazón, y haces atento Tu oído.`"^
footnote:[Salmos 10:17 RV1602P]
Ustedes no deben pensar sus propios pensamientos, ni hablar sus propias palabras,
sino retirarse de todas las imaginaciones confusas que
tienden a abarrotar y presionar la mente;
este verdaderamente es el silencio de la santa cruz.
No piensen ganar el amor del Todopoderoso con un tema bien estudiado,
puesto en la frase más elocuente.
No, un solo gemido, un solo suspiro de un alma afligida,
un corazón tocado con verdadero remordimiento,
o una tristeza sincera y piadosa que es obra del Espíritu de Dios,
excede y prevalece con Dios.

Por lo tanto,
permanezcan quietos en su mente y esperen sentir algo de Dios que los
prepare y disponga para adorarlo de manera verdadera y aceptable.
Así, tomando la cruz,
y cerrando las puertas y ventanas del alma contra todo lo que interrumpiría su
espera en Dios--sin importar cuán placentero pueda ser el objeto en sí mismo,
o cuán lícito o necesario sea en otro momento--el poder del Todopoderoso irrumpirá
y Su Espíritu preparará el corazón para que pueda ofrecer un sacrificio aceptable.
Él es quien le revela al alma sus verdaderas necesidades, y quien se las hace sentir;
y cuando el alma clama, solo Él puede suplirlas.
Las peticiones que no surgen de ese sentido y preparación son formales y ficticias;
no son verdaderas.
Porque los hombres oran en sus propios deseos ciegos y no en la voluntad de Dios,
y Su oído está tapado para tales cosas.
En cambio, por el mero suspiro del pobre y el clamor del necesitado,
Dios ha dicho que se levantará. Sí, por los pobres en espíritu, las almas desesperadas,
aquellos que necesitan Su ayuda, quienes están casi abrumados,
que sienten su necesidad y claman en voz alta por un redentor,
y que no tienen a nadie en la tierra que los ayude,
"`ninguno en el cielo sino a Él, ni nada en la tierra fuera de Él`"^
footnote:[Salmos 73:25 Traducción Literal Inglés]--a estos Él
librará. Redimirá su alma del engaño y la violencia,
y su sangre será preciosa ante Sus ojos.
"`Este pobre clamó, y le oyó Jehová, y lo libró de todas sus angustias.
El ángel de Jehová acampa alrededor de los que le temen, y los defiende.`"^
footnote:[Salmos 34:6-7]
Él invita a todos a venir y probar cuán bueno es Él.
Sí, Él "`bendecirá a los que temen al Señor, a pequeños y a grandes.`"^
footnote:[Salmos 115:13]

Pero, ¿qué es todo esto para aquellos que no tienen hambre?
Los sanos no tienen necesidad de médico; los llenos no tienen necesidad de gemir,
ni los ricos de pedir ayuda.
Aquellos que no son sensibles de sus necesidades internas,
que nunca han sido oprimidos por el miedo y el terror,
ni han sentido la necesidad de que el poder de Dios los ayude,
ni de que la luz de Su rostro los consuele--
¿Qué tienen que ver estos con la oración? Su devoción es,
en el mejor de los casos, una burla al Todopoderoso.
No saben, ni necesitan, ni desean aquello por lo que oran.
Oran para que se haga la voluntad de Dios, y, sin embargo, hacen constantemente la suya.
Piden gracia, pero abusan de la medida que tienen.
Oran por recibir el Espíritu, pero lo resisten en sí mismos, y lo desprecian en otros.
Ruegan por las misericordias y la bondad de Dios,
pero no sienten una necesidad verdadera de ellas.
En esta insensibilidad interna, son tan incapaces de alabar a Dios por lo que tienen,
como de orar por lo que no tienen.
Está escrito, "`Alabarán a Jehová los que le buscan; porque sacia al alma menesterosa,
y llena de bien al alma hambrienta.`"^
footnote:[Salmos 22:26; 107:9]
Esto también esta reservado para los pobres y necesitados,
y para aquellos que temen a Dios.
"`El pobre +++[+++espiritualmente]
y el menesteroso alabarán tu nombre.
Los que teméis a Jehová, alabadle; glorificadle, descendencia toda de Jacob.`"^
footnote:[Salmos 74:21; 22:23]
Jacob era un hombre simple, de corazón recto;
y los que son semejantes a él son su simiente.
Y a pesar de que pueden ser, como Jacob, tan pobres como gusanos en sus propios ojos,
aun así, reciben poder para luchar con Dios y prevalecer como él lo hizo.

Sin la preparación y la consagración que vienen de este poder,
ningún hombre es apto para presentarse ante Dios; de otro modo,
sería un asunto de menos santidad y reverencia adorar a Dios
en el tiempo del Evangelio de lo que era en el de la ley,
cuando todos los sacrificios se rociaban antes de que se ofrecieran y los que
ofrendaban eran consagrados antes de acercarse al Señor. Si tocar a un animal
muerto o inmundo los incapacitaba para servir en el templo o hacer un sacrificio,
o inclusive para socializar con los limpios
hasta que primero fueran rociados y santificados,
¿cómo podemos menospreciar la adoración instituida por
Cristo en los tiempos del Evangelio,
creyendo que permite ofrendas no preparadas ni santificadas?
¿Pueden aquellos, que tocan diariamente
(en sus pensamientos, palabras o acciones) lo que es moralmente inmundo,
adorar apropiadamente al Dios puro sin venir a la sangre de
Jesús que purifica la conciencia de obras muertas?
¡Es una completa contradicción!
Lo inmundo no puede adorar aceptablemente lo que es santo;
ni lo impuro adorar lo que es perfecto.
Hay una unión y comunión santa entre Cristo y Sus seguidores;
pero no hay ninguna en absoluto, entre Cristo y Belial,
entre Él y los que desobedecen Sus mandamientos,
y desprecian Su bendita cruz y la abnegación.

Y al igual que con el pecado, la formalidad no puede adorar a Dios,
incluso cuando la manera de hacerlo sea instituida por Dios.
Esto hizo al profeta clamar,
"`¿Con qué me presentaré ante Jehová, y adoraré al Dios Altísimo?
¿Me presentaré ante él con holocaustos,
con becerros de un año? ¿Se agradará Jehová de millares de carneros,
o de diez mil arroyos de aceite?
¿Daré mi primogénito por mi rebelión, el fruto de mis entrañas por el pecado de mi alma?
Oh hombre, él te ha declarado lo que es bueno, y qué pide Jehová de ti:
solamente hacer justicia, y amar misericordia, y humillarte ante tu Dios.`"^
footnote:[Miqueas 6:6-8]
El profeta real, consiente de esto, invoca a Dios de esta manera: "`Señor,
abre mis labios, y publicará mi boca tu alabanza.`"^
footnote:[Salmos 51:15]
No se atrevía a abrir sus propios labios,
porque sabía que así no podía alabar correctamente a Dios:
"`Porque no quieres sacrificio, que yo lo daría.`"
Si mis ofrendas legales sirvieran,
no las querrías; porque "`No quieres holocausto.
Los sacrificios de Dios son el espíritu quebrantado;
al corazón contrito y humillado no despreciarás tú, oh Dios.`"^
footnote:[Salmos 51:16-17]
Y ¿Por qué? Porque esta es la obra de Dios, el efecto de Su poder;
y Sus propias obras lo alabarán.

Dios Mismo habla algo parecido por medio de la boca de Isaías,
en oposición a las formalidades y a la adoración de boca de los judíos degenerados.
"`Jehová dijo así: El cielo es mi trono, y la tierra estrado de mis pies;
¿dónde está la casa que me habréis de edificar, y dónde el lugar de mi reposo?
Mi mano hizo todas estas cosas, y así todas estas cosas fueron, dice Jehová;
pero miraré a aquel que es pobre y humilde de espíritu, y que tiembla a mi palabra.`"^
footnote:[Isaías 66:1-2]
¡He aquí el verdadero adorador!--uno preparado por Dios, circunciso de corazón y oído,
que no resiste al Espíritu Santo, como lo hicieron aquellos altivos judíos profesantes.
Y viendo que esto era así en aquel entonces,
en el tiempo de la Ley (que fue la dispensación de ceremonias externas y sombrías),
¿podemos esperar aceptación sin la preparación del Espíritu en estos días del Evangelio,
que es el tiempo designado para el derramamiento del Espíritu?
¡De ninguna manera!
Dios sigue siendo lo que era;
y Sus verdaderos adoradores son solo aquellos que lo adoran en Su propio Espíritu puro.
Con estos es tierno como si fuesen la niña de Su ojo;
el resto no hace nada mas que burlarse de Él.

Escuchen lo que sigue inmediatamente en Isaías,
ya que es el estado de la cristiandad en este día:
"`El que sacrifica buey es como si matase a un hombre; el que sacrifica oveja,
como si degollase un perro; el que hace ofrenda, como si ofreciese sangre de cerdo;
el que quema incienso, como si bendijese a un ídolo.
Y porque escogieron sus propios caminos, y su alma amó sus abominaciones.`"^
footnote:[Isaías 66:3]
Que nadie diga ahora:
'`Nosotros no hemos presentado estos tipos de ofrendas,`' porque ese no es el punto.
Dios no se ofendió con las ofrendas,
sino con los que las ofrecían.
Estas eran las formas legales de sacrificio designadas por Dios,
pero puesto que el pueblo no las presentaba en ese estado de espíritu,
ni bajo esa disposición del alma que se requerían,
Dios declaró con mucha intensidad que las aborrecía.

En otro lugar, a través del mismo profeta, les declara,
"`No me traigáis más vana ofrenda; el incienso me es abominación;
luna nueva y día de reposo, el convocar asambleas, no lo puedo sufrir;
son iniquidad vuestras fiestas solemnes.
Vuestras lunas nuevas y vuestras fiestas solemnes las tiene aborrecidas mi alma;
me son gravosas; cansado estoy de soportarlas.
Cuando extendáis vuestras manos, yo esconderé de vosotros mis ojos;
asimismo cuando multipliquéis la oración, yo no oiré.`"^
footnote:[Isaías 1:13-15]
Esta es una denuncia muy terrible de su adoración.
¿Y por qué? Porque sus corazones estaban contaminados.
No amaban al Señor con todo su corazón, sino que quebrantaban Su ley,
se rebelaban contra Su Espíritu y no hacían lo recto delante de sus ojos.
La causa se ve claramente por el remedio que Él prescribe:
"`Lavaos y limpiaos;
quitad la iniquidad de vuestras obras de delante de mis ojos; dejad de hacer lo malo;
aprended a hacer el bien; buscad el juicio, restituid al agraviado,
haced justicia al huérfano, amparad a la viuda.`"^
footnote:[Isaías 1:16-17]

Según estas condiciones y nada más, Él los invita a que se vuelvan a Él,
y les dice que "`si sus pecados fueren como la grana, como la nieve serán emblanquecidos;
si fueren rojos como el carmesí, vendrán a ser como blanca lana.`"^
footnote:[Isaías 1:18]
Tan verdadero es ese notable pasaje del Salmista: "`Venid,
oíd todos los que teméis a Dios, y contaré lo que ha hecho a mi alma.
A Él clamé con mi boca, y fue exaltado con mi lengua.
Si en mi corazón hubiese yo mirado a la iniquidad, el Señor no me habría escuchado.
Mas ciertamente me escuchó Dios; atendió a la voz de mi súplica.
Bendito sea Dios, que no echó de sí mi oración, ni de mí Su misericordia.`"^
footnote:[Salmos 66:16-20]

=== Esperando en el Señor

Mucho se podría citar para demostrar el enojo de Dios,
incluso contra sus propias formas de adoración cuando se realizaban sin Su Espíritu,
y sin esa preparación de corazón necesaria en el hombre, que solo Él puede obrar o dar.
Más que cualquier otro escritor del texto sagrado,
esto más frecuente y enfáticamente nos es recomendado por el ejemplo del Salmista.

David, recordando repetidas veces sus grandes errores y la causa de ellos,
y la forma en la que llegaba a ser aceptado por Dios y a obtener fuerza y consuelo de Él,
frecuentemente se recordaba a sí mismo esperar en Dios.
"`Encamíname en tu verdad, y enséñame, porque tú eres el Dios de mi salvación;
en ti he esperado todo el día.`"^
footnote:[Salmos 25:5]
Su alma tenía la mirada puesta en Dios por salvación,
y para ser librada de las trampas y de los males del mundo.
Esto muestra un ejercicio interno,
una atención espiritual que no consistía en formas externas,
sino en la ayuda divina interna.

Y en verdad, David tenía un gran estímulo para esperarlo,
porque la bondad de Dios lo invitaba a ello, y lo fortalecía allí. Él dice,
"`Pacientemente esperé a Jehová, y se inclinó a mí, y oyó mi clamor.
Y me hizo sacar del pozo de la desesperación, del lodo cenagoso;
puso mis pies sobre peña.`"^
footnote:[Salmos 40:1-2]
El Señor apareció internamente para consolar el alma de David, la cual esperaba Su ayuda,
para ser librada de las tentaciones y aflicciones que estaban a punto de abrumarla,
y para recibir seguridad y paz.
Por lo tanto, dice, "`el Señor estableció mis pasos;`"^
footnote:[Salmos 40:2 RV1602P]
es decir, afirmó su mente en la justicia.

Antes de esto, cada paso que daba David lo hundía en el lodo,
y apenas podía andar sin caerse.
Las tentaciones lo asaltaban por todas partes;
pero él esperaba pacientemente en el Señor con su mente retirada,
vigilante y puesta en la ley y Espíritu de Dios,
sintiendo al Señor inclinado hacia él.
Su clamor sincero y desesperado entró en el cielo y prevaleció,
y entonces vinieron el rescate y la liberación. En el tiempo de Dios, no en el de David,
se le dio fuerza para atravesar sus pruebas y superar todas sus angustias.
Por lo tanto, "`fue puesto en su boca un cántico nuevo, alabanza a nuestro Dios.`"^
footnote:[Salmos 42:3]
Sin duda, este fue un cántico hecho y puesto por Dios, y no por sí mismo.

En otra ocasión, lo encontramos clamando de esta manera:
"`Como el ciervo brama por las corrientes de las aguas, así clama por ti, oh Dios,
el alma mía. Mi alma tiene sed de Dios, del Dios vivo; ¿Cuándo vendré,
y me presentaré delante de Dios?`"^
footnote:[Salmos 42:1-2]
Esto va más allá de la formalidad, y no puede ser el producto de ninguna lección externa.
Con esto podemos ver que la verdadera adoración es una obra interna,
que el alma debe ser tocada y levantada en deseos celestiales por el Espíritu celestial,
y que la verdadera adoración es en la presencia de Dios.
"`¿Cuándo vendré, y me presentaré?`" No en el templo, ni con sacrificios externos,
sino "`delante de Dios`"^
footnote:[Salmos 42:2], en Su presencia.
Las almas de los verdaderos adoradores deben ver a Dios y presentarse delante Él;
y por esto ellos esperan, ellos anhelan esto, y tienen sed de esto.

¡Oh, cuánto se ha degenerado del ejemplo de David la mayor parte del Cristianismo!
Y no es de extrañar, porque este buen hombre nos dice,
"`En Dios solamente espera en silencio mi alma;`"^
footnote:[Salmos 62:1 LBLA]
y le ordena a su alma que así lo haga;
"`Alma mía, espera en silencio solamente en Dios, pues de Él viene mi esperanza.`"^
footnote:[Salmos 62:5 LBLA] Es como si hubiera dicho,
'`Nadie más puede preparar mi corazón o suplir mis necesidades.
Mi esperanza no viene de mis propias obras voluntarias,
ni de la adoración corporal que pueda rendirle--estas cosas no tienen valor;
no pueden ni ayudarme, ni agradar a Dios.
Pero espero en Él por la fuerza y el poder para
presentarme de la manera que más le agrade;
porque Aquel que prepara el sacrificio,
ciertamente lo aceptará.`' En dos versículos repite tres veces,
"`Espero yo en Jehová;`" "`Espera mi alma;`" "`Mi alma espera al Señor,
más que los centinelas a la mañana.`"^
footnote:[Salmos 130:5-6]
Sí, él espera con tanta atención y con tal fervor del alma que en un lugar dice,
"`Han desfallecido mis ojos esperando a mi Dios.`"^
footnote:[Salmos 69:3]
Él no estaba satisfecho con muchas oraciones, con una forma preestablecida de adoración,
ni con mera repetición. No,
no se rindió hasta que encontró al Señor y los consuelos de Su presencia,
lo cual trajo la respuesta de amor y paz a su alma.

Tampoco esto era una práctica exclusiva de David,
por ser un hombre más ungido de lo normal;
porque él habla de ella como la forma de adoración del verdadero pueblo de Dios,
el Israel espiritual, los circuncisos de corazón en su día. "`He aquí,
como los ojos de los siervos miran a la mano de sus señores,
y como los ojos de la sierva a la mano de su señora,
así nuestros ojos esperan en Jehová nuestro Dios,
hasta que tenga misericordia de nosotros.`"^
footnote:[Salmos 123:2 Traducción Literal del Inglés]
En otro lugar dice,
"`Nuestra alma espera a Jehová; nuestra ayuda y nuestro escudo es Él.`"^
footnote:[Salmos 33:20]
Y "`esperaré en Tu nombre, porque es bueno, delante de tus santos.`"^
footnote:[Salmos 52:9]
Esta era la forma por la que los verdaderos piadosos de ese día
llegaron a disfrutar de Dios y a adorarlo de manera aceptable.

Y a partir de su propia experiencia del beneficio de esperar en Dios,
y de la práctica de los santos de esos tiempos, el salmista se lo recomienda a otros,
diciendo, "`Aguarda a Jehová; esfuérzate, y aliéntese tu corazón; sí, espera a Jehová.`"^
footnote:[Salmos 27:14]
Esperen con fe y paciencia, y Él vendrá a salvarlos.
De nuevo, "`Guarda silencio ante Jehová, y espera en Él.`"^
footnote:[Salmos 37:7]
Entréguense completamente a Él; estén contentos,
y esperen a que los ayude en sus necesidades.
Ustedes no pueden ni imaginar cuán cerca está
para ayudar a los que esperan en Él.
Una vez más, nos aconseja, "`Espera en Jehová, y guarda Su camino.`"^
footnote:[Salmos 37:34]
He aquí la razón por la que tan pocos obtienen provecho--están fuera de Su camino,
y tales personas nunca pueden esperar correctamente en Él. En cambio,
David tenía un gran motivo para decir lo que dijo,
pues recibió mucho consuelo y beneficio habiendo
encontrado al Señor en Su bendito camino.

El profeta Isaías nos dice,
que aunque la disciplina del Señor le causaba tristeza al pueblo debido a sus rebeliones,
aun así "`en el camino de Sus juicios,`" es decir,
en el camino de Sus reprensiones y correcciones, "`Lo esperaban;
Su nombre y Su memoria eran el deseo de su alma.`"^
footnote:[Isaías 26:8]
Ellos estaban contentos de ser reprendidos y disciplinados, porque habían pecado;
y el conocimiento de Dios de esta manera les era muy deseable.
Pero, ¿No vino finalmente, y esto en misericordia también? Sí, lo hizo,
y lo reconocieron cuando vino--una experiencia que el mundo carnal no conoce.
"`He aquí, éste es nuestro Dios, le hemos esperado, y nos salvará.`"^
footnote:[Isaías 25:9]
¡Oh bendito gozo! ¡Oh preciosa confianza!
Aquí hubo un esperar en fe que prevaleció.
Toda adoración que no es en la fe
es infructuosa para el adorador como también desagradable para Dios;
cuya fe es don de Dios y su naturaleza opera para purificar el corazón y
para darles a los que verdaderamente creen "`victoria sobre el mundo.`"^
footnote:[1 Juan 5:4]

Pero ellos continúan:
"`hemos esperado por Él, nos gozaremos y nos alegraremos en su salvación.`"^
footnote:[Isaías 25:9]
Y el profeta añade, "`bienaventurados todos los que esperan en Él`"^
footnote:[Isaías 30:18 Reina Valera de Gómez]
¿Y Por qué? Porque "`los que esperan en Jehová tendrán nuevas fuerzas;
levantarán las alas como las águilas; correrán y no se cansarán;
caminarán y no se fatigarán.`"^
footnote:[Isaías 40:31]
El estímulo es grande.
¡Oh escúchenlo una vez más! "`Desde la antigüedad no habían escuchado ni dado oídos,
ni el ojo había visto a un Dios fuera de ti que obrara a favor del que esperaba en Él.`"^
footnote:[Isaías 40:31 LBLA]
¡He aquí la vida y gozo interno de los justos,
los verdaderos adoradores!--aquellos cuyos espíritus se han
sometido a la aparición del Espíritu de Dios en ellos,
dejando y abandonando todo lo que el Espíritu no aprobaba,
y abrazando cualquier cosa a la que los llevaba.

En el tiempo de Jeremías, los verdaderos adoradores también esperaban en Dios,
y él nos asegura que, "`Bueno es Jehová a los que en Él esperan, al alma que le busca.`"^
footnote:[Lamentaciones 3:25]
Del mismo modo, el profeta Oseas exhortó a la iglesia a volverse y esperar en Dios: "`Tú,
pues, vuélvete a tu Dios; guarda misericordia y juicio, y espera siempre en tu Dios.`"^
footnote:[Oseas 12:6 RV1977]
Y Miqueas se muestra muy celoso y resuelto en este buen ejercicio, diciendo:
"`Mas yo a Jehová miraré, esperaré al Dios de mi salvación; el Dios mío me oirá.`"^
footnote:[Miqueas 7:7]
Así hicieron todos los hijos del Espíritu,
quienes estaban sedientos por sentir a Dios internamente.

A Israel se le acusa en el desierto,
como la causa de su desobediencia e ingratitud a Dios, que "`no esperaron Su consejo.`"^
footnote:[Salmos 106:13]
Y podemos estar seguros de que este es nuestro deber, y se espera de nosotros;
porque Dios lo requiere en Sofonías: "`Por tanto, esperadme, dice Jehová,
hasta el día que me levante.`"^
footnote:[Sofonías 3:8]
Oh, que todos los que profesan el nombre de Dios esperen de esta manera,
sin levantarse a adorar sin Él,
sino esperando sentir Sus movimientos y levantamientos
en ellos para prepararlos y santificarlos.
Cristo les mandó expresamente a Sus discípulos que se quedaran en
Jerusalén y esperaran hasta que recibieran la promesa del Padre,
el bautismo del Espíritu Santo,
con el fin de prepararlos para predicar el glorioso Evangelio de Cristo al mundo.
Y aunque eso fue un derramamiento extraordinario para una obra extraordinaria, aun así,
el grado no cambia la regla.
Por el contrario,
si se requería tanta espera y preparación por el
Espíritu para capacitarlos para predicarles a los hombres,
al menos un poco debe ser necesario para capacitarnos a nosotros para hablar con Dios.

Terminaré esta magnífica doctrina bíblica de esperar en el Señor,
con ese pasaje en Juan acerca del estanque de Betesda.
"`Hay en Jerusalén, cerca de la puerta de las ovejas, un estanque,
llamado en hebreo Betesda, el cual tiene cinco pórticos.
En éstos yacía una multitud de enfermos, ciegos, cojos y paralíticos,
que esperaban el movimiento del agua.
Porque un ángel descendía de tiempo en tiempo al estanque, y agitaba el agua;
y el que primero descendía al estanque después del movimiento del agua,
quedaba sano de cualquier enfermedad que tuviese.`"^
footnote:[Juan 5:2-4]
Esta es una representación muy exacta de lo que se intenta exponer
con todo lo que ha sido dicho acerca del asunto de esperar.
Porque, tal como en aquel entonces existía una Jerusalén externa y legal,
ahora hay una Jerusalén espiritual y del evangelio, la iglesia de Dios,
compuesta de los fieles.
El estanque en la antigua Jerusalén, en cierto modo,
representaba esa fuente que ahora se encuentra abierta en la Nueva Jerusalén.
Ese estanque era para aquellos que tenían enfermedades corporales;
esta fuente es para todos los enfermos del alma.
En aquel entonces, había un ángel que agitaba el agua para hacerla efectiva;
ahora el ángel de Dios, el gran Ángel de Su presencia,
es quien bendice esta fuente con éxito.
Los que entraron al estanque antes, sin mirar al ángel ni tomar ventaja de su movimiento,
no encontraron ningún benefició en ello.
Y los que ahora no esperan el movimiento del Ángel de Dios,
sino que con una devoción de su propia concepción y
tiempo corren delante de Dios como caballo a la batalla,
con la esperanza de tener éxito, sin duda, estos tendrán sus expectativas frustradas.

Por lo tanto,
al igual que aquellos que necesitaban y deseaban ser curados en ese entonces,
tenían que esperar con toda paciencia y atención el movimiento del ángel,
asimismo los verdaderos adoradores de Dios ahora lo hacen,
quienes necesitan y oran por Su presencia, la cual es la vida de sus almas,
así como el sol lo es para las plantas del campo.
Estos a menudo han probado la esterilidad de su propia
obra y ahora han llegado al verdadero Día de Reposo.
No se atreven a ofrecer una invención propia, ni una petición no santificada,
mucho menos a imponer una adoración corporal cuando el alma no está realmente
alcanzada ni preparada por el Señor.
En la luz de Jesús esperan ser preparados,
retirados y sacados de todos los pensamientos que causan la más
mínima distracción y desconcentración en la mente,
hasta que se mueve el Ángel, y se despierta su Amado;
porque no se atreven a llamarlo antes de Su tiempo.
Temen inventar una devoción en Su ausencia, porque saben que no solo es infructífero,
sino reprochable: "`¿Quién demanda esto de vuestras manos?`"^
footnote:[Isaías 1:12]
le dijo el Señor a Israel.
"`El que creyere, no se apresure.`"^
footnote:[Isaías 28:16]

Aquellos que adoran con sus propios recursos,
solo pueden hacer lo que hicieron los israelitas--convertir sus zarcillos en
una imagen de fundición y terminan malditos por sus esfuerzos.
Y no les fue mejor a los que recogían leña,
encendían fuego y se rodeaban con las teas que habían encendido; porque Dios les dijo,
"`en dolor seréis sepultados.`"^
footnote:[Isaías 50:11]
Esto no solo es de ninguna ventaja o beneficio para ellos,
sino que también incurre en un juicio del Señor;
dolor y angustia del alma serán su porción. ¡Ay!
La '`carne y sangre`' está muy dispuesta a orar, pero no puede esperar.
Está ansiosa por ser santa, pero no puede soportar hacer ni sufrir la voluntad de Dios.
Con la lengua bendice a Dios, y con ella maldice a los hombres hechos a Su semejanza.
Llama a Jesús Señor, pero no por el Espíritu Santo.
A menudo usa el nombre de Cristo, sí, y se arrodilla también,
pero no se aparta de la iniquidad que es abominable para Dios.

=== Cuatro Cosas Necesarias

Hay cuatro cosas necesarias para adorar a Dios correctamente,
y cada una de ellas hace que la adoración esté fuera del alcance del poder del hombre.
La primera es, la santificación del adorador.
La segunda, la consagración de la ofrenda, de la cual ya hemos hablado.
Tercero, por qué cosa orar--lo cual ningún hombre sabe sin la ayuda del Espíritu de Dios;
y, por lo tanto, sin ese Espíritu, ningún hombre puede orar verdaderamente.
El apóstol pone esto más allá de discusión, diciendo:
"`Pues qué hemos de pedir como conviene, no lo sabemos,
pero el Espíritu nos ayuda en nuestra debilidad.`"^
footnote:[Romanos 8:26]

Los hombres que no conocen la obra y el poder del Espíritu Santo,
no conocen la mente de Dios,
y estos ciertamente nunca pueden agradarlo con sus oraciones.
No es suficiente sólo saber que tenemos necesidad,
porque ¿cómo sabemos si nuestras necesidades no nos fueron
enviadas como una bendición? --desilusiones para el orgulloso,
pérdidas para el codicioso, azotes para el negligente.
Orar que Dios remueva estas cosas sería asegurar nuestra propia destrucción,
no colaborar con la salvación de nuestra alma.

El mundo vil conoce todas las cosas carnalmente,
según una manera e interpretación carnal;
y muchos que desean ser considerados iluminados son propensos a
ponerles nombres incorrectos a estos dones de la providencia.
Por ejemplo, llaman a las aflicciones juicios,
y a las pruebas (que son más preciosas que su amado oro) las llaman miserias.
Por otro lado, al reconocimiento del mundo le ponen el nombre de honor,
y a sus riquezas llaman felicidad.

Por lo tanto, qué conservar, qué rechazar, qué querer,
es una dificultad que solo Dios puede resolver en el alma.
Y puesto que Dios sabe, mucho mejor que nosotros, lo que necesitamos,
Él puede decirnos qué pedir,
mejor de lo que nosotros podemos decirle a Él. Esto hizo que Cristo
exhortara a Sus discípulos a evitar oraciones largas y repetitivas,
diciéndoles que su Padre celestial sabía de qué
cosa tenían necesidad antes que le pidieran.
Por lo tanto, les dio un patrón de oración;
no (como muchos han imaginado) para que sea un texto para las liturgias humanas,
que son tristemente famosas por la duración y la repetición;
sino expresamente para reprobar y evitar tales cosas.

Sin embargo, cómo orar es aún más importante que qué orar;
no es simplemente la petición sino el estado del espíritu del que pide.
El '`qué`' puede ser correcto, pero el '`cómo`' defectuoso.
Como dije, Dios no necesita que le digamos nuestras necesidades; de hecho,
Él debe decírnoslas a nosotros.
Sin embargo, desea que nosotros se las digamos,
para que podamos aprender a buscarlo y para que pueda encontrarse con nosotros.
"`Miraré a aquel,`" dice el Señor.
"`que es pobre y humilde de espíritu, y que tiembla a mi palabra.`"^
footnote:[Isaías 66:2]
Él mira a los enfermos de corazón, a las almas afligidas, a los hambrientos y sedientos,
a los cargados y cansados, a los que sinceramente necesitan de Su ayuda.

Pero incluso estas tres cosas no son suficientes en sí mismas
para completar la verdadera adoración del Evangelio,
porque un cuarto requisito debe tenerse, el cual es la fe--la fe verdadera,
la fe preciosa, la fe que purifica el corazón,
vence al mundo y es la victoria de los santos.
Es esta fe la que vivifica la oración y la hace exitosa,
como en el caso de la persistente viuda que no estaba dispuesta a ser rechazada,
o a quien Cristo le dijo, "`Oh mujer, grande es tu fe.`"^
footnote:[Mateo 15:28]

Sin embargo, esta fe no está en nuestro poder,
porque es don de Dios y debemos recibirla de Él.
Con un grano de ella se logra más,
se experimenta más liberación y se recibe más bondad y misericordia,
que con toda la actividad, el deseo y el esfuerzo del hombre,
con todos sus inventos religiosos y sus prácticas corporales.
Esto, debidamente considerado,
mostrará fácilmente por qué tanta adoración le genera tan poco beneficio al mundo,
como vemos que sucede; porque la verdadera fe se ha perdido.
Ellos piden, pero no reciben; buscan, pero no hallan; tocan la puerta,
pero no se les abre.
El asunto es claro:
sus peticiones no están mezcladas con esa fe purificadora por la cual prevalecerían,
así como el buen Jacob luchó con Dios y prevaleció.

La verdad es que la gran mayoría de los profesantes del
cristianismo todavía están en sus pecados,
siguiendo los deseos de sus corazones y viviendo en
placeres mundanos como extraños a esta fe preciosa.
El autor de los hebreos nos dice que la razón por la que la
palabra predicada al Israel de la antigüedad no tuvo provecho,
fue porque no estaba "`mezclada con fe en aquellos que la oyeron`"^
footnote:[Hebreos 4:2]¿Es posible entonces que un ministro predique sin fe?
No, y mucho menos un hombre puede orar aceptablemente al Dios Todopoderoso sin fe,
especialmente cuando se nos dijo que, "`El justo por la fe vivirá.`"^
footnote:[Romanos 1:17]
Porque la adoración es el acto supremo de la vida del hombre,
y todo lo que sea necesario en actos inferiores de religión, no debe faltar aquí.

Esto debe disminuir el asombro en cualquiera en cuanto a por qué
Cristo tan frecuentemente reprendió a Sus discípulos con las palabras,
"`¡Hombres de poca fe!`"
Sin embargo, nos dice que un grano de ella,
aunque sea tan pequeño como una semilla de mostaza, si es verdadero y correcto,
es capaz de remover montañas. Es como si hubiera dicho,
'`No hay prueba ni tentación demasiado fuerte que la fe no pueda vencer.
Por lo tanto, aquellos que están cautivos por el pecado y las tentaciones,
y todavía sus necesidades espirituales no son suplidas,
deben carecer de esta poderosa fe.`'
Tan necesaria era en la antigüedad,
que Cristo no podía hacer muchas obras milagrosas donde las personas no creían en Él,
aunque Su poder hacía maravillas en otros
lugares en los que la fe había abierto el camino.
De hecho, es difícil decir si era el poder por medio de la fe,
o la fe por medio del poder, lo que hacía el milagro.

"`¿Creéis,`" dijo el Señor "`que puedo abrir sus ojos?`"
"`Sí, Señor,`"^
footnote:[Mateos 9:28]
dijeron los ciegos, y entonces vieron.
Cristo le dijo al gobernante, "`No temas; cree solamente.`"^
footnote:[Lucas 8:50]
Creyó, y su hija muerta recuperó su vida.
A otro le dijo, "`Al que cree todo le es posible`" "`Creo,`" clamó el hombre,
"`ayuda mi incredulidad.`"^
footnote:[Marcos 9:23-24]
Entonces el espíritu inmundo fue echado y el niño se recuperó. Le dijo a uno "`Vete;
tu fe te ha salvado;`"^
footnote:[Lucas 17:19]
y a otra, "`Tu fe te ha salvado; tus pecados te son perdonados.`"^
footnote:[Lucas 7:48, 50] Y a Sus discípulos, "`De cierto os digo, que si tuviereis fe,
y no dudareis, no sólo haréis esto de la higuera, sino que si a este monte dijereis:
Quítate y échate en el mar, será hecho.
Y todo lo que pidiereis en oración, creyendo, lo recibiréis.`"^
footnote:[Mateos 21:21-22]
Solo este pasaje declara culpable a la Cristiandad de gran infidelidad; porque ora,
y no recibe.

Algunos en esta generación incrédula excusarían su falta de fe,
declarando que es imposible adquirir la fe que carecen.
Pero la respuesta de Cristo a la infidelidad de
Su época refutará bien la incredulidad de esta.
"`Lo que es imposible para los hombres, es posible para Dios.`"^
footnote:[Lucas 18:27]
No es imposible para Dios dar fe verdadera, sin embargo,
es cierto que "`sin fe es imposible agradar a Dios.`"^
footnote:[Hebreos 11:6]
Y si es imposible agradar a Dios sin esta fe preciosa,
sin duda debe ser imposible adorar u orar sin ella.

Pero alguien podría decir: ¿Qué es esta fe que es tan necesaria para la adoración,
que da aceptación con Dios y retorna beneficio a los hombres?
Yo digo, es una santa entrega a Dios y una confianza en Él,
que se manifiestan por una obediencia verdadera a Sus mandamientos santos,
y que además proporciona una evidencia segura para el alma de las cosas que no se ven,
y un sentido y sabor de la sustancia de las cosas que se esperan.
Puesto que esta fe es don de Dios, purifica los corazones de todos los que la reciben.^
footnote:[Hechos 15:9]
El apóstol Pablo testifica que ella solo mora en una conciencia pura,^
footnote:[1 Timoteo 3:9 RV1602P]
y en otro pasaje él une un corazón puro junto con la fe no fingida.^
footnote:[1 Timoteo 1:5]
En otro lugar, encontramos la fe vinculada con una buena conciencia.^
footnote:[1 Timoteo 1:19, 1:5]
Santiago une la fe con la justicia, y Juan con la victoria sobre el mundo, diciendo,
"`Esta es la victoria que ha vencido al mundo, nuestra fe.`"^
footnote:[1 Juan 5:4]

Los herederos de esta fe son los verdaderos hijos de Abraham,
aunque incircuncisos en la carne;
porque estos siguen las pisadas de Abraham según la obediencia de la fe.
Esta fe vive por encima del mundo,
a donde ninguno puede llegar salvo a través de la muerte del "`yo,`"
por medio de la cruz de Jesús y la dependencia total en Dios.
Las hazañas de este don divino son famosas y el tiempo no alcanzaría para contarlas todas.
Pero baste decir que, por ella los santos antiguos soportaron todas las pruebas,
vencieron a todos los enemigos, prevalecieron con Dios, mostraron Su verdad,
terminaron su testimonio y obtuvieron la recompensa de los fieles--la corona de justicia,
que es la bendición eterna de los justos.
