== Capítulo VII. El Pecado del Orgullo

Habiendo así aliviado mi conciencia contra ese tipo de yo ilícito que pretende ser cristiano,
creyente y santo,
sin dejar de ser un extraño a la cruz de Cristo y a los santos ejercicios de ella,
y habiendo descrito brevemente la naturaleza de la verdadera adoración,
y el uso y el papel de la santa cruz para hacerla agradable al Dios Todopoderoso;
ahora (si el Señor me ayuda) trataré más ampliamente esa otra parte del yo ilícito,
que llena el estudio, la atención y la conversación del mundo,
presentada en estos tres apetitos capitales: el orgullo, la codicia y la lujuria.
De estos tres fluyen diariamente todas las otras maldades,
como arroyos de sus propias fuentes.
El hacer morir estos males constituye una gran parte de la obra de la verdadera cruz,
abriendo paso a la muy necesaria reforma del hombre en humildad, templanza, amor,
paciencia, mente espiritual y todas las otras gracias del Espíritu.

La atención y el amor de toda la humanidad están dirigidos a Dios o a sí mismos.
Aquellos que realmente aman a Dios por encima de todo,
siempre están humillándose ante Sus mandamientos,
y se aman a sí mismos solo en subordinación a Aquel que es el Señor de todo.
Pero los que han rechazado este amor a Dios, son amadores de sí mismos;
porque todo amor debe centrarse en uno de estos dos.
El apóstol une apropiadamente a este excesivo amor al yo el mal del orgullo y la altivez;
porque, tan pronto como los ángeles abandonaron su amor, deber y reverencia a Dios,
se amaron y se valoraron desmedidamente a sí mismos.
Esto los llevó rápidamente a traspasar los límites de su propia
habitación y a aspirar más allá del orden de su creación. Sí,
fue el orgullo lo que provocó la triste apostasía y lamentable
caída de aquellos que están encerrados en prisiones de oscuridad,
reservados para el juicio del gran día de Dios.

El orgullo, ese peligroso mal,
comúnmente conocido por sus motivaciones y tristes efectos en cada alma no crucificada,
comenzó la miseria de la humanidad.
El orgullo es un excesivo amor al yo,
unido a un menosprecio de los demás y a un deseo de ejercer dominio sobre ellos;
es lo más dañino del mundo.
Hay cuatro cosas por las que el orgullo se ha dado
a conocer de manera evidente a la humanidad,
cuyas consecuencias han traído un grado de miseria acorde con su maldad.
La primera es una excesiva búsqueda de conocimiento.
La segunda, una ambiciosa búsqueda y ansia de poder.
La tercera, un deseo extremo de respeto y estima personal.
Cuarta, el excesivo deseo de posesiones y adornos mundanos.
Al testigo justo y verdadero del Dios eterno, puesto en las almas de todas las personas,
apelo con respecto a la verdad de estas cosas.

Con respecto a la primera,
es manifiesto que un deseo desmedido de conocimiento introdujo la miseria
del hombre y trajo la caída universal de la gloria de su estado primitivo.
Adán deseó ser más sabio de lo que Dios lo había hecho.
No le bastó conocer a su Creador,
ni darle ese santo homenaje al que naturalmente lo llamaba y movía su ser y su inocencia;
tampoco, tener un entendimiento mayor que el de todas las bestias del campo,
las aves del cielo y los peces del mar;
junto con el poder para gobernar sobre toda la creación visible de Dios.
No, también quería ser tan sabio como Dios.
Esta búsqueda injustificable, esta ambición tonta e injusta,
lo hizo indigno de las bendiciones que recibió de Dios.
Lo sacó del paraíso, y en lugar de ser señor del mundo entero,
Adán se convirtió en el vagabundo más miserable de la tierra.

¡Qué triste cambio!
En lugar de ser como dioses, cayeron por debajo de las mismas bestias.
La lamentable consecuencia de esta gran apostasía ha sido el intercambio
de la inocencia por la culpa y del paraíso por el desierto.
Pero lo que es aún peor, en este estado Adán y Eva adquirieron otro dios,
además del único Dios verdadero y vivo.
Aquel que los tentó a toda esta maldad,
los dotó con un conocimiento vano y con una sabiduría
peligrosa--la habilidad de mentir y evadir,
de tergiversar, acusar y excusar.
Perdieron su sencillez y sinceridad;
y de un corazón recto (la imagen en la que Dios lo había hecho),
el hombre se convirtió en una serpiente perversa y retorcida,
la imagen de ese espíritu injusto ante cuyas tentaciones cedió
su obediencia y la felicidad que tenía en el paraíso.

Esto no se limita a Adán;
porque todos los que han quedado cortos de la gloria
de Dios son verdaderos hijos de su desobediencia.
Ellos, como él, han comido de lo que ha sido prohibido.
Han hecho las cosas que no debían hacer y dejado de hacer las cosas que debían hacer.
Han pecado contra esa luz y conocimiento divino que Dios les ha dado.
Han contristado Su Espíritu, y en efecto, la horrible sentencia ha sido ejecutada:
"`El día que de él comieres, ciertamente morirás.`"^
footnote:[Génesis 2:16]
Es decir: '`Cuando hagas lo que no debes hacer, ya no vivirás más en Mi favor,
ni disfrutarás del consuelo y presencia de Mi Espíritu.`' Esto es una muerte
a todos esos deseos y afectos inocentes y santos con los que Dios creó al hombre;
y así, se volvió frío y se entumeció, y llegó a ser insensible al amor de Dios,
a Su Espíritu Santo, poder y sabiduría, a la luz y al gozo de Su rostro,
a la evidencia de una buena conciencia y a la aprobación del Espíritu Santo de Dios.

Habiendo caído, el conocimiento que Adán tenía de Dios,
ya no consistía en la experiencia diaria del amor y la obra de Dios en su alma,
sino en el recuerdo de lo que alguna vez conoció y experimentó.
Al no ser esto la sabiduría verdadera y viva que es de arriba,
sino una mera imagen, no puede preservar al hombre en pureza; sino al contrario,
lo envanece y hace a las personas orgullosas,
altivas e impacientes ante la contradicción. Este era el
estado de los judíos apóstatas antes de que Cristo viniera,
y ha sido la condición de los cristianos apóstatas desde que vino.
Además de la variedad de sus servicios externos, su religión consiste,
ya sea en lo que alguna vez experimentaron de la obra de
Dios en ellos mismos (obra de la cual se han rebelado);
o en una creencia histórica y en una concepción imaginaria de las experiencias
y profecías de esos hombres y mujeres santos de Dios que,
en todas las edades, han merecido el nombre y el reconocimiento de Sus verdaderos hijos.

Dicho conocimiento de Dios no puede ser verdadero,
y por experiencia hallamos que siempre produce frutos completamente contrarios a la
verdadera sabiduría. Porque como "`la sabiduría que es de lo alto es primeramente pura,
después pacífica, amable, y benigna,`"^
footnote:[Santiago 3:17]
así el conocimiento de los hombres degenerados y no crucificados es primeramente impuro.
De hecho, vino por la comisión del mal,
y es sostenido en una conciencia y corazón impuros que desobedecen la ley de Dios,
y diariamente hacen las cosas que no deberían hacer.
Por esto, quedan condenados ante el tribunal de Dios en las almas de los hombres,
donde la luz de Su presencia escudriña las cosas más ocultas de las tinieblas,
los pensamientos más secretos y las inclinaciones
más escondidas de los hombres impíos. Sí,
esta es una sabiduría falsa; y así como es impura, también es hostil, irritable y terca.
Es apresurada, perversa, perseguidora y celosa de que alguien sea mejor,
y luego odia y maltratan a los que lo son.

Fue este orgullo el que convirtió a Caín en un homicida; una característica malévola,
llena de envidia y venganza.
¿Qué? ¿Acaso su religión y adoración no era tan buenas como las de su hermano?
Él tenía todas las partes externas de adoración. Ofrendó tal como lo hizo Abel,
y la ofrenda en sí misma podría haber sido igual de buena;
pero parece que el corazón que la ofreció no lo era.
Desde tiempos muy remotos, Dios ya consideraba la adoración interna del alma.
¿Cuál fue la consecuencia de esta diferencia?
El orgullo de Caín no pudo soportar que su hermano lo superara.
Se enfureció y resolvió reivindicar su ofrenda vengando
su rechazo sobre la vida de su hermano.
Y sin tener en cuenta el afecto natural, o la baja y temprana condición de la humanidad,
bárbaramente manchó sus manos con la sangre de su hermano.

La religión de los judíos apostatas no era mejor; porque habiendo perdido la vida,
el poder y el Espíritu de la ley en el interior,
se envanecieron con el conocimiento que tenían. Sus pretensiones de Abraham,
de Moisés y de las promesas de Dios, en esa condición,
solo sirvieron para elevarlos a un orgullo, arrogancia y crueldad horribles.
No pudieron soportar la verdadera visión cuando vino a visitarlos,
y recibieron a los mensajeros de su paz como si hubieran sido lobos y tigres.

Es notable cómo los falsos profetas, los grandes conspiradores contra los verdaderos,
nunca dejaron de perseguirlos como si ellos fueran los falsos;
y por su influencia sobre los príncipes terrenales, o sobre la pobre multitud engañada,
hicieron de otros hombres los instrumentos de su malicia.
Así fue como un santo profeta fue aserrado, y otro apedreado hasta la muerte, etc.
¡Oh cuán orgulloso y obstinado es el conocimiento falso,
así como todos los que se esfuerzan por alcanzarlo!
De hecho, esto hizo que el santo Esteban clamara: "`¡Duros de cerviz,
e incircuncisos de corazón y de oídos!
Vosotros resistís siempre al Espíritu Santo; como vuestros padres,
así también vosotros.`"^
footnote:[Hechos 7:51]

El conocimiento verdadero vino de arriba con la alegría de los ángeles cantando,
"`en la tierra paz, buena voluntad para con los hombres;`"^
footnote:[Lucas 2:14]
y el conocimiento falso lo recibió con infamia y violencia.
Sí, Lo apedrearon y frecuentemente buscaron matarlo; y en su maldad,
finalmente lo lograron.
Pero, ¿cuál fue su motivo?
Que Él clamaba contra su hipocresía,
contra sus ceremonias sin vida y contra el honor que buscaban de los hombres.
De hecho, ellos mismos dan a conocer su motivo con las siguientes palabras:
"`Si Le dejamos así, todos creerán en Él;`"^
footnote:[Juan 11:48]
'`Quitará nuestro crédito ante el pueblo; se unirán a Él y nos abandonarán,
y así perderemos nuestro poder y reputación ante la multitud.`'

La verdad es que Él vino para abatir su honor y derrocar su orgulloso sistema religioso,
y por Su gracia traer al pueblo a ese conocimiento interno de Dios, del que ellos,
debido a su transgresión, se habían apartado hacía mucho.
Entonces verían el engaño de sus guías ciegos quienes, por sus vanas tradiciones,
habían hecho nula la justicia de Dios,
y estaban tan lejos de ser los verdaderos maestros y expositores vivos de ella,
que en realidad eran hijos del diablo--quien ha sido un orgulloso
mentiroso y un cruel homicida desde el principio.

Al ver cómo su orgullo en el conocimiento falso los había
hecho incapaces de recibir la simplicidad del Evangelio,
Cristo agradece a Su Padre porque había escondido
sus misterios de los sabios y de los entendidos,
y los había revelado a los niños. Esta misma sabiduría
falsa hinchó las mentes de los Atenienses a tal punto,
que despreciaron la predicación del apóstol Pablo como algo vano y tonto.
Pero este apóstol (quien más que los otros apóstoles,
fue educado en el conocimiento de aquellos tiempos),
critica duramente esa sabiduría que los judíos y los griegos valoraban tanto, diciendo:
"`¿Dónde está el sabio? ¿Dónde está el escriba?
¿Dónde está el disputador de este siglo?
¿No ha enloquecido Dios la sabiduría del mundo?`"^
footnote:[1 Corintios 1:20]
Y luego da una buena razón para ello:
"`Para que ninguna carne se jacte en su presencia.`"^
footnote:[1 Corintios 1:29]
Lo cual quiere decir,
que Dios anulará el orgullo de los hombres en su conocimiento falso,
para que no tengan nada de que jactarse,
pues todo dependerá de la revelación del Espíritu de Dios.

De hecho,
el apóstol va aún más allá y afirma que
"`el mundo no conoció a Dios mediante la sabiduría;`"^
footnote:[1 Corintios 1:21]
es decir, la sabiduría del hombre estaba tan lejos de ser una ayuda,
que en la medida que los hombres la usaban,
era un tropiezo para el conocimiento verdadero de Dios.
Y en su primera epístola a su amado Timoteo, concluye de esta manera: "`Oh Timoteo,
guarda lo que se te ha encomendado, evitando las profanas pláticas sobre cosas vanas,
y los argumentos de lo falsamente llamado conocimiento.`"^
footnote:[1 Timoteo 6:20]
Así era en los tiempos de los apóstoles,
cuando la gracia divina daba el conocimiento verdadero de Dios,
y era la guía de los cristianos.

Pero ¿cuánto éxito han tenido las edades que siguieron a los apóstoles?
¿Han superado en algo los tiempos de los judíos? ¡Ay, ni un poco!
De hecho, han excedido a los judíos tanto en sus pretensiones de un conocimiento mayor,
como en su degeneración de la verdadera vida cristiana.
Porque aunque han tenido un Modelo mucho más excelente que el de los judíos,
a quienes Dios habló a través de Moisés Su siervo--a saber, Cristo, el Hijo amado,
la imagen misma de la sustancia del Padre,
la perfección de toda mansedumbre y humildad--y aunque parecían entregados a
la adoración de Su nombre y a la veneración de Sus benditos discípulos y apóstoles;
aun así,
tan grande fue su abandono del poder y vida interior del cristianismo en el alma,
que su reverencia probó ser nada más que formal y ceremoniosa.
A pesar de que ellos, al igual que los judíos,
eran celosos en cuanto a la decoración de sus sepulcros
y se ocupaban en tallar sus imágenes;
con respecto a las cosas grandes e importantes de la ley de vida cristiana--a saber,
el amor, la humildad y la negación al yo--estaban degenerados.
Llegaron a ser altivos, orgullosos, jactanciosos, sin afecto natural,
entrometidos y contenciosos,
todo el tiempo desconcertando a la iglesia con preguntas confusas,
llenando a las personas de disputas, contienda y riña,
atrayéndolas hacia sectas y divisiones hasta que finalmente
cayeron en el derramamiento de sangre.

¡Oh, el estado miserable de estos supuestos cristianos quienes,
en lugar de la doctrina de Cristo y Sus apóstoles de amar
a los enemigos y bendecir a los que los maldicen,
enseñan a las personas (bajo un concepto de celo cristiano)
a matarse el uno al otro de la forma más inhumana!
Y en lugar de sufrir el derramamiento de su propia sangre por el testimonio de Jesús,
derraman la sangre de los testigos de Jesús, llamándolos herejes.
Así, aquella sutil serpiente, o astuto espíritu maligno,
que tentó a Adán a salir de la inocencia,
y persuadió a los judíos a abandonar la ley de Dios,
ha engañado a los cristianos con vanas mentiras para
que se aparten de la ley de santidad cristiana.
En consecuencia, se han vuelto sus esclavos;
porque él gobierna en los corazones de los hijos de desobediencia.

Fue este orgullo (que siempre es seguido por la superstición y la obstinación),
lo que hizo que Adán buscara un estado superior al que Dios le había asignado.
Los judíos, a partir del mismo orgullo,
intentaron superar el patrón sagrado dado por Dios a Moisés en el monte,
enseñando como doctrinas sus propias tradiciones,
a tal punto que aquellos que rehusaban conformarse a ellas corrían el riesgo de muerte.
Asimismo, los cristianos de nombre, a partir del mismo pecado del orgullo,
con gran superstición y arrogancia, han introducido,
en lugar de una adoración y disciplina espiritual,
algo que es evidentemente ceremonioso y mundano,
con sus grandes innovaciones y tradiciones de hombres,
que son el fruto de la sabiduría que es de abajo.

Y tal como este orgullo injustificable,
primero los hizo pervertir la espiritualidad de la adoración
cristiana--haciéndola más parecida a la religión figurativa
de los judíos y a la adoración extravagante de los egipcios,
que a la sencillez y simplicidad de la institución cristiana--así también
el mismo orgullo y arrogancia los ha impulsado a mantener su gran imagen,
por medio de todas las crueldades posibles.
Las súplicas mansas y las protestas humildes de aquellos que se
mantuvieron cerca de la pureza primitiva en la adoración y doctrina,
no pudieron hacer que estos cristianos de nombre dejarán de imponerles sus tradiciones.
Sino que, a medida que los ministros y los obispos de estos
cristianos degenerados se volvían más ambiciosos,
codiciosos y extravagantes (pareciéndose más a la realeza mundana que
a los seguidores abnegados y humildes de espíritu del bendito Jesús),
casi todas las historias nos cuentan con qué orgullo, crueldad, derramamiento de sangre,
matanza y torturas inusuales y refinadas han perseguido a los santos miembros de Cristo.
Los verdaderos cristianos llaman a estos, mártires;
pero el clero (al igual que los judíos perseguidores),
los ha llamado blasfemos y herejes--cumpliendo así
la profecía de nuestro Señor. Sin duda,
estos perseguidores son los lobos que el apóstol predijo que se levantarían entre ellos,
no perdonando al rebaño de Cristo, una vez que comenzara la gran caída;
cuya apostasía fue predicha por él como algo necesario para la prueba
de los fieles y la revelación del gran misterio de la iniquidad.

Concluiré este tema con la siguiente afirmación, que es una verdad innegable:
dondequiera que el clero ha tenido más poder y autoridad,
y la mayor influencia sobre los líderes y el estado, allí ha habido mayor confusión,
contención, derramamiento de sangre, encarcelamientos y exilios.
Para probar esto, apelo el testimonio de los registros de todos los tiempos.
Con respecto a nuestra época, lo dejo a criterio de los que aún viven; sin embargo,
les ofrezco una acusación que difícilmente puede ser cuestionada:
las personas no se han convertido, sino más bien corrompido hasta un grado lamentable.
La adoración del cristianismo es visible, ceremoniosa y extravagante.
El clero ambiciona los honores mundanos bajo el pretexto de promoción espiritual,
haciendo que la ganancia terrenal sea la razón principal de su función. De esta manera,
con su orgullo y avaricia (que el apóstol Pedro previó que serían sus trampas),
han amontado una gran cantidad de ignorancia,
miseria e impiedad sobre el cristianismo de nuestro tiempo.

El camino para recuperarse de esta miserable deserción es
llegar al conocimiento salvador de la verdadera religión,
el cual es la experiencia de la obra divina de Dios en el alma,
obtenida por la obediencia diligente a la gracia de Dios que aparece en tu propia alma.
Esta gracia trae salvación, volviéndote del camino espacioso al camino angosto,
de tus deseos a tu deber, del pecado a la santidad, de Satanás a Dios.
Debes ver y aborrecer el yo.
Debes vigilar, orar y ayunar.
No debes mirar a tu tentador, sino a tu Preservador.
Evita las malas compañías,
retírate a la soledad y sé un peregrino puro en este mundo malvado.
Así llegarás al conocimiento de Dios y de Cristo, que trae vida eterna al alma.

Era la queja de Cristo en la antigüedad, "`que la luz vino al mundo,
y los hombres amaron más las tinieblas que la luz, porque sus obras eran malas.`"^
footnote:[Juan 3:19]
Si deseas ser hijo de Dios y creyente en Cristo, debes ser hijo de la luz.
Debes traer tus obras a ella y examinarlas con esa antorcha santa en tu alma,
que es la lámpara del Señor que te muestra tu orgullo y arrogancia,
y reprueba tu deleite en las modas vanas de este mundo.

La verdadera religión es una continua negación al yo; sí,
y a la religión del yo también. Es un lazo o vínculo firme sobre el alma para la santidad,
cuyo fin es la felicidad,
porque por ella los hombres llegan a ver al Señor.
"`Los de limpio corazón,`" dice Jesús, "`verán a Dios.`"^
footnote:[Mateo 5:8]
El que llega a tomar el yugo de Cristo no se deja llevar por las tentaciones del diablo;
de hecho, encuentra una alegría mucho más grande en su vigilancia y en su obediencia.
Si Adán hubiese atendido más esa luz santa en el paraíso que el anzuelo de la serpiente,
y hubiera fijado su mente en su Creador, el galardonador de la fidelidad,
habría visto la trampa del enemigo y lo habría resistido.
¡Oh, entonces, no te deleites en lo que es prohibido!
No lo mires, si no quieres ser cautivado por ello.
¿Acaso no sometió Cristo Su voluntad a la de Su Padre,
y por el gozo puesto delante de Él,
sufrió la cruz y menospreció el oprobio de un nuevo camino nunca recorrido a la gloria?
Tú también debes someter tu voluntad a la santa ley y luz de Cristo en tu corazón,
y por la recompensa que Él pone delante de ti,
soportar Su cruz y menospreciar el oprobio de ella.
Muchos desean regocijarse con Él, pero pocos están dispuestos a sufrir con Él,
o por Él. Están dispuestos a seguirlo por las tortas de pan,
pero dejan la copa amarga de Su agonía. Sí, muchos magnifican Sus milagros,
aun cuando tropiezan con la humillación de Su cruz.
¡Pero, oh hombre, lo que Él ha hecho por tu salvación,
debes hacerlo por amor a Él! Debes humillarte y estar contento con ser despojado,
para que puedas seguirlo;
no en el camino carnal y formal de la tradición y la instrucción vana del hombre,
sino en "`el camino nuevo y vivo,`"^
footnote:[Hebreos 10:20]
que Jesús ha consagrado.
Todos los que andan por este camino viajan hacia el descanso eterno de Dios,
en el cual Él mismo ha entrado, quien es el santo y único bendito Redentor.

[.asterism]
'''

[.emphasized]
+++[+++La versión original de _No Cruz, No Corona_ continúa
más allá de este punto tratando exhaustivamente con los pecados del orgullo,
la avaricia y la lujuria, describiendo sus muchas ramas y frutos,
y el efecto corruptor que tienen en el corazón del hombre.
La versión completa también está disponible en www.bibliotecadelosamigos.org
o en nuestra aplicación gratuita.]
