== Capítulo I

[.chapter-subtitle--blurb]
Contiene Una Breve Reseña de las Diferentes Dispensaciones de Dios en el Mundo,
hasta el Tiempo en que Le Plació Levantar al Pueblo Llamado Cuáqueros.

Desde la creación del mundo ha habido varias dispensaciones
de Dios para con los hijos de los hombres;
y el gran propósito de todas ellas ha sido el honor de Su propio
y excelente nombre en la creación y restauración del hombre,
que fue hecho a la imagen de Sí Mismo y es la gloria de todas Sus obras.
El mundo comenzó con inocencia,
y todo entonces era bueno como el buen Dios lo había hecho.
Y así como Él bendijo las distintas obras de Sus manos,
asimismo la naturaleza y armonía de ellas magnificaban a su Creador.
En aquel entonces las estrellas del alba, juntas de alegría alababan,
y cada parte de Su obra le decía '`amen`' a Su ley.
No había la menor discordia en toda la creación; sino que el hombre en el paraíso,
las bestias en el campo, las aves en el aire, los peces en el mar,
las luces en los cielos, los frutos de la tierra, sí, hasta el aire, la tierra,
el agua y el fuego, adoraban, alababan y exaltaban Su poder, sabiduría y bondad.
¡Oh, santo Sabbat! ¡Oh, día santo del Señor!

Pero este estado feliz no duró mucho; porque el hombre,
quien era la corona y la gloria de todo,
al ser tentado a aspirar ser algo más allá de su lugar, tristemente cedió,
actuando en contra de su mandamiento y deber,
así como de su propio beneficio y felicidad,
y por lo tanto cayó muy por debajo de su condición original.
De este modo perdió la imagen divina--la sabiduría,
el poder y la pureza en los que fue hecho; y puesto que ya no era apto para el paraíso,
fue expulsado del jardín de Dios (que era su morada y residencia apropiada),
y echado como un pobre vagabundo fuera de la presencia de Dios, a deambular en la tierra,
la habitación de las bestias.

Sin embargo, el Dios que lo hizo le tuvo compasión;
porque vio que el hombre fue engañado, y que no fue por malicia,
sino por la sutileza de la serpiente (la cual había caído primero de su propio estado),
y a través de la mediación de la mujer--que era de su propia naturaleza
y su compañera--a quien la serpiente había engañado primero.
En consecuencia, Dios, en Su infinita bondad y sabiduría,
proporcionó una manera de reparar la brecha,
recuperar la pérdida y restaurar al hombre caído por medio de un Adán más noble y excelente,
el cual se prometió que iba a nacer de una mujer.
Y así como el maligno prevaleció sobre el hombre por medio de una mujer, así también,
el postrer Adán entraría al mundo a través de una mujer,
y prevalecería contra la serpiente,
heriría su cabeza y redimiría al hombre de su poder--todo lo cual fue extraordinariamente
cumplido de manera personal y completa por y en el Hijo de Dios en la carne,
como el Salvador y Redentor del hombre.

Pero la manifestación del poder de Dios a través
de Su Hijo no estaba limitada a ese tiempo;
porque tanto antes como desde Su manifestación bendita en la carne,
Él ha sido la luz y vida, la roca y fortaleza,
de todos los que en cualquier época han temido a Dios.
Él estaba presente con ellos en sus tentaciones, los seguía en sus viajes y aflicciones,^
footnote:[1 Corintios 10:1-4]
y los apoyaba y sostenía a través y por encima de las dificultades
que los acompañaban en su peregrinación terrenal.^
footnote:[Hebreos 11:26]
Fue solo por medio de esto que el corazón de Abel fue más excelente que el de Caín,
que Set obtuvo la preeminencia y que Enoc caminó con Dios.
Esta luz y poder fue lo que contendió con el mundo
antiguo antes del diluvio (contra el cual se rebelaron),
lo mismo que santificó e instruyó a Noé para salvación.

Pero los tratos externos de Dios con el hombre después de su caída,
especialmente entre los patriarcas,
fueron generalmente a través del ministerio de los ángeles;
como los escritos del Antiguo Testamento expresan en muchos lugares, como con Abraham,
Jacob, etc.
Y la siguiente dispensación fue aquella de la ley por medio de Moisés,
la cual también fue entregada por medio de ángeles, como nos dice el apóstol.
Esta dispensación fue muy externa, adaptada a su estado degenerado y servil,
por lo tanto, el apóstol Pablo la llamó la de "`ayo,`"^
footnote:[Gálatas 3:24-25]
porque señalaba y preparaba al pueblo para mirar y anhelar al Mesías,
quien los redimiría de la servidumbre de esa dispensación ceremoniosa e imperfecta,
al experimentar (dentro de sí mismos) las realidades de esas figuras y tipologías misteriosas.
En ese entonces la ley fue escrita en piedras,
y el templo fue hecho con manos y estaba acompañado de un sacerdocio físico,
de ritos externos y de ceremonias, que eran sombras de los bienes venideros.
Pero todo esto solo servía "`hasta que viniese la Simiente,`"^
footnote:[Gálatas 3:19]
es decir, la manifestación más excelente y general de Cristo;
porque a Él fue hecha la promesa, y a todos los hombres solamente en Él,
en Quien la promesa era sí y amén--sí, la promesa de pasar de muerte a vida,
y alcanzar la inmortalidad y la vida eterna.

Los profetas vieron esto de antemano y consolaron a los judíos
creyentes con la certeza de que acontecería. Porque el ministerio
de los profetas era lo más alto de la dispensación Mosaica,
la cual finalizó en Juan, el que le preparó el camino al Mesías;
y el ministerio de Juan terminó en Aquel quien era la plenitud de todo.
Y fue entonces cuando Dios,
quien en diversos tiempos y de muchas maneras había hablado
a los padres por medio de Sus siervos los profetas,
les habló a los hombres por Su Hijo Jesucristo, a quien constituyó Heredero de todo.
Este fue el amanecer del día del evangelio, la dispensación de hijos,
la cual comenzó un pacto mucho más cercano y una mejor esperanza; es decir,
el comienzo de la gloria de los días postreros, y la restauración de todas las cosas; sí,
la restauración del reino a Israel.

Ahora el Espíritu,
que era comunicado con menos frecuencia y en menor medida en las dispensaciones anteriores,
comenzó a derramarse sobre toda carne, de acuerdo con el testimonio del profeta Joel.
Y Dios, por su infinita bondad, hizo que la luz,
que antes resplandecía en las tinieblas (o de manera débil),
resplandeciera fuera de las tinieblas,
y el lucero de la mañana comenzó a levantarse en los corazones de los creyentes,
dándoles el conocimiento de Dios en la faz, o aparición, de Su Hijo Jesucristo.

Y entonces, los pobres de espíritu, los mansos, los que verdaderamente lloraban,
los que tenían hambre y sed de justicia, los pacificadores, los de corazón puro,
los misericordiosos y los que padecían persecución,
vinieron en memoria delante del Señor de manera más especial,
y fueron buscados y bendecidos por el verdadero Pastor de Israel.
La antigua Jerusalén con sus hijos envejeció,
y la nueva Jerusalén se volvió la madre de los hijos del día del Evangelio.
Por lo tanto, Dios ya no quiere ser adorado en la vieja Jerusalén,
ni en el monte de Samaria más que en otros lugares,
porque he aquí que Su propio Hijo declara y predica que Él es Espíritu,
y que así será conocido, y que será adorado en Espíritu y en Verdad.
Ahora Él se acercará más que en los tiempos antiguos, y escribirá Su ley en el corazón,
y pondrá Su temor y Espíritu en el interior, según Su promesa.
Así que, todas las señales, tipos y sombras pasaron,
habiendo el Día descubierto su insuficiencia en no alcanzar el interior de la copa,
para limpiar la conciencia.
Asimismo, todos los servicios rudimentales expiraron en y por Él,
el cual es la sustancia de todo.

Los apóstoles dieron testimonio de esta grande y bendita dispensación del Hijo de Dios,
a quienes el Señor había escogido y ungido por medio de Su Espíritu para
que hicieran volver a los judíos del prejuicio y de la superstición,
y a los gentiles de la vanidad y de la idolatría,
a la Luz y Espíritu de Cristo que brillaba dentro de ellos,
para que aquellos que estaban muertos en sus delitos y pecados recibieran
vida y sirvieran al Dios vivo en la novedad del Espíritu de Vida,
y caminaran como hijos de la luz y del Día. Tales
como estos en verdad se han vestido de Cristo,
la luz del mundo, y no proveen para los deseos de la carne.
Y por lo tanto esta luz, Espíritu y gracia de Dios,
que viene por Cristo y aparece en el hombre,
era el principio divino a partir del cual los apóstoles ministraban,
y al cual volvían las mentes de las personas,
y en el cual reunían y edificaban la iglesia de Cristo en sus días. Y
por esta causa les advertían a todos que no contristaran al Espíritu,
sino que esperaran al Espíritu, hablaran por el Espíritu,
oraran por el Espíritu y caminaran en el Espíritu,
como lo único que probaba que ellos eran verdaderamente hijos engendrados por Dios,
no nacidos de carne, ni de sangre, ni de voluntad de hombre, sino de la voluntad de Dios.
Porque al hacer Su voluntad y negar las suyas,
al beber la copa de Cristo y ser bautizados con Su bautismo,
se experimenta el camino y la senda por la cual todos
los herederos de la vida han viajado hacia la bendición.

Pero ¡ay! ¡incluso en los días de los apóstoles (esas
brillantes estrellas del amanecer del evangelio),
algunas nubes, que predecían un eclipse de esta primera gloria, comenzaron a aparecer!
Varios de ellos les advirtieron anticipadamente a
los cristianos de su tiempo respecto a esto,
diciendo que incluso entonces había (y que aún habría
más y más) una apostasía del poder de la piedad,
y de la pureza de esa dispensación espiritual,
mediante aquellos que buscaban tener una apariencia de justicia en la carne,
pero en quienes se había quitado el tropiezo de la cruz.
Su visión era verdadera;
y lo que les predecían a las iglesias que habían
sido reunidas en el nombre y poder de Jesús,
llegó a suceder; porque los cristianos comenzaron a degenerarse rápidamente,
cayendo en prácticas externas, tales como días, comidas y varias otras ceremonias.
Y lo que es peor, cayeron en contienda y disputa sobre estas cosas,
separándose unos de otros, y envidiándose unos a otros.
Y, según encontraban poder para hacerlo, se persiguieron unos a otros,
ocasionando la vergüenza y escándalo de su común cristianismo,
y un lamentable tropiezo y ofensa para los paganos.
Y luego,
habiendo finalmente obtenido el poder mundano en sus manos (mediante
reyes y emperadores que adoptaron la religión cristiana),
cambiaron el reino de Cristo, que no es de este mundo, a un reino mundano; o,
por lo menos, llamaron al reino mundano que estaba en sus manos, el reino de Cristo.
Entonces, las invenciones y novedades humanas, tanto en la doctrina como en la adoración,
se metieron y amontonaron rápidamente en la iglesia; porque en verdad,
se abrió una puerta para tales cosas por la inmundicia y la carnalidad
que entonces aparecieron entre la generalidad de los cristianos,
quienes habían abandonado la guía del Espíritu manso
y celestial de Dios desde hacía mucho tiempo,
y se habían entregado a la superstición, a un culto voluntario y a una humildad falsa.
Y así como la superstición es ciega,
también es temeraria y furiosa porque todos deben inclinarse ante su celo ciego e insaciable,
o perecer por él. De esta manera, en el nombre del Espíritu,
persiguieron la aparición misma del Espíritu de Dios en otros,
oponiéndose a eso en otros que ellos resistían en sí mismos, a saber, la luz,
gracia y Espíritu del Señor Jesucristo.
Pero esto lo hicieron (como siempre lo hacen), llamándolo herejía, cisma, innovación,
o cualquier otro nombre creíble;
a pesar de que el cristianismo verdadero no permite fundamento ni pretexto
alguno para perseguir a un hombre por cuestiones de mera religión,
siendo por naturaleza manso, gentil y tolerante, y consistiendo en fe, esperanza y amor,
cosas que ningún perseguidor puede tener.
Porque ¿cómo puede un perseguidor creer bien, tener una verdadera esperanza,
o una preocupación caritativa o tierna por otro,
mientras trata de violar la mente de otro,
o de perseguir su cuerpo por asuntos de fe o de adoración a Dios?

Así fue como surgió la falsa iglesia y se montó sobre el trono.
Pero, aunque perdió su naturaleza,
de ninguna manera renunciaría a su buen nombre--La esposa del Cordero,
la verdadera iglesia y madre de los fieles--obligando a todos a recibir su marca,
ya sea en su frente o en su mano derecha; es decir, de manera pública o privada.
Pero ante Dios, ella era Babilonia, la madre de las rameras, la madre de los que,
a pesar de su apariencia y religión externa, habían adulterado y salido del Espíritu,
naturaleza y vida de Cristo, habiéndose hecho vanos, mundanos, ambiciosos, codiciosos,
crueles, etc., los cuales son los frutos de la carne, y no del Espíritu.

Fue en ese momento que la verdadera iglesia huyó al desierto,^
footnote:[Véase Apocalipsis 12:6]
es decir, huyó de la superstición y de la violencia, a un estado retirado,
apartado y solitario--estaba escondida, y, por así decirlo,
fuera de la vista de los hombres, aunque no fuera del mundo.
Y esto demuestra que ella no dependía de su visibilidad anterior
para ser una verdadera iglesia según el juicio del Espíritu Santo;
porque ella era una iglesia tan verdadera en el desierto (aunque no tan visible y radiante),
como cuando estaba en su esplendor anterior.
Se han hecho muchos intentos para regresar de este estado de desierto,
pero las aguas han estado muy altas, y su camino bloqueado;
y muchos de sus excelentes hijos, en diversas naciones y edades,
han caído por la crueldad de la superstición,
debido a que ellos no estaban dispuestos a apartarse de su fidelidad a la verdad.

El tiempo de la reforma dio algunos pasos hacia ello,
tanto en la doctrina como en la adoración y en la práctica.
Pero cualquier avance en la práctica fracasaba rápidamente;
porque la iniquidad fluía libremente, tanto entre los profesantes^
footnote:[La palabra __profesantes__ se usa a través de este libro
para referirse a uno que profesa o afirma una creencia en Cristo.
De la misma manera,
la _profesión_ de una persona se refiere a lo que ellos creen o profesan como la verdad,
y no está relacionado con su empleo.]
de la reforma como entre aquellos de quienes ellos salieron;
de modo que por los frutos de su conducta no podían distinguirse.
Y los hijos de los reformadores (si no los mismísimos reformadores) comenzaron
a buscar la política y poder terrenal para sostener y continuar su reforma,
que había empezado con armas espirituales;
lo cual a menudo he considerado como una de las razones más grandes por las que
la reforma no hizo un mejor progreso en cuanto a la vida y el corazón de la religión.
Porque mientras que los reformadores se mantenían humildes y de mente espiritual,
y confiaban en Dios y lo miraban a Él, y vivían en Su temor,
y no consultaban con carne y sangre, ni buscaban ser libres a su manera,
diariamente se añadían a la iglesia los que habían de ser salvos.
Porque estos, por un tiempo,
se preocupaban más por ser fieles e inofensivos durante
la persecución que por estar a salvo de ella,
teniendo mayor interés en difundir la verdad por medio de su fe y paciencia en la tribulación,
que en tomar el poder mundano de las manos de sus perseguidores.

En cuanto a la doctrina, quedaron cortos en algunas cosas; en otras cosas,
para evitar un extremo, corrían hacia el otro; y en cuanto a la adoración,
había (en general) mucho más de hombre en ella que de Dios.
Ellos reconocían la necesidad del Espíritu, la inspiración y la revelación,
y de hecho basaron su separación y reforma en el
sentido y entendimiento que habían recibido de ello,
en la lectura de las Escrituras de la verdad.
Y este era su lema: La Escritura es el texto, el Espíritu el intérprete,
y cada hombre puede decidir por sí mismo.
Pero aun así había demasiada invención,
tradición y arte humanos que quedaban tanto en la oración como en la predicación;
y también quedaba una autoridad y grandeza mundanas
en sus ministros--especialmente en Gran Bretaña,
Suecia, Dinamarca y en algunas partes de Alemania.
Por lo tanto, Dios vio conveniente en Inglaterra movernos de una cosa a otra,
y humillar el ministerio, de modo que la gente se volvía más estricta en la predicación,
más devota en la oración,
más celosa por guardar el día del Señor y por catequizar a hijos y a siervos,
muchos repitiendo en casa con sus familiares lo que
habían escuchado en el servicio religioso.
Pero a medida que estos crecían en el poder,
se encontraban no solo echando a algunos fuera de sus templos,
sino forzando a otros a entrar en ellos.
Se mostraron rígidos en sus espíritus, en lugar de serios en sus vidas,
y con más inclinación hacia los partidos políticos que hacia la piedad interna;
lo cual dio origen a otro pueblo que todavía era más retirado y vigilante.

Estos no buscaban comunión con todos, ni asociación con la iglesia nacional,
sino que formaban iglesias entre ellos con personas que
estaban dispuestas a ser responsables de sus conductas.
Tenían experiencias muy prometedoras de la obra de la gracia de Dios en sus corazones,
y vivían bajo mutuos acuerdos y pactos de comunión que los mantenían unidos.
Estas personas, al ser de temperamento tierno,
parecían recomendar la religión por los encantos de su amor, misericordia y bondad,
y no por los terrores de sus juicios y castigos;
que el grupo anterior intentó usar como un medio para hacer que
las personas corrieran por miedo a la religión. Ellos además dieron
más libertad para profetizar que aquellos que fueron antes de ellos;
porque admitían que cualquier miembro hablara u orara,
así como su pastor (a quien ellos siempre designaron, y no el magistrado civil).
Y si alguno de ellos sentía la carga de la palabra del Señor,
sin importar cual fuera su oficio, y sin distinción de clero o laico,
tenía la libertad de hablar, incluso si fuera una persona muy simple y sin educación.

Pero ¡ay, incluso estas personas sufrieron una pérdida muy grande!
Porque al degustar el imperio mundano,
el favor de los príncipes y las ganancias que les seguían, se degeneraron demasiado.
Y a pesar de que habían criticado a la iglesia y al ministerio nacional,
y también a su mantenimiento forzado,^
footnote:[Diezmos obligatorios.]
cuando llegó su turno de ser probados,
muchos fueron vencidos por el deseo de honor y ventaja mundanos.
Porque lograron puestos en parroquias lucrativas,
y rápidamente contradijeron sus propios principios; y, lo que es peor,
algunos de ellos se volvieron terribles perseguidores
de otros hombres usando el nombre de Dios,
habiendo apenas salido del mismo horno.

Y esto llevó a muchos un paso más adelante, esto es,
al agua--por otro bautismo--creyendo que no habían sido bautizados según las Escrituras,
teniendo la esperanza de encontrar la presencia y el poder
de Dios que carecían al someterse a esta ordenanza de agua.
Estas personas también estaban a favor de la negación (si
no de la renuncia y censura) no solo de la necesidad,
sino del uso de todo aprendizaje humano en lo que respecta al ministerio,
no buscando nada más que las ayudas y los dones del Espíritu de Dios,
y esas habilidades naturales y comunes para los hombres.

Por un tiempo estos parecían ser como el Juan de antaño;
una luz ardiente y brillante para otras sociedades cristianas.
Ellos eran muy diligentes, simples y serios;
fuertes en la Escritura y audaces en la profesión,
soportando mucho reproche y contradicción. Pero eso que había engañado a otros,
también probó ser su trampa.
Porque fueron corrompidos al saborear el poder mundano,
y se estancaron demasiado en su dispensación de agua,
en lugar de pasar más plenamente a aquella del Espíritu Santo y fuego,
el cual era el bautismo de Aquel que vino con el aventador en Su
mano para limpiar completamente (y no solo en parte) Su era,
y quitar la escoria y la impureza de Su pueblo, y hacer al hombre más fino que el oro.
Por lo tanto, se volvieron altivos, críticos y seguros de su propia justicia,
oponiéndose a aquellos que crecieron más en el Espíritu,
y olvidando los días de su infancia y pequeñez,
los cuales les habían dado algo de belleza verdadera.

Por eso muchos los dejaron,
y también abandonaron todas las iglesias y sociedades visibles,
y anduvieron perdidos de un lado a otro como ovejas sin pastor,
y como palomas sin compañía, buscando a su Amado,
pero sin poder encontrar a Aquel que sus almas amaban más que su supremo gozo.
Algunos llamaron a estas personas "`Buscadores,`" y otros "`la Familia del Amor.`"
Y a medida que se conocían, a veces se reunían,
no para orar o predicar formalmente en tiempos o lugares determinados en sus
propias voluntades (como estaban acostumbrados a hacer en tiempos pasados),
sino más bien, para esperar juntos en silencio;
y según algo se levantaba en alguna de sus mentes que tenía el sabor del Manantial divino,
ellos algunas veces hablaban.
Pero entonces sucedió,
que algunos de ellos no se mantuvieron humildes ni temerosos de Dios,
y después de una abundancia de revelación se exaltaron desmedidamente.
Y por falta de mantener sus mentes en una humilde dependencia en el Único
que había abierto sus entendimientos para mirar las maravillas de Su ley,
corrieron en sus propias imaginaciones.
Entonces, mezclando sus ideas oscuras con las revelaciones divinas,
dieron a luz un nacimiento monstruoso,
para el escándalo de todos los que temían a Dios y esperaban diariamente
por la consolación de Israel en el templo no hecho con manos;
es decir, el judío interior y el circunciso en espíritu.

Estas personas recibieron el nombre de Ranters,^
footnote:[En inglés,
la palabra "`rant`" significa hablar o gritar de una manera salvaje y apasionada.]
debido a sus extravagantes discursos y prácticas.
Porque ellos interpretaron el cumplimiento de la ley que Cristo realizó por nosotros
como si fuera una exoneración de cualquier obligación y deber que la ley nos requería,
diciendo que ahora no era pecado hacer lo que antes era pecado cometer.
Y al declarar que el temor esclavizante de la ley había sido quitado por Cristo,
enseñaban que todas las cosas que el hombre hace son buenas,
si tan solo las hace pensando y estando persuadido de que lo son.
Así, muchos cayeron en prácticas inmundas y escandalosas,
pretendiendo (como excusa) que podían, sin hacer ningún mal,
cometer el mismo acto que para otros era pecado;
porque ellos distinguían entre la acción y el mal de dicha acción
según la dirección de la mente y la intención al llevarla a cabo.
Esto hizo que el pecado sobreabundara por la abundancia de la gracia,
pues convirtió la gracia de Dios en libertinaje,^
footnote:[Judas 1:4]
al ofrecer un pretexto para pecar más seguro que antes--como
si Cristo no hubiera venido a salvarnos _de_ nuestros pecados,
sino _en_ nuestros pecados; no a _quitar_ el pecado,
sino para que pudiéramos pecar más libremente a Su cargo,
y con menos peligro para nosotros mismos.
Este engaño atrapó a muchos y los llevó a sufrir una profunda
y lamentable pérdida con respecto a su estado eterno.
Estas personas se convirtieron en una gran molestia para la mejor clase de personas,
y le dieron a la clase más ligera una oportunidad para blasfemar.
