== Capítulo II

[.chapter-subtitle--blurb]
El Primer Instrumento, y el Surgimiento del Pueblo llamado Cuáqueros.

Fue en este mismo tiempo que al Dios eterno,
sabio y bueno le plació (por Su infinito amor) honrar y visitar desde
lo alto a esta nación oscura y desconcertada con Su gloriosa aurora,
trayendo un sonido más seguro y certero de la Palabra de luz y vida,
a través del testimonio de un vaso escogido, para un propósito eficaz y bendito,
por el cual muchos miles pueden decir '`¡Gloria sea al nombre del Señor para siempre!`'

El primer instrumento o persona por quien Dios comenzó a reunir
a este pueblo en la verdad que ahora profesan fue George Fox,
cuyas muchas excelentes cualificaciones demostraban que un poder divino, y no humano,
había sido su origen.
Y no teniendo deseo de exaltar a la criatura,
sino de magnificar al Dios que obró poderosamente en y a través de él,
declararé (según Dios me lo haga posible) quién y qué era;
no solo por el reporte de otros,
sino a partir de mi propia amplia y muy íntima relación y conocimiento de él.

George Fox nació en Leicestershire, en el año 1624.
Descendió de padres honestos,
que se esforzaron por criarlo de acuerdo con la forma
y al modo de adoración de la iglesia nacional,
tal como hicieron con el resto de sus hijos,
siendo su madre una mujer muy virtuosa más que la mayoría de su
nivel en el lugar donde vivía. Pero desde niño era evidente que
él tenía una mentalidad diferente a la del resto de sus hermanos,
puesto que era más religioso, interno, quieto, sobrio y observador de lo común a su edad,
lo cual era notorio por las respuestas que daba y por las preguntas que hacía,
que asombraban a aquellos que lo oían, especialmente acerca de cosas divinas.

Su madre, notando que su conducta no era común, y percibiendo la seriedad,
la sabiduría y la piedad que resplandecían a través de él a una edad muy temprana,
y cómo rechazaba los juegos y compañías infantiles y vanos, incluso cuando era muy joven,
fue tierna e indulgente con él,
de modo que se encontró con poca dificultad de parte de ella.
En cuanto a su empleo, fue criado en los negocios del campo.
El cuidado de las ovejas era lo que más disfrutaba, y era muy hábil con ellas;
un empleo muy adecuado para su mente en diversos aspectos,
primero por su inocencia y soledad,
y segundo por ser un emblema idóneo del ministerio y servicio que tuvo más adelante.

Cuando tenía un poco más de veinte años de edad,
dejó a parientes y visitó a las personas más retiradas y religiosas de aquellos lugares;
porque había algunos en esta nación que esperaban noche y día la consolación de Israel,
así como Zacarías, Ana y el buen viejo Simeón lo hicieron en la antigüedad.
Él fue enviado a tales como estos, y a estos buscaba en los condados cercanos,
y entre ellos permaneció hasta que le fue dado un ministerio más extenso.
Durante este tiempo enseñó y fue un ejemplo del silencio,
esforzándose por sacar a las personas fuera de todos los
servicios que se realizaban por la fuerza del hombre.
Él les testificaba de la Luz de Cristo dentro de ellos, y los volvía hacia ella,
animándolos a esperar con paciencia,
y a desear sentir el poder de Cristo moviéndose en sus corazones,
a fin de que su conocimiento y adoración de Dios estuvieran
fundados en el poder de una vida indestructible.
Este poder debía encontrarse en la luz,
y tenía que obedecerse en todas sus manifestaciones en el hombre;
porque en la Palabra está la vida, y esa vida es la luz de los hombres, y, por lo tanto,
a medida que la luz se obedece, también se convierte en vida en los hombres.
Y a medida que los hijos de la luz viven por la vida de la Palabra,
son engendrados nuevamente para Dios,
lo cual es la regeneración o el nuevo nacimiento
sin el cual ninguno puede entrar en el reino de Dios.
Más el que entra por esta puerta es mayor que Juan; es decir,
mayor que la dispensación de Juan, que no era la del reino, sino la del fin de la ley,
que preparó el camino para los tiempos del evangelio.
En consecuencia, se formaron varias reuniones en esos lugares;
y así empleó su tiempo durante algunos años.

En 1652, estando en su retiro habitual con su mente puesta en el Señor,
en una montaña muy alta en algunas de las partes más altas de Yorkshire,
tuvo una visión de la gran obra de Dios en la tierra,
y de la manera en que debía manifestarse en un ministerio público para comenzarla.
Vio una gran cantidad de personas, tantas como el polvo en un rayo de sol,
que con el tiempo serían llevadas de regreso a casa, al Señor,
para que pudiera haber solo un pastor y un rebaño en toda la tierra.
Allí sus ojos fueron dirigidos hacia el norte,
y vio de antemano que muchas personas en esos lugares lo recibirían a él y su mensaje.
En esta montaña,
fue movido por el Espíritu a proclamar el día grande y manifiesto del Señor,
como si hubiera estado en un gran auditorio; y de allí partió al norte,
tal como el Señor le había mostrado.
Y en cada lugar al que llegaba, si no antes de que llegara,
el Señor le mostraba su ejercicio y servicio particulares,
de modo que Él en verdad era su líder.
Y no era en vano que viajaba, porque Dios, en la mayoría de los lugares,
sellaba su comisión con el convencimiento de algunos de todas las clases,
desde los peores pecadores hasta los más sobrios profesantes de religión.

Algunos de los primeros y más eminentes de aquellos que surgieron en un ministerio público,
y quienes ahora descansan, fueron: Richard Farnsworth, James Nayler, William Dewsberry,
Thomas Aldam, Francis Howgill, Edward Burroughs, John Camm, John Audland,
Richard Hubberthorn, Thomas Taylor, Thomas Holmes, Alexander Parker, William Simson,
William Caton, John Stubbs, Robert Withers, Thomas Low, Josiah Coale, John Burnyeat,
Robert Lodge, Thomas Salthouse,
y muchos más hombres honorables que no pueden ser nombrados aquí. Estos,
después de experimentar un tiempo del juicio purificador de Dios en sí mismos,
y una espera en silencio en Él para sentir y recibir poder desde lo alto a fin
de hablar en Su nombre (lo cual ninguno puede hacer correctamente de otra manera,
aunque puedan usar las mismas palabras), sintieron sus movimientos divinos,
y eran llevados frecuentemente a reprobar, informar y exhortar a las personas.
Algunas veces en mercados, en ferias, en calles y al lado de carretera,
llamaban a las personas al arrepentimiento,
y a que se volvieran al Señor con todo su corazón y fuerza,
dirigiéndolos a la luz de Cristo dentro de ellos, a través de la cual podían ver,
examinar y considerar sus caminos,
y así apartarse del mal con el fin de hacer la buena y agradable voluntad de Dios.
Estos pasaron por grandes apuros por su amor y buena voluntad,
siendo a menudo puestos en el cepo, apedreados, golpeados, azotados y encarcelados,
a pesar de que eran hombres honestos y de buena reputación donde vivían,
quienes habían dejado esposas, hijos,
casas y tierras para visitar la nación con un llamado vivo al arrepentimiento.
Y aunque los sacerdotes en general se juntaban para oponerse a ellos,
y escribían en su contra e inventaban las más falsas y escandalosas historias para difamarlos,
incitando a los magistrados a reprimirlos, especialmente en esos lugares del norte,
sin embargo,
a Dios le plació llenarlos con Su vivo poder y concederles
una gran capacidad de hablar en Su servicio,
que hubo un gran convencimiento en esos lugares.

Pero volviendo a este excelente hombre, cuyas cualidades naturales,
morales y espirituales aparecían manifiestamente en su comunión
con los hermanos y en la iglesia de Dios.

El fue un hombre que Dios dotó con una profundidad clara y maravillosa,
teniendo la capacidad de discernir los espíritus de otros hombres,
habiendo aprendido a mantener su propio espíritu en servidumbre.
Y aunque su entendimiento de las cosas (y especialmente su manera de expresarlas)
tal vez sonara inculto y poco elegante para los oídos más refinados,
aun así, la sustancia de sus palabras era impactante, instructiva y profunda.
Y en verdad,
el hecho de que ningún arte ni habilidad naturales tuvieron
lugar en la sustancia o en el modo de su ministerio,
demostraba más allá de toda contradicción que Dios lo había enviado.
Sí,
las muchas verdades excelentes y necesarias que predicaba a la humanidad no tenían nada
del ingenio o sabiduría del hombre como para ser recomendadas por ello.

Como hombre era original, pues no era copia de ninguno;
y su ministerio y escritos mostraban que venían de uno que no era enseñado por hombre,
ni había aprendido lo que decía por el estudio.
Tampoco estas doctrinas fueron nociones o especulaciones,
sino verdades palpables y prácticas que tienden a la conversión y regeneración,
y al establecimiento del reino de Dios en los corazones de los hombres.
En verdad,
muchas veces he sido alcanzado profundamente en mi corazón y llevado
a decir con mi Señor y Maestro estando en una ocasión parecida,
"`Gracias te doy, oh Padre, Señor del cielo y de la tierra,
porque escondiste estas cosas de los sabios y prudentes de este mundo,
y las has revelado a los niños.`"^
footnote:[Mateo 11:25; Lucas 10:21 RV 1602 Purificada]
Porque, muchas veces mi alma se ha inclinado agradeciendo humildemente al Señor,
por no haber escogido a ningún sabio y entendido de este mundo como el
primer mensajero de Su bendita verdad a los hombres en nuestra época;
sino que tomó a uno que no era de un alto rango, ni tenía un lenguaje elegante,
ni era un erudito según el modo de este mundo,
con el fin de que su mensaje y obra pudieran manifestarse sin atraer
la atención y envidia de la sabiduría e interés humanos,
y con más fuerza y claridad en la consciencia de aquellos que sinceramente
estaban buscando el camino de la verdad.

Sí,
al contemplar con el ojo de mi mente (que el Dios de los
cielos había abierto en mí) las señales visibles de la mano
de Dios en este testimonio--que se manifestaban por la claridad,
el poder y la eficacia del mismo en la extraordinaria sobriedad, simpleza, celo, firmeza,
humildad, templanza,
caridad y cuidado diligente en el gobierno de los asuntos de la iglesia,
que brillaban en la vida y testimonio de este hombre--me confirmaron grandemente
que era de Dios y sumergieron mi alma en un profundo amor,
temor, reverencia y gratitud por Su amor y misericordia para con la humanidad.

En su ministerio,
George Fox se esforzaba mucho por revelar la verdad al entendimiento de las personas
y por establecerlas sobre el único fundamento estable--Jesucristo la luz del mundo;
para que (al llevarlos a experimentar el don de Dios en sí mismos)
pudieran conocer y juzgar mejor lo concerniente a Él y a sí mismos.
Y, en verdad,
él tenía un don extraordinario para revelar las Escrituras.
Él llegaba hasta el meollo de las cosas y mostraba la mente,
armonía y cumplimiento de ellas con mucha claridad,
generando mucho consuelo y edificación. Hablaba mucho
del misterio del primero y segundo Adán,
de la caída y la restauración, de la ley y el evangelio, de las sombras y la substancia,
del estado de siervo y de Hijo,
y del cumplimiento de las Escrituras en Cristo y por Cristo en todos los que son de Él,
a través de la obediencia de la fe.
Y realmente se sentía que hablaba solo lo que había
recibido de Cristo y era su propia experiencia,
en ese Espíritu que nunca erra ni se equivoca.

Pero, sobre todo,
se destacaba en la oración. La realidad interna y genuina de su espíritu,
la reverencia y la solemnidad en su manera de comportarse y dirigirse a Dios,
y la brevedad y plenitud de sus palabras,
frecuentemente han golpeado incluso a los extraños
con admiración. Debo decir que la actitud más impactante,
viva y reverente que alguna vez haya sentido o visto era la de él cuando oraba.
Y de verdad esto era un testimonio de que conocía
y vivía más cerca del Señor que otros hombres;
porque los que más Lo conocen,
sienten una mayor necesidad de acercarse a Él con temor y reverencia.

Tenía una vida inocente, no era un entrometido ni uno que buscaba lo suyo propio.
No era ni delicado ni crítico, y lo que salía de su boca era irreprochable y edificante.
Él era tan manso, alegre, modesto, fácil de tratar, firme y tierno,
que era un placer estar en su compañía. No ejercía ninguna autoridad
sino sobre el mal y esto lo hacía en todas partes y con todos,
pero con amor, compasión y mucha paciencia.
Era un hombre muy misericordioso, siempre estaba dispuesto a perdonar,
y era casi imposible que se ofendiera o que agraviara a alguien.
Miles pueden realmente decir que era de un excelente
espíritu y de un grato olor entre ellos,
y por eso los espíritus más excelentes lo amaban con un amor no fingido e inmarcesible.

Él era un obrero incesante.
En sus años de juventud (antes de que sus muchos,
grandes y profundos sufrimientos y viajes hubieran debilitado
demasiado su cuerpo para los servicios itinerantes),
hizo una gran labor en Inglaterra, Escocia e Irlanda, convirtiendo a muchos a Dios,
confirmando a aquellos que estaban convencidos de la verdad,
y estableciendo buen orden en los asuntos de la iglesia.
Y cerca del final de sus viajes de servicio, entre los años 1671 y 1677,
visitó las iglesias de Cristo en las colonias de América, en las Provincias Unidas,
y en Alemania, para el convencimiento y consuelo de muchos.

En su servicio a Dios y a Su pueblo se mostró inagotable y valiente,
y fue muy grande el cuidado que asumió en los asuntos de la iglesia en general.
Y aunque no había ninguna persona a quien los descontentos atacaran con más resentimiento,
no había manera de provocar que este buen hombre sintiera temor o ira.
Él soportaba toda la debilidad y prejuicio de ellos, y no devolvía mal por mal;
perdonando muchos comentarios tontos y ofensivos, y orando por sus enemigos,
para que pudieran tener un sentido de su condición, y volverse a la Luz del mundo.

Y en verdad debo decir que,
aunque Dios lo había revestido visiblemente con preferencia y autoridad, aun así,
él nunca abusó de ello;
sino que mantuvo su lugar en la iglesia de Dios con gran mansedumbre,
y en maravillosa humildad y moderación. Porque en
todas las ocasiones fue un siervo de todos,
sosteniendo y ejerciendo su posición de anciano en
el poder invisible que había reunido a este pueblo.
Sí, su autoridad era interna y no externa, y la obtuvo y mantuvo por el amor de Dios,
y en el poder de una vida indestructible.
Escribo lo que sé y no un reporte; y mi testimonio es verdadero;
habiendo estado con él durante semanas y meses en muchas ocasiones, sí,
incluso en las circunstancias más estresantes y difíciles.
Y puedo decir, que de noche y de día, por el mar y por la tierra,
en este país y en los países extranjeros, nunca lo vi fuera de su lugar,
o no estando a la altura de cada servicio y situación.
Porque en todas las cosas se portaba varonilmente,
sí, como un hombre fuerte, un hombre nuevo y de mente celestial,
la hechura del Dios Todopoderoso.

Pero ahora regreso al amanecer de este gran día del evangelio en la nación de Inglaterra,
donde muchos fueron rápidamente reunidos por el brazo del Señor
y llevados a una verdadera experiencia de la luz y vida de Cristo,
tanto a través del ministerio de George Fox como el de otras personas honorables,
tanto en hombres como mujeres, quienes habían sido levantados por el mismo poder.
Y en la medida que el ministerio de ellos alcanzaba la conciencia,
quebrantaba el corazón y llevaba a muchos al sentido y entendimiento de que aquello
que habían buscado en vano externamente (con mucho esfuerzo y costo) se encontraba adentro,
a saber, el camino correcto para la paz con Dios.
Porque estos fueron dirigidos a la luz de Jesucristo en su interior,
como la Semilla y Levadura del reino de Dios que está cerca de todos,
porque está sembrada en todos,
siendo el don o talento de Dios dado a todos como un Testigo fiel y verdadero,
un Monitor de justicia en cada pecho.
Este es el don y gracia de Dios que se ha manifestado a todos para dar vida y salvación,
aunque pocos le prestan atención; lo cual el cristiano tradicional,
estando seguro de sí mismo, siendo fuerte en su propia voluntad y justicia,
y estando dominado por un celo y pasión ciegos, lo
ha despreciado como algo pequeño y común, o rechazado como si fuera una novedad.
Sí,
los profesantes del cristianismo le han puesto a este don
celestial muchos nombres duros y términos abusivos;
negando, en sus mentes ignorantes y enojadas,
la posibilidad de que haya alguna manifestación fresca del
poder y Espíritu de Dios en el hombre en estos días,
a pesar de que ahora es más necesaria que nunca para producir verdaderos cristianos.
Estos no son diferentes a esos judíos de la antigüedad,
los cuales rechazaron al Hijo de Dios aun cuando profesaban ciegamente
esperar a su Mesías. Porque ¡ay! Él no apareció entre ellos de
acuerdo con sus mentes y expectativas carnales.

Asimismo, la apariencia de este ministerio en Inglaterra provocó muchos libros abusivos,
causando que algunos se llenaran de envidia, y otros de ira,
y haciendo que el camino y progreso de este testimonio bendito fuese verdaderamente
estrecho y angosto para aquellos que lo recibían. Sin embargo,
Dios reconocía Su propia obra, y este testimonio alcanzó, reunió,
consoló y estableció a los cargados y cansados, a los hambrientos y sedientos,
a los pobres y necesitados, a los que lloraban y estaban enfermos,
quienes habían gastado todo lo que tenían en médicos nulos,
y esperaban alivio solo del cielo.
Porque muchos de estos fueron llevados a ver,
después de un examen sincero de todas las demás cosas,
que solamente Cristo podría hacerlo--la luz de Su rostro, un toque de Su manto,
la ayuda de Su mano, quien había curado el flujo de la pobre mujer,
resucitado al siervo del centurión,
al hijo de la viuda y a la hija de un hombre principal.
Y al igual que la suegra de Pedro,
apenas sintieron Su poder y eficacia sobre sus propias almas,
inmediatamente se entregaron a obedecerlo como un testimonio de Su poder,
lo cual hicieron con voluntades rendidas y corazones fieles, a pesar de toda la burla,
contradicción, saqueo de sus bienes, palizas,
prisiones y muchos otros peligros que los acompañaban por amor de Su bendito nombre.

Y, en verdad, sus persecuciones fueron muchísimas y muy grandes; de modo que,
según toda probabilidad humana,
debieron haber sido tragados rápidamente por las orgullosas
y furiosas olas que se hinchaban y los golpeaban,
pero el Dios de todas sus misericordias estuvo con ellos en Su gloriosa autoridad.
Porque en verdad,
los montes a menudo huían y los collados se derretían ante el poder que los llenaba,
el cual actuaba poderosamente por ellos,
así como en ellos--lo externo siempre surgiendo de lo interno.
Y con esto vieron claramente, para su grandísima confirmación y consuelo,
que todas las cosas eran posibles por medio de Aquel a quien tenían que dar cuenta.
Y aunque lo que Dios requería parecía contradecir
la sabiduría humana y exponerlos a la ira del hombre,
sin embargo, Él aparecía para ayudarlos y sostenerlos a través de todo para Su Gloria.

Fue tanto así que, si alguna vez algún pueblo pudo decir en verdad,
'`Tú eres nuestro sol y nuestro escudo, nuestra roca y santuario;
y por Ti hemos saltado murallas, y por Ti hemos desbaratado ejércitos,
y por Ti hemos puesto en fuga a los ejércitos extranjeros`'--este
pueblo tenía el derecho de decirlo.
Y a medida que Dios redimía sus almas de las pesadas cargas del pecado y la vanidad,
y enriquecía su pobreza de espíritu,
y satisfacía su gran hambre y sed de justicia eterna,
y los llenaba con los bienes de Su propia casa,
y los hacía administradores de Sus multiformes dones,
en esa medida ellos iban a todos los rincones de estas naciones para declarar
lo que Dios había hecho por ellos--lo que habían encontrado,
y dónde y cómo lo habían encontrado, esto es: El camino a la paz con Dios;
invitando a todos a venir y ver, y a probar por sí mismos,
la verdad de lo que les declaraban.

Y puesto que ellos daban testimonio de la luz, gracia o Espíritu de Dios en el hombre,
la perla preciosa y la levadura del reino,
como el único medio bendito designado por Dios para vivificar,
convencer y santificar al hombre; ellos, por lo tanto,
les revelaban a otros lo que este don era en sí mismo,
explicándoles para qué se les dio y cómo podían diferenciarlo
de su propio espíritu y de la aparición sutil del maligno.
Además,
mostraban lo que haría por todos los que volvieran sus mentes de la vanidad del mundo,
y de sus caminos y maestros sin vida,
y se aferraran a la bendita luz de Cristo en su interior,
la cual descubre y condena el pecado en todas sus manifestaciones,
y muestra cómo vencerlo,
en todos los que prestan atención y obedecen sus santas manifestaciones y reprensiones.
Porque a estos les da poder,
tanto para evitar como para resistir aquellas cosas que no agradan a Dios,
y para crecer fuertes en el amor, la fe y las buenas obras.
De este modo, el hombre, a quien el pecado ha hecho como un desierto,
totalmente lleno de espinos y de cardos, puede llegar a ser como el huerto de Dios,
cultivado por Su poder divino y adornado con las
plantas más virtuosas y hermosas que Dios mismo sembró,
para Su alabanza eterna.

Pero estos experimentados predicadores de las buenas
nuevas de la verdad y del reino de Dios,
no podían correr cuando querían, ni orar o predicar cuando les parecía,
sino solo cuando Cristo su Redentor los preparaba
y los movía por Su propio y bendito Espíritu.
Era por esto, que esperaban en sus servicios y reuniones,
y sólo hablaban según Él les daba que hablasen,
lo cual los hizo hablar como quienes tenían autoridad,
y no como los fariseos secos y formales.
Y, por lo tanto, se manifestó claramente para todos los que eran serios,
cuyo ojo espiritual el Señor Jesús había abierto en alguna medida,
que a uno le era dada la palabra de exhortación, a otro la palabra de reprensión,
a otro la palabra de consolación, y todo por el mismo Espíritu, en Su buen orden,
para el convencimiento y la edificación de muchos.

Y, en verdad,
estos ministros del evangelio se hicieron fuertes y valientes por medio de la fidelidad,
y por el poder y Espíritu del Señor Jesús se volvieron muy fructíferos.
En poco tiempo,
miles fueron convertidos a través de su testimonio de la verdad en el interior,
habiendo sido compungidos de corazón tanto por su ministerio como por sus sufrimientos;
al punto de que, en la mayoría de los condados,
y en muchas de las ciudades de Inglaterra, se establecieron reuniones,
y eran añadidos cada día a la iglesia los que habían de ser salvos.
Porque ellos se ocuparon con diligencia en plantar y regar,
y el Señor bendijo sus labores con un incremento extremadamente grande,
a pesar de toda la oposición que surgió mediante falsos rumores,
calumnias y cruda persecución--no solo de parte de los poderes de la tierra,
sino de cualquiera que deseaba injuriarlos y abusar de ellos.
Así parecían "`como pobres ovejas contadas para el matadero,
y como un pueblo puesto a muerte todo el día.`"^
footnote:[Romanos 8:36 LBLA]

Sin duda, relatar la amplitud de sus crueles sufrimientos llenaría muchos volúmenes,
puesto que recibieron escarnio y abusos de parte de religiosos y de paganos,
de magistrados como también de la muchedumbre.
De hecho, se puede decir de este pueblo maltratado y despreciado,
que "`iban andando y llorando, sembrando con lágrimas,
llevando el testimonio de la preciosa Semilla,`"^
footnote:[Salmos 126:6]
sí, de la Semilla del reino, la cual no consiste en palabras (no,
ni en las más refinadas y elevadas que el ingenio
del hombre pueda usar) sino en poder--a saber,
el poder de Cristo Jesús,
a quien Dios el Padre le ha dado toda potestad en el cielo y en la tierra,
para gobernar a los ángeles arriba y a los hombres abajo.
Fue este Jesús el que les dio poder, como se veía claramente por sus obras, porque,
a través de su ministerio, multitudes fueron convertidas de las tinieblas a la luz,
y del camino ancho al camino angosto de vida y de paz,
llevando a muchos a una conducta sobria, seria y piadosa,
lo cual era la práctica de esa doctrina que ellos enseñaban.

Sin embargo,
su estricta conformidad a los dictados de la Verdad y a
esa luz que manifiesta todas las cosas que son reprobadas,^
footnote:[Efesios 5:13 RVG "`Pero todas las cosas que son
reprobadas son hechas manifiestas por la luz,
porque lo que manifiesta todo, es la luz.`"]
les dio una apariencia que era extraña y desagradable para muchos,
quienes los consideraban como gente que "`trastorna el mundo entero.`"^
footnote:[Hechos 17:6]
Y, en cierto sentido, sí lo eran,
pero no de una manera diferente a esa por la que Pablo fue acusado, a saber,
por tratar de traer las cosas de regreso a su primer y correcto orden.
Porque su conducta y práctica inusuales no eran el
resultado de la fantasía o presunción personal,
o de algún deseo de distinción civil, como algunos han imaginado;
sino el fruto de un sentido interno que Dios había
engendrado en ellos por medio de Su santo temor.
Ellos no estaban buscando cómo contradecir el mundo,
o cómo distinguirse como un grupo particular y distinto de los
demás (no teniendo deseos de apoyar ni la división ni la novedad).
Sino que habiendo recibido una visión verdadera de sí mismos,
vieron al mundo entero a través del mismo lente de la verdad.
Sí, discernieron claramente los afectos y pasiones de los hombres,
y el origen y tendencia de las cosas;
entendiendo qué era lo que gratificaba "`los deseos de la carne, los deseos de los ojos,
y la vanagloria de la vida, que no provienen del Padre, sino del mundo.`"^
footnote:[1 Juan 2:16]
Porque de estas cosas han surgido muchas costumbres vanas durante
la noche de oscuridad y apostasía que se ha extendido sobre las
personas a través de su degeneración de la Luz y Espíritu de Dios.
Pero por medio del Día celestial de Cristo que amanece en el alma,
se puede ver claramente que tales cosas son o malas en su origen, o,
por el tiempo y el abuso, dañinas en su práctica.
Y aunque su negativa a conformarse con estas cosas
se consideraba algo trivial para algunos,
y los hacía parecer tontos y engreídos en las opiniones de tales personas,
las razones por las que hacían esto,
eran más profundas de lo que la mayoría podía percibir.
En realidad,
no fue fácil para nuestros primeros amigos convertirse en
un espectáculo para el desprecio y escarnio del mundo;
pero ellos discernieron fácilmente cómo esto debía ser la consecuencia
de una relación con el mundo que no fuera de acuerdo con su moda.

Y aunque a menudo no eran hombres importantes y sabios en la estima de este mundo (porque
de ser así no les habrían faltado seguidores en virtud de su propio crédito y autoridad),
sin embargo,
generalmente estaban entre los más sobrios de las diversas
persuasiones religiosas a las que antes pertenecían,
y eran de los que tenían mejor reputación por causa de la piedad;
y muchos de ellos eran hombres con capacidades y recursos,
muy respetados entre los hombres.

Y también, algunos de ellos no carecían en lo absoluto de educación,
aprendizaje o bienes; aunque ahora, como en la antigüedad, no muchos sabios ni nobles,
etc., son llamados; o, al menos,
no muchos entre ellos reciben el llamado celestial por causa
de la cruz que acompaña cada respuesta sincera.
Pero, aunque el talento y el estudio hacen mejores oradores y disputadores,
no hacen mejores cristianos;
y es la ignorancia de las personas respecto al don
divino lo que causa este error común y perjudicial.
La teoría y la práctica, la especulación y la experiencia,
las palabras y vida son dos cosas muy distintas.
¡Oh, cristiano es aquel que tiene un alma arrepentida, reformada, humilde, vigilante,
abnegada y santa!
Y esta condición es el fruto y la obra del Espíritu,
el cual es la vida de Jesucristo--cuya vida,
aunque está escondida en su plenitud en Dios el Padre,
es derramada en los corazones de todos los que verdaderamente creen, según su capacidad.
¡Oh, si tan solo las personas experimentaran a este Espíritu que los limpia,
los circuncida, los vivifica y los hace en verdad nuevas criaturas,
creados nuevamente (o regenerados) en Cristo Jesús para buenas obras!
Entonces podrían vivir para Dios, y no para sí mismos;
y ofrecerían oraciones y alabanzas vivas al Dios vivo,
a través de Su propio Espíritu vivo,
en quien se ofrece la única adoración verdadera en este día del evangelio.

Ahora, con respecto al ministerio de este pueblo,
y sus cualificaciones adecuadas para el mismo, a continuación,
presentaré varias de las marcas o señales que demuestran que fue verdaderamente cristiano:

En primer lugar, ellos eran hombres transformados,
antes de intentar cambiar a los demás. Sus corazones estaban rasgados,
así como sus vestidos, y conocían el poder y obra de Dios en sí mismos.
Esto se vio por el gran cambio que había hecho dicho poder,
lo cual inmediatamente hizo que su estilo de vida
fuese más estricto y su conducta más piadosa.

En segundo lugar, no corrían ni predicaban en su propio tiempo o voluntad,
sino en la voluntad de Dios; y no hablaban su propia materia estudiada,
sino solo en la medida que el Espíritu de Dios abría sus bocas y los movía,
con el cual estaban bien familiarizados debido a su propia experiencia de la
regeneración. Soy consciente de que esto no puede expresarse a los hombres carnales,
como para darles una explicación entendible; porque estas cosas para ellos,
como Cristo dijo, son como el soplo del viento,
que ningún hombre sabe de dónde viene ni adónde va.
Sin embargo, esta prueba y sello iba de la mano con su ministerio:
que muchos se convertían de las religiones muertas, y de la maldad de sus caminos,
al conocimiento interno y vivo de Dios,
y a una vida santa (como miles pueden atestiguar).
Y así como recibían de gracia lo que tenían que decir de parte del Señor,
lo administraban gratuitamente a los demás.

En tercer lugar,
el énfasis y tendencia de su ministerio era la conversión
a Dios--verdadera regeneración y santidad.
No eran esquemas de doctrinas y de credos verbales, o nuevas formas de adoración;
sino el abandono de todo lo que es superfluo en la religión,
reduciendo la parte ceremonial y formal,
e insistiendo fervientemente en la parte sustancial,
necesaria y provechosa para el alma.

En cuarto lugar,
dirigían a las personas a un don o Semilla que estaba
_en_ sí mismos (aunque no provenía _de_ sí mismos),
por la que todo lo que afirmaban,
predicaban y exhortaban podía ser obrado en ellos y ser conocido por experiencia.
Esto realmente es una marca importante y distintiva de la verdad de su ministerio,
porque ellos conocían por experiencia lo que decían
y alentaban a todos a ponerlo a prueba.
Sí, ellos eran valientes debido a la certeza que tenían,
y no querían que nadie creyera su testimonio basándose en la autoridad humana,
sino más bien en la convicción interna--la convicción que provenía de esta Semilla,
la cual ellos afirmaban que estaba sembrada en aquellos a quienes les predicaban.
Era a esta Semilla del reino, esta medida del Espíritu,
a la que dirigían a todos los hombres,
para que todos pudieran examinar y probar la realidad
de esas cosas que habían afirmado sobre ella,
en cuanto a su manifestación y operación en el hombre.
Y, en verdad, esto es mucho más de lo que muchos ministros pueden hacer,
los cuales declaran teoría y especulación, y predican doctrinas acerca de Dios,
de Cristo, de la santidad y del cielo, etc.;
pero no hablan de su propio conocimiento y experiencia,
y nunca dirigen a sus oyentes al don divino,
a "`la palabra implantada la cual puede salvar el alma,`"^
footnote:[Santiago 1:21]
ni enseñan dónde encontrarlo,
ni cómo deben esperar para poder sentirlo obrando
en ellos la buena y agradable voluntad de Dios.

En quinto lugar, alcanzaban el estado y condición interna de las personas,
lo cual es una evidencia de la virtud de esta Palabra implantada,
y de cómo ellos ministraban a partir de ella, y no a partir de sus propias imaginaciones,
prejuicios u opiniones de las Escrituras.
Porque nada alcanza al corazón,
salvo lo que viene del corazón. Nada penetra la conciencia,
salvo lo que viene de una conciencia viva.
De modo que, en el ministerio de este pueblo,
a menudo ha acontecido que los secretos de los corazones han sido
revelados y los verdaderos estados y condiciones han sido declarados.
Sí,
los pensamientos e intenciones de los corazones de muchos han sido detectados tan claramente,
que ellos, como Natanael, han clamado con respecto a esta aparición interna de Cristo:
"`Tú eres el Hijo de Dios; Tú eres el Rey de Israel.`"^
footnote:[Juan 1:49]
Y aquellos que han abrazado esta Palabra o Semilla divina,
han encontrado la misma marca de su verdad y divinidad que la mujer
de Samaria encontró con respecto a Cristo cuando estaba en la carne,
a saber: "`Les dijo todo lo que habían hecho`"^
footnote:[Juan 4:9]
Les mostró su interior, los secretos más internos de sus corazones,
"`poniendo el juicio por medida, y la justicia por nivel,`"^
footnote:[Isaías 28:17 LBLA]
de lo cual miles en este día pueden dar testimonio.
De modo que aquellos que se han vuelto a esta Semilla
celestial han tenido motivos para decir:
"`Verdad es lo que oí, ni aun se me dijo la mitad`"^
footnote:[1 Reyes 10:6-7]
del poder, la pureza, la sabiduría y la bondad de Dios en ella.

En sexto lugar,
el entendimiento extraordinario en las cosas divinas con el que algunos (incluso de
los más pequeños entre ellos) fueron dotados por la operación de esta Semilla celestial,
hizo que muchos se asombraran, diciendo de ellos, como algunos dijeron de su Maestro,
"`¿No es éste el hijo del carpintero?
¿De dónde, pues, adquirió éste un entendimiento tan grande?`"^
footnote:[Mateo 13:54-56]
A partir de esto,
los hombres malvados aprovecharon la ocasión para sospechar
e insinuar que eran Jesuitas o grandes eruditos disfrazados;
aunque no había ni el menor fundamento de verdad para tal calumnia,
ya que todos conocían el lugar donde vivían, su parentela y su educación.

En séptimo lugar, estos ministros comenzaron su labor siendo hombres humildes,
despreciados y aborrecidos, así como los primeros cristianos,
sin tener nada de la ayuda de la sabiduría o del poder mundanos,
como en parte lo han tenido las reformas anteriores.
Sí, en todas las cosas se puede decir que este pueblo surgió manteniéndose bajo la cruz,
en una verdadera contradicción a los caminos, modos de adoración,
modas y costumbres de este mundo; contra todas sus corrientes y tendencias,
para que ninguna carne pudiera gloriarse delante de Dios.

En octavo lugar, era evidente,
por la manera en que se expusieron a tal desprecio y abuso,
que no tenían ningún propósito personal en su obra y servicio.
Ellos gastaron y fueron gastados, dejaron esposa e hijos, casa y tierra,
y todo lo que el hombre considera precioso, arriesgando sus vidas,
estando en peligro diariamente,
para declarar este primer mensaje que había revivido en
sus espíritus por el buen Espíritu y poder de Dios,
a saber: Que Dios es luz, y no hay ningunas tinieblas en Él;
y que Él ha enviado a Su Hijo al mundo como una luz para
alumbrar a todos los hombres y para guiarlos a la salvación;
y que aquellos que dicen que tienen comunión con Dios y aun andan en tinieblas (es decir,
en desobediencia a la luz en sus conciencias,
y según la vanidad de este mundo) mienten y no practican la verdad.
Pero que todos los que aman la luz, y traen sus obras a ella, y caminan en la luz,
así como Dios es luz,
experimentan la sangre de Jesucristo Su Hijo limpiándolos de todo pecado.
(1 Juan 1:4, 19; 3:20-21; 1:5-7.)

En noveno lugar,
su gran constancia y paciencia en medio de los sufrimientos
por su testimonio (en todas sus ramas^
footnote:[Él quiere decir,
las diversas formas en que ellos se sintieron llevados por el Señor a dar testimonio
de la verdad y a oponerse a todo pecado y error.]) son bien conocidas por todos;
y cómo algunas veces sufrieron hasta la muerte, con palizas, golpes,
y encarcelamientos largos y abarrotados de gente en calabozos inmundos.
Cuatro de ellos en Nueva Inglaterra murieron en manos de verdugos,^
footnote:[William Robinson, Marmaduke Stevenson, Mary Dyer y William Leddra.
Véase [.book-title]#La Historia del Surgimiento,
Aumento y Progreso de ese Pueblo Cristiano llamado Cuáqueros de William Sewel#.]
solo por predicar entre el pueblo de Boston.
Sin mencionar los destierros y despojos excesivos
de bienes y propiedades en casi todas partes,
por su fidelidad a la buena y gloriosa causa,
rehusando frecuentemente obtener libertad por caminos o medios deshonrosos,
a pesar de que se les ofreció muchas veces.

En décimo lugar,
no solo demostraron que no tenían ningún deseo de
venganza cuando en algún momento estaba en su poder,
sino que perdonaban a sus crueles enemigos,
mostrando misericordia a aquellos que no les habían mostrado ninguna.

En onceavo lugar,
su manera directa de tratar a los que estaban en
autoridad era muy similar a los antiguos profetas,
pues no tenían temor de declarar los pecados privados y
públicos de los gobernadores y magistrados en sus caras,
ni de profetizar acertadamente sus aflicciones y su caída,
incluso cuando estaban en la cima de su gloria.
De la misma manera predijeron algunos juicios nacionales de manera muy clara,
tales como la plaga de 1665^
footnote:[La Gran Plaga de 1665-1666 fue la última y más
grande epidemia de peste bubónica que ocurrió en Inglaterra,
matando un estimado de 100.000 personas en 18 meses,
alrededor de la cuarta parte de la población de Londres.]
y el gran incendio de Londres,^
footnote:[El Gran Incendio de Londres que duró desde el domingo
2 de septiembre hasta el miércoles 5 de septiembre de 1666.
Consumió 87 iglesias parroquiales,
la mayoría de los edificios que usaban las autoridades de la ciudad y
13.200 casas--las casas de 70.000 de 80.000 habitantes de la ciudad.]
como también juicios particulares sobre varios perseguidores impíos,
que les acontecieron a cada uno según lo predicho.

¡Oh, que aquellos que leen mis palabras tan solo pudieran sentir lo que yo siento!
Porque mi corazón está alcanzado por esta visitación misericordiosa
del Padre de las luces y de los espíritus a esta pobre nación,
y al mundo entero a través del mismo testimonio vivo.
¿Por qué los habitantes de la tierra la rechazarían?
¿Por qué perderían el bendito beneficio de ella?
¿Por qué no se volverían al Señor con todo su corazón y dirían desde el corazón:
"`habla Señor, porque ahora Tus pobres siervos escuchan`"? Y clamar, "`¡Oh,
que Tu voluntad sea hecha--Tu grande, buena y santa voluntad,
en la tierra como en el cielo!
Hazla en nosotros, hazla sobre nosotros, haz lo que quieras con nosotros;
porque somos Tuyos, y deseamos glorificar a nuestro Creador, nuestro Redentor.
Porque Tú nos estás redimiendo de la tierra,
de las vanidades y de las contaminaciones de ella,
para que seamos un pueblo especial para Ti.`" ¡Oh,
este habría sido un gran día para Inglaterra,
si ella hubiera dicho eso en verdad! ¡pero ay, el caso es otro!

¡Oh tierra de mi natividad!
Algunos han endechado sobre ti con un amargo aullido y lamento.
Sus cabezas en verdad han sido como aguas, y sus ojos como fuentes de lágrimas,
debido a tu transgresión y rebelión; porque no quisiste oír, ni temer,
ni volver a la Roca de donde fuiste cortada.
Pero toma la advertencia, ¡oh! tierra de gran profesión religiosa,
para que lo recibas a Él en tu corazón. He aquí,
Él ha estado mucho tiempo a la puerta llamando;
pero hasta ahora no has querido nada de Él.

¡Oh, despierta, no sea que los juicios de Jerusalén te alcancen repentinamente,
porque sus pecados abundan en ti!
Porque Jerusalén abundaba en formalidad,
pero hacía nulo lo más importante de la ley de Dios, como tú lo haces diariamente.
Ella resistió al Hijo de Dios en la carne, y tú resistes al Hijo de Dios en el Espíritu.
Él quería juntarla como la gallina a sus polluelos debajo de sus alas y ella no quiso;
así también quería sacarte de las religiones sin vida y llevarte a heredar la sustancia,
para que conocieras Su poder y Su reino.
Con este fin, a menudo tocó la puerta desde adentro por medio de Su gracia y Espíritu;
y llamó desde afuera por medio de Sus siervos y testigos;
pero tal como la Jerusalén antigua persiguió la manifestación
del Hijo de Dios en la carne y lo crucificó,
y azotó y encarceló a Sus siervos;
así tú has crucificado nuevamente para ti misma al Señor de vida y gloria,
y has hecho afrenta a Su Espíritu de gracia.
Sí,
has despreciado Su visitación como Padre y has perseguido
con tus leyes y magistrados a los que la declaraban,
a pesar de que ellos han contendido contigo día y noche en el poder y Espíritu del Señor,
en amor y mansedumbre, para que pudieras conocer al Señor y servirlo,
y convertirte en la gloria de todas las naciones.

¡Ay!
Tú los has tratado y recompensado con maldad.
Tú has dejado de lado todos sus consejos, y no has deseado ninguna de sus reprensiones.
Su apariencia era demasiado sencilla,
y sus cualidades eran muy pobres como para que tú los recibieras.
Tú eres como los judíos de antaño quienes clamaron:
"`¿No están Sus hermanos y hermanas con nosotros?
¿Cuál de los escribas y de los entendidos (los ortodoxos) creen en Él?`" Por lo tanto,
profetizaste su caída en un año o dos, e intentaste llevarla a cabo,
haciendo y ejecutando leyes severas e injustas.
Sí, trataste de aterrorizarlos para que abandonaran su camino santo,
o de destruirlos por permanecer fieles a él. Pero tú has visto cuántos
gobiernos que se levantaron contra ellos y determinaron su caída,
fueron derrocados y extinguidos, y ellos siguen siendo preservados,
y se han vuelto un pueblo grande y numeroso.
Y a pesar de todas las dificultades externas e internas,
bajo las cuales han laborado desde que el Señor los reunió por primera vez,
son un pueblo en crecimiento; porque el Señor todavía les añade, en diversos lugares,
los que han de ser salvos si perseveran hasta el fin.

Recuerda, oh nación de gran profesión religiosa,
cómo el Señor ha esperado por ti y ha litigado contigo.
Despierta y levántate de tu profundo sueño, y escucha hoy Su Palabra en tu corazón,
a fin de que vivas.
No dejes que este día de tu visitación pase sobre tu cabeza,
ni descuides una salvación tan grande como esta, la cual ha llegado a tu casa, ¡oh,
Inglaterra! ¿Por qué morirás? Oh tierra que Dios desea bendecir,
ten por seguro que Él es quien ha estado en medio
de este pueblo despreciado que está en medio de ti.
No es un engaño, como te han hecho creer tus maestros equivocados.
Y seguramente te darás cuenta de esto por sus marcas y sus frutos,
si tan solo consideras estas cosas en el espíritu de moderación.
