== Capítulo III

[.chapter-subtitle--blurb]
El Don de Dios--La Luz de Cristo en el Corazón

Habiendo hablado algo sobre el origen y surgimiento de este pueblo,
y descrito de forma breve la manera y objetivo de su ministerio,
me corresponde hablar más expresamente de los principios y prácticas fundamentales
que distinguen a este pueblo de los muchos otros profesantes de religión
en este día. Ya he hablado un poco sobre su principio fundamental,
el cual es la luz de Cristo en el corazón,
entendiendo esto como el don de Dios para la salvación del hombre.
Y puesto que esta es la raíz del excelente árbol de doctrinas que creció y brotó de ella,
creo que merece mayor consideración y explicación más profunda.

Lo siguiente es aquello que el pueblo llamado Cuáqueros
establece como el fundamento principal en la religión:
Que Dios, a través de Jesucristo, ha puesto un don de Su Espíritu en cada hombre,
para informarles sobre su deber, y capacitarlos para cumplirlo;
y que aquellos que viven en humilde sumisión a esto son el pueblo de Dios,
y aquellos que viven en desobediencia al mismo, no son el pueblo de Dios,
independientemente de cuál sea el nombre de su religión o su profesión religiosa.
Este es su testimonio antiguo, primero y permanente.
Con esto comenzaron, y de esto dieron testimonio y siguen dándolo al mundo.

Ahora, cuando hablan de este don de Su Espíritu, se refieren a algo que es divino;
pero aunque esté _en_ el hombre, no es _del_ hombre, sino de Dios; y así como vino de Él,
asimismo conduce hacia Dios a todos los que quieran ser guiados por él.

Ahora bien,
este pueblo ha sido guiado a usar diversas maneras de describir este Espíritu,
por medio de las cuales declaran y expresan lo que es.
Lo llaman la luz de Cristo en el interior del hombre, o simplemente la Luz interior,
que es su frase antigua, y más general y familiar;
también lo llaman la manifestación o aparición de Cristo, el testigo de Dios,
la semilla de Dios, la semilla del reino, Su sabiduría o Palabra en el corazón,
la gracia que se ha manifestado a todos los hombres,
una medida del Espíritu dada a cada hombre, la Verdad en lo íntimo,
la levadura espiritual que leuda toda la masa del hombre, etc.
Muchas de estas son expresiones figurativas,
pero todas ellas han sido usadas por el Espíritu Santo en las Escrituras,
y serán usadas en este tratado,
ya que se encuentran con frecuencia en los escritos y en el ministerio de este pueblo.
Pero para evitar algún malentendido o confusión en el lector, quiero que todos sepan que,
con todos estos diversos términos o denominaciones,
ellos se refieren a lo mismo que se mencionó anteriormente, a saber: al don o gracia,
que, aunque está _en_ el hombre, _no es del_ hombre, sino de Dios, y por lo tanto es divino.
Este Espíritu es uno en sí mismo,
aunque es expresado de diversas maneras por los autores de las Escrituras,
de acuerdo con sus distintas manifestaciones y operaciones.

Es este Espíritu de luz, vida y gracia al que este pueblo dirige a todos;
porque ellos declaran que este es el gran instrumento en toda religión verdadera,
y que sin Él no hay convicción, y por lo tanto no hay conversión ni regeneración,
y consecuentemente no hay entrada al reino de Dios.
Es decir, sin este don no puede haber una verdadera visión del pecado ni tristeza por él,
y por lo tanto no es abandonado o vencido,
ni se experimenta la verdadera remisión o justificación.
¡Qué Espíritu tan necesario y poderoso,
si ni la santificación ni la justificación se pueden obtener sin Él! En resumen,
no hay posibilidad de llegar a la piedad, ni de volverse santo y bueno sin Él;
y no hay ninguna aceptación con Dios, ni paz en el alma,
sino a través de Él. Así entonces,
la razón por la que hay tanta religión falsa entre los cristianos,
tanta superstición en lugar de devoción, tanta profesión sin posesión,
y tan poca reforma del corazón,
es porque las personas en la religión generalmente pasan por alto al Espíritu Santo,
y lo dejan totalmente atrás.

Por desgracia, los hombres buscan ser religiosos sin Él, ser cristianos sin Él,
pero este Espíritu es el único medio para alcanzar ese fin.
Es natural para los hombres en su estado degenerado
preferir el sacrificio antes que la obediencia,
y las oraciones verbales antes que las vidas cambiadas.
Estos se adulan a sí mismos con una falsa esperanza
debido a sus servicios ceremoniales y externos.
De esta manera,
se excusan ante Dios y evaden la disciplina estricta de Su Espíritu en el alma,
la cual lleva a todos a tomar la cruz,
a negarse a sí mismos y hacer lo que Dios requiera de ellos.
Esto debería ser la religión verdadera de todo hombre, porque,
aunque un hombre no puede hacerse a sí mismo santo, humilde, paciente, manso,
misericordioso, justo, amable y caritativo;
el Espíritu Santo lo llevará a cabo en todos los que abrazan sus convicciones y enseñanzas;
porque esta obra interna del Espíritu es la única raíz de toda religión verdadera
y la buena Semilla de la cual proceden todos los buenos frutos.

Es por la medida de este Espíritu, que fue derramado sobre toda carne,^
footnote:[Joel 2:28; Hechos 2:17]
que el hombre recibe las siguientes cosas: Primero,
el conocimiento de Dios y de sí mismo,
y por dicho conocimiento una visión de su deber y de cualquier desobediencia al mismo.
Segundo,
engendra un verdadero sentido del pecado y una verdadera tristeza
por él en aquellos que consideran seriamente Sus convicciones.
Tercero, les da poder para dejar el pecado y los santifica de él. Cuarto,
aplica las misericordias de Dios en Cristo para el perdón
de los pecados pasados para alcanzar verdadera justificación,
sobre la base del arrepentimiento sincero y la obediencia.
Quinto, le da a los fieles perseverancia para llegar a la medida del hombre perfecto,
y la seguridad de recibir bendición en el siglo venidero.

=== La Evidencia de las Escrituras a favor de la Luz de Cristo

[.offset]
_Juan 1:1._ En el principio era la Palabra, y la Palabra era con Dios,
y la Palabra era Dios.^
footnote:[Reina Valera Versión 1602 Purificada]

[.offset]
_Verso 3._ Todas las cosas por Él fueron hechas.

[.offset]
_Verso 4._ En Él estaba la vida, y la vida era la luz de los hombres.

[.offset]
_Verso 9._ Aquél era la Luz verdadera, que alumbra a todo hombre que viene a este mundo.^
footnote:[Reina Valera de Gómez]

He comenzado con el relato del discípulo amado,
bien conocido por su excelente conocimiento y sabiduría en cosas celestiales.
Él empezó su historia con Aquel que era el principio de la creación de Dios,
y en primer lugar nos dice qué era Cristo en el principio, a saber, la Palabra.
"`En el principio era la Palabra.`"
Y aunque esto implica lo que la Palabra debe ser, aun así,
él añade y explica que "`la Palabra era con Dios,
y la Palabra era Dios;`" no sea que alguien dude de la divinidad de la Palabra,
o piense que Él es algo menos de lo que realmente es.
La Palabra, por lo tanto, es divina;
y este en verdad es un nombre apropiado por el cual llamarlo,
ya que Él es una perfecta expresión de la sabiduría
y poder de Dios para con los hombres.

"`Todas las cosas por Él fueron hechas.`"
Si esto es así, entonces Él no carece de ningún poder.
Nada puede ser muy difícil para Aquel que fue suficiente para hacer todas las cosas,
y "`sin quien nada de lo que ha sido hecho, fue hecho.`"^
footnote:[Juan 1:3]
Y así como fuimos creados por Él en el principio,
tenemos que ser hechos nuevamente por Él, o nunca podremos disfrutar de nuestro Dios.
Sí, así como el Hacedor del hombre debe ser su marido,
su Creador también debe ser su Redentor.^
footnote:[Véase Isaías 54:5]

"`En Él estaba la vida, y la vida era la luz de los hombres.`"
Este es precisamente nuestro punto.
El evangelista primero comienza con la naturaleza y ser de la Palabra;
de allí prosigue a hablar de las obras de la Palabra; y finalmente,
nos dice lo que es esta Palabra con respecto al hombre
(que es mayor que el resto de la creación):
a saber, Su luz.
La Palabra era la vida, y _la vida era la luz de los hombres._
Esta relación debe ser muy cercana e íntima en verdad,
ya que se dice que la vida misma de la Palabra (que estaba con Dios,
y era Dios) es la luz de los hombres.
Esto no se dice de ninguna otra criatura.

El hombre, entonces, no puede existir sin tener una luz; sin tener una luz _divina;_
porque si nosotros negamos que esta luz es divina (de la cual se
dice claramente que es la vida de la Palabra divina) entonces negamos
la posibilidad de que exista una luz y vida divina y sobrenatural.
Y este texto no solo prueba la divinidad de la luz, sino también su universalidad,
porque está escrito en el noveno versículo, que "`Aquél era la Luz verdadera,
que alumbra a todo hombre que viene a este mundo.`"
Juan no era la luz, sino que daba testimonio de Aquel que lo era,
y que alumbra a todo hombre; a saber, la Palabra que se hizo carne.
Así, tanto la naturaleza divina como la universalidad^
footnote:[En años más recientes,
ha habido malentendidos y conclusiones falsas derivados del uso de los
Cuáqueros del término __universal__ con referencia a la luz de Cristo.
Esta palabra fue utilizada por los Amigos para establecer un contraste
intencional con la idea prevaleciente de que Dios le ofrece el conocimiento
salvador de Cristo solo a un pequeño grupo de personas predestinadas.
Los Cuáqueros rechazaron la idea de la predestinación individual y de una "`expiación
limitada,`" insistiendo que Cristo murió por todos los hombres,
y que a través de la luz y de la gracia de Dios se extiende una oferta de redención
hacia todos los hijos de Adán. Es esta invitación bondadosa e interna lo que es universal.
Cuando la luz de Cristo es recibida,
seguida y obedecida se convierte en la vida y la salvación del alma.
Cuando es rechazada, la misma luz se vuelve la condenación eterna de los hombres.
Véase Juan 3:19-21. Los Primeros Cuáqueros no fueron en lo absoluto defensores del universalismo,
o de la reconciliación universal.]
de la luz de Cristo en el corazón, ambas son confirmadas aquí.

=== No es una Luz Natural

Pero a pesar de que no hay pasaje o proposición en las Sagradas
Escrituras que sea más importante para la humanidad,
o que esté más claramente establecido por el Espíritu Santo que este que he presentado,
aun así,
casi ninguna Escritura se ha
torcido de su sentido verdadero y evidente con tanto esmero.
Algunos insisten en que esto no es más que una luz natural,
o una parte de la naturaleza del hombre,
a pesar de que es llamada la vida misma de la Palabra por la cual el mundo fue hecho.
Pero debido a que deseo que me entiendan, y que quiero hablarles con claridad,
consideraré los términos de esta objeción lo mejor que pueda,
y entonces ofreceré mi respuesta a la misma.

Si con _natural_ se refieren a una cosa creada, como lo es el hombre,
o a alguna parte inherente en la composición del hombre, lo niego.
El texto se muestra claramente en contra de tal idea,
y dice que la luz con la que el hombre es iluminado
es la vida de la Palabra que estaba con Dios,
y era Dios.
Pero si con natural solo se quiere decir,
que nosotros tenemos esta luz desde que nacemos,
y que (a veces) resplandece en nuestras mentes y entendimientos,
y que no es el resultado de ninguna revelación externa (como de ángeles u hombres),
entonces queremos decir y nos referimos a lo mismo.
En este sentido, es natural para el hombre tener una luz sobrenatural,
y que la criatura sea iluminada por una luz no creada--la vida de la Palabra creadora.

Y si las personas tan solo consideraran la constitución del hombre,
ayudaría mucho a sacarlos de cualquier dilema en este asunto.
Porque el hombre no puede ser una luz para su propia
mente más de lo que es para su propio cuerpo.
Él tiene la capacidad de ver objetos cuando tiene la ayuda de la luz,
pero no puede _ser_ una luz para sí mismo por la cual pueda verlos.
Por lo tanto, así como el sol en el firmamento es la luz del cuerpo,
y nos da discernimiento en nuestros asuntos temporales,
asimismo la vida de la Palabra es la gloriosa luz y sol del alma.
Es nuestra luminaria interna, que tiene poder de informar a nuestra mente,
y de darnos verdadero juicio y distinción respecto a esas cosas
que le conciernen más directamente a nuestro hombre interior.

Pero otros sugieren que la Palabra mencionada en este texto no ilumina a todos los hombres,
sino solo a todos los hombres que están iluminados por ella.
De esta manera, no solo limitan y abusan del texto,
sino que hacen que Dios se muestre parcial y tan severo con Sus
criaturas como para dejar parte del mundo en completa oscuridad,
sin ningún medio u oportunidad de salvación. Sin embargo,
las Escrituras nos aseguran que a todo se les ha dado luz,
que Cristo es "`la luz del mundo,`"^
footnote:[Juan 8:12]
y que "`Él murió por todos los hombres;`"^
footnote:[2 Corintios 5:14-15; Romanos 6:10; Hebreos 2:9, etc.]
sí, incluso por "`los impíos,`"^
footnote:[Romanos 5:6; véase también 2 Pedro 2:1]
y que Dios "`no quiere la muerte de ninguno,
sino que todos procedan al arrepentimiento y vengan
al conocimiento de la verdad y sean salvos;`"^
footnote:[Ezequiel 18:32, 33:1; 1 Timoteo 2:4; 2 Pedro 3:9.]
y que "`la gracia de Dios se ha manifestado a todos los hombres,`"^
footnote:[Tito 2:11]
etc.

Hay un tercer tipo de personas que alegan que esta Escritura no habla
de una iluminación por medio de la luz divina o el Espíritu en el hombre,
sino por la doctrina que Cristo predicó,
y por la vida y ejemplo que fue y manifestó al mundo.
Pero el conocimiento de esto no alcanzó ni a la milésima parte de la humanidad,
ni concuerda esta idea con lo que el apóstol Juan
quiso decir en el principio de su historia,
la cual únicamente relata lo que Cristo era antes de tomar un cuerpo de carne,
y lo que Él es para el alma del hombre por medio de Sus
iluminaciones e influencias internas y directas.

Es muy cierto que Cristo, en cierto sentido,
fue la luz del mundo en Su aparición externa,
y que Él resplandeció a través de Su doctrina celestial, Sus muchos milagros admirables,
y Su vida de abnegación y dolorosa muerte.
Sin embargo,
esto no anula la verdad de que Él también fue y es la luz espiritual que brilla
(en diversos grados) en los corazones de los hijos e hijas de los hombres.
Porque el evangelista, para distinguir la luz de Cristo de la de Juan,
quien no era la luz verdadera, no mencionó su ayuno de cuarenta días,
sus sermones extraordinarios, sus muchos milagros, ni su vida santa y muerte paciente.
Más bien, mostró que la luz verdadera, el Mesías, la Palabra hecha carne,
alumbra a todo hombre que viene al mundo.
Por lo tanto, Cristo se manifiesta y se distingue por el hecho de que Él da luz;
así como Sus verdaderos seguidores se distinguen de otros pueblos,
por recibir y obedecer dicha luz.
Hay muchas otras Escrituras, tanto en el Antiguo como en el Nuevo Testamento,
que se refieren a la luz interior, ya sea de manera expresa o indirecta, que,
por motivos de brevedad, me abstendré de citar.

=== La Eficacia de la Luz de Cristo en el Corazón

Consideremos entonces la virtud y eficacia de esta luz en
relación con el propósito por el cual Dios la ha dado,
a saber, llevar y guiar el alma del hombre a la bendición. Para llevar a cabo esto,
lo primero que hace en y por el hombre es darle una
verdadera visión o discernimiento de sí mismo,
mostrando lo que es y lo que hace,
para que pueda ver su verdadera condición y saber qué juicio
hacer con respecto a la religión y al estado futuro.
Escuchemos lo que la Palabra misma (la cual no puede errar) dice acerca de esta luz,
tal como lo narra Juan en el tercer capítulo de su evangelio:
"`Porque todo aquel que hace lo malo, aborrece la luz y no viene a la luz,
para que sus obras no sean reprendidas.
Mas el que practica la verdad viene a la luz,
para que sea manifiesto que sus obras son hechas en Dios.`"^
footnote:[Juan 3:20-21]

Esta es una descripción muy completa de la virtud y autoridad de la luz.
Primero, dice que es aquello por lo que los hombres deben examinarse.
Segundo, que es lo que da un verdadero discernimiento entre el bien y el mal,
de lo que es de Dios y lo que no es de Dios.
Y, por último, que es un juez, que condena o absuelve,
reprueba o consuela el alma del hombre, según él la rechaza u obedece.
Ahora bien, aquello que es capaz de mostrarle al hombre qué es y qué no es de Dios,
y darle al obediente un conocimiento indudable de lo que
ha sido hecho o realizado por el poder de Dios,
y de acuerdo con Su voluntad y también hacerle saber
cuáles son las meras obras de la criatura,
esto ciertamente debe ser algo tanto divino como eficaz.
Porque si no fuera así, de ninguna manera podría manifestar la mente de Dios,
ni darle al hombre un sentido y discernimiento veraz del estado,
naturaleza y tendencia de su mente u hombre interior,
tal como se expresa y se implica en esas palabras de nuestro Salvador.

Pero que esta luz verdaderamente manifiesta a Dios,
es evidente en Romanos 1:19. "`Porque lo que se conoce
acerca de Dios es evidente dentro de ellos,
pues Dios se lo hizo evidente.`"^
footnote:[LBLA, Reina Valera 1602 Purificada]
Esta es una declaración universal; tenemos la palabra fiel del apóstol,
quien fue inspirado por el Espíritu para decirnos la verdad;
dejen pues que este dicho tenga su debido peso en sus corazones.
Si lo que de Dios se puede conocer es manifiesto dentro de los hombres,
entonces el pueblo llamado Cuáqueros no podría estar fuera del
verdadero camino al predicar la luz de Cristo en el corazón,
sin la cual nada puede manifestarse a la mente del hombre,
como lo dice el mismo apóstol en su epístola a los Efesios (verso 5:13):
"`la luz es lo que manifiesta todo.`"
Por lo tanto,
este pueblo llama correctamente a esta luz una manifestación o aparición de Dios,
puesto que revela en y al hombre todo lo que de Dios se puede conocer.

Un pasaje muy parecido a este es el del profeta Miqueas, capítulo 6:8. "`Oh hombre,
él te ha declarado lo que es bueno, y qué pide Jehová de ti:
solamente hacer justicia, y amar misericordia, y humillarte ante tu Dios.`"
¡Oh hombre, Dios te lo ha declarado!
Esto es muy enfático.
Pero ¿cómo se lo ha declarado?
Pues, a través de esta luz en la conciencia,
contra la cual se rebelan los impíos. Porque Job dijo, "`Ellos son los que,
rebeldes a la luz, nunca conocieron sus caminos, ni estuvieron en sus veredas;`"^
footnote:[Job 24:13]
pero Sus caminos son placenteros y todas sus veredas son paz para los que la obedecen.

Esta luz les da "`la luz de la vida`" (que es la
vida eterna) a los que la reciben y la obedecen.
Pues, así dice el bendito Salvador del mundo, "`Yo soy la luz del mundo; el que me sigue,
no andará en tinieblas, sino que tendrá la luz de la vida.`"^
footnote:[Juan 8:12]
Ahora bien,
Él se llama la luz del mundo entero porque Él alumbra a todo hombre que viene al mundo.
Los que obedecen Su luz lo obedecen a Él, y por lo tanto tienen la luz de la vida;
es decir, Su luz se convierte en vida eterna para sus almas.
Porque, de nuevo, la vida de la Palabra es la luz en el hombre,
y esta se vuelve la vida en el hombre a través de su sumisa
obediencia a sus diversas manifestaciones.

Además, esta luz era el fundamento mismo del mensaje apostólico,
como nos asegura el discípulo amado, diciendo: "`Este es el mensaje que hemos oído de él,
y os anunciamos: Dios es luz,
y no hay ningunas tinieblas en él. Si decimos que tenemos comunión con él,
y andamos en tinieblas, mentimos, y no practicamos la verdad; pero si andamos en luz,
como él está en luz, tenemos comunión unos con otros,
y la sangre de Jesucristo Su Hijo nos limpia de todo pecado.`"^
footnote:[1 Juan 1:5-7]
Esto habla tan ampliamente acerca de la virtud y
excelencia de la luz de Cristo en referencia al hombre,
que muy poco podría añadirse.
Porque aquí vemos, primero, que ella revela a Dios, y que Dios Mismo es luz.
Segundo, manifiesta la diferencia entre las tinieblas y la luz,
estableciendo que no hay ninguna comunión entre ellas.
Tercero, muestra que el hombre debe caminar en la luz,
como la manera de obtener tanto el perdón de pecado como la santificación del mismo.
Y cuarto,
declara que este es el medio para tener paz y comunión con Dios y con Su pueblo--Su
verdadera iglesia--quienes son redimidos de las contaminaciones del mundo.
