== Capítulo 4

Algunas Objeciones Consideradas y Respondidas

Objeción:
Pero algunos pueden objetar que las virtudes y efectos que le atribuimos a la
luz en el corazón corresponden más bien al Espíritu y a la gracia de Dios,
que son las bendiciones peculiares del nuevo y segundo pacto,
y el fruto de la venida de Cristo.

Respuesta:
Si las propiedades atribuidas a la luz en el corazón son las mismas
que se otorgan al Espíritu Santo y gracia de Dios,
entonces sin duda estos son solo varios términos o epítetos,
utilizados para expresar las diversas manifestaciones
u operaciones de un mismo Espíritu.

Ahora bien, para demostrar esto,
y poder ver si la luz en el corazón es de la misma
naturaleza que el Espíritu y la gracia de Dios,
y tiende al mismo fin (el cual es llevar a las personas a Dios),
comparemos las propiedades de la luz con las del Espíritu y la gracia de Dios.
Primero, la luz procede de la Palabra, y de la única vida de esta Palabra,
la cual era con Dios y era Dios, Juan 1:4 y 1:9. Segundo, es universal, es decir,
está escrito que alumbra a todo hombre.
Tercero, da el conocimiento de Dios y comunión con Él,
Romanos 1:19. Juan 3:21. 1 Juan 1:5-6. Cuarto, manifiesta y reprende el mal,
Juan 3:20. Efesios 5:13. Quinto,
es constituida como la regla y guía de la vida cristiana,
Salmo 43:3. Juan 8:12. Efesios 5:13, 15. Sexto,
es la senda por la que el pueblo de Dios debe caminar,
Salmos 119:105. Proverbios 4:18. Isaías 2:5. 1 Juan 1:7. Apocalipsis 21:24,
"`las naciones de los que son salvos andarán en la luz del Cordero.`"^
footnote:[Reina Valera 1602 Purificada]
Por último, es la armadura de los hijos de Dios contra Satanás, Salmos 27:1,
"`El Señor es mi luz: ¿de quién temeré?`" Y Romanos 13:12,
"`Vistámonos las armas de la luz.`"

Ahora comparemos todo esto con las propiedades del Espíritu Santo,
y su concordancia será demasiado evidente.
Primero, el Espíritu procedió de Dios, porque es el Espíritu de Dios,
Romanos 8:11. Segundo, es universal; contendió con el mundo antiguo (Génesis 6:3),
y sin duda lo hace con el nuevo también. A cada uno
le ha sido dada una medida de Él para provecho,
1 Corintios 12:7. Tercero, revela a Dios, Job 32:8, 1 Corintios 2:10-11. Cuarto,
reprende el pecado, Juan 16:8. Quinto,
es la regla y guía por la cual los hijos de Dios deben andar, Romanos 8. Sexto,
también es la senda por la que deben caminar, Romanos 8:1, Gálatas 5:16,
"`Andad en el Espíritu.`"
Por último, es el arma espiritual de todo cristiano verdadero, Efesios 6:17,
"`Tomad la espada del Espíritu, que es la palabra de Dios.`"
Así pues,
creo que nadie negará que esta luz y este Espíritu deben ser de una misma naturaleza,
que hacen un mismo efecto y que evidentemente tienden a un mismo y santo fin.

Y la coherencia que existe entre la luz y el Espíritu,
evidentemente existe también entre la luz y la gracia de Dios.
Porque primero,
la gracia fluye de Cristo--la Palabra que se hizo carne--como también la luz; porque,
así como "`en él estaba la vida, y la vida era la luz de los hombres,`"^
footnote:[Juan 1:4]
también estaba "`lleno de gracia y de verdad,`" Juan 1:14,
y "`de su plenitud todos nosotros hemos recibido,
y gracia por gracia,`" Juan 1:16. Segundo, es universal,
lo cual puede verse tanto en el texto anterior como
también en las palabras del apóstol a Tito;
"`Porque la gracia de Dios que trae salvación se ha manifestado a todos los hombres,`"^
footnote:[Reina Valera Gómez]
Tito 2:11. Tercero, manifiesta el mal,
porque "`enseña a renunciar a la impiedad y a los
deseos mundanos,`" versículo 12. En cuarto lugar,
revela la piedad y, por consiguiente, manifiesta a Dios.
En quinto lugar, es un instructor y guía;
porque el apóstol dice que "`enseña a vivir en este mundo sobria,
justa y piadosamente;`" y aquí está la regla o guía de la vida cristiana.
En sexto lugar, es para los que la reciben todo lo que pueden necesitar o desear,
2 Corintios 12:9,
"`Bástate mi gracia;`"--este es un fuerte testimonio desde
el cielo a favor del poder de esta gracia que enseña y salva,
incluso bajo las más fuertes tentaciones.

Objeción: Pero antes de la venida de Cristo, hay pocas referencias al Espíritu,
y ninguna a la gracia.
Por lo tanto,
el Espíritu y especialmente la gracia que se mencionan en el Nuevo Testamento
deben ser algo diferente y más noble que la luz en el corazón.

Respuesta: De ninguna manera es algo diferente,
sino otro nombre para otra manifestación u operación del mismo Espíritu.
Es llamada luz debido a la percepción y discernimiento que da.
"`Sea la luz; y fue la luz,`" dijo Dios en el principio del mundo antiguo.
Así también, en el principio de la nueva creación de Dios en el hombre, primero hay luz.
Es llamado Espíritu, porque da vida, sentido, movimiento y vitalidad,
y a menudo se menciona así tanto en los escritos del Antiguo como del Nuevo Testamento.
Por este Espíritu, Dios contendió con el mundo antes del diluvio (Génesis 6:3),
y con Israel en el desierto (Nehemías 9:30). Y David preguntó en la agonía de su alma,
"`¿A dónde me iré de tu Espíritu?`"
(Salmos 139:7); y los profetas lo sentían con frecuencia.
Y es llamado gracia, no por ser otro Espíritu,
sino porque era una dispensación más plena de la virtud y poder del mismo Espíritu divino;
la cual, siendo puramente el favor y la misericordia de Dios, y no el mérito del hombre,
es debidamente llamada la gracia de Dios para el hombre que no lo merece.

El viento no siempre sopla con fuerza, ni el cielo siempre envía lluvia libremente,
ni el sol siempre brilla con claridad.
Por esta razón, ¿diremos que cuando el viento, la lluvia o la luz, sopla,
llueve o brilla tan solo un poco, es de una naturaleza diferente que cuando sopla,
llueve o brilla mucho?
Ciertamente es lo mismo en naturaleza y género;
y así ocurre con este bendito Espíritu en todas sus diversas dispensaciones,
manifestaciones y operaciones,
las cuales son todas para el beneficio del alma del hombre, desde que comenzó el mundo.

Y nosotros, con la mayor libertad, humildad y agradecimiento,
reconocemos que la dispensación del Evangelio es más clara,
plena y noble que todas las demás,
tanto con respecto a la venida de Cristo en la carne para ofrecerse (mediante
el Espíritu eterno) como nuestra única ofrenda santa por el pecado;
como por el amanecer de Su luz,
el derramamiento de Su Espíritu y la aparición de Su gracia en y para el hombre,
de una manera mucho más excelente después de Su ascensión. Porque,
aunque no era una luz o Espíritu diferente a lo que
le había dado al hombre en los siglos anteriores,
sin embargo, era una medida distinta y mayor;
y este es el gran privilegio del Evangelio por encima
de todas las dispensaciones anteriores.

Lo que antes brillaba tenuemente, desde ese momento comenzó a brillar con mayor gloria.
Lo que entonces apareció como un misterio, ahora aparece con el rostro descubierto.
Los tipos,
las figuras y las sombras velaban Sus apariciones y hacían
que Su gloria se viera menos y sin tanta claridad;
pero en el tiempo del Evangelio el velo es rasgado
y la gloria oculta ahora es hecha manifiesta.
Bajo la ley, el Espíritu no era más que un rocío o una ligera lluvia,
pero en el Evangelio, se puede decir que es derramado sobre todos los hombres,
de acuerdo con esa promesa misericordiosa y memorable de Dios por medio del profeta Joel:
"`En los postreros días, derramaré de mi Espíritu sobre toda carne.`"^
footnote:[Joel 2:28; Hechos 2:17]

Cuando llueve abundantemente, decimos, '`¡Mira qué aguacero!`' Así también Dios,
ha aumentado Su luz,
gracia y Espíritu para todos en estos postreros días. No
lo tendrán en pequeñas cantidades ni por pequeñas gotas,
sino de manera plena y libre, y rebosante también. Así Pedro,
ese profundo y excelente apóstol,
aplicó la promesa de Joel al día de Pentecostés como el comienzo de su cumplimiento.
¡Esto verdaderamente es gracia, favor y bondad!
Por lo tanto, esta iluminación mucho más brillante,
este derramamiento mayor del Espíritu, puede llamarse apropiadamente gracia; porque,
tal como la venida del Hijo superó el tiempo de siervo,
así también la manifestación de la luz y del Espíritu de Dios desde la venida de Cristo,
superó la de todas las dispensaciones anteriores; no obstante,
siempre fue suficiente para salvar a todos los que caminaban en ella.

Este es nuestro entendimiento y experiencia de la luz, Espíritu y gracia de Dios.
Y por lo que ha sido dicho, es evidente que son una misma cosa,
y que aquel que tiene la luz, no carece del Espíritu ni de la gracia de Dios,
si tan solo la "`recibe en el amor de ella.`"^
footnote:[2 Tesalonicenses 2:10]
Porque la luz misma que le aparece a él, es también el Espíritu que lo vivifica,
la gracia que lo enseña, lo ayuda y lo consuela,
y esto es suficiente en todas las circunstancias de la vida para
aquellos que con diligencia le prestan atención y la obedecen.

Objeción: Pero algunos todavía podrían decir, "`Si es así como ustedes dicen,
¿por qué entonces todos los que son iluminados, no son tan buenos como deberían ser,
o tan buenos como esta luz busca hacerlos?`"

Respuesta: Porque las personas no la reciben ni la obedecen.
Todos los hombres tienen la capacidad de razonar,
pero no todos los hombres son razonables.
¿Es culpa del grano no producir fruto cuando se encuentra en el almacén,
o del talento no generar interés cuando está escondido en el pañuelo?

Es evidente en la parábola que un talento fue dado;
e igual de evidente que tenía la capacidad de incrementarse--tanto,
porque talentos idénticos habían dado ganancia en las manos de otros, como,
porque el Juez justo esperaba recibir Su talento con intereses.
Ahora bien, ¿de quién fue la culpa de que el talento no se incrementara?
¿No fue el siervo inútil, el que fue infiel en lo poco?
Los ciegos no deben culpar al sol,
ni los pecadores acusar a la gracia de Dios de insuficiencia.
Es el pecado lo que oscurece el ojo,
endurece el corazón e impide que las cosas buenas lleguen a los hijos de los hombres.
Cristo nos dice, "`Si alguno quisiere hacer Su voluntad, conocerá de la doctrina.`"^
footnote:[Juan 17:17 RV 1602 Purificada]
Los hombres que no viven en obediencia a lo que conocen no pueden
culpar a Dios por no conocer más. La esterilidad está en nosotros,
no en el talento, y de verdad sería muy bueno que esto se tomara en serio.

Objeción: Pero algunos todavía objetan:
"`Si la humanidad siempre ha tenido el Espíritu Santo ¿Por qué
las verdades del Evangelio no se conocieron tan plenamente antes
de la venida de Cristo por aquellos que fueron obedientes a Él?

Respuesta: Porque un niño no es un adulto, ni el principio es el final; y, sin embargo,
Aquel quien es el principio también es el final.
El Espíritu es el mismo, aunque no la manifestación,
y aquellos que son fieles a lo que conocen de la
dispensación de su propio día oirán la feliz bienvenida:
"`Bien, buen siervo y fiel.`"^
footnote:[Mateo 25:21]

Y, aun así,
muchos del pueblo de Dios en aquellos días tenían
una visión de la gloria de los postreros tiempos,
del mejoramiento del pacto y de la felicidad de la iglesia de Dios.
Esto lo vemos claramente en la profecía de Jacob y de Moisés acerca
de la restauración de Israel por medio del Mesías. Y David,
en muchos de sus excelentes salmos,
expresa un gozo muy vivo y extraordinario del Espíritu,
y profetiza acerca de cosas por venir.^
footnote:[Particularmente en el Salmo 2, 15, 18, 22, 23, 25, 27, 32, 36, 37, 42, 43, 45,
51, 84, etc.]
Los profetas están llenos de tales expresiones, y por esa razón tienen su nombre.^
footnote:[Particularmente Isaías, capítulos 2, 9, 11, 25, 28, 32, 35, 42, 49, 50, 51, 52,
53, 54, 59, 60, 61, 63, 65, 65, 66. Jeremías también, capítulos 23, 30, 31, 33. Ezequiel,
capítulos 20, 34, 36, 37. Daniel, capítulos 8, 9, 10, 11, 12. Oseas, capítulos 1,
3+++.+++ Joel, capítulos 2, 3. Amós, capítulo 9. Miqueas, capítulos 4 y 5. Zacarías,
capítulos 6, 8, 9, 11, 13, 14. Malaquías, capítulos 3, 4.]
Todo eso no era otro Espíritu, sino otra manifestación de Él mismo.
El Espíritu que vino sobre Moisés fue el mismo que vino sobre Juan el Bautista;
y el Espíritu que vino sobre Gedeón y Sansón, también cayó sobre Pedro y Pablo;
pero no era la misma dispensación de ese Espíritu.

Ha sido la manera de Dios visitar y manifestarse
a los hombres de acuerdo con sus estados y condiciones,
y según hayan sido preparados para recibirlo, ya sea de manera más externa o interna,
física o espiritual.
No hay capacidad humana demasiado baja,
o demasiado elevada para el alcance de este Espíritu Divino; porque,
así como Él los hizo y conoce a todos, así también alcanza a todas las personas.
Él se extiende hasta el más bajo,
y aun así el más alto no puede subsistir sin Él. Esto hizo que David gimiera en su angustia,
diciendo, "`¿A dónde me iré de tu Espíritu?
¿O a dónde huiré de tu presencia?`"^
footnote:[Salmos 139:7]
Aquí implica que el Espíritu está en todas partes,
aunque no está en todas partes o en todo tiempo de la misma manera.
"`Si subiere a los cielos, allí estás Tú: y si en el infierno hiciere mi cama,
he aquí allí Tú estás. Si tomare las alas del alba, y habitare en el extremo de la mar,
aun allí me guiará Tu mano, y me asirá Tu diestra.`"^
footnote:[Salmos 139:8-10 RV1602P]
Sí, incluso allí esta Palabra Divina, esta luz de los hombres, este Espíritu de Dios,
me encontrará, me guiará, me ayudará,
y me consolará. Porque está conmigo en donde sea que esté y a donde quiera que vaya,
de una manera u otra.
"`Te guiará cuando anduvieres; cuando durmieres te guardará;
hablará contigo cuando despertares;`"^
footnote:[Proverbios 6:22]
y sintiéndolo siempre tan presente y cerca, más fácil sería deshacerme de mí mismo,
que deshacerme de Él.

Objeción:
Pero que los judíos hayan tenido esta luz no significa
que los gentiles la tuvieran también;
sin embargo, según su doctrina, todos la tienen.

Respuesta: Sí,
y la gloria de esta doctrina que profesamos es que
ella declara que el amor de Dios es ofrecido a todos.
Y aparte de los textos ya citados (que no podrían
expresarse de manera más completa y positiva),
el apóstol es muy específico en el segundo capítulo de su Epístola a los Romanos,
cuando dice que, "`Los gentiles que no tenían ley,
hacían por naturaleza lo que es de la ley, y eran una ley para sí mismos.`"^
footnote:[Romanos 2:14]
Es decir, no tenían una ley externa como los judíos,
pero tenían "`la obra de la ley escrita en sus corazones,`"^
footnote:[Romanos 2:15]
y, por lo tanto, teniendo la ley en sí mismos, bien podían ser una ley para sí mismos.

De esta manera también los judíos tenían la ley,
pero además tenían mayores ayudas externas para animar su obediencia a ella,
cosas que Dios no concedió a ninguna otra nación. Es por esa razón que se dice
que la obediencia de los gentiles (o la incircuncisión) es por naturaleza,^
footnote:[Romanos 2:14]
o naturalmente, porque era sin esas leyes y señales adicionales,
externas y extraordinarias que los judíos recibieron para incitarlos a cumplir su deber.
Pero esto está tan lejos de descartar a los gentiles obedientes, que más bien,
según el juicio del apóstol, los exalta; porque,
aunque tenían menos ventajas que los judíos, sin embargo,
la obra de la ley escrita en sus corazones se hacía mucho más evidente
por la vida piadosa que vivían en el mundo.

Luego Pablo añade, "`dando testimonio juntamente sus conciencias,
y acusándose mientras tanto, o también excusándose sus pensamientos, unos con otros,
en el día en que juzgará Dios los secretos de los hombres por Jesucristo,
según mi evangelio.`"^
footnote:[Romanos 2:15-16]
Esto nos presenta cuatro cosas a favor de nuestro punto,
y merece nuestra seria reflexión: Primero,
que los gentiles tenían la ley escrita en sus corazones.
Segundo,
que se les permitía que su conciencia fuese un testigo
o evidencia con respecto a su deber.
Tercero,
que el juicio hecho en ella será confirmado por el Evangelio del apóstol en el gran Día,
y, por lo tanto, será válido e irreversible.
Cuarto, que esto jamás podría ser así,
a menos de que la luz que brillaba en la conciencia fuera una luz divina y suficiente.

Objeción: Pero podría decirse: "`Si todo es obra de un solo Espíritu Santo,
entonces ¿por qué existen tantos tipos y formas de religión desde que comenzó el mundo?
Porque la religión patriarcal, mosaica y cristiana, todas tienen sus grandes diferencias;
sin mencionar lo que le ha sucedido a la religión cristiana
desde el día en que comenzó a publicarse al mundo.`"

Respuesta: No sé cómo estos pueden llamarse correctamente religiones diferentes,
ya que todas afirman al verdadero Dios como el objeto de adoración,
al Señor Jesucristo como el único Salvador y a la luz o Espíritu de Cristo como
el gran agente y medio de la conversión del hombre y de su felicidad eterna;
porque esto sería como decir que la infancia,
la juventud y la edad adulta constituyen tres hombres,
en lugar de tres crecimientos o períodos de tiempo de un mismo hombre.
Pero, dejando eso de lado,
las muchas formas o maneras por las que Dios se aparece a los hombres,
surgen (como ha sido dicho), de los diversos estados de los hombres,
en todos los cuales parece haber sido la intención principal de Dios el evitar
la idolatría y el vicio al dirigir sus mentes al verdadero objeto de adoración,
y exigir virtud y santidad.
A los patriarcas Él parece haberles hablado principalmente
por medio de ángeles en forma de hombres,
además de la iluminación interna del Espíritu.
Con los profetas,
mayormente se comunicó por medio de la revelación del Espíritu Santo en ellos, y,
consecuentemente, a los judíos a través de ellos.
Y desde la dispensación del Evangelio, ha hablado por Su Hijo,
tanto externamente por medio de Su venida en la carne,
como internamente por Su aparición espiritual en el alma como la gran luz del mundo.
Sin embargo, en todas estas dispensaciones,
el uso de los instrumentos o agentes externos debe
entenderse como una "`siembra de luz`"^
footnote:[Salmos 97:11]
en la tierra por el mismo Espíritu,
la cual coopera con la manifestación de la luz que se experimenta
directamente en el propio pecho del hombre.

Esto realmente es muy importante,
tanto para nuestra información como para nuestro aliento, que la obra de Dios,
en relación con el hombre, es una y la misma,
y que Su ojo siempre ha estado puesto sobre la misma cosa en todas Sus dispensaciones,
a saber,
hacer a los hombres verdaderamente buenos al sembrar
Su santo temor y temblor en sus corazones.
Sin embargo, Él ha sido condescendiente,
debido a la dureza y oscuridad de los corazones de los hombres, y, por lo tanto,
se ha acercado y les ha revelado Su santa mente a través de formas sencillas y externas,
permitiendo que la Verdad se ponga varios tipos de vestimentas,
con el fin de alcanzar mejor el estado bajo de los hombres,
y apartarlos de los dioses falsos y de las vidas impías.

Y si tan solo consideráramos la razón por la cual la idolatría ha prevalecido en los
tiempos más antiguos y oscuros del mundo (de la cual la Escritura habla ampliamente),
encontraremos que surge a partir de lo siguiente: que su adoración era más física, y,
por lo tanto, diseñada para satisfacer los sentidos de los hombres,
siendo más externa y visible,
y estando más en su propio poder realizarla que una
adoración de una naturaleza más espiritual.
Ellos deseaban ver el objeto de su devoción,
y tener en su poder la capacidad de adorarlo cómo y cuándo lo quisieran.
Por esta razón, Dios, mediante muchos juicios y grandes liberaciones,
engendró un pueblo para Sí Mismo,
para que recordaran y adoraran la Mano que los salvó. Y de este modo,
también buscó desarraigar la idolatría y plantar el conocimiento
y temor de Él en sus mentes como un ejemplo para las otras naciones.
Cualquiera que lea Deuteronomio (que es un resumen de los otros
cuatro libros de Moisés) encontrará el frecuente y ferviente cuidado
y preocupación de ese buen hombre con respecto a este mismo punto,
y verá con qué frecuencia Israel se deslizó y reincidió (a pesar del amor,
cuidado y paciencia de Dios para con ellos),
en las costumbres idólatras de las naciones a su alrededor.^
footnote:[Varias otras Escrituras nos informan lo mismo,
especialmente las de los profetas, Isaías 54 y 4, Salmos 37, 115, y Jeremías 10,
donde el Espíritu Santo confronta y reprende al pueblo,
y se burla de sus ídolos con una especie de desprecio santo.
--W. P.]

Ahora bien,
el Espíritu de Dios (del que hemos hablado) es totalmente contrario a la idolatría,
y por lo tanto es el mejor antídoto contra ella.
Y cuanto más las mentes de las personas se vuelvan y se acerquen a Él,
y cuanto más su fe,
adoración y obediencia se liguen a la santa iluminación y al poder de Él mismo,
más se acercan al propósito de su creación, y, por consiguiente, a su Creador.
Estos están más calificados espiritualmente,
y llegan a estar mejor preparados para adorar a Dios tal como Él es;
porque (como nos dice nuestro Señor Jesucristo), Él es Espíritu,
y será adorado en Espíritu y en Verdad.
Estos son los adoradores que Dios busca que le adoren en este día del Evangelio.

Cristo dice: "`La hora viene, y ahora es;`"^
footnote:[Juan 4:23]
es decir, '`algunos ahora lo hacen,
pero más lo harán`'--lo cual fue una afirmación muy precisa para el tiempo presente,
y una promesa y profecía del aumento de tales adoradores en el futuro.
Esto muestra que se pretendía un cambio de la adoración
y estado ceremoniales de la iglesia de Dios,
a la adoración y estado espirituales.
Y esto quiere decir el siguiente texto, "`Mas la hora viene, y ahora es,
cuando los verdaderos adoradores adorarán al Padre en Espíritu y en Verdad;`"^
footnote:[Juan 4:23]
es decir, cuando la adoración de Dios será más interna que externa, y por lo tanto,
más conforme a la naturaleza de Dios y a la parte
más noble del hombre--el hombre interior y mejor.
Esta adoración es en el Espíritu, es decir, a través del poder del Espíritu; y en Verdad,
es decir, en la substancia, no en sombras, ceremonias o formalidades.
He aquí, una adoración en sinceridad, con y en la vida de Dios,
siendo divinamente preparada y vivificada,
que hace que el hombre ofrezca lo que es agradable para Él,
y eleve su alma a una íntima comunión y unión con Dios, quien es Espíritu.

Y si esto se considera debidamente, será evidente que Dios,
en todas las diferentes manifestaciones de Sí Mismo,
se ha acercado cada vez más al interior de los hombres,
a fin de alcanzar sus entendimientos,
abrir sus corazones y darles una relación más plena y cercana con Él Mismo en el Espíritu.
Es allí, en el corazón,
donde el hombre debe buscar y encontrar el conocimiento
de Dios para su felicidad eterna.

Todas las cosas que son hechas muestran el poder
y la sabiduría de Dios y Su bondad para con la humanidad.
De hecho,
muchos recurren a la majestuosidad de la creación
para silenciar las objeciones ateístas de los hombres.
Pero, aunque todas las cosas creadas muestran que hay un Dios, sin embargo, el hombre,
por encima de todo, es el que más lo muestra.
Él es la piedra preciosa en el anillo, y la joya más gloriosa del planeta.
El hombre es una composición de ambos mundos; su cuerpo es de éste,
su alma del otro mundo.
El cuerpo es como el templo del alma, el alma el templo de la Palabra viva,
y la Palabra el gran templo y manifestación de Dios.
Mediante el cuerpo, el alma observa y contempla la creación,
y por la Palabra contempla a su Dios y al mundo que no tiene fin.
Mucho podría decirse de este orden de las cosas, pero deseo ser breve.
