== Capítulo V

[.chapter-subtitle--blurb]
Las Doctrinas de la Justificación y la Salvación

Ha habido muchos rumores y acusaciones falsas sobre nosotros,
de parte de nuestros adversarios en relación con las siguientes e importantes doctrinas:
1+++.+++ Cómo el sacrificio de Cristo hizo que Dios quedara satisfecho por nuestros pecados,
y 2. Cuál es el fundamento de la justificación de un pecador ante Dios.
Primero hablaré negativamente en cuanto a lo que _no creemos_,
lo cual quizás haya dado ocasión a los que han sido más apresurados que sabios,
para juzgar como deficiente nuestra creencia en la eficacia de
la muerte y los sufrimientos de Cristo para justificación.

En primer lugar,
nosotros no podemos creer que los sufrimientos y
la muerte de Cristo hagan que Dios quede satisfecho,
o justifiquen a los hombres, de tal forma que sean inmediatamente aceptados por Dios.
Creemos que ellos, por dichos sufrimientos y muerte,
son verdaderamente puestos en un estado en el que
tienen la capacidad de ser aceptados por Dios,
pero que es a través de la obediencia de la fe y de la santificación del Espíritu,
que llegan a un verdadero estado de aceptación. Jamás podremos
considerar que un hombre esté justificado delante de Dios
mientras siga condenándose a sí mismo en su propio corazón,
o que algún hombre pueda estar en Cristo sin ser una nueva criatura;
o que Dios considere a los hombres de manera diferente a lo que realmente son.
Creemos que es un estado de presunción y no de salvación llamar a Jesús Señor,
y no por la obra del Espíritu Santo; o Maestro, cuando aún no es maestro de sus afectos;
o Salvador cuando no son salvos por Él de sus pecados;
o Redentor cuando aún no han sido redimidos por Él de su pasión, orgullo, codicia,
vanidad, honores vanos, y de las amistades y gloria de este mundo.
Creemos que esto es engañarse a sí mismo, porque Dios no será burlado;
lo que el hombre siembre, eso también debe cosechar.
Y aunque ciertamente Cristo murió por nosotros, aun así,
con la ayuda de Su gracia debemos "`obrar nuestra salvación con temor y con temblor.`"^
footnote:[Filipenses 2:12 RV 1602 Purificada]
Así como Él murió por el pecado, nosotros también debemos morir al pecado,
o no podemos decir verdaderamente que somos salvos por la muerte y sufrimientos de Cristo,
o que estamos completamente justificados y aceptados ante Dios.

[.offset]
Ahora hablaré de manera positiva lo que creemos con respecto a la justificación:

Sin ninguna duda creemos que Jesucristo fue nuestro santo sacrificio,
expiación y propiciación; que Él llevó nuestras iniquidades,
y que por Su llaga fuimos curados de las heridas que Adán nos hizo en su caída;
y que Dios es justo al perdonar a los que están verdaderamente
arrepentidos por el mérito de esa santa ofrenda,
que Cristo hizo de Sí Mismo a Dios por nosotros.
Creemos que lo que Cristo hizo y padeció ha satisfecho y ha agradado a Dios,
y que fue por el bien del hombre caído que había desagradado a Dios.
Y es a través de la ofrenda de Sí mismo hecha una
vez para siempre mediante el Espíritu eterno,
que Él "`hizo perfectos para siempre a los que (en todos los tiempos) son santificados,`"^
footnote:[Hebreos 10:14]
los que no han caminado "`conforme a la carne, sino conforme al Espíritu.`"^
footnote:[Romanos 8:1, 4.]

En resumen, creemos que la justificación consta de dos partes,
o debe considerarse en dos aspectos--a saber:
la justificación de la culpa del pecado y la justificación
del poder y la contaminación del pecado;
y es en función de estos dos aspectos de la justificación,
que el hombre llega a una aceptación plena y evidente delante de Dios.
Y es debido a la carencia de esta última parte,
que muchas almas (que tienen inclinaciones religiosas) a menudo tienen dudas,
escrúpulos y desesperación,
a pesar de todo lo que sus maestros les dicen acerca del alcance
y la eficacia de la primera parte de la justificación. Y es un
error demasiado común entre los profesantes del cristianismo,
tratar de encubrir su propia desobediencia activa
y pasiva con la obediencia activa y pasiva de Cristo.

En cuanto a la primera parte de la justificación,
nosotros reconocemos con reverencia y humildad,
que es únicamente en virtud de la muerte y sufrimientos de Cristo.
No es nada que podamos hacer, sino algo que es hecho por la operación del Espíritu Santo,
que es capaz de cancelar las deudas pasadas y borrar las cuentas antiguas.
Es el poder y eficacia de esta ofrenda propiciatoria,
por medio de la fe y el arrepentimiento, lo que nos justifica de los pecados pasados;^
footnote:[Véase Romanos 3:25]
y es el poder del Espíritu de Cristo en nuestros corazones,
lo que nos purifica y nos hace aceptos ante Dios.
Porque hasta que el corazón del hombre sea purgado del pecado,
Dios nunca lo aceptará. Él reprueba,
reprende y condena a los que hospedan el pecado allí,
y no se puede decir correctamente que estos están en un estado justificado--ya
que la condenación y la justificación son cosas contrarias.
Por lo tanto,
aquellos que creen que están en un estado de justificación
debido a la obediencia activa y pasiva de Cristo,
incluso cuando no son activa y pasivamente obedientes al Espíritu de Cristo Jesús,
están bajo un engaño fuerte y peligroso ¡Y por clamar en
contra de esta imaginación (y doctrina) a favor del pecado,
es que somos considerados y reprochados como una gente que niega y desprecia
la muerte y los sufrimientos de nuestro Señor Jesucristo!

Pero que todos aquellos que caminan en impiedad y que al
mismo tiempo tienen una profesión de justificación,
sepan lo siguiente:
ustedes les suman a los sufrimientos de Cristo y
crucifican de nuevo para sí mismos al Hijo de Dios,
hollando bajo sus pies la sangre de Su pacto.
Porque Dios no tomará por inocentes a los culpables,
ni justificará a los desobedientes e infieles.
Ustedes se engañan a sí mismos, y en el gran juicio final su sentencia no será, "`venid,
benditos,`" porque no se les podrá decir, "`Bien,
buen siervo y fiel;`" sino más bien "`Apartaos de mí,
malditos,`" porque viven y mueren en un estado reprobable y condenable.
Porque ninguno realmente experimenta a Cristo como su sacrificio,
si lo rechaza como su santificador;
porque el propósito de Su venida es salvar a Su pueblo
de la naturaleza y contaminación del pecado,
así como de la culpa del mismo.
Por consiguiente, aquellos que resisten Su luz y Espíritu,
hacen que Su venida y ofrenda no tengan efecto para ellos.

Por lo tanto ¡oh mi lector!
No descanses, ni te sientas totalmente satisfecho con lo que Cristo
ha hecho por ti en Su bendita Persona fuera de ti,
sino esfuérzate por experimentar Su poder y reino dentro de ti,
para que el hombre fuerte (que por mucho tiempo ha dominado tu casa) pueda ser atado,
sus bienes despojados, sus obras desechas y el pecado terminado,
de acuerdo con 1 Juan 3:5-8. Es para esto, dice ese discípulo amado, que Cristo apareció;
para que todas las cosas sean hechas nuevas--nuevos cielos y nueva tierra,
en los cuales mora la justicia.
En esto llegarás a glorificar a Dios en tu cuerpo y en tu espíritu, los cuales son de Él;
y así vivir para Él y no para ti mismo.
En verdad, tu amor, gozo, adoración y obediencia; tu vida, conducta y práctica;
tu estudio, meditación y devoción, todo esto será espiritual.

El Padre y el Hijo harán su morada contigo, y Cristo se te manifestará;
porque el secreto del Señor es para los que le temen,
y estos tienen una unción santa que los guía a toda verdad,
sin necesidad de las enseñanzas de los hombres.
Sí, estos son enseñados de una mejor manera, ya que son instruidos por el oráculo Divino.
Ellos no son simples cristianos de oídas o tradicionales,
sino frescos y vivos testigos--aquellos que han visto con sus propios ojos,
oído con sus propios oídos y palpado con sus propias manos, la Palabra de vida,
en sus diversas operaciones, para la salvación de sus almas.
En esta Palabra se reúnen, en ella predican, y en ella oran y alaban.
¡He aquí el nuevo pacto cumplido, la iglesia, la unción, y la adoración de Cristo!

=== La Salvación por medio de Cristo

Y para evitar que alguien diga que somos ambiguos en nuestras expresiones,
y que consideramos la aparición de Cristo en la carne como una alegoría
que solo se refiere a Su aparición interna en nuestra propia carne;
o que todas las veces que lo mencionamos a Él hablamos únicamente del misterio,
o del sentido espiritual y místico de Él,
es mi deseo preservar a todos de ser engañados por tales insinuaciones,
e informar y recuperar a aquellos que están bajo el prejuicio de tales malentendidos,
al declarar lo siguiente: Nosotros realmente creemos y confesamos,
para la gloria de Dios Padre y el honor de Su querido y amado Hijo,
que Jesucristo tomó nuestra naturaleza sobre Él, y fue como nosotros en todas las cosas,
con excepción del pecado.
Creemos que nació de la virgen María, que sufrió bajo Poncio Pilato,
el gobernador Romano, que fue crucificado,
muerto y sepultado en el sepulcro de José de Arimatea, que resucitó al tercer día,
ascendió al cielo y está sentado a la diestra de Dios,
en el poder y majestad de Su Padre, quien en un día juzgará al mundo por medio de Él--sí,
por ese bendito Hombre, Jesucristo--de acuerdo con sus obras.

Pero debido a que nosotros creemos esto, también debemos creer en lo que Cristo ha dicho,
"`Aquel que mora con vosotros estará en vosotros.`"^
footnote:[Juan 14:17]
"`Yo en ellos, y ellos en Mí,`"^
footnote:[Juan 14:20] etc.
Y en las muchas declaraciones similares de los apóstoles:
"`Pero cuando agradó a Dios revelar a su Hijo en mí.`"^
footnote:[Gálatas 1:16]
"`El misterio que había estado oculto desde los siglos y edades;
que es Cristo en vosotros, la esperanza de gloria.`"^
footnote:[Colosenses 1:27]
"`¡A menos que Jesucristo esté en vosotros, estáis reprobados!`"^
footnote:[2 Corintios 13:5]
¿O deberíamos ser considerados como un pueblo que niega la venida de Cristo en la carne,
y todas las partes y ramas de Su obra y sufrimientos solo
porque creemos y enfatizamos la necesidad de creer,
recibir y obedecer Su aparición y manifestación interna y espiritual, a través de Su luz,
gracia y Espíritu en los corazones y las conciencias de hombres y mujeres,
para reprobarlos, convencerlos, convertirlos y cambiarlos?
Esto nos parece un trato duro e injusto de parte de nuestros adversarios.

Sin embargo, nosotros estamos listos para declararle al mundo entero,
que no podemos creer que los hombres y mujeres puedan
ser salvos solo creyendo en la obra externa,
sin sentir ni experimentar la interna.
Es a esto a lo que nos oponemos, y no a Su bendita manifestación en la carne.
Porque nosotros confesamos libremente que Cristo, en ese tiempo,
venció a nuestro común enemigo, lo derrotó públicamente,
y (participando de nuestra naturaleza),
triunfó sobre aquel que había triunfado sobre ella^
footnote:[Es decir, la naturaleza del hombre,
refiriéndose a la conquista de Satanás y a su largo
reinado en y sobre la naturaleza caída de la humanidad.]
en nuestro antepasado Adán y en toda su posteridad.
Sin embargo, de la misma manera que Cristo realmente lo venció en Su propia persona,
así también, al recibir y obedecer Su gracia Divina, Él vence al enemigo en nosotros;
es decir,
lo detecta con Su luz en la conciencia y capacita
a la criatura para resistir sus dardos de fuego,
para pelear la buena batalla de la fe y vencer, y para echar mano de la vida eterna.

Esta es la dispensación de la gracia que declaramos que se ha manifestado a todos,
en diversas medidas,
enseñando (a todos los que están dispuestos a recibirla)
"`a renunciar a la impiedad y a los deseos mundanos,
y a vivir en este mundo sobria, justa y piadosamente,
aguardando la esperanza bienaventurada y la manifestación
gloriosa de nuestro gran Dios y Salvador Jesucristo.`"^
footnote:[Tito 2:11-13]
Y puesto que nosotros ministramos a los demás a partir de la enseñanza,
experiencia y operación de esta gracia,
el propósito mismo de nuestro ministerio es volver los corazones
de las personas a esta gracia que se encuentra en su interior,
para que todos puedan hacer la buena y agradable voluntad de Dios,
y trabajar su salvación con temor y con temblor,
haciendo firme su llamado y elección celestiales.

Porque lo que el hombre sembrare, eso segará;
y él es el esclavo de aquel a quien obedezca.
Debemos experimentar una verdadera regeneración,
o no podemos ser hijos de Dios ni herederos de la gloria eterna.
Para nacer de nuevo, otro Espíritu debe prevalecer en nosotros, leudarnos,
sazonarnos y gobernarnos, aparte del espíritu del mundo,
o de nuestros propios espíritus depravados.
Este no puede ser otro Espíritu que aquel que moraba en Cristo; porque está escrito que:
a menos que Su Espíritu more en nosotros, no somos de Él,
Romanos 8:9. Este Espíritu comienza por la convicción,
y termina en la conversión y en la perseverancia;
la una necesariamente siguiendo a la otra.
Porque la conversión es la consecuencia de obedecer las convicciones,
y la perseverancia es un fruto natural de la conversión y de haber nacido de Dios.
Tales como estos "`no practican el pecado,
porque la Simiente de Dios permanece en ellos,`"^
footnote:[1 Juan 3:9]
y por medio de la fidelidad continúan hasta el fin y obtienen la promesa, es decir,
la vida eterna.

Pero que mi lector esté seguro de que nosotros sí reconocemos que Cristo,
a través de Su santa obra y sufrimiento,
ha obtenido misericordia de Dios Su Padre para la humanidad,
y que Su obediencia tiene una gran influencia sobre
nuestra salvación en todas sus partes y ramas,
ya que por ella se hizo vencedor,
llevó cautiva la cautividad y obtuvo dones para los
hombres (con otras preciosas y grandísimas promesas),
para que "`llegásemos a ser participantes de la naturaleza divina,
habiendo huido de la corrupción que hay en el mundo a causa de la concupiscencia.`"^
footnote:[2 Pedro 1:4]
En verdad,
creemos y confesamos que la obediencia activa y pasiva
de Cristo Jesús influye en toda nuestra salvación,
salvándonos del poder y contaminación del pecado, como también de la culpa,
siendo Él un conquistador como también un sacrificio,
y ambas cosas a través del sufrimiento.
Sin embargo, aquellos que rechazan el don divino que Él obtuvo de esta manera,
y que Él les ha dado,
(mediante el cual pueden ver su pecado y la pecaminosidad del mismo,
y arrepentirse y apartarse de él),
y que no esperan en Dios por fuerza diaria para resistir los dardos de fuego del enemigo,
y para ser confortados a través de la obediencia de la fe en esta
gracia divina del Hijo de Dios--tales como estos no agradan a Dios,
ni realmente creen en Dios,
ni están en un estado de verdadero cristianismo o salvación.
"`Mujer,`" le dijo Cristo a la samaritana en el pozo,
"`Si conocieras el don de Dios, y quién es el que te habla,`"^
footnote:[Juan 4:10]
etc.
Las personas no conocen a Dios ni a Cristo, "`a quien conocer es la vida eterna,`"^
footnote:[Juan 17:3]
porque ignoran el don de Dios, es decir,
la "`manifestación del Espíritu de Dios dada a cada uno para provecho;`"^
footnote:[1 Corintios 12:7]
el cual le revela a Cristo y a Dios al alma.

La carne y la sangre no pueden hacer esto;
ser educados en Oxford y en Cambridge no pueden hacer esto;
los idiomas y la filosofía no pueden hacer esto;
porque aquellos que "`mediante la sabiduría no conocieron a Dios,`"^
footnote:[1 Corintios 1:21]
tenían estas cosas como su sabiduría. Eran fuertes,
profundos y precisos en ese tipo de conocimiento; pero ¡ay! estaban nublados,
envanecidos y distanciados del conocimiento interno y salvador
de Dios porque lo buscaban donde no puede ser hallado.
Sin embargo, la llave de David es otra cosa, la cual cierra y ninguno puede abrir,
y abre y ninguno puede cerrar.
Y todos los que reciben el don de Dios en sus corazones encuentran esta llave,
y ella les abre el conocimiento de Dios y de sí mismos, y les da una visión,
sabor y juicio de las cosas que es muy diferente a lo que
su conocimiento intelectual o tradicional les puede dar.
Este es el principio de la nueva creación de Dios,
y por ello nos convertimos en nuevas criaturas.

Por lo tanto, nos atrevemos a declarar que no hay otro camino como este,
por el cual las personas puedan llegar a Cristo, o ser verdaderos cristianos,
o recibir el beneficio que viene por causa de los
sufrimientos y la muerte del Señor Jesucristo.

Y, por lo tanto, decimos--y con buena autoridad,
incluso la de nuestra propia experiencia,
así como también la de las Escrituras de la Verdad--que Cristo no será
un sacrificio salvador para aquellos que se nieguen a obedecerlo.
Los que rechazan el don, niegan al Dador,
en lugar de negarse a sí mismos por amor al Dador.
¡Ojalá que las personas fueran sabias,
que consideraran el fin que les espera y las cosas que son para
su paz eterna! ¿Por qué morirían en una vana esperanza de vida,
mientras que la muerte todavía reina en el corazón? ¿O por
qué tendrían la esperanza de vivir para siempre con Dios,
cuando no viven para Él, ni caminan con Él ahora?
¡Despierta tú que duermes en tu pecado, o, en el mejor de los casos,
en tu propia justicia! ¡Despierta, te digo, y Cristo te dará vida!
Porque Él es el Señor del cielo, el Espíritu que da vida,
quién nos vivifica por Su Espíritu,
si no lo resistimos ni contristamos con nuestra desobediencia, sino al contrario,
lo recibimos, amamos y obedecemos en todas sus santas directrices y enseñanzas.
"`Porque todos los que son guiados por el Espíritu de Dios, éstos son hijos de Dios.`"^
footnote:[Romanos 8:14]

A este Espíritu Santo te encomiendo, mi lector, para que puedas ver mejor dónde está Él,
y llegar a la verdadera creencia y beneficio de los hechos
y sufrimientos de nuestro bendito Señor y Salvador Jesucristo.
Porque, en verdad, Él salva tanto del poder y de la contaminación del pecado,
como de su culpa, en el corazón de todos los que oigan Su llamado,
le abran la puerta de sus corazones,
y le permitan realizar una reforma real y completa en y para ellos.
De este modo, el beneficio,
virtud y eficacia de Sus hechos y sufrimientos fuera de nosotros,
llegarán a aplicarse y a experimentarse de manera viva y efectiva dentro de nosotros,
y también se sentirá y conocerá una comunión con Cristo en Su muerte y sufrimientos,
de acuerdo con la doctrina de los apóstoles.
Pero aquellos que continúan viviendo en ese pecado que hizo sufrir a Cristo,
demuestran que no lo conocen,
aunque profesan ser salvos por causa de Su muerte y sufrimientos.

Concluyo este capítulo con este ferviente deseo: aunque las personas confundan,
malinterpreten o tergiversen nuestros puntos de vista sobre este importante tema,
ruego que no se engañen a sí mismos en el gran asunto de su propia salvación,
y que mientras felizmente declaran que Cristo lo ha hecho todo,
sean repudiados por Él en el último día. Lee el capítulo 7 de Mateo:
es aquel que oye a Cristo--la gran Palabra de Dios--y hace lo que Él ordena,
manda y recomienda por Su propio bendito ejemplo,
que es comparado con un edificador prudente que puso un fundamento sólido.
Ninguna otra casa permanecerá en el temblor y juicio final.
Por esta razón, a menudo tratamos de manera clara, directa y seria a las personas,
para que consideren que Cristo no vino a salvarlos _en,_ sino _de_ sus pecados.
Aquellos que piensen desprenderse de Su yugo y carga, de Su cruz y ejemplo,
y se sientan seguros alabando a Cristo por haber hecho todo
por ellos (mientras que Él ha hecho poco o nada en ellos,
ni han dejado nada por amor a Él),
finalmente despertarán con una espantosa sorpresa al oír el sonido de la última trompeta,
y de esta triste e irrevocable sentencia, "`apartaos de mí, hacedores de maldad,
nunca os conocí.`"^
footnote:[Mateo 7:23; Lucas 13:27]
Es mi deseo que todos eviten este terrible final al escuchar a tiempo la voz de la sabiduría
y volverse a Su reprensión. Porque sin duda los guiará por caminos de justicia,
y en medio de las sendas del juicio sus almas llegarán a heredar la sustancia--sí,
riquezas duraderas y la justicia en el reino de Dios.
