== Capítulo VI

[.chapter-subtitle--blurb]
Con Respecto a la Verdadera Adoración de Dios y al Verdadero Ministerio,
que es por Su Espíritu.

Ahora bien,
a medida que el Señor obraba eficazmente en los corazones
de este pueblo mediante Su gracia divina,
Él los llevaba a una adoración y ministerio divinos,
por los cuales llegaron a experimentar las palabras de Cristo: "`Dios es Espíritu;
y los que le adoran,
en espíritu y en verdad es necesario que adoren...
porque el Padre tales adoradores busca que le adoren.`"^
footnote:[Juan 4:24, 23]
Porque habiéndose sometido a las convicciones del Espíritu en el curso diario
de sus vidas (por el cual fueron enseñados a renunciar a toda especie de mal,
y a hacer lo que era bueno),
ellos entonces se sentaban y esperaban la preparación del Espíritu Santo en sus reuniones,
con el fin de ver sus verdaderos estados y condiciones ante el Señor,
y de adorarlo de manera aceptable.
Y en la medida que sentían alguna necesidad, deficiencia o debilidad,
en el secreto de sus propios corazones,
brotaba una oración a Dios a través de Jesucristo, por ayuda,
asistencia y provisión. Pero no se atrevían a despertar a su Amado antes de Su tiempo,^
footnote:[Cantares 2:7, 3:5, 8:4]
ni a acercarse al trono del Rey de gloria hasta que extendiera Su cetro.^
footnote:[Ester 4:11, 5:2, 8:4]
Tampoco se preocupaban por lo que habían de decir,
ni ofrecían sus propias palabras y formas estudiadas (o las de otros hombres),
porque habían aprendido que esto era ofrecer "`fuego extraño;`"^
footnote:[Levíticos 10:1]
era orar, pero no por el Espíritu; era pedir, pero no en el nombre.
Porque el nombre es el poder de nuestro Señor Jesucristo,
quien oraba y hablaba como uno que tenía autoridad, es decir, con poder,
energía divina y una fuerza que alcanzaba y penetraba los cielos.
Y este poder se lo da a todos los que obedecen Su luz,
gracia y Espíritu cuando esperan solemnemente en Él. Por consiguiente,
es el principio de este pueblo, que el fuego debe venir del cielo,
la vida y poder deben venir de Dios,
para que el alma pueda derramarse a sí misma de manera aceptable delante
de Él. Y cuando un carbón de Su santo altar toca nuestros labios,
entonces podemos orar y alabarlo como conviene.

Y así como este es nuestro principio (que es de acuerdo con las Escrituras),
también es nuestra experiencia y práctica; y, por lo tanto,
nos hemos separado de la adoración de los hombres, en sus diversas formas,
porque no está fundada en la operación, movimiento y ayuda del Espíritu de Cristo,
sino en la designación, invención y creación del hombre,
tanto en materia como en palabras y tiempo.
No es en nuestra propia voluntad que disentimos de los demás,
sino que no nos atrevemos a conformarnos a ellos en contra de la voluntad
de Aquel que nos ha llamado y llevado a Su propia adoración espiritual.
Sí,
es por obediencia a Él que somos lo que somos en nuestra separación
de las muchas formas de adoración en el mundo.

Además,
tal como nuestra adoración consiste en la operación
del Espíritu de la Verdad en nuestro interior,
así es también en nuestro ministerio.
Porque,
así como los testimonios de los siervos de Dios en la antigüedad
surgían de la operación de Su bendito Espíritu,
así deben hacerlo los testimonios de Sus siervos en cada época;
y todo lo que no tenga el Espíritu de Cristo como su fuente y origen no es de Cristo,
sino del hombre.
Según las Escrituras, los ministros cristianos deben ministrar lo que reciben.
Y lo que recibimos no es nuestro, y mucho menos de otro hombre,
sino más bien del Señor. En consecuencia,
no solo debemos dejar de robar las palabras de nuestros prójimos,
sino que también debemos tener cuidado de no estudiar o hablar nuestras propias palabras.
Porque Cristo les dijo a Sus ministros, "`Mas cuando os entreguen,
no os preocupéis por cómo o qué hablaréis;
porque en aquella hora os será dado lo que habéis de hablar.
Porque no sois vosotros los que habláis,
sino el Espíritu de vuestro Padre que habla en vosotros.`"^
footnote:[Mateo 10:19-20]
Ahora bien,
si no debemos estudiar lo que diremos ante los magistrados en defensa de nosotros mismos,
mucho menos deberíamos estudiar lo que diremos de parte de Dios a Su pueblo.
"`Si alguno habla, hable como los oráculos de Dios; si alguno ministra,
ministre conforme al poder que Dios da.`"^
footnote:[1 Pedro 4:11 Traducción Literal del Inglés]
Debemos ministrar como los oráculos de Dios, y, por lo tanto, debemos recibir de Cristo,
el gran Oráculo de Dios, lo que tenemos que ministrar.
Y si ministramos lo que recibimos, entonces no es lo que estudiamos,
recolectamos ni extraemos de nuestros cerebros, porque esto no es la mente de Cristo,
sino nuestras propias imaginaciones, y no serán de provecho alguno para el pueblo.

Esto se lo recomendó el apóstol Pablo a los Corintios en 1 Corintios 14, es decir,
que ellos debían hablar según eran movidos, o,
a medida que algo les era revelado por el Espíritu para la edificación de la iglesia.
"`Porque,`" dice Él, "`todos pueden profetizar;`" es decir,
todos pueden predicar para edificación,
en la medida que algo les sea revelado para el bien de los demás,
y según el Espíritu les da que hablen.^
footnote:[Véase 1 Corintios 14:29-31]
Y sabiendo que el Espíritu tiene que darles a los ministros de Cristo lo que deben hablar,
por esta razón,
aquellos a quienes Él ha preparado y enviado tienen temor y cuidado
de no decir nada en Su nombre que no provenga de Su Espíritu.
Por consiguiente, los que corren antes del verdadero Guía,
y pronuncian palabras sin conocer la mente del Espíritu,
no son de los verdaderos ministros de Cristo.
Estos ciertamente corren, pero Dios no los ha enviado,
y no pueden ser de provecho alguno para el pueblo.^
footnote:[Jeremías 23:32 LBLA]
Y en realidad ¿cómo podrían serlo?
Porque es imposible que un simple hombre, con todas sus habilidades,
artes y conocimientos,
convierta a las personas de las tinieblas a la luz,
y de la potestad de Satanás a Dios,
que es el propósito y la obra del ministerio del Evangelio.
De hecho, los hombres inspirados, dotados por Dios,
enseñados e influenciados por Su Espíritu celestial,
son los únicos que están calificados para una obra tan grande, tan interna,
y tan espiritual.

Se dice que los ministros de Cristo son Sus testigos,
y el crédito de un testigo es que ha oído, visto o tocado algo verdadero.
Por eso,
el discípulo amado declara la verdad y autoridad
de su misión y ministerio con las siguientes palabras:
"`Lo que hemos oído, lo que hemos visto con nuestros ojos, lo que hemos contemplado,
y palparon nuestras manos, eso os anunciamos,
para que también vosotros tengáis comunión con nosotros;
y nuestra comunión verdaderamente es con el Padre, y con su Hijo Jesucristo.`"^
footnote:[1 Juan 1:1-3]
Yo digo, si los ministros de Cristo son Sus testigos, ellos deben _conocer_ lo que hablan;
es decir,
deben haber experimentado y pasado a través de los diversos
estados y condiciones acerca de los cuales predican,
y conocer en la práctica las verdades que le declaran al pueblo.
De lo contrario, no han entrado por la puerta, sino que han trepado la pared,
y son ladrones y salteadores.

Él que tiene la llave de David entra por la puerta (la cual es Jesucristo),
y es admitido y aprobado por Él, siendo ungido por Él,
el único Sumo Sacerdote de la dispensación del Evangelio.
Él es el que sopla y pone Sus manos sobre Sus propios ministros.
Sí, Él los unge, rellena sus vasijas y renueva sus cuernos con aceite,
para que lo tengan fresco para cada ocasión y servicio al que Él los llame y envíe.

Y así como de gracia reciben, de gracia dan; ellos no enseñan por precio,
ni adivinan por dinero, ni predican por dones ni recompensas.
Dar de gracia, era un mandamiento santo de Cristo para Sus ministros,
y esta es nuestra práctica.
Y en verdad pensamos que es extraño que esto se considere como un error,
y que predicar por precio no se vea como una característica de los falsos profetas,
cuando contra esto habían clamado los verdaderos profetas
de Dios con tanta frecuencia y severidad en el pasado.
No es mi intención ofender,
pero sería sabio recordar el caso de uno que anteriormente ofreció dinero para ser ministro,
y la respuesta que recibió de parte del apóstol Pedro,
Hechos 8:18-20. Que el Señor toque los corazones de aquellos que
están dando su dinero para convertirse en ministros profesionales,
con la intención de vivir de su predicación,
para que puedan ver sobre qué fundamento están edificando.
Ojalá que se arrepientan y se vuelvan al Señor,
para que hallen misericordia y se conviertan en testigos
vivos de Su poder y bondad en sus propias almas.
Entonces podrán contarles a otros lo que Dios ha hecho por ellos,
lo cual es la raíz y fundamento de todo ministro verdadero, y aquello que Dios bendice.

[.discourse-part]
Objeción:
Pero ¿acaso no tiende este tipo de ministerio y adoración
hacer que algunas personas sean ociosas,
y a levantar el orgullo espiritual en otros?
Y, ¿acaso no da ocasión para grandes problemas e impiedad?

[.discourse-part]
Respuesta: De ninguna manera,
porque el fin de todas las palabras es llevar a las personas a la gran Palabra,
Jesucristo, y entonces se cumple la promesa de Dios,
que "`todos serán enseñados por el SEÑOR,
desde el más pequeño de ellos hasta el más grande, y en justicia serán establecidos,
y grande será su paz.`"^
footnote:[Isaías 54:13-14; Jeremías 31:34: Hebreos 8:11]
El discípulo amado concuerda con está declaración de Isaías,
y por lo tanto da una respuesta completa a esta objeción:
"`Os he escrito esto sobre los que os engañan. Pero la unción
que vosotros recibisteis de Él permanece en vosotros,
y no tenéis necesidad de que nadie os enseñe;
así como la unción misma os enseña todas las cosas, y es verdadera, y no es mentira,
según ella os ha enseñado, permaneced en Él.`"^
footnote:[1 Juan 2:26-27]
Hay tres cosas aquí que son muy dignas de nuestra atención: Primero,
que Juan escribió su epístola con una intención particular, esto es,
para evitar que fueran engañados.
En segundo lugar,
que él los encomienda a un ministro más cercano y superior que él mismo, a saber,
la unción o gracia que habían recibido y que los acompañaría en todas las situaciones.
En tercer lugar, que si ellos solo prestaran atención a sus enseñanzas,
no tendrían necesidad de las instrucciones de los hombres,
ni tendrían temor de ser engañados.
En este mismo sentido, el apóstol Pablo también les habló a los tesalonicenses, diciendo,
"`Pero acerca del amor fraternal no tenéis necesidad de que os escriba,
porque vosotros mismos habéis aprendido de Dios que os améis unos a otros.`"^
footnote:[1 Tesalonicenses 4:9]

Sin embargo, las ayudas externas son útiles y una gran bendición cuando son de Dios.
Así era Juan el Bautista; pero recuerden que él dirigía a todos a Cristo, diciendo,
"`¡He aquí el Cordero de Dios!`"^
footnote:[Juan 1:29, 36]
"`Yo a la verdad os bautizo en agua, pero Él os bautizará en Espíritu Santo y fuego.`"^
footnote:[Mateo 3:11; Lucas 3:16]
Todo verdadero ministerio hace lo mismo.
Y dondequiera que haya personas de mente carnal,
que estén bajo un eclipse oscuro por el reino del pecado y de Satanás,
Dios se complace en enviar a Sus iluminados siervos para despertarlas
y hacerlas volver de las tinieblas a la luz que brilla en sus corazones,
para que, a través de la obediencia a ella, lleguen a ser hijos de la luz,
y tener su comunión en ella,
y finalmente una herencia con los santos en la luz para siempre.

Y puesto que esta es la manera en que Dios ha escogido llamar y reunir a Su pueblo,
entonces un ministerio vivo y santo es de gran ventaja,
para velar sobre los jóvenes y edificarlos,
y para consolar y establecer a los débiles y simples.
Pero, aun así, yo digo, cuanto más interno, menos externo.
Es decir,
mientras más personas sean enseñadas directamente por Dios
a través de la luz de Su Palabra y Espíritu en sus corazones,
menos necesidad tendrán de medios externos.
Porque el profeta escribe:

[quote.scripture, , Isaías 16:19-20]
____
El sol nunca más te servirá de luz para el día,
ni el resplandor de la luna te alumbrará; sino que el Señor te será por luz perpetua,
y el Dios tuyo por tu gloria.
No se pondrá jamás tu sol, ni menguará tu luna: porque te será el Señor por luz perpetua,
y los días de tu luto serán acabados.
____

Todos sostienen esto como una promesa del Evangelio,
y generalmente se entiende que aquí el sol y la luna
representan los diversos medios externos en la iglesia.
Compara esto con Juan 1:13; Romanos 1:19; 1 Corintios 2:11, 15; 1 Tesalonicenses 4:9;
1 Juan 2:20, 27; y Apocalipsis 21:22-24;
todo lo cual demuestra lo que nosotros afirmamos acerca
de la suficiencia de las enseñanzas internas y espirituales,
y del glorioso privilegio de tenerlas.
Y sin duda alguna, a medida que los hombres crecen en la gracia,
y conocen la unción de la Palabra en sí mismos,
la dispensación será menos en palabras (aunque todavía en palabras) y más en la vida;
la predicación, en gran medida, se convertirá en alabanza,
y la adoración será más un caminar con Dios que un hablar de Él. Porque la adoración
más verdadera y pura que un hombre puede realizar en este mundo es,
inclinarse ante la voluntad de Dios en todo momento y en todo lugar.
Sí, es ser conformados a Él lo que da comunión; y jamás se disfrutará la unidad con Dios,
ni la luz de Su rostro, ni la verdadera paz y confianza,
a menos que haya obediencia a Su voluntad y fidelidad a Su Palabra que mora en el interior,
de acuerdo con la manifestación de Su luz en el corazón.

Yo digo, este es el estado de adoración más verdadero, y más grande;
porque los días y los lugares establecidos, con toda su solemnidad,
mayormente se utilizaron durante una dispensación menor a la del Espíritu.
Los altares, arcas y templos, los días de reposo y las fiestas,
etc. no se encuentran en los escritos del Nuevo Testamento.
Allí, todos los días son iguales,
y todos los lugares son iguales (pero "`si se guarda un día,
que se guarde para el Señor`"). Así dice el apóstol,
pero él muestra claramente un estado superior a guardar lugares y tiempos;
porque para él, el vivir era Cristo, y el morir era ganancia;
porque la vida que vivía era por la fe del Hijo de Dios, y, por lo tanto,
no era él el que vivía, sino Cristo quien vivía en él; es decir, Cristo reinaba,
dirigía y llevaba las riendas en él. Esta es la verdadera vida cristiana,
la vida de conversión y regeneración,
a la cual todas las dispensaciones de Dios y los
ministerios de Sus siervos siempre han apuntado,
como la consumación de la obra de Dios para la felicidad del hombre.
Aquí cada hombre es un templo, y cada familia una iglesia,
y cada lugar un lugar de reunión, y cada visita una reunión.

Sin embargo, que no se piense que subestimamos las reuniones públicas y solemnes; porque,
de hecho, las tenemos en toda la nación dondequiera que el Señor nos haya llamado.
Sí, aunque seamos solo dos o tres en un rincón de un país, allí nos reunimos,
como el apóstol exhortó a los santos de su tiempo,
y reprendió a los que negaban congregarse.
También nos reunimos para dar testimonio público de la religión y la adoración,
para edificar y estimular a aquellos que aún son jóvenes en la verdad,
y para llamar y reunir a otros al conocimiento de ella,
quienes todavía están descarriados, etc.
Y bendito sea Dios, estas reuniones no son en vano,
ya que a través de ellas muchos se añaden a la iglesia,
quienes esperamos y creemos que serán salvos.
Pero aun así ¡oh lector! te mostramos un modo más excelente
de adoración. Porque muchos pueden asistir a las reuniones,
e irse de ellas carnales, muertos y secos;
pero los adoradores en Espíritu y en verdad--cuyos corazones se inclinan,
cuyas mentes adoran al Dios eterno (quien es Espíritu) en y por Su propio Espíritu,
los que se conforman a Su voluntad,
y caminan con Él en una vida espiritual--estos son los verdaderos, constantes,
vivos y aceptables adoradores, ya sea que estén en reuniones o fuera de ellas.
