== Capítulo VII

Otros Principios y Prácticas Distintivos

Además de estas doctrinas generales (que eran como largas ramas en el árbol del evangelio),
surgieron varias doctrinas y prácticas particulares que evidenciaban
aún más las verdades que este pueblo defendía. Y,
ciertamente, muchas de estas ramas o testimonios más pequeños,
son los que otros profesantes del cristianismo pretenden sostener en palabras y formas,
pero no en el poder de la piedad.
Porque, hablando de manera general,
el poder ha estado perdido por mucho tiempo debido a que el hombre se ha apartado
de la gracia o Semilla de vida que está en él. Y habiéndola ignorado,
ha perdido el sentido de ella,
a pesar de que solo en y a través de ella es que el hombre puede
ser vivificado para servir al Dios vivo en novedad de vida.
Por lo tanto, al descubrir que la vida de la religión fue abandonada en gran medida,
y que la mayoría de los hombres vivía y adoraba a Dios según sus propias voluntades--y
no según la voluntad de Dios ni la mente de Cristo--por lo tanto,
lo que el pueblo llamado Cuáqueros buscaba no era una noción, sino la experiencia;
no la formalidad, sino la verdadera piedad;
porque llegaron a estar conscientes en sus corazones (a través de la obra de
los justos juicios de Dios) de que "`sin santidad nadie verá al Señor.`"^
footnote:[Hebreos 12:14]
Algunos de sus testimonios distintivos son los siguientes:

Primero, tener comunión y amarse unos a otros.
Esta es una característica famosa entre ellos,
que todas las diferentes clases de hombres confiesan con respecto a este pueblo.
Ellos se reúnen, se ayudan, y se mantienen unidos,
de modo que es común oír a las personas decir:
"`¡Mira como los Cuáqueros se aman y se cuidan unos a otros!`"
Por lo tanto, si amarse unos a otros,
gozar de una comunión íntima en la religión y manifestar
una solicitud constante de reunirse para adorar a Dios y
ayudarse el uno al otro es una marca del cristianismo primitivo,
ellos la tenían de manera amplia; bendito sea el Señor.

En segundo lugar, recomiendan el silencio por su ejemplo,
teniendo muy pocas palabras en todas las ocasiones,
ya que "`en las muchas palabras no falta el pecado.`"^
footnote:[Proverbios 10:19]
Ellos buscan frecuentemente la soledad y el retiro,
pero cuando están en compañía se esfuerzan por no usar, ni escuchar voluntariamente,
conversaciones innecesarias o injustas,
por lo cual conservan sus mentes puras y sin las perturbaciones
de muchos pensamientos y distracciones que no son de provecho.
También mantienen su palabra en los negocios, su sí es sí, y su no es no;
tampoco pueden sus clientes (ni con muchas palabras) disuadirlos de ella,
porque la verdad es más importante para ellos que la costumbre o la ganancia.

En tercer lugar, enseñan y también practican el amor a sus enemigos.
Ellos no solo se niegan a buscar venganza por cualquier mal que
les hayan hecho (condenando esto como un espíritu que no es cristiano),
sino que también perdonan libremente,
e incluso ayudan y alivian a aquellos que han sido crueles con ellos,
aun cuando está en su poder tomar venganza de sus opresores.
Se podrían dar muchos ejemplos extraordinarios de esto si el tiempo lo permitiera.

En cuarto lugar, sufrir en lugar de pelear, es otro testimonio peculiar de este pueblo.
Ellos afirman que el Espíritu de Cristo enseña a
los hombres a "`volver sus espadas en rejas de arado,
sus lanzas en hoces, y a no adiestrarse más para la guerra,`"^
footnote:[Isaías 2:4]
para que "`el lobo pueda morar con el cordero, y el becerro con el león,`"^
footnote:[Isaías 11:6]
y nada que haga mal o dañe, tenga lugar en los corazones de las personas.
En consecuencia, ellos exhortan a los hombres a emplear su celo contra el pecado,
y a volver su ira contra Satanás,
haciendo guerra contra el pecado y la iniquidad para destronar al autor de toda enemistad.
Porque todas las guerras y pleitos surgen de los deseos de los corazones de los hombres,
según el apóstol Santiago,^
footnote:[Santiago 4:1-2]
y no del manso Espíritu de Cristo Jesús,
quien es el capitán de otra guerra que se lleva a cabo con otras armas.
Y en verdad,
su testimonio en este respecto no debe considerarse como un desprecio al gobierno cívico,
puesto que, si ellos no pueden pelear por él, tampoco pueden pelear en su contra.
Tampoco es razonable que sean reprochados por no pelear por los demás,
cuando ellos ni siquiera pelearían por sí mismos.
Pero, aunque no están a favor de las guerras, sí están a favor de someterse al gobierno,
y esto no solamente lo hacen por razón del castigo,
sino también por causa de la consciencia,
siempre y cuando el gobierno no interfiera con ella.
Porque ellos creen que el gobierno es una ordenanza
de Dios y un gran beneficio para la humanidad,
dondequiera que se administre con justicia.

En quinto lugar, debido a que Dios le ha placido llamarlos a salir del ministerio humano,
ellos no pueden (por causa de la consciencia) apoyarlo y mantenerlo;
y es basados en esto (y no por rebeldía ni codicia) que se niegan a pagar diezmos,
u otras supuestas cuotas de la iglesia como esta,
con respecto a lo cual se han escritos muchos libros en su defensa.
Ellos no pueden apoyar lo que no pueden aprobar,
pero ciertamente deben testificar en su contra por dos razones: Primero,
porque todo mantenimiento obligatorio es expresamente contrario al mandamiento de Cristo,
quien dijo: "`Gratuitamente habéis recibido, gratuitamente dad.`"^
footnote:[Mateo 10:8 RV 1602 Purificada]
de modo que cualquier mantenimiento de los ministros
del evangelio debería ser voluntario y no forzado.
Y segundo,
porque los ministros nacionales no tienen el Espíritu Santo como su fundamento,
sino más bien una variedad de artes y conocimientos humanos.

En sexto lugar, ellos hablan la verdad en todas las ocasiones,
pero no se atreven a jurar, porque Cristo lo prohíbe, diciendo: "`Pero yo os digo:
No juréis en ninguna manera; ni por el cielo, porque es el trono de Dios;
ni por la tierra, porque es el estrado de sus pies; ni por Jerusalén,
porque es la ciudad del gran Rey... Pero sea vuestro hablar: Sí, sí; no, no;
porque lo que es más de esto, de mal procede.`"^
footnote:[Mateo 5:34-37]
Y Santiago, Su seguidor, dice: "`Pero sobre todo, hermanos míos, no juréis,
ni por el cielo, ni por la tierra, ni por ningún otro juramento;
sino que vuestro sí sea sí, y vuestro no sea no, para que no caigáis en condenación.`"^
footnote:[Santiago 5:12]
Jurar es innecesario y también malo,
porque el motivo de jurar es que el hombre no habla la verdad, cuando su sí,
realmente no es sí. Los juramentos se usaban para incitar a los hombres a decir la verdad,
y para darles a otros la seguridad de que lo que se había jurado era verdad.
Pero el sí del cristiano verdadero,
siendo realmente sí (estando ya ligado a la verdad
en sí mismo) cumple el propósito del juramento,
y, por lo tanto, su uso es innecesario, superfluo, y debe proceder del mal.

En séptimo lugar, no se atreven a dar honores mundanos, cumplidos vanos,
títulos halagadores, ni usar los saludos frecuentes y de moda de la época,^
footnote:[En este tiempo,
el saludo común entre las personas consistía en arrastrar
el pie derecho hacia atrás sobre suelo,
inclinarse mientras se quitaban el sombrero,
y entonces adularse uno a otro con títulos como "`su Señoría`" o "`su Eminencia,`" etc.]
viendo claramente la vanidad, orgullo y ostentación que corresponden a estas cosas.
Cristo también prohibió tales cosas en Su día,
denunciando al espíritu que se halagaba a sí mismo,
que amaba las salutaciones en las plazas y que los hombres lo llamaran
"`Rabí.`" Ellos se niegan a conformarse en estas cosas,
no por orgullo, ni por mala educación, ni por capricho,
ni por tratar de distinguirse de esta manera como grupo,
sino por obediencia a la perspectiva y sentido que han recibido del Espíritu
de Cristo respecto al fundamento y tendencia perversos de tales cosas.
Y aunque esto ha hecho que su conducta sea desagradable para muchos
que son amadores de sí mismos y de ese honor que viene de los hombres,
aun así, ellos están conscientes de lo que Cristo les dijo a los judíos:
"`¿Cómo podéis vosotros creer, pues recibís gloria los unos de los otros,
y no buscáis la gloria que viene del Dios único?`"^
footnote:[Juan 5:44]

En octavo lugar, por la misma razón ellos han regresado a la manera simple de hablar,
es decir, usar tú y usted con una sola persona,
independientemente de su estatus o grado entre los hombres.^
footnote:[En el idioma inglés (puesto que en español no tiene el mismo sentido),
en los años 1600,
se puso de moda (como una manera de mostrar honor o de halagar) utilizar
el equivalente en inglés de las palabras plurales "`vosotros`" y "`ustedes`"
para dirigirse a una persona singular de un mayor estado social,
mientras que las palabras singulares "`tú`" y "`usted`" estaban reservadas para sirvientes,
niños o personas de una condición social o económica inferior.
Los primeros Amigos se mantenían en lo que entonces era considerado "`el
lenguaje simple`" (usando "`tú`" y "`usted`" con una persona singular,
y "`vosotros`" y "`ustedes`" con dos o más personas),
en lugar de mostrar preferencia al dirigirse a ciertos individuos en plural.
Esto puede parecer un asunto pequeño para lector del siglo XXI,
pero es impresionante cuántos miles de Amigos fueron insultados, golpeados,
encarcelados e incluso colgados por negarse a conformarse a estas costumbres.]
Y aunque los hombres no usan otra forma de hablar cuando se dirigen a Dios,^
footnote:[Aunque las personas en este tiempo usaban el plural
"`vosotros`" y "`ustedes`" para dirigirse unos a otros,
todos continuaban usando "`tú`" para dirigirse a Dios en oración.
A los primeros amigos les parecía extraño e hipócrita que,
aunque sus perseguidores oraran a su Creador usando "`tú,`" no
tolerarían que se dirigieran a ellos con el mismo lenguaje.]
ellos raras veces están dispuestos a soportar que les hablemos de la misma manera.
Esto ha sido una gran prueba para el orgullo de muchos,
mostrando su ceguera y debilidad interior,
a pesar de su orgullosa profesión externa de religión. Y, en verdad,
la postura de este pueblo con respecto a este punto es puramente por causa de la conciencia,
independientemente de lo que la gente piense o diga de ellos por ello.
Y aunque sean despreciados y maltratados,
su manera simple de actuar está respaldada tanto por la Escritura como por la gramática;
y así como tienen la manera apropiada de hablar a su favor,
también han encontrado paz en su práctica.

En noveno lugar,
la simpleza y sencillez en su vestimenta y en el
mobiliario es otro testimonio peculiar de ellos,
junto con la moderación en la comida y la abstinencia de las vanas
recreaciones y pasatiempos del mundo--todo lo cual el Espíritu
del Señor Jesucristo les ha enseñado que es conforme a la piedad.
Por lo tanto,
durante mucho tiempo han exhortado a todos a que
"`su modestia sea conocida a todos los hombres;`"^
footnote:[Filipenses 4:5 RVG, y RV1602 Purificada]
puesto que se han dado cuenta que el Señor está cerca
para entrar en juicio por toda extravagancia,
falta de modestia y exceso.

En décimo lugar, no pueden, por causa de su conciencia ante Dios,
observar los llamados días santos, o los ayunos y fiestas públicas,
sabiendo que tales cosas no tienen un mandato divino, sino que son instituidas,
ordenadas y designadas en la voluntad del hombre.

Por último,
ellos han sido guiados por el buen Espíritu de nuestro Señor Jesucristo (según el ejemplo
de los primeros santos) a tener el debido cuidado los unos de los otros,
con el fin de que toda la Sociedad sea preservada en una conducta
y disciplina que correspondan a su santa profesión. El primer asunto
de importancia que surgió entre ellos era el ejercicio de caridad,
es decir, satisfacer las necesidades de los pobres, y cuidar de las viudas,
los huérfanos y los desamparados.
En consecuencia,
se hacían colectas generosamente para este y varios otros servicios en la iglesia,
que eran confiadas a hombres fieles de buena reputación,
que temían a Dios y no se cansaban de hacer el bien.
Esta sigue siendo su práctica regular y cuidadosa en todos
los lugares donde se encuentra este pueblo.

Y a medida que su número se incrementaba mucho, tanto en la ciudad como en el campo,
al punto de que eran observados por toda clase de indagadores,
a ellos les preocupaba que todos los que pertenecían a la Sociedad caminaran
como es digno del Evangelio en todo su comportamiento entre los hombres,
y en todas las ocasiones.
Ya que no obligan a nadie a unirse a ellos;
tienen razón en insistir en que aquellos que son de ellos caminen conforme a su profesión,
para ser reconocidos por ellos y permanecer en comunión con ellos.

Y a fin de que este buen orden se mantenga en los caminos de la verdad y sobriedad,
para el consuelo y la edificación de la Sociedad,
se fijaron reuniones selectas para negocios,
supervisión y disciplina en todos los lugares que ellos habitan,
las cuales se celebran mensualmente, y están sujetas a Reuniones Trimestrales,
y estas a una gran Reunión Anual.
Estas fueron establecidas para una mejor comunicación entre
ellos en aquellas cosas que mantienen la piedad y la caridad,
y para el manejo cuidadoso de los pobres, huérfanos; además,
para asegurarse de que todos caminen ordenadamente,
guarden la integridad de su profesión religiosa y mantengan registros precisos de nacimientos,
matrimonios, entierros, sufrimientos y otros asuntos de este tipo,
a fin de que este pueblo viva pacíficamente entre los hombres,
y de que sean buenos ejemplos en todas las cosas.

Este, pues, es el testimonio que tengo para dar del pueblo de Dios llamado Cuáqueros,
en cuanto a su surgimiento, apariencia, principios y prácticas, en esta era del mundo,
con respecto tanto a su fe y adoración, como a su disciplina y conducta.
