== Capítulo VIII

[.chapter-subtitle--blurb]
Varias Exhortaciones

Y ahora, Amigos, ustedes que profesan andar en este camino,
les ruego que reciban una palabra de exhortación--tanto padres como hijos,
ancianos como jóvenes.
Ustedes saben que la gloria de este día,
y el fundamento de la esperanza que nos hizo valientes
desde que el Señor nos reunió para ser un pueblo,
es ese bendito don de la luz y vida de Cristo, el cual profesamos,
y hacia el cual dirigimos a todas las personas,
como el gran instrumento y agente divino para convertir al hombre a Dios.
Fue por esto que fuimos primero alcanzados e iluminados eficazmente,
en cuanto nuestro estado interior,
y fue esto lo que nos llevó a considerar nuestro final,
llevándonos a poner al Señor delante de nuestros ojos, y a contar nuestros días,
para que trajéramos al corazón sabiduría.

En ese día no juzgábamos según la vista del ojo, ni según el oír del oído,
sino de acuerdo a la luz y sentido que recibíamos de este bendito don; sí,
por él juzgábamos y actuábamos, en relación a las cosas y a las personas,
a nosotros mismos y a los demás, e incluso con respecto a Dios nuestro Hacedor.
Porque siendo vivificados por este don en nuestro hombre interior,
pudimos discernir fácilmente la diferencia entre las cosas,
llegando a sentir lo que estaba bien y lo que estaba mal, lo que era apropiado,
y lo que no, tanto en lo referente a los asuntos religiosos como a los civiles.
Y en este don de luz y vida (siendo el fundamento de la comunión de todos los santos),
consistía nuestra comunión. En él deseábamos conocernos el uno al otro, y relacionarnos,
los unos con los otros, y con todos los hombres, en amor, fidelidad y temor.

Cuando sentíamos las agitaciones y movimientos de esta gracia en nuestros corazones,
nos acercábamos al Señor, y esperábamos ser preparados por ella,
para que pudiéramos sentir internamente los llamados y movimientos
de Dios antes de aproximarnos al Señor en oración,
o abrir nuestras bocas en el ministerio.
Nuestro consuelo,
servicio y edificación consistían en empezar y terminar unidos a esta gracia.
Y a medida que corríamos más rápido que ella,
o nos quedábamos cortos de ella en nuestros servicios,
nos hacíamos cargas para nosotros mismos;
hallando en nosotros una reprensión en vez de una aceptación,
y en lugar de "`Bien hecho,`" encontrábamos,
"`¿Quién ha demandado esto de vuestras manos?`"^
footnote:[Isaías 1:12]
En aquel día éramos un pueblo tratado fuertemente por Dios;
nuestro propio rostro y porte lo declaraban.

En ese entonces, teníamos muy presente el cuidado de los demás,
como también el de nosotros mismos, y especialmente el de los recién convencidos.
A menudo teníamos la carga de la palabra del Señor por nuestros vecinos,
familiares y conocidos,
y algunas veces por extraños también. De la misma manera
sufríamos dolores de parto por la preservación de cada uno;
no buscando, sino evitando motivos de cualquier frialdad o malentendido,
tratándonos unos a otro como aquellos que habían creído y sentido a Dios presente,
lo cual mantenía nuestra conducta en inocencia, seriedad y sobriedad,
vigilando contra las preocupaciones y amistades del mundo.
Sosteníamos la verdad en el Espíritu de ella, y no en nuestros propios espíritus,
ni según nuestras propias voluntades y afectos.

Fuimos humillados y sometidos al Señor,
hasta el punto de que todos los que nos conocían podían verlo.
No nos considerábamos a nuestra propia disposición, para ir a donde deseábamos,
o decir o hacer lo que queríamos, o cuando lo deseábamos.
Nuestra libertad consistía en la libertad del Espíritu de la verdad; y ningún placer,
ni ganancia, ni miedo, ni favor, podían sacarnos de esta postura retirada,
estricta y vigilante.
Estábamos tan lejos de buscar ocasiones para compañía social,
que las evitábamos cuando podíamos,
ocupándonos de nuestros propios negocios con moderación,
en lugar de entrometernos innecesariamente en los asuntos de otras personas.

Nuestras palabras eran pocas y "`sazonadas con sal,`"
nuestras expresiones serenas y serias,
y toda nuestra conducta estaba a plena vista de todos.
La verdad es que este tipo de vida retirada y estricta nos exponía
a la crítica de muchos de los libertinos y humoristas del mundo,
y de personas engreídas y llenas de su propia justicia,
pero era nuestra preservación de muchas trampas a las que los demás estaban continuamente
expuestos debido a la predominancia de los deseos de los ojos,
los deseos de la carne y la vanagloria de la vida,
que nunca carecen de oportunidad para incitar a los hombres a lo externo,
hacia la comunión con el mundo.

No puedo olvidar la humildad y el celo santo de ese día. Oh,
cuán constantes en las reuniones, y cuán vigilantes en ellas;
cuán fieles a la vida de la verdad, como también a los principios de la verdad;
y cuán unidos nos sentíamos en nuestra comunión, como, de hecho,
corresponde a aquellos que profesan tener una sola Cabeza, Cristo Jesús el Señor.

Ahora, pues, primero a ustedes mis amados y muy honrados hermanos en Cristo,
quienes están en el ejercicio del ministerio.
A ustedes les digo: ¡Oh, sientan vida en su ministerio!
Dejen que la vida sea su comisión, su fuente y tesoro en todas esas ocasiones;
de lo contrario (como ustedes lo saben bien) no se puede engendrar nada para Dios.
Porque nada puede dar vida salvo la vida de Dios;
y solo un ministerio en y desde esta vida puede vivificar a un
pueblo para Él. Hemos visto el fruto de todos los demás ministerios,
y cuán pocos son realmente convertidos por ellos de la maldad de sus caminos.
No es nuestro estudio, nuestra memoria,
ni la repetición de revelaciones anteriores en nuestra
propia voluntad y tiempo lo que hará la obra de Dios.
Un ministerio doctrinal y seco, independientemente de lo acertado que esté en palabras,
solo puede alcanzar los oídos, y su efecto, en el mejor de los casos,
es como un sueño. Hay otro tipo de eficacia que es mejor que cualquier otra, a saber:
Cristo el poder de Dios.
Esta es la llave de David, la cual abre y ninguno puede cerrar;
y cierra y ninguno puede abrir.
Este poder es a las palabras, lo que el aceite es a una lámpara,
y lo que el alma es al cuerpo, lo cual hizo que Cristo dijera,
"`Mis palabras son Espíritu y son vida;`"^
footnote:[Juan 6:63]
es decir, proceden de la vida, y por lo tanto vivifican a todos los que las reciben.
Y si los discípulos que habían vivido con Jesús debían
quedarse en Jerusalén hasta recibir este poder,
mucho más nosotros debemos esperar recibir poder de lo alto,
antes de ministrar en Su nombre,
si en verdad buscamos que las personas "`se conviertan de las tinieblas a la luz,
y de la potestad de Satanás a Dios.`"^
footnote:[Hechos 26:18]

Doblo fervientemente mis rodillas ante el Dios y Padre de nuestro Señor Jesucristo,
para que ustedes siempre sean de un mismo sentir,
y para que siempre esperen con reverencia la venida y revelación de la Palabra de vida,
y se aferren a ella en su ministerio y servicio,
para que así ustedes puedan servir a Dios en Su propio Espíritu.
Y si su servicio es poco o mucho, está bien; porque mucho no es demasiado,
y lo más pequeño es suficiente,
siempre y cuando fluya de la inspiración del Espíritu de Dios.
Pero en verdad, sin ella, hasta lo más mínimo es demasiado,
y no tiene provecho en lo absoluto.

Porque es el Espíritu del Señor,
ya sea de manera directa o a través del ministerio de Sus siervos,
el que "`enseña a Su pueblo provechosamente;`"^
footnote:[Isaías 48:17]
y somos de provecho solo en la medida en que lo llevemos
a Él con nosotros en nuestros servicios,
y no más allá. Porque si el Señor es quien debe obrar
todas las cosas en nosotros para nuestra salvación,
mucho más debe obrar a través de nosotros para la
conversión y edificación de los demás. Por lo tanto,
si alguna vez fue una cruz para nosotros hablar en Sus congregaciones,
aunque el Señor lo requería de nuestras manos,
que el permanecer en silencio jamás lo sea, cuando Él no requiera que hablemos.

Uno de los dichos más terribles en el libro de Dios es el siguiente:
"`Si alguno añadiere a las palabras de la profecía de este libro,
Dios traerá sobre él las plagas que están escritas en este libro.`"
Y retener el consejo de Dios es igual de terrible;
"`si alguno quitare de las palabras del libro de esta profecía,
Dios quitará su parte del libro de la vida.`"^
footnote:[Apocalipsis 22:18-19]
En verdad,
esto contiene una gran advertencia para todos los que usan el nombre del Señor;
que estén bien seguros de que el Señor en verdad habla,
y que no sean encontrados dentro del número de los
que añaden al testimonio que el Señor les da,
ni retengan o disminuyan el mismo--siendo ambas cosas muy ofensivas para Dios.

Por lo tanto, hermanos, tengamos cuidado de no correr delante de nuestro líder,
ni de quedarnos atrás de Él, puesto que aquel que se apresura puede desviarse,
y el que se queda atrás puede perder a su guía. Porque incluso
aquellos que anteriormente recibieron poder de lo alto,
tenían que esperar a recibir sabiduría para ver cómo "`usar bien la palabra;`"^
footnote:[2 Timoteo 2:15]
lo cual claramente implica que es posible que alguien
que haya recibido la palabra del Señor,
dé un paso en falso en su uso y aplicación. Esto, sin duda,
proviene de un espíritu impaciente que actúa por sí mismo,
el cual hace una mezcla poco sana y peligrosa.
Un ministerio como este nunca puede engendrar correctamente
para Dios un pueblo vivo y recto.

Siento mucha seriedad con respecto a esto, más que por cualquier otra consideración,
sabiendo bien lo mucho que concierne al estado y preservación
(presente y futuro) de la iglesia de Cristo Jesús,
la cual ha sido reunida y edificada por un ministerio vivo y poderoso.
Que su ministerio, entonces, siempre se mantenga,
preserve y continúe en las manifestaciones,
movimientos y suministros de la misma vida y poder.

Y dondequiera que se observe,
que alguien ministre más a partir de sus dones y
habilidades que a partir de la vida y poder,
aunque tenga un entendimiento iluminado y doctrinal,
que este sea debidamente advertido y amonestado para su propia preservación;
ya que tales como estos sin duda llegarán a depender de su propia autosuficiencia,
abandonando sin darse cuenta a Cristo, la Fuente viva,
para cavar para sí cisternas que no podrán retener aguas vivas.^
footnote:[Véase Jeremías 2:13]
Y de este modo,
poco a poco arrastrarán a otros y harán que dejen
de esperar en el don de Dios en sí mismos,
y de sentirlo obrando en otros (para su fortalecimiento y refrescamiento),
para que esperen por _ellos,_ y así volverse de Dios al hombre otra vez.
Estos naufragan en cuanto a esa fe que ha sido una vez dada a los santos,
y en cuanto a una buena conciencia hacia Dios,
que solo se mantienen por ese don divino de vida que primero engendra la fe,
y luego despierta y santifica la conciencia.

Tampoco es suficiente que alguna vez hayamos experimentado el don divino,
y que por él hayamos alcanzado a los espíritus encarcelados,
y que hayamos sido los instrumentos para convencer a otros acerca del camino de Dios,
si no nos mantenemos tan bajos y pobres en nosotros mismos,
y tan dependientes del Señor como siempre.
Porque ni la memoria, ni la repetición de descubrimientos,
revelaciones o experiencias anteriores, llevarán un alma a Dios,
o darán pan a los hambrientos, o agua a los sedientos,
a menos que la vida acompañe todo lo que decimos; y eso debe ser esperado.

¡Oh que no tengamos ninguna otra fuente, tesoro ni dependencia! ¡Oh, que nadie,
desde sus propios recursos, se atreva a actuar por Dios,
simplemente porque por mucho tiempo lo ha hecho inspirado por Dios!
Que nunca reemplacemos la necesidad de esperar,
con palabras que surjan de nuestra propia sabiduría,
ni pensemos que podemos tener menos cuidado y tomar más libertad para hablar que antes.
Y en el momento en que no sintamos al Señor abriéndonos y capacitándonos con su poder,
que nunca excedamos Su suministro, ni llenemos el tiempo con el nuestro,
independientemente de lo que hayamos hecho en el pasado,
o cual sea la expectativa de la gente.

Espero que siempre recordemos quién fue el que dijo,
"`separados de mí nada podéis hacer.`"^
footnote:[Juan 15:5]
Nuestra competencia proviene de Él. Y, en verdad,
el ministerio del Espíritu debe mantener su paralelo
y concordancia con el nacimiento del Espíritu;
porque así como ningún hombre puede heredar el reino de Dios a menos que nazca del Espíritu,
asimismo ningún ministerio puede engendrar un alma para Dios sino aquel que es del Espíritu.
Fue por esto, como dije antes, que los discípulos esperaron antes de salir a predicar;
y fue en este mismo poder que nuestros ancianos hermanos
y mensajeros de Dios en nuestro día esperaron,
nos visitaron y nos alcanzaron.
Entonces, habiendo comenzado en el Espíritu,
que nadie jamás espere o busque perfeccionarse por la carne;
porque ¿qué tiene que ver la carne con el Espíritu, o la paja con el trigo?
Y si nos mantenemos en el Espíritu, nos mantendremos en la unidad del mismo,
la cual es el fundamento de toda verdadera comunión. Porque al beber de un mismo Espíritu,
somos hechos un solo pueblo para Dios,
y por él somos mantenidos en la unidad de la fe y en el vínculo de la paz.
De esta manera, ninguna envidia,
ni amargura ni contienda puede tener lugar entre nosotros.
Así continuaremos velando unos por otros para bien, y no para mal; y jamás envidiaremos,
sino más bien nos regocijaremos grandemente,
al ver a otros creciendo en las riquezas de esa gracia mediante
la cual Dios llena a Sus siervos fieles.

Y hermanos, así como a ustedes se les han encomendado los oráculos de Dios,
lo cual les da frecuentes oportunidades y gran libertad
con las personas entre las que viajan,
les ruego que no piensen que basta con declarar la palabra de vida en sus congregaciones,
por muy edificantes y confortantes que sean esas
oportunidades tanto para ustedes como para ellos.
Sino que (como era la práctica del hombre de Dios
antes mencionado cuando estaba entre nosotros^
footnote:[Se refiere a George Fox]) investiguen el estado de las iglesias que visitan.
Inquieran quiénes entre ellos están afligidos o enfermos, quiénes son tentados,
y si alguno está siendo infiel u obstinado,
y entonces esfuércense por atender estas cosas en la sabiduría y poder de Dios.
Esto preparará el camino para ustedes en sus corazones,
para que los reciban como hombres de Dios,
y les dará crédito con ellos para que les puedan
hacer bien aconsejándolos en otros aspectos.
De este modo, los afligidos serán consolados por ustedes,
los tentados serán fortalecidos, los enfermos refrescados,
los infieles reprendidos y aquellos que están endurecidos serán ablandados y preparados
para la reconciliación. Así ustedes se mostrarán como verdaderos obreros de Dios,
llevando a cabo sus asuntos para la alabanza de Su nombre,
quien los ha llamado de las tinieblas a la luz,
para que vuelvan a otros del poder de Satanás a Dios y a Su reino, que es interno.

Y ustedes, jóvenes convencidos,
los invito y exhorto a esperar de manera diligente y casta en Dios,
en el camino de Su bendita manifestación y aparición interna en sus corazones.
No miren hacia afuera, sino hacia adentro.
No dejen que la libertad de otro sea su trampa; ni actúen por imitación,
sino por un verdadero sentido y experiencia del poder de Dios en ustedes mismos.
¡Oh no aplasten los tiernos brotes de Su planta en sus almas,
ni corran delante de sus movimientos santos y gentiles
debido a sus deseos y al calor de sus afectos!
Recuerden que es una "`voz suave y delicada`"^
footnote:[1 Reyes 19:12 Reina Valera de Gómez]
la que nos habla en este día. No se puede escuchar en el ruido y apuro de la mente,
pero se entiende con claridad en un estado retirado y vigilante.
Jesús amaba la soledad, y solía elegirla, yendo a las montañas,
a los huertos y a las orillas del mar para evitar las multitudes
y el ajetreo y para mostrarles a Sus discípulos que era
bueno ser solitarios y estar libres de este mundo.

Dos enemigos yacen cerca de ustedes: la imaginación y la libertad carnal.
Pero la verdad simple, santa y viva que los ha convencido también los preservará,
si le prestan atención en ustedes mismos, y llevan todos los pensamientos,
inclinaciones y afectos a la luz,
para que vean si son hechos en Dios o si son del enemigo o de ustedes mismos.
De esta manera, se formará y preservará en ustedes un verdadero gusto,
discernimiento y juicio, con respecto a lo que deben hacer y dejar de hacer.
En su diligencia y fidelidad llegarán a heredar la sustancia, y Cristo,
la sabiduría eterna de Dios, llenará sus tesoros.
Y cuando estén convertidos, como también convencidos,
entonces fortalezcan a sus hermanos,
y estén listos para toda buena palabra y obra a la cual el Señor los llame.
Entonces podrán vivir para la alabanza de Aquel que los ha escogido,
para que sean partícipes con los santos en luz, de un reino que no puede ser conmovido,
de una herencia incorruptible en las moradas eternas.

Y ahora, en cuanto a ustedes que son los hijos del pueblo de Dios,^
footnote:[Aquí él se está dirigiendo a los hijos de la primera generación de los Amigos.]
hay una gran preocupación sobre mi espíritu por su bien,
y con frecuencia mis rodillas están dobladas ante
el Dios de sus padres por causa de ustedes,
para que lleguen a participar de la misma vida y
poder divinos que han sido la gloria de este día,
y para que sean una generación de Dios, una nación santa y un pueblo propio,
celoso de buenas obras, cuando todas nuestras cabezas estén tendidas en el polvo.
¡Oh ustedes jóvenes, no crean que es suficiente que sean hijos del pueblo del Señor;
ustedes también deben nacer de nuevo si desean heredar el reino!
Sus padres no son más que carne,
y solo pueden engendrarlos en la semejanza del primer Adán;
pero ustedes deben ser engendrados en la semejanza
del segundo Adán por medio de un nacimiento espiritual,
o no serán (no _pueden_ ser) Sus hijos ni Su descendencia.

Por lo tanto, examínense cuidadosamente, ¡Oh, hijos de los hijos de Dios!
Consideren su fundamento, y vean lo que realmente son en relación a este parentesco,
familia y nacimiento divinos.
¿Han obedecido la luz, y han recibido y caminado en el Espíritu,
el cual es la Semilla y Palabra incorruptible del reino de Dios,
de la cual deben nacer de nuevo?
Dios no hace acepción de personas.
El padre no puede salvar ni responder por el hijo, ni el hijo por el padre.
En el pecado que cometen morirán;
y en la justicia que hacen (por medio de Cristo Jesús) vivirán;
porque es el que quiere y obedece que comerá lo mejor de la tierra.`"^
footnote:[Isaías 1:19]
No se engañen, Dios no puede ser burlado.
Todo lo que las naciones y pueblos siembren, eso segarán de la mano del Dios justo.
Y entonces sus muchos y grandes privilegios (mayores que los de
los hijos de otros pueblos) añadirán peso a la escala contra ustedes,
si no escogen el camino del Señor. Pues ustedes no solo han tenido buena doctrina,
sino buen ejemplo;
y (lo que es aún más importante) ustedes han sido vueltos a esa luz celestial,
y (y se han familiarizados con ella) de la cual otros han sido, en su mayoría,
muy ignorantes.
Y si ustedes,
después de oír y ver las maravillas que Dios ha hecho
para libertar y preservar a sus honorables padres,
incluso a través de un mar de aflicciones,
y de contemplar las bendiciones temporales y espirituales
con las que Él los ha llenado ante la vista de sus enemigos,
yo digo,
si ustedes descuidan y le dan la espalda a una salvación tan grande y tan cercana,
no solo serán los hijos más ingratos tanto para Dios como para ellos,
sino que no podrán evitar recibir un horrendo juicio de parte de
la mano del Señor. ¡Pero que nunca sea así con ninguno de ustedes,
dice mi alma!

Por lo tanto ¡oh, jóvenes!
Miren la Roca de sus padres; no hay otro Dios sino Él. No hay otra luz salvo la de Él,
ni otra gracia más que la de Él, ni ningún otro Espíritu sino el Suyo para convencerlos,
vivificarlos y consolarlos; para liderarlos,
preservarlos y guiarlos al reino eterno de Dios.
Búsquenlo a Él, para que puedan ser poseedores de la verdad,
como también profesantes de ella, adoptándola no solo por educación,
sino por juicio y convicción,
a partir de un sentido engendrado en sus almas mediante
la operación del eterno Espíritu y poder de Dios.
Solo por esto llegarán a ser de la simiente de Abraham por fe,
y a experimentar la circuncisión no hecha con manos,
y así volverse herederos de la promesa hecha a los padres de una corona incorruptible.
Entonces, como dije antes, serán una generación para Dios,
manteniendo la profesión de Su bendita verdad en la vida y poder de la misma.
Porque la formalidad en la religión es repugnante
para Dios y para todos los hombres buenos.
Por eso les digo, tengan cuidado de caer en esterilidad y formalidad,
continuando con nuestra profesión sin esa sal y sabor por los que
han llegado a obtener un buen testimonio entre los hombres.
Porque dondequiera que su virtud divina no se sienta en el alma,
ni se espere ni se viva en ella, las impurezas brotarán y se mostrarán rápidamente,
y manifestarán la infidelidad de esas personas cuyos corazones no están
sazonados con la naturaleza de ese Espíritu Santo que profesan.

Por lo tanto, queridos hijos,
permítanme invitarlos a que cierren sus ojos ante las tentaciones
y seducciones de este mundo vil y perecedero,
y que no permitan que sus afectos sean cautivados
por esos deseos y vanidades a los que sus padres,
por amor de la verdad, les dieron la espalda hace mucho tiempo.
Mas bien, crean en la verdad y recíbanla en sus corazones,
para que sean hechos hijos de Dios,
y para que nunca se diga de ustedes lo que el evangelista
escribe de los judíos en su tiempo,
que Cristo, la luz verdadera, "`vino a lo suyo, pero los suyos no le recibieron.`"^
footnote:[Juan 1:11]
Porque al igual que los Judíos de esa época,
ustedes tienen el nombre y las prácticas del pueblo de Dios (puesto que son sus hijos),
y se puede decir que Cristo, a través de Su luz en ustedes, ha venido a los suyos;
pero si no lo obedecen,
y le dan la espalda a Su luz al caminar en pos de las vanidades de sus mentes,
serán contados con esos que "`no lo recibieron.`"
Por lo tanto, vuélvanse al Señor y a Su don y Espíritu dentro de ustedes.
Escuchen Su voz y obedézcanla,
para que puedan atestiguar el testimonio de sus padres
por la evidencia de su propia experiencia.
Así las canas de sus queridos padres, que aún viven, descenderán a la tumba con alegría,
sabiendo que el Espíritu y naturaleza que han conocido
y amado vivirá en ustedes cuando se hayan ido.

[.asterism]
'''

Concluiré este capítulo con unas pocas palabras dirigidas
a aquellos que no son de nuestra comunidad,
en cuyas manos pueda llegar este pequeño libro.

Amigos, puesto que son los hijos e hijas de Adán, y mis hermanos según la carne,
mis deseos y oraciones a Dios han sido frecuentes y fervientes por ustedes,
que mediante el poder y Espíritu de Su Hijo Jesucristo,
a quien Él ha dado como luz y vida del mundo,
experimenten a su Creador convirtiéndose en su Redentor,
y en el Restaurador de esa imagen santa que han perdido por causa del pecado.
¡Y oh, que ustedes, que son llamados cristianos,
lo reciban verdaderamente en sus corazones;
porque allí es donde lo necesitan! Él está a la puerta de sus corazones,
y llama para que ustedes lo dejen entrar;
pero ¡ay! Él encuentra que ya están llenos de otros invitados,
de modo que Su porción entre ustedes no es más que un solitario pesebre,
así como lo fue en la antigüedad.
Sin embargo,
ustedes están llenos de creencias y conceptos como
los pretenciosos judíos que no lo conocían,
sino que lo rechazaron y maltrataron en los días de Su carne.
Y al igual que ellos,
si ustedes no llegan a poseer y experimentar lo que profesan con palabras,
toda su formalidad en la religión no servirá de nada en el día del juicio de Dios.

Les ruego que reflexionen respecto a su condición eterna, y consideren qué derecho,
base y fundamento tienen para su cristianismo.
¿Tienen ustedes más que una profesión y una creencia histórica de las verdades del evangelio?
¿Han sentido el bautismo del Espíritu Santo y fuego,
y el aventador de Cristo que avienta la paja en sus corazones,
con todos los deseos y afectos carnales?
¿Experimentan la levadura divina del reino que, al ser recibida,
leuda toda la masa del hombre, "`santificándolo por completo, cuerpo, alma,
y espíritu`"?^
footnote:[1 Tesalonicenses 5:23]
Si este no es el fundamento de su confianza, todavía están en un estado miserable.

Quizás ustedes digan que,
aunque son pecadores y viven diariamente bajo el dominio del pecado,
y no están santificados como lo he descrito, aun así,
tienen fe en Cristo quien ha llevado la maldición por ustedes,
y en Él están completos por la fe--alegando que Su justicia les ha sido imputada.
Pero, mis amigos,
permítanme rogarles que no se engañen en un asunto
tan importante como el destino de sus almas inmortales.
Si ustedes tienen una verdadera fe en Cristo, su fe los purificará.^
footnote:[Véase Hechos 15:9]
Sí, los santificará; porque la fe de los santos fue "`su victoria sobre el mundo.`"^
footnote:[1 Juan 5:4]
Por la fe vencieron el pecado internamente y a los hombres pecadores externamente.
Y si ustedes en verdad están en Cristo, no caminarán conforme a la carne,
sino conforme al Espíritu, cuyos frutos son evidentes para todos.
Ustedes serán una nueva creación--hecha y forjada nuevamente,
según la voluntad y molde de Dios.
Las cosas viejas habrán pasado, y he aquí, todas serán nuevas--nuevo amor y voluntad,
nuevos deseos, afectos y prácticas.
No serán más ustedes los que viven (la parte carnal, desobediente y mundana de ustedes),
sino Cristo que vive en ustedes.
El vivir será Cristo, y morir será su ganancia eterna,
estando seguros de que su parte "`corruptible se vestirá de incorrupción,
y su parte mortal se vestirá de inmortalidad,`"^
footnote:[1 Corintios 15:53]
teniendo una casa gloriosa, eterna en los cielos,
que nunca envejecerá ni pasará. Todo esto proviene
de la verdadera realidad de estar en Cristo,
así como el calor procede del fuego, y la luz del sol.

Por lo tanto,
tengan cuidado de suponer que están a salvo según esa noción--creyendo
que están en Cristo incluso cuando todavía viven en su naturaleza vieja
y caída. Porque "`¿qué comunión tiene la luz con las tinieblas,
o Cristo con Belial?`"^
footnote:[2 Corintios 6:14-15]
Escuchen lo que el discípulo amado les dice: "`Hijitos, nadie os engañe;
el que hace justicia es justo, como Él es justo.`"^
footnote:[1 Juan 3:7]
Y, "`Si decimos que tenemos comunión con él, y andamos en tinieblas, mentimos,
y no practicamos la verdad.`"^
footnote:[1 Juan 1:6]
Es decir, si continuamos en un camino pecaminoso,
si estamos cautivados por nuestros afectos carnales y no estamos convertidos a Dios,
entonces andamos en tinieblas,
y en ese estado no podemos tener ninguna comunión con Dios.
Cristo reviste con Su justicia a los que reciben Su gracia en sus corazones,
y se niegan a sí mismos, toman Su cruz diariamente y lo siguen.
La justicia de Cristo hace que los hombres sean santos internamente--de mente,
voluntad y prácticas santas.
Que nosotros la tengamos no significa que no sea de Cristo;
porque no es nuestra por naturaleza, sino por fe y adopción; es el don de Dios.
Pero, aun así,
aunque no es nuestra justicia en el sentido de que es o viene de nosotros mismos,
(porque en ese sentido es de Cristo, al ser siempre de Él y viniendo de Él), sin embargo,
_es_ nuestra, y _tiene que ser nuestra_ en posesión, eficacia y experiencia,
para poder hacernos algún bien; de lo contrario,
la justicia de Cristo no nos será de ningún provecho.
Fue de esta manera que Él fue hecho para los primeros cristianos su "`justicia,
santificación, justificación y redención`"^
footnote:[1 Corintios 1:30]--no una imputación imperceptible,
sino un poder que transforma verdaderamente.
Y si alguna vez desean conocer el consuelo, la sustancia,
el meollo de la religión cristiana,
van a tener que aprenderla y obtenerla de esta manera también.

Ahora, mis amigos, por lo que han leído,
pueden percibir que Dios verdaderamente ha visitado
a un pueblo menospreciado entre ustedes,
con este conocimiento y testimonio salvador--un pueblo
que Él ha sostenido y aumentado hasta este día,
a pesar de la feroz oposición con la que se ha encontrado.
Por lo tanto, no menosprecien la pequeñez de esta aparición; fue,
y todavía es (lo sabemos), un día de pequeñeces y de poca importancia para muchos,
y se le han dado muchos nombres duros y perversos.
Sin embargo, es de Dios;
vino de Él porque conduce a Él. Esto lo sabemos sin ninguna duda,
aunque no podemos hacer que alguien sepa lo que sabemos,
a menos que tome la misma senda que hemos tomado.

El mundo habla de Dios, pero ¿qué es lo que hacen?
Ellos oran por el poder, pero rechazan la luz en la que se conoce el poder.
Por lo tanto, si desean conocer a Dios, y adorarlo y servirlo como deberían hacerlo,
deben venir al medio que Él ha ordenado y dado para este propósito.
Algunos lo buscan en libros y otros en hombres sabios;
pero lo que buscan se encuentra dentro de sí mismos (aunque no viene de ellos mismos),
y por lo tanto lo pasan por alto.
La voz es muy suave, la semilla es demasiado pequeña,
y la luz resplandece en las tinieblas, pero los hombres están vagando en el exterior.
La mujer que perdió su dracma lo encontró en su casa,
después de encender su lámpara y barrerla.
Ustedes deben hacer lo mismo,
y entonces se encontrarán con la respuesta a la pregunta de Pilato,
"`¿Qué es la verdad?`"
De hecho, encontrarán la Verdad en lo íntimo, la luz de Cristo en su interior.
Porque Cristo es la luz del mundo,
y será una luz para ustedes para mostrarles la verdad
de su condición. Y al prestarle atención a Él,
los guiará fuera de toda oscuridad a la luz maravillosa de Dios;
porque la luz aumenta sobre los obedientes.
Sí, "`Luz está sembrada para el justo,`"^
footnote:[Salmo 97:11]
y "`la senda de ellos es como la luz de la aurora,
que va en aumento hasta que el día es perfecto.`"^
footnote:[Proverbios 4:18]

Por lo tanto ¡oh amigos! ¡Vuélvanse hacia adentro, vuélvanse hacia adentro, les ruego!
Donde se encuentra el veneno, allí también encontrarán el antídoto.
Es ahí donde necesitan a Cristo, y allí deben encontrarlo.
Búsquenlo y lo hallarán
¡se los testifico de parte de Dios!
Pero deben buscar correctamente, con todo su corazón, como hombres que buscan su vida,
sí, su vida eterna--con diligencia, humildad, y paciencia,
como aquellos que no pueden encontrar ningún placer,
consuelo o satisfacción en cualquier otra cosa,
a menos que encuentren a Aquel que sus almas necesitan por encima de todo.
¡Oh, este es un camino de aflicción, de aflicción espiritual!
Que el mundo carnal y profano piense y diga lo que quiera.
Ustedes deben caminar a través de una senda de aflicción
a la ciudad de Dios que tiene fundamentos eternos,
si realmente desean llegar.

[.offset]
¿Y que hará esta bendita luz por ustedes?
Se los diré:

_Primero,_ les mostrará cómo el hombre ha caído de Dios,
y el estado miserable en el que se encuentra.
Detectará el espíritu del mundo en cada uno de sus anzuelos y tentaciones,
y "`pondrá sus pecados en orden delante de sus ojos.`"^
footnote:[Salmos 50:21; Salmos 90:8]

_Segundo,_
engendrará un profundo sentimiento de tristeza en todos los que creen en su testimonio.
La luz les mostrará a Aquel a quien traspasaron,
los golpes y heridas que le han hecho con su desobediencia,
y cómo lo han obligado a ser siervo por causa de sus pecados.
Entonces llorarán y se lamentarán por su terrible ofensa,
pero su dolor será esa "`tristeza que es según Dios, que obra arrepentimiento`"^
footnote:[2 Corintios 7:10 RV1602P]
de la cual habla el apóstol.

_Tercero,_ los llevará a una vigilancia santa, para que tengan cuidado de no hacerlo más,
y que el enemigo no los sorprenda otra vez.
De este modo serán enseñados a llevar cada pensamiento,
palabra y obra al juicio de la luz,
el cual es la calzada de santidad donde caminan los redimidos del Señor. Entonces,
y no antes, amarán verdaderamente a Dios sobre todas las cosas,
y a sus prójimos como a sí mismos; y "`nada hará mal ni dañará,
ni nada habrá que espante en este santo monte.`"^
footnote:[Isaías 11:9: 65:25; 17:2]
Entonces llegarán a ser de Cristo en verdad; porque serán de Su naturaleza y Espíritu.
Y cuando sean de Cristo, entonces Cristo será de ustedes,
y ustedes experimentarán una comunión preciosa con el Padre y con el Hijo.
Y conocerán (más allá de las palabras) el poder de la sangre, sí,
de la sangre de Jesucristo, el Cordero sin mancha, que habla mejor que la sangre de Abel,
y limpia la conciencia de las obras muertas para servir al Dios vivo.

[.asterism]
'''

He aquí el testimonio y la doctrina del pueblo llamado Cuáqueros.
He aquí su práctica y disciplina,
y los hombres y mujeres que fueron enviados por Dios para esta excelente obra y servicio.
Que Dios, en este día de Su gran amor y poder, siempre tenga la gloria, el honor,
la acción de gracias y el renombre, a través de Su amado Hijo y Cordero,
nuestra luz y vida, el cual se sienta con Él en el trono, por los siglos de los siglos.
Amén.

-- Dice uno a quien Dios favoreció hace mucho tiempo con Su visitación misericordiosa,
y quien no fue desobediente al llamado y visión celestial;
para quien el camino de la verdad es más hermoso y precioso que nunca,
y conociendo la belleza y el beneficio del mismo por encima de todos los tesoros mundanos,
lo ha escogido como su más grande alegría, y por lo tanto,
les recomienda que lo amen y escojan, porque él es, con gran sinceridad y afecto,

[.signed-section-closing]
Un amigo de sus almas,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
1696
